### ISSUE TITLE
how to print each executed line of program?

### ISSUE THREAD

**Issue by Ankur008** [derekparker/delve#1000]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

What version of Delve are you using (dlv version)-
Delve Debugger
Version: 1.0.0-rc.1
Build: 5c9b200
What version of Go are you using? (go version)?- go version go1.8.3 linux/amd64
What operating system and processor architecture are you using?- ubuntu16.04.3 LTS

What did you do?
I am trying to print each line of code that is executed. 

I have tweak some line of code in next and continue cmd. It is working fine for all program that is not calling other function i.e have the only main function. But if the program has another function then it is not printing the custom function body.

I know why it is not working as next cmd require breakpoint to locate the line that is outside of int function. 

How will I achieve that?

If anyone wants to check code, I will provide. 
Or anyone can help me anyway... I am struggling with it from very long time. 

**P.S.-** This is not a bug. I am not able to find the solution elsewhere that's why putting it here.

**Comment by aarzilli** [comment]
Is you want to step into functions you need to use the "step" command, not "next"
