### ISSUE TITLE
"Unknown File" when file name not unique in GOPATH

### ISSUE THREAD

**Issue by jmhazty** [derekparker/delve#1003]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
  Delve Debugger
  Version: 1.0.0-rc.1
Build: $Id: b6077a6a35c48a31716aad2ad3fdf77bbdf70abd
2. What version of Go are you using? (`go version`)?
go1.8
3. What operating system and processor architecture are you using?
linux/amd64
4. What did you do?
use dlv in gogland
5. What did you expect to see?
dlv correct
6. What did you see instead?
![image](https://user-images.githubusercontent.com/8497943/32218893-60eb1a48-bdfa-11e7-84e6-be980d746cdc.png)
7. More
I sloved with change file name.
       before:
           src/project/db/user.go
           src/project/cache/user.go
           src/project/handler/user.go
       change to:
           src/project/db/db_user.go
           src/project/cache/cache_user.go
           src/project/handler/handler_user.go

**Comment by aarzilli** [comment]
This is a bug with gogland, you need to report it to them. @dlsniper

**Comment by dlsniper** [comment]
I've opened https://youtrack.jetbrains.com/issue/GO-4804
Thank you for the ping @aarzilli!
