### ISSUE TITLE
Command failed: can not convert "a" to string

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#1005]
1. What version of Delve are you using (`dlv version`)?
94c3b401cd02896ac15a16e0f739a33200e41ba6
2. What version of Go are you using? (`go version`)?
go version go1.9.2
3. What operating system and processor architecture are you using?
linux/amd64 (Kubuntu 17.10)
4. What did you do?
```
(dlv) p string(a)
```
5. What did you expect to see?
```
"demo"
```
6. What did you see instead?
```
Command failed: can not convert "a" to string
```

```go
package main

import "fmt"

func main() {
	a := []byte("demo")
	fmt.Println(a) // set breakpoint and evaluate here
}
```

Originally reported here: https://youtrack.jetbrains.com/issue/GO-4801

**Comment by aarzilli** [comment]
support for those advanced typecasts was added on the commit immediately after the one you are using: 8f16b371d1eaa340b86a5b63303486ce5f5115c2

**Comment by dlsniper** [comment]
Oh, my bad. Thank you!
