### ISSUE TITLE
delve and go on grafana codebase error - decoding dwarf section info at offset 0x0: too short

### ISSUE THREAD

**Issue by komalvmehta** [derekparker/delve#1006]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? **1.0.0-rc.2, Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c**
2. What version of Go are you using? (`go version`)? **go1.9.2 darwin/amd64**
3. What operating system and processor architecture are you using? **macOS Sierra**
4. What did you do? Trying to debug [grafana](https://github.com/grafana/grafana) codebase by executing command - **dlv debug ./pkg/cmd/grafana-server/** 
5. What did you expect to see? expect to start the debugger
6. What did you see instead? Error - **could not launch process: decoding dwarf section info at offset 0x0: too short**

I have setup grafana and delve successfully and tried to debug, exec and attach delve to the process but the same error.

I tried to build the go code by the below command on MacOS Sierra - 
`go build -ldflags -w -o ./bin/grafana-server -ldflags -s ./pkg/cmd/grafana-server`

Also tried to build by the command `go run build.go build`

No matter what I try, it gives the above error.

go env:
`shell $ go env`

- GOARCH="amd64"
- GOBIN=""
- GOEXE=""
- GOHOSTARCH="amd64"
- GOHOSTOS="darwin"
- GOOS="darwin"
- GOPATH="some text"
- GORACE=""
- GOROOT="/usr/local/go"
- GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
- GCCGO="gccgo"
- CC="clang"
- GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/n9/5zrsxnw50v59m6yq5vtl10jrn4qz37/T/go-build892668727=/tmp/go-build -gno-record-gcc-switches -fno-common"
- CXX="clang++"
- CGO_ENABLED="1"
- CGO_CFLAGS="-g -O2"
- CGO_CPPFLAGS=""
- CGO_CXXFLAGS="-g -O2"
- CGO_FFLAGS="-g -O2"
- CGO_LDFLAGS="-g -O2"
- PKG_CONFIG="pkg-config"

**Comment by aarzilli** [comment]
Delve is a symbolic debugger, it won't work on stripped executables. Either stop stripping the debug symbols (flags -w and -s) or use an assembly level debugger.

**Comment by komalvmehta** [comment]
@aarzilli 
Now I built like below:
go build -o ./bin/grafana-server ./pkg/cmd/grafana-server 

This would stop stripping debug symbols, right ?

dlv exec ./bin/grafana-server
**could not launch process: decoding dwarf section info at offset 0x0: too short**

Still getting same error. Please suggest how can I build to use the debugger.

**Comment by aarzilli** [comment]
Can you upload bin/grafana-server somewhere so I can take a look?

**Comment by komalvmehta** [comment]
@aarzilli sorry for late reply. grafana-server is a binary file, not sure if that would be helpful. Can you please reopen this issue ?

**Comment by aarzilli** [comment]
> grafana-server is a binary file, not sure if that would be helpful

it would. Or you can verify yourself if it has all the debug sections with readelf or gnu objdump. It should have __debug_info, __debug_line, __debug_abbrev and __debug_frame. If it doesn't it has been stripped.

**Comment by komalvmehta** [comment]
I opened file using the command "gobjdump -x grafana-server".

I didn't find any of the words mentioned above (__debug_info, __debug_line, __debug_abbrev and __debug_frame) so seems that the debug info is stripped off.

I am trying to find if there is another way to compile the go code so that I can use delve debugger.
I am building the grafana master branch from [here](https://github.com/grafana/grafana). I appreciate if you could do the same by following instructions and debug using the dlv, please do let me know.

I can't attach executables.

In the meanwhile, can you please point me to github GO project that works with dlv?

**Comment by aarzilli** [comment]
build.go:415 comment out `b.WriteString("-w")`. In the `build` function you will also want to append `-gcflags=-N -l` to `args`.

**Comment by komalvmehta** [comment]
I am building with below command:
`go build -gcflags="-N -l" -o ./bin/grafana-server ./pkg/cmd/grafana-server`

still not working

**Comment by aarzilli** [comment]
strange, it should work

**Comment by komalvmehta** [comment]
Do you mind, checking out the code base and doing it yourself. May be I am doing something wrong

**Comment by komalvmehta** [comment]
May be this helps in debugging the issue:
`gobjdump -x ./bin/grafana-server > a.txt`

PFA a.txt
[a.txt](https://github.com/derekparker/delve/files/1532972/a.txt)

**Comment by komalvmehta** [comment]
@aarzilli any updates ?

**Comment by aarzilli** [comment]
Checked out grafana, I can confirm that building with `go build -gcflags '-N -l' -o bin/grafana-server ./pkg/cmd/grafana-server` does *not* produce a stripped executable (unlike the one you have).

This is what the start of `gobjdump -x bin/grafana-server` looks like for me:

```
./grafana-server:     file format mach-o-x86-64
./grafana-server
architecture: i386:x86-64, flags 0x00000012:
EXEC_P, HAS_SYMS
start address 0x000000000405eef0

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 __TEXT.__stubs 00000288  0000000004001c40  0000000004001c40  00001c40  2**1
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 __TEXT.__stub_helper 00000448  0000000004001ec8  0000000004001ec8  00001ec8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  2 .text         00de4828  0000000004002310  0000000004002310  00002310  2**4
                  CONTENTS, ALLOC, LOAD, CODE
  3 __TEXT.__rodata 004958e9  0000000004de6b40  0000000004de6b40  00de6b40  2**5
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  4 __TEXT.__typelink 0000d7cc  000000000527c440  000000000527c440  0127c440  2**5
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  5 __TEXT.__itablink 00001be8  0000000005289c10  0000000005289c10  01289c10  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  6 __TEXT.__gosymtab 00000000  000000000528b7f8  000000000528b7f8  0128b7f8  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  7 __TEXT.__gopclntab 0065cfcd  000000000528b800  000000000528b800  0128b800  2**5
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  8 .cstring      0000614d  00000000058e87d0  00000000058e87d0  018e87d0  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  9 .const        00003c62  00000000058ee920  00000000058ee920  018ee920  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 10 __TEXT.__unwind_info 00000a6c  00000000058f2584  00000000058f2584  018f2584  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 11 __DATA.__got  00000020  00000000058f3000  00000000058f3000  018f3000  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 12 __DATA.__nl_symbol_ptr 00000010  00000000058f3020  00000000058f3020  018f3020  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 13 __DATA.__la_symbol_ptr 00000360  00000000058f3030  00000000058f3030  018f3030  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 14 .const_data   00002170  00000000058f3390  00000000058f3390  018f3390  2**4
                  CONTENTS, ALLOC, LOAD, DATA
 15 __DATA.__noptrdata 0003f0e1  00000000058f5500  00000000058f5500  018f5500  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 16 .data         00012f70  0000000005934600  0000000005934600  01934600  2**5
                  CONTENTS, ALLOC, LOAD, DATA
 17 .bss          001a4198  0000000005947580  0000000005947580  00000000  2**5
                  ALLOC
 18 __DATA.__noptrbss 00003f18  0000000005aeb720  0000000005aeb720  00000000  2**5
                  ALLOC
 19 __DATA.__common 00000010  0000000005aef638  0000000005aef638  00000000  2**3
                  ALLOC
 20 .debug_line   001f5d2b  0000000005e38000  0000000005e38000  01948000  2**0
                  CONTENTS, DEBUGGING
 21 .debug_pubnames 002d2d4d  000000000602dd2b  000000000602dd2b  01b3dd2b  2**0
                  CONTENTS, DEBUGGING
 22 .debug_pubtypes 000e8624  0000000006300a78  0000000006300a78  01e10a78  2**0
                  CONTENTS, DEBUGGING
 23 .debug_ranges 0004d1a0  00000000063e909c  00000000063e909c  01ef909c  2**0
                  CONTENTS, DEBUGGING
 24 .debug_aranges 00071c20  000000000643623c  000000000643623c  01f4623c  2**0
                  CONTENTS, DEBUGGING
 25 .debug_info   003ab18c  00000000064a7e5c  00000000064a7e5c  01fb7e5c  2**0
                  CONTENTS, DEBUGGING
 26 .debug_frame  001484f4  0000000006852fe8  0000000006852fe8  02362fe8  2**0
                  CONTENTS, DEBUGGING
 27 .debug_loc    0018284c  000000000699b4dc  000000000699b4dc  024ab4dc  2**0
                  CONTENTS, DEBUGGING
 28 .debug_abbrev 000008f2  0000000006b1dd28  0000000006b1dd28  0262dd28  2**0
                  CONTENTS, DEBUGGING
 29 .debug_str    0038642f  0000000006b1e61a  0000000006b1e61a  0262e61a  2**0
                  CONTENTS, DEBUGGING
 30 __DWARF.__apple_names 00104e94  0000000006ea4a49  0000000006ea4a49  029b4a49  2**0
                  CONTENTS, ALLOC, LOAD, DATA
 31 __DWARF.__apple_namespac 00000024  0000000006fa98dd  0000000006fa98dd  02ab98dd  2**0
                  CONTENTS, ALLOC, LOAD, DATA
 32 __DWARF.__apple_types 000629d6  0000000006fa9901  0000000006fa9901  02ab9901  2**0
                  CONTENTS, ALLOC, LOAD, DATA
 33 __DWARF.__apple_objc 00000024  000000000700c2d7  000000000700c2d7  02b1c2d7  2**0
                  CONTENTS, ALLOC, LOAD, DATA
```

Can not reproduce and even if I could it wouldn't be a delve bug.
If you do manage to build note that this program is also affected by #852.

**Comment by eL0ck** [comment]
@komalvmehta Did you work out what was doing this?

**Comment by komalvmehta** [comment]
No I didn't. Seemed like a bug because of my OS.

**Comment by friends110110** [comment]
But when I downupgrade the go version to 1.9.4 , it could debug normally. Go version 1.10 does not work

**Comment by prathibha-cb** [comment]
@komalvmehta 
I am facing exact same issue and I am on macOS Sierra. Did you find out the resolution for the "decoding dwarf section info at offset 0x0: too short" issue?

**Comment by komalvmehta** [comment]
I have spent lot of time to get it work on grafana 4.4.3.. but nothing
worked... I am upgrading to grafana V5.. will try it out later
