### ISSUE TITLE
Importing a cgo package messes with line numbers

### ISSUE THREAD

**Issue by loderunner** [derekparker/delve#1008]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
Version: 1.0.0-rc.2
Build: a5b230b81d0d23bf3f0681235de6bb90d6a956d0
```

2. What version of Go are you using? (`go version`)?

```
go version go1.9.2 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
macOS 10.12.6
Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
```

4. What did you do?

Attempted to stop on a breakpoint after importing [`go-sqlite3`](/mattn/go-sqlite3).

5. What did you expect to see?

Stopping on the breakpoint, as usual.

6. What did you see instead?

Breakpoint was not recognized.

----

I realize there are a lot of issues about cgo, and that you're hard at work on them already. For the most part it seemed to work, except line numbers are all over the place, and mess with source mapping. Here is a simple example, I built:

```go
package main

import (
	"fmt"
)

func sayHello() {
	fmt.Println("Hello World!")
}

func main() {
	sayHello()
}
```

I want to break inside `sayHello`. Here is my debugger session:

```
$ dlv debug .
Type 'help' for list of commands.
(dlv) b main.go:8
Breakpoint 1 set at 0x10b26c1 for main.sayHello() ./main.go:8
(dlv) c
> main.sayHello() ./main.go:8 (hits goroutine(1):1 total:1) (PC: 0x10b26c1)
     3:	import (
     4:		"fmt"
     5:	)
     6:
     7:	func sayHello() {
=>   8:		fmt.Println("Hello World!")
     9:	}
    10:
    11:	func main() {
    12:		sayHello()
    13:	}
```

Adding a breakpoint using the func name works too.

```
(dlv) b sayHello
Breakpoint 2 set at 0x10b26b3 for main.sayHello() ./main.go:7
```

Now I add the following import:

```go
import(
    "fmt"

    _ "github.com/mattn/go-sqlite3"
)
```

Here is my debugger session:

```
$ dlv debug .
Type 'help' for list of commands.
(dlv) b main.go:9
Command failed: no code at /Users/chrales/Work/go-workspace/src/dlv-cgo-bug/main.go:9
(dlv) b sayHello
Breakpoint 1 set at 0x410bf03 for main.sayHello() ./main.go:1320062
(dlv) c
> main.sayHello() ./main.go:1320062 (hits goroutine(1):1 total:1) (PC: 0x410bf03)
```

Issues:

* couldn't set a breakpoint at a valid line number
* setting a breakpoint using function name works, but indicates an invalid line number (`main.go:1320062`)
* when `dlv` stops at the breakpoint, it is unable to show the corresponding Go source

**Comment by aarzilli** [comment]
This can not be reproduced with a development version of go. It's likely that this is a different manifestation of https://github.com/golang/go/issues/22068 (fixed during 1.10 cycle).

**Comment by jordanlewis** [comment]
Is there a workaround for this besides using a development version of go? That's not a great option for me.

**Comment by jordanlewis** [comment]
@aarzilli Hmm I'm still seeing this even with a binary produced with go tip. Do I need to recompile delve against the new go as well, or something?

**Comment by aarzilli** [comment]
No, you don't need to recompile delve. Make sure you are really using the go version compiled from tip, if you are I would need to see the compiled binary.

**Comment by aarzilli** [comment]
On second thought this is a bug in delve.
