### ISSUE TITLE
delve test cannot see local variables in for loop

### ISSUE THREAD

**Issue by deltaskelta** [derekparker/delve#1013]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 0.12.2
Build: v0.12.2
```
2. What version of Go are you using? (`go version`)?

```
go version go1.9.2 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
OSSierra
```
4. What did you do?

used `delve test` to run a test case with a breakpoint inside a for loop

5. What did you expect to see?

variables in the scope of the for loop accessible by delve

6. What did you see instead?

only variables in the outer scope were visible

This simple test...
```
func TestDelveBreakPoint(t *testing.T) {
	outer := "foo"
	for i := 0; i < 10; i++ {
		inner := "bar"
		runtime.Breakpoint()
		log.Println(outer, inner)
	}
}


```

this debugger flow...
```
$ delve test
Type 'help' for list of commands.
(dlv) c
> github.com/deltaskelta/grpc-webapp/db.TestDelveBreakPoint() ./auth_test.go:215 (PC: 0x14277c9)
   210:	func TestDelveBreakPoint(t *testing.T) {
   211:		outer := "foo"
   212:		for i := 0; i < 10; i++ {
   213:			inner := "bar"
   214:			runtime.Breakpoint()
=> 215:			log.Println(outer, inner)
   216:		}
   217:	}
   218:
   219:	func TestUpdateUser(t *testing.T) {
   220:		db := SetupAuthTest(t)
(dlv) locals
outer = "foo"
```

**Comment by aarzilli** [comment]
the version of delve you are using is old and doesn't support go1.9.

**Comment by deltaskelta** [comment]
any idea when the 1.0 release will be an official release? I am using the homebrew installed version which only has 0.12

**Comment by aarzilli** [comment]
it should have 1.0.0-rc.2 too, which does support 1.9.

**Comment by deltaskelta** [comment]
ok I see that now, IDK why `brew update` and `upgrade` wasn't catching it but I uninstalled and reinstalled and now it is 1.0.0-rc.1
