### ISSUE TITLE
lldb-server target argument list drops args with leading - char on macOS

### ISSUE THREAD

**Issue by jpap** [derekparker/delve#1014]
1. What version of Delve are you using (`dlv version`)?

```
1.0.0-rc.1
```

2. What version of Go are you using? (`go version`)?

```
go version go1.9 darwin/amd64
```

3. What operating system and processor architecture are you using?

macOS 10.13.1 (17B48), amd64

4. What did you do?

Using Visual Studio Code (VSC) I launched the debugger on a target with a command line option `-arg test`; I am using the `flag` package for argument processing.

I can see that LLDB was launched, when listing processes:
```
59940   ??  S      0:00.03 /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver -F 127.0.0.1:53156 /Users/jpap/PROJECT/debug -arg test
```

But the argument list actually passed to the debug target is just `[test]`, and missing the first argument `-arg`.  It turns out any argument that is prefixed by `-` is being dropped by the LLDB framework debugserver.

When I add a new argument `--` to the arg list in the VSC launch configuration, prefixing all other arguments, the arg list is passed to the debug target as it should, sans the initial `--` argument.

It might be that this is a bug in the LLDB framework.  Having Delve automatically add the `--` argument is one solution.

5. What did you expect to see?

The `-arg` argument being passed to the debug target.

6. What did you see instead?

The `-arg` argument was missing from the debug target `os.Args` list.

**Comment by aarzilli** [comment]
already fixed in rc.2 by 8d3e74a445d070f3b59905db73b03ec387f63b89
