### ISSUE TITLE
Debugger fails on macOS: "could not launch process: stub exited while waiting for connection: exit status 0"

### ISSUE THREAD

**Issue by jpap** [derekparker/delve#1016]
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.0.0-rc.2
Build: a5b230b81d0d23bf3f0681235de6bb90d6a956d0
```
2. What version of Go are you using? (`go version`)?

```
go version go1.9.2 darwin/amd64
```

3. What operating system and processor architecture are you using?

macOS 10.13.1 (17B48)

4. What did you do?

I tried to debug a test from Visual Studio Code (VSC) and it fails with the error *could not launch process: stub exited while waiting for connection: exit status 0*.

VSC is executing delve with the following arguments:
```
/usr/local/bin/dlv test --headless=true --listen=127.0.0.1:2346 --log=true --wd=/Users/jpap/PROJECT --
```

In the system log, I see:
```
default	20:47:34.286794 -0800	debugserver	debugserver will use os_log for internal logging.
default	20:47:34.286827 -0800	debugserver	debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-900.0.57
 for x86_64.
default	20:47:34.287087 -0800	debugserver	1 +0.000000 sec [12684/0307]: RNBRunLoopLaunchInferior DNBProcessLaunch() returned error: 'No such file or directory (./debug.test)'
default	20:47:34.287137 -0800	debugserver	error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: No such file or directory (./debug.test)
default	20:47:34.287164 -0800	debugserver	Exiting.
```

And in the terminal I see:
```
2017/11/14 20:47:34 server.go:73: Using API v1
2017/11/14 20:47:34 debugger.go:96: launching process with args: [./debug.test]
could not launch process: stub exited while waiting for connection: exit status 0
```

What is this missing `debug.test` binary all about?

**Comment by jpap** [comment]
I can run the debugger manually, as follows, where `${MY_PACKAGE}` is the package name to test:
```
/usr/local/bin/dlv test --log=true ${MY_PACKAGE}
```
In this case, I get the `(dlv)` prompt and I can press `c` to run the tests OK.

When I add the `--` argument, it fails in the same way as outlined in the previous comment:
```
/usr/local/bin/dlv test --log=true ${MY_PACKAGE}
2017/11/14 21:03:48 server.go:73: Using API v1
2017/11/14 21:03:48 debugger.go:96: launching process with args: [./debug.test syncatron/lib/serialize]
could not launch process: stub exited while waiting for connection: exit status 0
```
and I see similar console messages.

I'll next see if I can find where the `--` arguments are coming from...

**Comment by jpap** [comment]
It looks like the `--` argument is coming from Visual Studio Code. I'll remove it and see if that fixes this issue.

**Comment by jpap** [comment]
I think the issue here is on the VSC debug adapter. Closing...

**Comment by bnairom1** [comment]
I'm seeing this problem as well just running from the command line:
```
13:06 $ dlv debug --log
2018/02/26 13:22:42 server.go:73: Using API v1
2018/02/26 13:22:42 debugger.go:98: launching process with args: [XXXXX]
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by ivdelchev** [comment]
This worked for me. 

`dlv --backend native debug --log`

And you can adjust your launch.json accordingly 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${fileDirname}",
            "env": {},
            "args": [],
            "showLog": true,
            "backend": "native"
        }
    ]
}
```

**Comment by aarzilli** [comment]
Don't do what @ivdelchev suggests, the native backend is broken in subtle ways.

**Comment by Quanjiang** [comment]
Just do @ivdelchev suggests. It works for me. What will be broken in this way ? @aarzilli

**Comment by tsocial-kiennt** [comment]
@Quanjiang this does not help
I follow @ivdelchev 's solution, and I works.

Seems like backend native is not a safe way, but it is a workaround.

**Comment by teramonagi** [comment]
Thanks @ivdelchev !!!

**Comment by 5mb** [comment]
I am getting following issue:

debugger.go:101: launching process with args: [/Users/newuser/go/src/github.com/smbhuin/myservice/debug]
could not launch process: stub exited while waiting for connection: exit status 0

Go Version: go version go1.10.1 darwin/amd64
Mac OS Version: 10.13.3
Visual Studio Code Version: 1.24.1
Delve Version: 1.0.0

If I run the debugger manually from command line it works file, but if I use any IDE then it throws similar  error.
