### ISSUE TITLE
Breakpoint does not hit the expected number of times

### ISSUE THREAD

**Issue by abu-w** [derekparker/delve#1019]
1. What version of Delve are you using (`dlv version`)?
Version: 1.0.0-rc.2
Build: 20171114-rev.a5b230b

2. What version of Go are you using? (`go version`)?
go version go1.9.2 linux/amd64

3. What operating system and processor architecture are you using?
Ubuntu, x86-64 (I see similar behavior on the Mac)

4. What did you do?
Ran the following commands:
$ dlv debug test.go
(dlv) break main.test
(dlv) continue
(dlv) continue
(dlv) continue

5. What did you expect to see?
6. What did you see instead?
I expected the breakpoint to hit 5 times since the test function is called 5 times. However, it only hit twice and then the process exited.

Here is the test program (the breakpoint was set on the main.test function):
```
package main

import (
	"fmt"
	"sync"
)

func test() {
	fmt.Println("test")
}

func main() {
	var wg sync.WaitGroup

	for i := 0; i < 5; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			test()
		}()
	}

	wg.Wait()
}
```

**Comment by derekparker** [comment]
This is because that function is executing asynchronously. If you look at the output, you'll see that the breakpoint hit count jumps by more than 1 when it is hit, as seen below:

```
➜  dlv-race-test dlv debug
Type 'help' for list of commands.
(dlv) b main.test
Breakpoint 1 set at 0x49f073 for main.test() ./test.go:8
(dlv) c
> main.test() ./test.go:8 (hits goroutine(21):1 total:4) (PC: 0x49f073)
> main.test() ./test.go:8 (hits goroutine(19):1 total:4) (PC: 0x49f073)
> main.test() ./test.go:8 (hits goroutine(23):1 total:4) (PC: 0x49f073)
> main.test() ./test.go:8 (hits goroutine(20):1 total:4) (PC: 0x49f073)
     3: import (
     4:         "fmt"
     5:         "sync"
     6: )
     7:
=>   8: func test() {
     9:         fmt.Println("test")
    10: }
    11:
    12: func main() {
    13:         var wg sync.WaitGroup
(dlv) c
test
test
test
test
> main.test() ./test.go:8 (hits goroutine(22):1 total:5) (PC: 0x49f073)
     3: import (
     4:         "fmt"
     5:         "sync"
     6: )
     7:
=>   8: func test() {
     9:         fmt.Println("test")
    10: }
    11:
    12: func main() {
    13:         var wg sync.WaitGroup
(dlv) c
test
Process 20371 has exited with status 0
(dlv) 
```

Notice the hit count when the breakpoint is activated. If you were to start the debug session like `GOMAXPROCS=1 dlv debug` you would see the behavior you are wanting.

**Comment by abu-w** [comment]
Got it. Thanks!
