### ISSUE TITLE
OSX: "could not acquire mach task 5"

### ISSUE THREAD

**Issue by technosophos** [derekparker/delve#102]
I just started testing out Delve. I installed per the directions on the site, and then wrote a quick program to test:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	time.Sleep(2 * time.Second)
	fmt.Println("OH HAI!")
}
```

Running `dlv run` in the directory produces the following output:

```
$ dlv run
[Could not launch program: could not acquire mach task 5]
```

The same happens if I first `go build` then `dlv ./main.go`.

I looked through the issues and also googled the issue, but didn't find anything relevant.

Environment:
Golang 1.4.2
OSX Yosemite 10.10.2

Thanks!

**Comment by ironcladlou** [comment]
@technosophos 

The `mach task` error means you haven't signed the `dlv` binary you built. When building delve on OSX, you also have to use the `codesign` tool to sign the binary. The steps to facilitate code signing are outlined [here](https://github.com/derekparker/delve/#os-x). The `install` task of the Makefile invokes `codesign` for you after building.

It's a lot of extra steps, but luckily you only need to do it once. After you get things working, be sure to check [these tips](https://github.com/derekparker/delve/#tips-and-troubleshooting) I recently added which alleviate some other common annoyances (like authentication prompts during the code signing and process attachment stages).

Hope this was helpful. Good luck!

**Comment by technosophos** [comment]
Oh -- so for Mac there's actually one more step: "CERT=<certname> make install"?

That wasn't quite clear from the OSX instructions. Maybe it could be explicitly added to the end of the bullet list?

At any rate, I'm up and running now! Thank you!

**Comment by derekparker** [comment]
I'll update the README to be a little more explicit.
