### ISSUE TITLE
some local variables read error

### ISSUE THREAD

**Issue by cch123** [derekparker/delve#1029]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.2
Build: 94b50d0f607bcde3857b66166af9d60a96d0c4e2

2. What version of Go are you using? (`go version`)?
go version go1.9.2 darwin/amd64

3. What operating system and processor architecture are you using?
Mac OS

4. What did you do?
dlv exec xxxx

5. What did you expect to see?
local variables can be read correctly

6. What did you see instead?
```
   139:		for _, featureName := range featureList {
   140:			metaData, getMetaErr := config.GetFeatureMeta(featureName)
=> 141:			if getMetaErr != nil {
   142:				logger.Debugf("")
   143:				...
   144:				groupDataErr = errors.New("...")
   145:				continue
   146:			}
(dlv) p metaData
xxx.xxx.xxx.com/yyy/zzz-fs/config.FeatureMetaData {CanBeCached: false, IsOnline: false, IsDisfService: false, CanBeMerged: false, CacheTime: 0, APIName: "", QueryKey: "", ValueType: "", Domain: "", EvalExpr: "", Validate: "", Protocol: "", RequestTemplate: "", HTTPRequestMethod: ""}
(dlv) p getMetaErr
Command failed: could not find symbol value for getMetaErr
```

**Comment by aarzilli** [comment]
Could be a duplicate of https://github.com/derekparker/delve/issues/964.

Can you install GNU objdump on macOS, and do this:
```objdump --dwarf <executable> | grep -B1 -A50 -e 'DW_AT_name.*<whatever function you are stopped on>'```

**Comment by cch123** [comment]
@aarzilli , yes, I forgot to turn off optimization, after I add gcflags, I can see the value of this local variable.
