### ISSUE TITLE
[Could not launch program: could not acquire mach task 5] 

### ISSUE THREAD

**Issue by ypwu1** [derekparker/delve#103]
I update the latest build of delve. I  ran my and test of my go application  with delve,  got this error message below:
[Could not launch program: could not acquire mach task 5]

Development environment: go 1.4 Mac OSX yosemite

**Comment by derekparker** [comment]
Have you code signed the binary? Take a look at the README, specifically
the OS X instructions.

**Comment by ypwu1** [comment]
I did the code sign before, and It works before I did the update. Do I need to do it again or use new code sign?

**Comment by derekparker** [comment]
You have to code sign every time you compile, but you can use the same
cert.
