### ISSUE TITLE
install error on ubuntu16.04

### ISSUE THREAD

**Issue by KeepChen** [derekparker/delve#1030]
Hi, @derekparker 
* `go version 1.6.2`
* `ubuntu 16.04 x64`
* `sudo go get github.com/derekparker/delve/cmd/dlv`
# error message below:
`# github.com/derekparker/delve/pkg/dwarf/reader
var/www/amazing/src/github.com/derekparker/delve/pkg/dwarf/reader/variables.go:78: vrdr.dwarf.Ranges undefined (type *dwarf.Data has no field or method Ranges, but does have dwarf.ranges)`

**Comment by aarzilli** [comment]
If you want to use go 1.6 use version 1.0.0-rc1
