### ISSUE TITLE
failed to load golang source code from relative path when debugging bazel build go binary

### ISSUE THREAD

**Issue by yuekui2** [derekparker/delve#1033]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 1.0.0-rc.2
2. What version of Go are you using? (`go version`)?
go 1.9.2
3. What operating system and processor architecture are you using?
ubuntu amd64
4. What did you do?
use dlv to debug bazel build produced go binary
5. What did you expect to see?
expect relative path source to replace absolute path in binary correctly
6. What did you see instead?
failed to load the source code in  the relative path of current working dir.

ws_nac$ dlv exec bazel-bin/learn/learn
(dlv) sources
...
/home/kui/.cache/bazel/_bazel_kui/e2229d3d4fa09fd2cd8e45b37cedb3ef/bazel-sandbox/2894852405464345649/execroot/__main__/GOROOT/src/unicode/utf8/utf8.go
/home/kui/.cache/bazel/_bazel_kui/e2229d3d4fa09fd2cd8e45b37cedb3ef/bazel-sandbox/2894852405464345649/execroot/__main__/learn/main.go

(dlv) break main.go:11
Breakpoint 1 set at 0x4880f8 for main.main() /home/kui/.cache/bazel/_bazel_kui/e2229d3d4fa09fd2cd8e45b37cedb3ef/bazel-sandbox/2894852405464345649/execroot/__main__/learn/main.go:11

(dlv) c
> main.main() /home/kui/.cache/bazel/_bazel_kui/e2229d3d4fa09fd2cd8e45b37cedb3ef/bazel-sandbox/2894852405464345649/execroot/__main__/learn/main.go:11 (hits goroutine(1):1 total:1) (PC: 0x4880f8)

ws_nac$ ls learn/main.go 
learn/main.go

--------------------
package main

import (
	"fmt"
	"time"
)

func main() {
	for {
		str := "Hello"
		fmt.Println(str)
		time.Sleep(time.Second)
	}
}

**Comment by aarzilli** [comment]
I presume `/home/kui/.cache/bazel/_bazel_kui/e2229d3d4fa09fd2cd8e45b37cedb3ef` gets deleted after the build? See `config substitute-path`

**Comment by derekparker** [comment]
No follow up, going to close this issue. Please reopen if still a valid issue.
