### ISSUE TITLE
map[int]struct bug

### ISSUE THREAD

**Issue by vanhumbeecka** [derekparker/delve#1039]
1. What version of Delve are you using (`dlv version`)?
--> latest at the moment: 1.0.0-rc2
2. What version of Go are you using? (`go version`)?
1.9.2
3. What operating system and processor architecture are you using?
Mac OS High Sierra
4. What did you do?
See screenshot, debugging a map[int]Pair, where Pair is a simple 2 param struct
5. What did you expect to see?
In debugger: correct numbering with the map datastructure
6. What did you see instead?
incorrect nummeration (see screenshot)
The 'watched' res[2] equals the res[5] in the debugger values

![image](https://user-images.githubusercontent.com/4650078/33798345-eebe22d0-dd16-11e7-9153-4ba6bfc92228.png)

**Comment by aarzilli** [comment]
To be clear the `res` map is `{ 0: { 6, 0 }, 1: { 8, 0 }, 2: { 3, 0 }, 3: {...}, 4 {...} }`?
If so, this is a problem with the plugin. We return an array with keys in the even numbered positions and values in odd numbered positions, the plugin is responsible for showing this in a clear manner, which it isn't doing.

**Comment by vanhumbeecka** [comment]
Yes, the assumption of the content of ```res``` is correct.
You are probably right about the fact that it is maybe the plugin's fault instead of delve.
At first I thought it was delve itself because the plugin can't function without delve installed.
