### ISSUE TITLE
illegal character issue

### ISSUE THREAD

**Issue by alinz** [derekparker/delve#104]
Hello,
Thanks for making this amazing project.

I'm having an issue. Here's the steps:
1: run my application
2: find the process id of my application
3: run `dlv attach <process id>`
4: run `break main.go:10`
5: run `continue`
6: it stops at the breaking code
7: run `n` to go to next statement causes this error

```
Command failed: /usr/local/go/src/runtime/sys_darwin_amd64.s:14:1: illegal character U+0023 '#'
```

the only way I can by pass this issue is set the breaking point at line 11 and call `continue`

any help would appreciated. 

thanks

**Comment by derekparker** [comment]
Thanks! And thanks for the report. This is a known issue (as in it's known to me, hah) but it's due to a re-working of how 'next' works, that is still in progress.

I'm hoping to have a fix for this up by later this evening.

**Comment by alinz** [comment]
Awesome! Looking forward to that.

**Comment by derekparker** [comment]
Fixed on master.
