### ISSUE TITLE
Delve & Docker 

### ISSUE THREAD

**Issue by Sergei-Rudenkov** [derekparker/delve#1041]
I am reproducing this [helloworld example](https://blog.golang.org/docker)
Only difference - I would like to have `delve` for remote debug.

Here is my `Dockerfile`:
```bash
FROM golang:1.9.2

ADD . /go/src/github.com/golang/example/outyet
ADD . /go/src/github.com/derekparker/delve/cmd/dlv

RUN go install github.com/golang/example/outyet
RUN go install github.com/derekparker/delve/cmd/dlv

RUN ["chmod", "+x", "/go/src/github.com/golang/example/outyet/bootstrap.sh"]
CMD ["/go/src/github.com/golang/example/outyet/bootstrap.sh"]

EXPOSE 8091
EXPOSE 5432
```

`bootstrap.sh`:
```bash
#!/bin/sh
go build -gcflags='-N -l' github.com/golang/example/outyet && 
dlv --listen=:5432 --headless=true --api-version=2 exec outyet;
```

`bootstrap.sh` - runs fine on my Ubuntu 17.10 host machine, but when I execute it in Docker image it throws:

> 
> flag provided but not defined: -listen
> Usage of dlv:
>   -http string
>         Listen address (default ":8091")
>   -poll duration
>         Poll period (default 1s)
>   -version string
>         Go version (default "1.4")

What is wrong? Is Docker supported at all?

Same question on stackoverflow: https://stackoverflow.com/questions/47797445/dlv-flag-provided-but-not-defined

**Comment by derekparker** [comment]
This isn't the help output from Delve, it seems you're accidentally mounting the `outyet` project into the container filesystem as Delve, and it's getting built as the on-disk binary called `dlv` but it's not actually the debugger. You can remove the `ADD ...` lines in the dockerfile since you're `go get`ing anyways.

**Comment by Sergei-Rudenkov** [comment]
@derekparker  thank you for the answer! However I don't understand what is `go get`ing anyways. helloword Docker example in your documentation would be really helpful!

**Comment by Sergei-Rudenkov** [comment]
I was able to fix it, my `Dockerfile` looks like this now:

```bash
FROM golang:1.9.2

ADD . /go/src/github.com/golang/example/outyet

RUN go install github.com/golang/example/outyet
RUN ["chmod", "+x", "/go/src/github.com/golang/example/outyet/bootstrap.sh"]
RUN ["chmod", "+x", "/go/bin/outyet"]

CMD ["/go/src/github.com/golang/example/outyet/bootstrap.sh"]

EXPOSE 8091
EXPOSE 5432
```
bootstrap.sh:
```bash
#!/bin/sh
go get github.com/derekparker/delve/cmd/dlv;
go build -gcflags='-N -l' github.com/golang/example/outyet && 
dlv --listen=:5432 --headless=true --api-version=2 exec outyet
```
And run it as following:

```bash
sudo docker build -t outyet .
sudo docker run --security-opt=seccomp:unconfined --net=host -p 8091:8091 -p 5432:5432  --name test --rm outyet
```
