### ISSUE TITLE
./variables.go:81: vrdr.dwarf.Ranges undefined (type *dwarf.Data has no field or method Ranges, but does have dwarf.ranges)

### ISSUE THREAD

**Issue by PigPigAutumn** [derekparker/delve#1043]
I install go-debug in atom,then delve was installed automatically with this exception:
./variables.go:81: vrdr.dwarf.Ranges undefined (type *dwarf.Data has no field or method Ranges, but does have dwarf.ranges)

now go-debug can not run on my atom.

I use Go 1.6.2 on my machine.

Can somebody help? Thanks

**Comment by derekparker** [comment]
That error is because you are using an older version of Go, and the `debug/dwarf` package has since changed to expose that method. This should be fixed by using a more recent version of Go.

Is there any reason you're using `1.6.2`?
