### ISSUE TITLE
location lists

### ISSUE THREAD

**Issue by glycerine** [derekparker/delve#1046]
https://tip.golang.org/doc/diagnostics.html  reports that
> As of Go 1.10, the Go binaries will have the required DWARF information for accurate debugging. To enable the DWARF improvements, use the following compiler flags and use GDB until Delve supports location lists:
>
> $ go build -gcflags="-dwarflocationlists=true"

I'm not really sure what this means. Nonetheless, delve is so far superior to gdb that it would be great to take advantage of the new DWARF improvements and support "location lists", assuming that they are means to get accurate variable display. Go 1.10 beta 1 is out now. Woot!

**Comment by aarzilli** [comment]
Support for this was added with commit 99cad1044b695e4bd75b0431c4b25982636e4a71 (which isn't in any release of delve yet). We should remember to change that page when we do a new release.

Note that -dwarflocationlists only affects optimized binaries.
