### ISSUE TITLE
go get fail on OSX

### ISSUE THREAD

**Issue by gaoxiangxyz** [derekparker/delve#1053]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?  go get latest release
2. What version of Go are you using? (`go version`)?  go1.9.2 darwin/amd64
3. What operating system and processor architecture are you using? OSX 10.10.2
4. What did you do? go get -u github.com/derekparker/delve/cmd/dlv
5. What did you expect to see? go get successful
6. What did you see instead? error

```
gaoxiangzydeMacBook-Pro:delve gaoxiangzy$ go get -u github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/cmd/dlv
/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: abort trap
error: invalid abbreviation code [110] for DIE at 0x0013fb44 in '/var/folders/3_/j6bfy2lj59z8p4rv6zpln2zr0000gn/T/go-link-182298449/go.o'
Assertion failed: (ref_addr_die != NULL), function AppendDependants, file /SourceCache/dwarf_utilities/dwarf_utilities-121.1/source/DWARFDebugInfoEntry.cpp, line 375.
```

**Comment by aarzilli** [comment]
That error isn't from delve, it's from go. It should be reported to http://github.com/golang/go, not here. However a couple of bugs that could cause this have been fixed in 1.10, you should first check if it can be replicated with 1.10.

**Comment by gaoxiangxyz** [comment]
@aarzilli thanks, it seems the error only happen on go 1.9, go 1.8 works fine.

**Comment by aarzilli** [comment]
You should really try with the 1.10 beta, if it's broken the time to have it fixed is now, otherwise it will have to wait until 1.11.

**Comment by gaoxiangxyz** [comment]
@aarzilli where can I download the go 1.10?

**Comment by gaoxiangxyz** [comment]
go 1.10 have this issue too, I have submit a issue to golang [here](https://github.com/golang/go/issues/23176).
