### ISSUE TITLE
Go 1.10 DWARF location list support

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#1056]
Hi, 

I was just reading this page https://tip.golang.org/doc/diagnostics.html#debugging and there's the following mention:

> As of Go 1.10, the Go binaries will have the required DWARF information for accurate debugging. To enable the DWARF improvements, use the following compiler flags and use GDB until Delve supports location lists:
>
> $ go build -gcflags="-dwarflocationlists=true"

From my understanding of this, it means what apps wouldn't need to be debugged with -N -l anymore but just with that parameter, as soon as delve supports the feature mentioned. Or does it still need to have the other parameters as well and the documentation is just wrong?

I'm happy to send a CL to rectify any Go documentation issues if needed but I want to understand this a bit better first and see if it's something that you guys are aware of.

Thank you.

**Comment by aarzilli** [comment]
Support for that is already merged in master, it's just not in any release yet. There's still advantages to debugging a non-optimized binary (lexical scopes, less instruction reordering) also, AFAIK, -dwarflocationlists is still incomplete.

**Comment by derekparker** [comment]
Going to close this since support is in master. We should absolutely update the docs on the Go side of things however.

**Comment by dlsniper** [comment]
Sorry for not updating this earlier. I've also seen the previous discussion about this in the other issue.
