### ISSUE TITLE
Debugging on OSX/Darwin always demands user password interaction

### ISSUE THREAD

**Issue by dr2chase** [derekparker/delve#1058]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 1.0.0-rc.2
Build: 1758f8523aff3abbb6e07ba8bebac49d70f10c94

2. What version of Go are you using? (`go version`)?
go version devel +60be6f85c1 Thu Dec 21 17:00:39 2017 +0000 darwin/amd64
(approximately 1.10beta1)

3. What operating system and processor architecture are you using?
amd64, OSX 10.12.6

4. What did you do?
Debugged an executable more than once

5. What did you expect to see?
A single dialog asking for confirmation and password, across all the N debugging sessions.

6. What did you see instead?
Every time I debug, a dialog.

I know that there is some way not to require this, because MacPorts gdb 8.0.1 manages not to require this after the first confirmation.  I have tried to find some difference in the files (owner, group, codesigning, etc) that correlated with this different behavior, but no luck yet.  Both binaries are signed with the same certificate, I have tried calling dlv "gdb" instead to see if it depends on some weird hack, ensured that both binaries had same owner, etc, directories had same owner, etc.

Clues:
- a difference in behavior when I click "cancel" on the dialog; gdb exits, whereas dlv reasserts the dialog.
- I think I have to re-password the dialog for gdb each time I reboot.

**Comment by aarzilli** [comment]
I just tested this and it doesn't happen for me or, at least, if I start dlv, quit start it again I don't get a password dialog. This is on 10.12.6 with an unsigned dlv binary.

Since on macOS we don't call the kernel directly but instead go through either lldb-server or debugserver it could depend on that. The debugserver binary is located at /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver if we don't find it we try to use lldb-server instead (which we look for in $PATH). This could have something to do with it.

**Comment by dr2chase** [comment]
There's no lldb-server on my path, but there is a debugserver at the location you named, and it appears to be signed:
```
codesign -d -v -v -v -v -v /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
Executable=/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
Identifier=com.apple.debugserver
Format=Mach-O thin (x86_64)
CodeDirectory v=20200 size=37045 flags=0x0(none) hashes=1150+5 location=embedded
OSPlatform=36
OSSDKVersion=658688
OSVersionMin=658176
Hash type=sha256 size=32
CandidateCDHash sha1=230b93f1b5bff52b6cd8b28188b0d6457a83623b
CandidateCDHash sha256=1fbe35ee3ae711005093d9bab9191751a2789c41
Hash choices=sha1,sha256
Page size=4096
    -5=0f03e7ae430135179f41645776f756709b56ff9aa0556992e96a0a81330caa71
    -4=0000000000000000000000000000000000000000000000000000000000000000
    -3=0000000000000000000000000000000000000000000000000000000000000000
    -2=5337899028526c2fc244bf40775eba51fcb0af43470fe07a2f4adcf78f682a50
CDHash=1fbe35ee3ae711005093d9bab9191751a2789c41
Signature size=4535
Authority=Software Signing
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA
Info.plist entries=6
TeamIdentifier=59GAB85EFG
Sealed Resources=none
Internal requirements count=1 size=72
```

So not a bug in delve, but a mystery at the Apple end?  Do you know which of these two binaries you are using?

**Comment by aarzilli** [comment]
I'm using debug server too:

```Executable=/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
Identifier=com.apple.debugserver
Format=Mach-O thin (x86_64)
CodeDirectory v=20200 size=37045 flags=0x0(none) hashes=1150+5 location=embedded
OSPlatform=36
OSSDKVersion=658688
OSVersionMin=658176
Hash type=sha256 size=32
CandidateCDHash sha1=e99f66dff7c0a7f4451ec3dca793b248b0f39c18
CandidateCDHash sha256=d286cc84195b28f7f0c2d1ee35dd07bf5f537d87
Hash choices=sha1,sha256
Page size=4096
    -5=0f03e7ae430135179f41645776f756709b56ff9aa0556992e96a0a81330caa71
    -4=0000000000000000000000000000000000000000000000000000000000000000
    -3=0000000000000000000000000000000000000000000000000000000000000000
    -2=5337899028526c2fc244bf40775eba51fcb0af43470fe07a2f4adcf78f682a50
CDHash=d286cc84195b28f7f0c2d1ee35dd07bf5f537d87
Signature size=4535
Authority=Software Signing
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA
Info.plist entries=6
TeamIdentifier=59GAB85EFG
Sealed Resources=none
Internal requirements count=1 size=72```

maybe it's because I'm using an admin account?

**Comment by dr2chase** [comment]
I'm also in the admin group.  I tried firing up XCode to see if there was some preference or something or remaining initialization from the last upgrade, and there were additional installs, but they made no difference even after rebooting the laptop.

**Comment by dr2chase** [comment]
Haha, works just fine on my personal laptop at home.  First invocation with `dlv exec foo` requested password, second did not.  I can compare and contrast in the comfort of my own home, will report back what I find.

**Comment by aarzilli** [comment]
https://discussions.apple.com/thread/5083304 could be relevant

**Comment by dr2chase** [comment]
We have a winner!
```
~/.../go/src/cmd/compile/internal/ssa$ DevToolsSecurity 
Developer mode is now enabled.
~/.../go/src/cmd/compile/internal/ssa$ DevToolsSecurity 
Developer mode is already enabled.
```
and the problem is solved.
