### ISSUE TITLE
Installing on Windows error: "fatal: No remote repository specified"

### ISSUE THREAD

**Issue by vfrank66** [derekparker/delve#1070]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

2. What version of Go are you using? (`go version`)?
go version go1.9.2 windows/amd64

3. What operating system and processor architecture are you using?
Win10\amd64
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\dev\GoWorkspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

4. What did you do?
 Ran the command provided in the installation documentation:
`C:\dev\GoWorkspace\go get -u -v github.com/derekparker/delve/cmd/dlv
`
5. What did you expect to see?
delve downloaded

6. What did you see instead?
`C:\dev\GoWorkspace\go get -u  github.com/derekparker/delve/cmd/dlv`

github.com/derekparker/delve (download)
 cd C:\dev\GoWorkspace\src\github.com\derekparker\delve; git pull --ff-only
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
package github.com/derekparker/delve/cmd/dlv: exit status 1

**Comment by aarzilli** [comment]
I think this is a problem with your local setup, deleting $GOPATH/github.com/derekparker/delve and rerunning the program should fix it.

**Comment by vfrank66** [comment]
You were correct deleting and restaring the computer corrected this problem.
