### ISSUE TITLE
gopath\src\github.com\derekparker\delve\pkg\proc\disasm.go:9:14: undefined: ArchInst

### ISSUE THREAD

**Issue by di3663** [derekparker/delve#1083]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
not installed with `go get -u`
2. What version of Go are you using? (`go version`)?
go version go1.9.2 windows/386
3. What operating system and processor architecture are you using?
win7 x86_64
4. What did you do?
go get -u github.com/derekparker/delve/cmd/dlv
5. What did you expect to see?
got command `dlv` installed
6. What did you see instead?
gopath\src\github.com\derekparker\delve\pkg\proc\disasm.go:9:14: undefined: ArchInst

**Comment by dlsniper** [comment]
you need to use Go for 64 bit not the 32bit version to get this working. As you have Windows 7 with 64bit this will work.

**Comment by di3663** [comment]
OK , 64bit software is commonly used on linux these days , but not really on windows . 

@dlsniper thanks for let me know this.

**Comment by dlsniper** [comment]
> OK , 64bit software is commonly used on linux these days , but not really on windows .

Almost all industry has moved to 64bit across all operating systems (Windows included).

If you want to follow progress for 32bit, please see: https://github.com/derekparker/delve/issues/20.

**Comment by thomaspeugeot** [comment]
Hi, I am using go1.11.1 with
CYGWIN_NT-10.0 DESKTOP-<xxxxxx> 2.11.1(0.329/5/3) 2018-09-05 10:24 x86_64 Cygwin
on a Windows 10 Family and I am getting the same issue
