### ISSUE TITLE
GLFW undefined: "strdup" error

### ISSUE THREAD

**Issue by dericatienza** [derekparker/delve#1084]
1. What version of Delve are you using (`dlv version`)?
1.0.0-rc.2

2. What version of Go are you using? (`go version`)?
go1.8.3 windows/amd64

3. What operating system and processor architecture are you using?
Windows 10 Pro x64

4. What did you do?
I've been following this tutorial https://medium.com/@drgomesp/opengl-and-golang-getting-started-abcd3d96f3db to learn OpenGL with Go. I was able to follow the tutorial and have the project run through "go run main.go" command. But, when I run the project through VS Code's Go debugger, an undefined: "strdup" error shows up. Also tried running "dlv debug" and same errors popup.

5. What did you expect to see?
Project runs and debugger is attached. Can confirm project builds and runs successfully when running "go run main.go".

6. What did you see instead?
![capture](https://user-images.githubusercontent.com/5621894/34958134-76c2f6e4-fa6b-11e7-8391-afa02ab74ae6.PNG)

Any ideas what may be causing this?

**Comment by dlsniper** [comment]
You are using a really old Go version.

Try to upgrade to at least Go 1.9.2 if not Go 1.10 Beta 2 (which vastly improves debugging over 1.9.2).

**Comment by dericatienza** [comment]
Upgraded to 1.10 Beta 2 and everything is fine now. Can build and debug. Thanks!
