### ISSUE TITLE
installation: codsign delve under macOS

### ISSUE THREAD

**Issue by Macilias** [derekparker/delve#1085]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
current master: Version: 1.0.0-rc.2
Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c $
2. What version of Go are you using? (`go version`)?
go version go1.9.2 darwin/amd64
3. What operating system and processor architecture are you using?
macOS 10.13.2 (17C88)
4. What did you do?
tried to use delve with VS Code
5. What did you expect to see?
Debugger
6. What did you see instead?
exceptions about fork/foo

...until I found out, that I need to codesign delve with:
codesign -s dlv-cert $(which dlv)

**Comment by aarzilli** [comment]
It should be using the lldb backend by default, how are you running it?

**Comment by Macilias** [comment]
I´m using it from within VS Code Version 1.19.2 (1.19.2)
The brew installed version didn’t worked any more, so
I tried with a custom build, you can find out more about it here:
https://stackoverflow.com/questions/46107769/visual-studio-code-debug-code-does-not-match-gopath-using-golang/48344290#48344290 <https://stackoverflow.com/questions/46107769/visual-studio-code-debug-code-does-not-match-gopath-using-golang/48344290#48344290>

-- 
Maciej Niemczyk 
Software Entwickler  




E-Mail: maciek.niemczyk@vitraum.de 
Internet: www.vitraum.de 

Vitraum GmbH 
Am Sandtorkai 71  
D-20457 Hamburg

Vertretungsberechtigte Geschäftsführer: Alexander Schwaab, David Ranft, Martin Treusch von Buttlar 
Amtsgericht Hamburg, Registernummer: HRB 137090

**Comment by aarzilli** [comment]
What options is VSCode passing to delve?

**Comment by Macilias** [comment]
If you mean the ones from launch.json there are no option, only args, do you mean those?


-- 
Maciej Niemczyk 
Software Entwickler  




E-Mail: maciek.niemczyk@vitraum.de 
Internet: www.vitraum.de 

Vitraum GmbH 
Am Sandtorkai 71  
D-20457 Hamburg

Vertretungsberechtigte Geschäftsführer: Alexander Schwaab, David Ranft, Martin Treusch von Buttlar 
Amtsgericht Hamburg, Registernummer: HRB 137090

**Comment by aarzilli** [comment]
I mean the ones that are actually passed to the dlv executable.

**Comment by Macilias** [comment]
I´m not sure how to determinate which those options are, 
All I deal with is a launch.json config file, which is defining the debugger context.

-- 
Maciej Niemczyk 
Software Entwickler  




E-Mail: maciek.niemczyk@vitraum.de 
Internet: www.vitraum.de 

Vitraum GmbH 
Am Sandtorkai 71  
D-20457 Hamburg

Vertretungsberechtigte Geschäftsführer: Alexander Schwaab, David Ranft, Martin Treusch von Buttlar 
Amtsgericht Hamburg, Registernummer: HRB 137090

**Comment by aarzilli** [comment]
Closing, no feedback
