### ISSUE TITLE
path error when case-sensitive apfs on macOS

### ISSUE THREAD

**Issue by btcking0** [derekparker/delve#1088]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.2
Build: v1.0.0-rc.2

2. What version of Go are you using? (`go version`)?
go version go1.9.2 darwin/amd64

3. What operating system and processor architecture are you using?
macOS 10.13.2 (case-sensitive apfs)

4. What did you do?
debug a go application.

5. What did you expect to see?
(dlv) ls
Stopped at: 0x1459119c
=>no source available
Command failed: open : no such file or directory
(dlv)

6. What did you see instead?
show source code.

I guess caused by case-sensitive apfs.

**Comment by aarzilli** [comment]
No, you are just stopped before any go code, set a breakpoint on main.main `b main.main` and `continue`.

**Comment by aarzilli** [comment]
Ok, that's different. It looks like a compiler/linker problem. To confirm that I'd need to see either the executable, built with `-gcflags='-N -l'` or the output of `objdump --dwarf ` on the same executable, using GNU objdump.

**Comment by aarzilli** [comment]
PS. you should check if this also happens on go1.10.

**Comment by btcking0** [comment]
https://github.com/derekparker/delve/blob/48288edd187f094959c12776689471162ec41438/pkg/terminal/command.go#L1145

https://github.com/derekparker/delve/blob/48288edd187f094959c12776689471162ec41438/pkg/terminal/command.go#L1401

https://github.com/derekparker/delve/blob/48288edd187f094959c12776689471162ec41438/pkg/terminal/terminal.go#L166

https://github.com/derekparker/delve/blob/48288edd187f094959c12776689471162ec41438/pkg/terminal/terminal.go#L189-L194

I did some trace,  maybe there.
