### ISSUE TITLE
CI: check for outdated usage documentation

### ISSUE THREAD

**Issue by schomatis** [derekparker/delve#1097]
As discussed in this [PR](https://github.com/derekparker/delve/pull/1095#issuecomment-360575692), the usage documentation is updated manually through the script `gen-usage-docs.go` (and something similar happens for the CLI).

This could be integrated to the CI to automatically check for outdated documentation and force an update before merging. This mechanism should be documented in the contribution guidelines (#1091).

**Comment by aarzilli** [comment]
This has been implemented a while ago.
