### ISSUE TITLE
Can dlv work with Go plugins ?

### ISSUE THREAD

**Issue by fsunaval** [derekparker/delve#1099]
How do I get dlv to work with Go plugins?
Here's my scenario.
I compile a Go plugin as follows.
go build --buildmode=plugin -o function.so function.go

The plugin function.so is then invoked from another go executable.

I want dlv to be able to break into the function.so plugin.
Is this possible ?

**Comment by aarzilli** [comment]
Not currently, see #865

**Comment by fsunaval** [comment]
Are there any plans to support dvelve with plugins ?
