### ISSUE TITLE
Set tracepoint during debug session

### ISSUE THREAD

**Issue by pmorie** [derekparker/delve#110]
...as suggested by @pnasrat.

Tracepoints let you evaluate expressions during program execution without pausing the program.  They are useful when the program cannot be stopped long enough to debug interactively.

Background:

*  https://sourceware.org/gdb/onlinedocs/gdb/Tracepoints.html
*  https://msdn.microsoft.com/en-us/library/ktf38f66%28v=vs.90%29.aspx

**Comment by derekparker** [comment]
I'm 100% on board with this. In fact, I wanted to support this from the beginning.

It would be great to set tracepoints from within a debug session, but I'd also like to support a `dlv trace` subcommand, so that if you only wanted to trace your program you don't have to enter a full on debug session.

**Comment by pnasrat** [comment]
I'd just ask for machine parseable output for this feature.

**Comment by derekparker** [comment]
Syntax during a debug session should be similar to the current `break` command, i.e. `trace foo.go:13`.

**Comment by aarzilli** [comment]
I would like to implement this feature along with the feature request in Issue #96.
My implementation proposal is as follows:

1. I would augment proc.Breakpoint with a field `Continue bool` that specifies whether its a breakpoint or a tracepoint as well as a list of variable names to collect when the breakpoint is hit (this is to avoid multiple client/server roundtrips each time a tracepoint is hit as well as avoiding the need to keep a parallel breakpoint map on the client)
2. When a breakpoint is hit debugger.Debugger.Command will read the requested variables and send everything back to the client inside `api.DebuggerState`
3. rpc.RPCClient.Continue is responsible for calling continue again when a tracepoint is hit, its return type would become `<- chan api.DebuggerState` (another option is to pass a callback as an argument but this seems more idiomatic)
4. when a breakpoint file is specified terminal.cont is responsible for loading it onto the server
5. furthermore I would like to use https://github.com/go-fsnotify/fsnotify to watch for changes to the breakpoint file and reload it automatically (this would also go inside the `terminal` package)

Remains to be decided a format for the breakpoint file: ini-style? yaml? a language we write a parser for?

**Comment by derekparker** [comment]
@aarzilli Thanks for taking this on.

A few comments:

* The two issues are independent, please split into 2 PRs (tracepoints & breakpoint file).
* I would change `Continue bool` to `Tracepoint bool`, seems more descriptive that way.

Other than those two minor things I think your proposal is solid.

**Comment by aarzilli** [comment]
Great. What about the breakpoint file? What do you want it to look like?

**Comment by derekparker** [comment]
@aarzilli I think the simpler the better. I feel we could get away with just a newline delimited list of breakpoint locations (i.e. function names, file:line pairs, etc..) and just iterate line by line, calling `SetBreakpointByLocaition`.
