### ISSUE TITLE
Installlation fails on ubuntu linux x64 system 

### ISSUE THREAD

**Issue by davidmdm** [derekparker/delve#1107]
Using a ubuntu machine running linux x64 architecture, running make install fails to build the binary. 

Here is the output: 

make install
go install -ldflags="-X 
main.Build=74d330a013a5412649aaa069d932b93889c2dbd2" 
github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/pkg/dwarf/reader
pkg/dwarf/reader/variables.go:81: vrdr.dwarf.Ranges undefined (type 
*dwarf.Data has no field or method Ranges, but does have dwarf.ranges)
Makefile:52: recipe for target 'install' failed
make: *** [install] Error 2

Which seems to indicate a problem in the source code. This was after cloning master. Today. I couldn't find the version number of delve sorry.

Similarly running "go get" we recieve a similar response:

go get -u github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/pkg/dwarf/reader
src/github.com/derekparker/delve/pkg/dwarf/reader/variables.go:81: vrdr.dwarf.Ranges undefined (type *dwarf.Data has no field or method Ranges, but does have dwarf.ranges)

**Comment by schomatis** [comment]
@davidmdm What version of go are you using? According to #936 which shows a similar error message Delve now requires Go 1.7 or higher (see [Installation](https://github.com/derekparker/delve/blob/master/Documentation/installation/README.md)).
