### ISSUE TITLE
Sometimes go test inside delve/proctl will fail on TestNextGeneral and/or TestNextGoroutine

### ISSUE THREAD

**Issue by aarzilli** [derekparker/delve#111]
Most of the time all tests pass, sometimes TestNextGeneral or TestNextGoroutine (or both) fail:

    --- FAIL: TestNextGeneral-4 (2.57s)
	proctl_test.go:248: Program did not continue to correct next location expected 23 was testnextprog.go:40

(this always seems to happen after the message "thread context changed from X to X")

    --- FAIL: TestNextGoroutine-4 (0.74s)
	proctl_test.go:54: failed assertion at proctl_test.go:244: Next() returned an error : process 9596 has exited with status 0

    --- FAIL: TestNextGoroutine-4 (0.23s)
	proctl_test.go:54: failed assertion at proctl_test.go:234: Continue() : process 10201 has exited with status 0

I'm using the latest revision of delve, compiled with go version 1.4.2 under Ubuntu 14.04.2

**Comment by ironcladlou** [comment]
@aarzilli Can you try and reproduce this again with the latest master build? Lots of work has been done around this area recently.

**Comment by aarzilli** [comment]
Perhaps I wasn't clear, my test failures were with the latest revision of master as of yesterday (i.e. 19a98fb49c9d1110da83008342c827ef0db5a083). But I can still reproduce the errors even with the current master (i.e. f9c64d30c205c3b869bf8bad4fe6ed92cf799115):

    --- FAIL: TestNextGoroutine-4 (0.74s)
        proctl_test.go:54: failed assertion at proctl_test.go:244: Next() returned an error : could not get registers: no such process

    --- FAIL: TestNextGoroutine-4 (0.25s)
        proctl_test.go:54: failed assertion at proctl_test.go:234: Continue() : process 29222 has exited with status 0

    --- FAIL: TestNextGeneral-4 (2.42s)
        proctl_test.go:248: Program did not continue to correct next location expected 23 was testnextprog.go:40

    --- FAIL: TestNextFunctionReturn-4 (0.25s)
        proctl_test.go:54: failed assertion at proctl_test.go:234: Continue() : process 29824 has exited with status 0

**Comment by aarzilli** [comment]
I have done some personal investingation of this bug.
It seems to be caused by an interaction between clone(2) and hardware breakpoints. Either setting GOMAXPROCS=1 or disabling the code that sets hardware breakpoints gets rid of those errors.

I should probably have mentioned that I had GOMAXPROCS set to 4 in my original error report but I had forgotten.

Further investigation reveals that resetting hardware breakpoints on DebuggedProcess.addThread with this loop:

	for i, v := range dbp.HWBreakPoints {
		if v != nil {
			setHardwareBreakpoint(i, tid, 0)
			setHardwareBreakpoint(i, tid, v.Addr)
		}
	}

gets rid of some errors. I have no idea why this actually works, btw.

The errors that remain are like this:

--- FAIL: TestNextGoroutine-4 (0.51s)
        proctl_test.go:54: failed assertion at proctl_test.go:243: Next() returned an error : process 32501 has exited with status 0

(line numbers may not match, I have local changes). If u_debugreg happens to be thread local (which seems plausible) this would be completely expected, Next() sets a temp breakpoint for the current thread (did I read the code wrong?) but TestNextGoroutine expects the call to Next to break into a goroutine different than the current one and this could happen on the same os thread or not.

**Comment by derekparker** [comment]
@aarzilli great catch, I definitely agree that's likely the issue. Can hopefully have a fix up today.
