### ISSUE TITLE
Delve isn't attaching to the PID process. How do I fix it?

### ISSUE THREAD

**Issue by directmeasure** [derekparker/delve#1113]
go version go1.9.2 darwin/amd64  
$ brew list delve
/usr/local/Cellar/delve/1.0.0-rc.2/bin/dlv
osX version 10.11.6

I'm have been trying to get Delve to work with the GAE tutorial helloworld app and I can't attach to the PID.
From here: https://cloud.google.com/appengine/docs/standard/go/quickstart#download_the_hello_world_app

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:39:31 ~/Dropbox/go/src/helloworld 
$ ps aux | grep _go_app
Bryan             6530   0.0  0.0 556601504   3144 s002  S+   11:07AM   0:00.05 /var/folders/mw/0y88j8_54bjc93d_lg3120qw0000gp/T/tmpixQP7gappengine-go-bin/_go_app
Bryan             9281   0.0  0.0  2434840    800 s000  S+    9:40AM   0:00.00 grep _go_app

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:40:19 ~/Dropbox/go/src/helloworld 
$ sudo dlv attach 6530
could not attach to pid 6530: open : no such file or directory

It seems that you need to attach to the PID in order to call:
go debug [package-name]

I tried anyway. None of my attempts worked.

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:40:28 ~/Dropbox/go/src/helloworld 
$ ls
total 24
drwxr-xr-x@  6 Bryan  staff  204 Jan 30 11:03 .
drwxr-xr-x@  7 Bryan  staff  238 Jan 30 09:44 ..
drwxr-xr-x@ 13 Bryan  staff  442 Jan 30 09:44 .git
-rw-r--r--@  1 Bryan  staff    9 Jan 30 09:44 .gitignore
-rw-r--r--@  1 Bryan  staff   69 Jan 30 09:44 app.yaml
-rw-r--r--@  1 Bryan  staff  195 Jan 30 09:44 hello.go

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:43:51 ~/Dropbox/go/src/helloworld 
$ dlv debug helloworld/hello.go
stat helloworld/hello.go: no such file or directory
exit status 1

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:45:21 ~/Dropbox/go/src/helloworld 
$ dlv debug ../helloworld/hello.go
Can not debug non-main package

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:46:08 ~/Dropbox/go/src/helloworld 
$ dlv debug ../helloworld/hello
can't load package: package helloworld/hello: cannot find package "helloworld/hello" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/helloworld/hello (from $GOROOT)
	/Users/Bryan/go/src/helloworld/hello (from $GOPATH)
	/Users/Bryan/Dropbox/go/src/helloworld/hello
exit status 1

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:46:19 ~/Dropbox/go/src/helloworld 
$ dlv debug helloworld/hello
can't load package: package helloworld/hello: cannot find package "helloworld/hello" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/helloworld/hello (from $GOROOT)
	/Users/Bryan/go/src/helloworld/hello (from $GOPATH)
	/Users/Bryan/Dropbox/go/src/helloworld/hello
exit status 1

Bryan@Bryans-MacBook-Pro Wed Jan 31 09:47:44 ~/Dropbox/go/src/helloworld 
$ dlv debug ../helloworld/hello.go hello
Can not debug non-main package

I'm probably doing something wrong, but I can't figure out what it is. I think I'm passing the entire package path incorrectly, but I tried several different package paths and I don't understand what I'm doing incorrectly.

**Comment by aarzilli** [comment]
> Bryan@Bryans-MacBook-Pro Wed Jan 31 09:40:19 ~/Dropbox/go/src/helloworld
> $ sudo dlv attach 6530
> could not attach to pid 6530: open : no such file or directory

Because you are using an old version of macOS you need to specify the path of the executable manually after the PID. Everything else was [addressed on the mailing list](https://groups.google.com/forum/#!topic/delve-dev/SYIVpugbCu4)

**Comment by directmeasure** [comment]
Now I understand. Here's the fix:

$ ps aux | grep _go_app
Bryan            13039   0.0  0.0  2453272    836 s005  S+   11:01AM   0:00.00 grep _go_app
Bryan            13037   0.0  0.0 556605840   4688 s006  S+   11:01AM   0:00.02 /var/folders/mw/0y88j8_54bjc93d_lg3120qw0000gp/T/tmpW6oGLcappengine-go-bin/_go_app


Bryan@Bryans-MacBook-Pro Wed Mar 07 11:01:58 ~/Dropbox/go/src/skincarereview 
$ dlv attach 13037 /var/folders/mw/0y88j8_54bjc93d_lg3120qw0000gp/T/tmpW6oGLcappengine-go-bin/_go_app
