### ISSUE TITLE
ListLocalVars treats key/value pairs of maps as individual children

### ISSUE THREAD

**Issue by ramya-rao-a** [derekparker/delve#1115]
1. What version of Delve are you using (`dlv version`)?
1.0.0-rc.1
2. What version of Go are you using? (`go version`)?
go version go1.9.2 darwin/amd64
3. What operating system and processor architecture are you using?
Mac OS X El Capitan Version 10.11.6
4. What did you do?
Request to [ListLocalVars](https://github.com/derekparker/delve/blob/c5c41f635244a22d93771def1c31cf1e0e9a2e63/service/rpc1/server.go#L211) when debugging code that contains map which contains a single key value pair. Using API v1
5. What did you expect to see?
The variable with single child
6. What did you see instead?
The variable with 2 children. 1 for the key, the other for the value

Sample code:
```
package main

func main() {
	a := make(map[string]string)
	a["one"] = "abc"
	a["two"] = "def"
}
```

Add a breakpoint in the last line. At this point `a` should have a single child with key `one` and value `abc`

Instead, ListLocalVars returns `a` with 2 children.

Original issue: https://github.com/Microsoft/vscode-go/issues/1384
Below, the text between `ScopesRequest` and `ScopesResponse` is the output of the `ListLocalVars` call in VS Code

<img width="891" alt="screen shot 2018-02-04 at 6 39 39 pm" src="https://user-images.githubusercontent.com/16890566/35786274-f25a10a2-09da-11e8-8df1-1fef421d8e78.png">

**Comment by aarzilli** [comment]
This is working as intended. For maps we return an array alternating keys and values. Couldn't be any other way since in go structs can be used as keys. 
It is up to the frontend to make the distinction clear to the user. Same goes for when we return truncated arrays/maps/strings.

**Comment by aarzilli** [comment]
PS. this is documented in https://github.com/derekparker/delve/blob/62fe792bfdf6599ad06c084096efd96a01246ab8/service/api/types.go#L176

**Comment by ramya-rao-a** [comment]
Thanks @aarzilli
