### ISSUE TITLE
support eh_frame if debug_frame is not present

### ISSUE THREAD

**Issue by drakonka** [derekparker/delve#1118]
Please note that I am not sure if this is an issue with Delve not fully supporting Go 1.10rc1 or with Go 1.10rc1 itself/something not being built with the correct flags. As the error comes from Delve code I'm filing it here first.

**1. What version of Delve are you using (`dlv version`)?**

Version: 1.0.0-rc.2

**2. What version of Go are you using? (`go version`)?**

go version go1.10rc1 linux/amd64

**3. What operating system and processor architecture are you using?**
Fedora 26; GOARCH="amd64"

**4. What did you do?**

Tried to run with debugger attached through Jetbrains Goland on a project that imports `plugin`. Goland setup scripts are as follows:

```
GOROOT=/home/lazer/sdk/go1.10rc1 #gosetup
GOPATH=/home/lazer/go #gosetup
/home/lazer/sdk/go1.10rc1/bin/go test -c -o /tmp/___1auth0_test_go -gcflags "all=-N -l" gitlab.com/drakonka/gosnaillife/server/lib/infrastructure/auth/cli/auth0/tests #gosetup
/home/lazer/Apps/goland/plugins/intellij.go/lib/dlv/linux/dlv --listen=localhost:37591 --headless=true --api-version=2 --backend=default exec /tmp/___1auth0_test_go -- -test.v -test.run "^TestAuth0Signup|TestAuth0Login|TestAuth0Logout$" #gosetup
```

**5. What did you expect to see?**

I expected the tests to start and break at the first breakpoint.

**6. What did you see instead?**

`could not launch process: could not find .debug_frame section in binary`

I am able to repro this by simply putting in some dummy code using "plugin" in my package, eg:

```
	test := plugin.Plugin{}
	fmt.Println(test)
```

The above attaches fine on Go 1.9, but not Go 1.10rc1

**Comment by aarzilli** [comment]
Looks like 1.10 can't emit debug symbols when plugin is imported. This isn't a bug with delve and will be tracked on the go repository at https://github.com/golang/go/issues/23733.
