### ISSUE TITLE
erratic source line displaying

### ISSUE THREAD

**Issue by nuliknol** [derekparker/delve#1120]
1. What version of Delve are you using (`dlv version`)? **1.0.0-rc.2**
2. What version of Go are you using? (`go version`)?**go version go1.9.2 linux/amd64**

3. What operating system and processor architecture are you using? **Linux desk 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

4. What did you do? **dlv debug on my sources**
5. What did you expect to see? correct flow of source code
6. What did you see instead? program jumped to another source line totally impossible to occur

Aparently source code displayed does not match current execution when returning from some functions. This is my dlv session, the code has been obfuscated due to privacy reasons, but it is enough to illustrate how it happens:

```
> main.some_process ./github.com/someuser/somerepo/somestuff.go:57 (PC: 0xfebac0)
Warning: debugging optimized function
    52:	//	var var230548 []*Type232312_t;
    53:	
    54:		lakjdfsw := somepackage.lakjdfsw()
    55:		bc_cfg:=lakjdfsw.Config()
    56:		some_num:=some_num_t(stackd.Number234())
=>  57:	    if some_num == 0 {
    58:			somedb, err := lakjdfsw.LookUp(lakjdfsw.GetSomeStuffByKey(stackd.Zip()).Root())
    59:	        if err != nil {
    60:	            log.Error("Can't get LookUp()","some_num",stackd.Number().Uint64())
    61:	            return  err
    62:	        }
(dlv) 
> main.some_process ./github.com/someuser/somerepo/somestuff.go:58 (PC: 0xfebac8)
Warning: debugging optimized function
    53:	
    54:		lakjdfsw := somepackage.lakjdfsw()
    55:		bc_cfg:=lakjdfsw.Config()
    56:		some_num:=some_num_t(stackd.Number234())
    57:	    if some_num == 0 {
=>  58:			somedb, err := lakjdfsw.LookUp(lakjdfsw.GetSomeStuffByKey(stackd.Zip()).Root())
    59:	        if err != nil {
    60:	            log.Error("Can't get LookUp()","some_num",stackd.Number().Uint64())
    61:	            return  err
    62:	        }
    63:	        some_table_dump := somedb.RawDump()
(dlv) 
> main.some_process ./github.com/someuser/somerepo/somestuff.go:121 (PC: 0xfebad5)
Warning: debugging optimized function
   116:		num_elts:=len(stackd.Records())
   117:		log.Info("block ","num",stackd.Number(),"transactions",num_elts)
   118:	    for i, tx := range stackd.Records() {
   119:			someLogger := vm.NewLogger(lcfg)
   120:			machine.Logger=someLogger
=> 121:	        somedb.Prepare(cool.Zip(), stackd.Zip(), i)
   122:	
   123:		    msg, err := cool.AsMessage(types.MakeProgress(bconf, stackd.Number()))
   124:		    if err != nil {
   125:				log.Error("MyApp: Error in cool.AsMessage()")
   126:				return err


```
I am using `next` to go over the source code. When I `next` over the line 58, it executes some long process, and when the program returns from the function LookUp() the PC counter is lost (or I don't know what exactly happens) and the PC counter is now set to line 121, which is a line totally impossible to execute. If I do few more `next`s or `step`s , the PC is restored , so this bug is sort of temporary and leaves you totally blind on what is going on.

**Comment by aarzilli** [comment]
This is a problem with the compiler assigning line numbers to instructions poorly (or reording too much), it should be somewhat better in 1.10 and more improvements are planned for 1.11. You should try 1.10, if that doesn't fix it you could report it to [go](https://github.com/golang/go/issues/), howerver investigating this is going to be hard without source code.

**Comment by nuliknol** [comment]
yep, I just saw the same problem in `gdb`, thanks!
