### ISSUE TITLE
Remove full compilation flag for version 1.10

### ISSUE THREAD

**Issue by torre76** [derekparker/delve#1123]
Hi,

today has been released Go Version 1.10 which hopefully solves the issue #970.
Is it possible to fix the commit ec8e6c4af3de43ee78cc09a3f64c347dce510378 in order to exclude Go 1.10 from using the `-a` flag?

This will speed up code debugging a lot.

Thank you!

**Comment by aarzilli** [comment]
It was removed back in november with b723f50b4a99ca92e7f58570d7fccbe85f5c0dc9
