### ISSUE TITLE
No local variables after upgrading to Go 1.10

### ISSUE THREAD

**Issue by torre76** [derekparker/delve#1124]
Referring to https://github.com/Microsoft/vscode-go/issues/1520, after the upgrade to Go 1.10, I am unable to see the Local Variables into the "Local Variable Pane" on VSCode.

Program source is 

[main.go.zip](https://github.com/derekparker/delve/files/1734521/main.go.zip)

What I see into VSCode is:

![schermata 2018-02-17 alle 10 37 45](https://user-images.githubusercontent.com/3954720/36349784-6daa70f6-148c-11e8-85ec-c15895b4b401.png)

Delve Trace launch by console is:

[vscode-go-debug.txt](https://github.com/derekparker/delve/files/1734522/vscode-go-debug.txt)

I have run Delve on command line, as requested by @ramya-rao-a on https://github.com/Microsoft/vscode-go/issues/1520, and it seems that local variables are not showing at all...

![schermata 2018-02-18 alle 09 09 50](https://user-images.githubusercontent.com/3954720/36349811-bdfb283e-148c-11e8-9de1-0ca04f8e1cb3.png)

**Comment by aarzilli** [comment]
Did you update delve? If you did I'd have to see the executable produced by `go build -gcflags='all=-N -l' main.go`

**Comment by torre76** [comment]
My `dlv` version is 

>Delve Debugger
>Version: 1.0.0-rc.2
>Build: v1.0.0-rc.2

And here the file you requested:

[main.bin.zip](https://github.com/derekparker/delve/files/1734529/main.bin.zip)

**Comment by aarzilli** [comment]
The executable looks fine and I can't reproduce your problem with the latest version of go and delve. Maybe do a `go get -u github.com/derekparker/delve/cmd/dlv`?

**Comment by torre76** [comment]
It worked!

By the way I was using the *Homebrew* version obtained using your [instruction](https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md).

Maybe the problem is there?

**Comment by aarzilli** [comment]
we just need to make a new release.
