### ISSUE TITLE
replay rewind inside VS Code

### ISSUE THREAD

**Issue by t-bast** [derekparker/delve#1128]
Congrats on the 1.0.0 release, this is really great work!

I'm really excited to see the support for Mozilla RR so I jumped in to give it a try.
Using it from the CLI works like a charm, so I wanted to go further and try to use it inside VS Code for a more visual debugging experience ;)

Replaying a trace works fine, but I wasn't able to find a way to rewind. 
I'm running the replay with _dlv replay {trace path} --headless --listen=:50505_ and then remote debugging from VS Code, and it looks like the VS Code debug console doesn't allow me to send dlv commands to the debug server (does it only evaluate go code?).

I tried connecting to the debug server from the dlv command line separately to rewind (it would be an acceptable solution until a rewind UI is available) but it looks like the debug server accepts a single connection.

I couldn't find more info on the web, do you have guidelines on how to do this?

I'm using dlv 1.0.0 with go 1.10 on ubuntu 16.04.

**Comment by aarzilli** [comment]
The plugin for VSCode is maintained at https://github.com/Microsoft/vscode-go. If you want you can pass `--accept-multiclient=true` to delve, but the VSCode plugin is likely to get confused when you rewind from the command line client.

**Comment by t-bast** [comment]
Thanks for the tip on using `--accept-multiclient=true`, I hadn't noticed that. But you're right, the plugin gets confused when I'm using it to try to rewind ;).
I'll post this issue on the VSCode plugin repo, it makes more sense there.
But if someone has the answer here, don't hesitate to post it though!
