### ISSUE TITLE
delve 1.0.0 causes `SEGV 11` on macOS High Sierra

### ISSUE THREAD

**Issue by hachi8833** [derekparker/delve#1132]
Encountered the following:

---------------

1. What version of Delve are you using (`dlv version`)?
  * 1.0.0
2. What version of Go are you using? (`go version`)?
  * 1.10
3. What operating system and processor architecture are you using?
  * macOS 10 High Sierra with latest patches
4. What did you do?
  * installed via `brew install go-delve/delve/delve` and run `dlv`
  * checked that cert has been correctly generated and installed
5. What did you expect to see?
  * running `dlv`
6. What did you see instead?
  * `Segmentation fault: 11` with no other messages

**Comment by dlsniper** [comment]
According to this: https://stackoverflow.com/questions/12762944/segmentation-fault-11 , it may be that you are running out of memory on the system? Try to monitor that when your app is running and see what happens.

**Comment by hachi8833** [comment]
You're right. Rebooting the Macbook fixed the issue.
Thank you very much!
