### ISSUE TITLE
```goroutines -g``` report inaccurate location for creating the goroutine

### ISSUE THREAD

**Issue by hitzhangjie** [derekparker/delve#1135]
for example, I write code as following to learn how to switch between 2 goroutines in delve.

```
var wg sync.WaitGroup

func main() {
	fmt.Println("vim-go")

	wg.Add(1)
	go gofunc1()

	wg.Add(1)
	go gofunc2()

	wg.Wait()
}

func gofunc1() {
	defer wg.Done()

	for i := 0; i < 10; i++ {
		fmt.Println("gofunc1")
		time.Sleep(time.Microsecond * 10)
	}
}

func gofunc2() {
	defer wg.Done()

	for i := 0; i < 5; i++ {
		fmt.Println("gofunc2")
		time.Sleep(time.Microsecond * 10)
	}
}

```

Then I use delve to debug the code as following:

![dlv](https://user-images.githubusercontent.com/3725760/36778237-28215536-1ca7-11e8-9e06-44ae72ea2d73.png)

The command *goroutines -g* report inaccurate source code location, It seems to include the blank lines following the accurate location. For example, goroutine 5 is created in line 15, but dlv reports line 17, and goroutine is created in line 18, it reports 20.

another question, ```list <linespec>```, if there's no gocode in location gofile:offset, it reports there's no go code. Why not consider a valid source line number a valid offset?

I am a golang beginnner, really appreciate your work, Thanks!

**Comment by derekparker** [comment]
Thanks for reporting this and for the detail you provided! Just put up a fix, we'll get it reviewed and merged for the next release.
