### ISSUE TITLE
Unreadable interface type because corresponding type is not found

### ISSUE THREAD

**Issue by lafolle** [derekparker/delve#1137]
1. What version of Delve are you using (`dlv version`)?
1.0.0-rc.1

2. What version of Go are you using? (`go version`)?
go version go1.9.2 linux/amd64

3. What operating system and processor architecture are you using?
Linux/amd64

4. What did you do?
One of our program's was misbehaving on server (linux),  so we took a core dump (gcore) for later analysis before restarting the server.  I got the dump on local machine and fired dlv to analyze it.  Specifically,  i wanted to know the state of a particular object in the process.
GNU gdb (GDB) Amazon Linux (7.6.1-64.33.amzn1) was used to get coredump.

5. What did you expect to see?
I'm accessing a map where key is string and val an interface.  Problem occurs on trying
to read value. I expect the value to be details of underlying type of interface.

6. What did you see instead?
```
(dlv) goroutine 286775964 frame 6 p c.socketMap["5_cGv-6ietdHEcyRUzSt"]
client.tSafeSocket {
        Soc: (unreadable interface type "*github.com/googollee/go-socket.io.socket" not found for 0xc425cffed0: no type entry found, use 'types' for a list of valid types),
        Source: 1,}
(dlv)
```

Let me know if you need more details.

PS: This is the first time i used dlv (after fighting with gdb for Go) and it did pretty well job in giving some insight into the problem we're trying to solve.  Had dlv been not there,  we would have had to parse gigabytes of logs to get that information.  dlv did it in few minutes :)
Thanks for this!

**Comment by lafolle** [comment]
:+1:

**Comment by Glowdable** [comment]
How to resolved？
