### ISSUE TITLE
Error: invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool

### ISSUE THREAD

**Issue by friends110110** [derekparker/delve#1139]
GOROOT=/usr/local/Cellar/go/1.10/libexec #gosetup
GOPATH=/Users/friends/Documents/VirtualMachine/share/gopath #gosetup
/usr/local/Cellar/go/1.10/libexec/bin/go build -o /private/var/folders/cg/mwzlhrjs5y55ny553g6xz9tr0000gn/T/___peer_server -gcflags "all=-N -l" /Users/friends/Documents/VirtualMachine/share/gopath/src/github.com/hyperledger/fabric/peer/main.go #gosetup
go build github.com/hyperledger/fabric/vendor/github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool

Delve Debugger
Version: 1.0.0
go version go1.10 darwin/amd64

Darwin friendsdeMacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by derekparker** [comment]
Can you give more information around this? Is this when installing from homebrew?

**Comment by aarzilli** [comment]
This is just a build problem on the target program. Closing.
