### ISSUE TITLE
couldn't start listener: listen tcp 192.168.0.101:0: bind: can't assign requested address

### ISSUE THREAD

**Issue by Vasu-p** [derekparker/delve#1140]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
Tried both 1.0.0 and 0.12.2
2. What version of Go are you using? (`go version`)?
go version go1.10 darwin/amd64
3. What operating system and processor architecture are you using?
OSX 10.13.1

I am trying to debug but this message pops up. I even tried changing port number but none works. and none of those ports are in use.

```
./dlv debug hello
couldn't start listener: listen tcp 192.168.0.101:0: bind: can't assign requested address
```

**Comment by aarzilli** [comment]
Do you have the executable at `/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver` and if you don't did you do the xcode-select thing?

**Comment by Vasu-p** [comment]
Hi,
I have it. and when I run the following command it doesn't throw any error.
`./debugserver localhost:0`

**Comment by aarzilli** [comment]
I was wrong, this doesn't have anything to do with debugserver, sorry.

What's happening here is that delve itself can't open a listener on localhost:0. My guess is that you have a firewall that's preventing delve from listening. If you write a little program that just does `net.Listen("tcp", "localhost:0")` that should return an error too, if I'm right.

**Comment by Vasu-p** [comment]
Yes, Exactly. `net.Listen("tcp", "localhost:0")` also gives the same error. But I am able to run something like `python -m SimpleHTTPServer 8080`. Why would that might be?

**Comment by aarzilli** [comment]
Maybe your firewall is configured to prevent listening on ephemeral ports?

**Comment by Vasu-p** [comment]
Hi, 
Sorry for all the trouble. It was not firewall but my `/etc/hosts` file. My localhost was pointing to `192.168.0.101` instead of `127.0.0.1`.

**Comment by wustzhy** [comment]
please help me

$ dlv version
Delve Debugger
Version: 1.0.0

$ go version
go version go1.10.3 darwin/amd64

macOS 10.13.4 (17E199)

**### error info in terminal:**
dlv debug math_1.go
couldn't start listener: listen tcp 185.199.108.153:0: bind: can't assign requested address

###  **error log in the DEBUG CONSOLE of VSCode**
```
Verbose logs are written to:
/var/folders/sn/mpj6kgn55q9746zh_4sz95dm0000gn/T/vscode-go-debug.txt
09:30:55, 2018-7-18
InitializeRequest
InitializeResponse
Using GOPATH: /Users/erice/Desktop/tool_test/Go
Running: /Users/erice/Desktop/tool_test/Go/bin/dlv debug test1 --headless=true --listen=127.0.0.1:2345 --log=true --
API server listening at: 127.0.0.1:2345
time="2018-07-18T09:30:55+08:00" level=info msg="launching process with args: [/Users/erice/Desktop/tool_test/Go/src/test1/debug]" layer=debugger
could not launch process: listen tcp 185.199.108.153:0: bind: can't assign requested address
Process exiting with code: 1
Delve is closed
DisconnectRequest
```
