### ISSUE TITLE
list command shows assembly source code instead of go source code

### ISSUE THREAD

**Issue by hehailong5** [derekparker/delve#1148]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.0.0
2. What version of Go are you using? (`go version`)?
go1.8 linux/amd64
3. What operating system and processor architecture are you using?
4. What did you do?
dlv debug ./main
(dlv) list
5. What did you expect to see?
go source code
6. What did you see instead?
asm code as follow:
(dlv) l
> _rt0_amd64_linux() /usr/local/go/src/runtime/rt0_linux_amd64.s:8 (PC: 0x44e6e0)
     3: // license that can be found in the LICENSE file.
     4:
     5: #include "textflag.h"
     6:
     7: TEXT _rt0_amd64_linux(SB),NOSPLIT,$-8
=>   8:         LEAQ    8(SP), SI // argv
     9:         MOVQ    0(SP), DI // argc
    10:         MOVQ    $main(SB), AX
    11:         JMP     AX
    12:
    13: // When building with -buildmode=c-shared, this symbol is called when the shared
(dlv) q

**Comment by aarzilli** [comment]
Working as intended. When you start a program it will be stopped at the program's entry proint which, in the case of linux/amd64, is implemented in assembly. Set a breakpoint somewhere and continue.

**Comment by pysta3515** [comment]
if i just want to debug from the beginning of the program(like runtime) instead of main.main, what shoud i do please?
