### ISSUE TITLE
Trendmicro flags dlv as a Trojan and autodeletes it

### ISSUE THREAD

**Issue by stalwartgiraffe** [derekparker/delve#1161]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
what ever downloaded to windows 3/27/18
exe was removed by Antivirus

2. What version of Go are you using? (`go version`)?
go version go1.9.2 windows/amd64

3. What operating system and processor architecture are you using?
Win10 x64

4. What did you do?
On Windows 10 x64 with TrendMicro anti virus installed I ran
go get -u github.com/derekparker/delve/cmd/dlv   on 3/27/2018
I restarted my DOS cmd windows 
i started a small custom go lang web server
I ran the command 
dlv attach <PID>

5. What did you expect to see?
a debug session

6. What did you see instead?
Trendmicro flagged dlv as a threat and auto deleted the exe file
In the report it flagged the exe as a trojan HEU_AEGISCS003
and complained about ZwCreateThreadEx

I can whitelist dlv with Trendmicro but is there any way I can be assured that dlv.exe does not contain malware?

**Comment by aarzilli** [comment]
`go get` compiles from source, you can examine the source code. We could tell you that we didn't put malware in but if we did we would still tell you we didn't, so there's no reason to.

**Comment by stalwartgiraffe** [comment]
welp I guess I have to tell the AV "seems ligit".
