### ISSUE TITLE
# runtime/cgo _cgo_export.c:2:10: fatal error: 'stdlib.h' file not found

### ISSUE THREAD

**Issue by chenziliang** [derekparker/delve#1178]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.2
Build: v1.0.0-rc.2

2. What version of Go are you using? (`go version`)?
go version go1.9.3 darwin/amd64

3. What operating system and processor architecture are you using?
MACOS

4. What did you do?
Debug a test case by using `dlv test package`

5. What did you expect to see?
dlv shall attach the test case and start a debug session

6. What did you see instead?
# runtime/cgo _cgo_export.c:2:10: fatal error: 'stdlib.h' file not found

**Comment by derekparker** [comment]
Is that the full output? I assume the test runs fine without Delve? Also I notice you're on the last RC, would recommend upgrading to the real 1.0 release.

**Comment by chenziliang** [comment]
it is macOS High Sierra version 10.13.3

**Comment by aarzilli** [comment]
It's not clear what error you are getting. It's impossible that you are both getting a compile error (the stdlib thing) as well as a launch error. To fix the latter you have to install xcode's command line tools because for some reason (some versions of) lldb-server crashes on Go executables.

**Comment by chenziliang** [comment]
As I mentioned in the description, they are seperate sub commands dlv exec and dlv debug

**Comment by aarzilli** [comment]
Closed, no feedback.

**Comment by onepiecelyk** [comment]
> As I mentioned in the description, they are seperate sub commands dlv exec and dlv debug

Have you solved this problem?

**Comment by AlexCppns** [comment]
I have the same error since I upgraded macosx to Mojave (v10.14). I had to reinstall xcode too.

**Comment by pp5ere** [comment]
Did you install the essential package?
sudo apt-get update
sudo apt-get install build-essential
For me works!

**Comment by karluto** [comment]
@pp5ere  nice

**Comment by tunggnu** [comment]
It works! Thank you, @pp5ere

**Comment by AndrewMiao2021** [comment]
very nice, it is very kind of you!!! @pp5ere

**Comment by vinicius77** [comment]
You are a life saver @pp5ere . Thanks a ton!
