### ISSUE TITLE
[debugserver]Could not launch process: stub exited while waiting for connection: exit status 0

### ISSUE THREAD

**Issue by curelyreas** [derekparker/delve#1180]
1. What version of Delve are you using (`dlv version`)?
![image](https://user-images.githubusercontent.com/6175648/38628343-b6eb0f5c-3de3-11e8-9c9c-cd2e621fbdf8.png)
2. What version of Go are you using? (`go version`)?
![image](https://user-images.githubusercontent.com/6175648/38628370-c1f1fe88-3de3-11e8-8dc8-cf346166d45a.png)
3. What operating system and processor architecture are you using?
![image](https://user-images.githubusercontent.com/6175648/38628393-cf030c70-3de3-11e8-8c97-ce72ec637d39.png)
4. What did you do?
I update my go from 1.7.5 to 1.9. From then the dlv seems not working.

I try to downgrade the xcode command line tool's version(to Xcode 7.2) but no use.

Current lldb-server seems not support version sub command
![image](https://user-images.githubusercontent.com/6175648/38628544-2b0273da-3de4-11e8-9346-01ecc0295b4e.png)

And I try to add some log in dlv (gdbserver.go) and it print the args(send to debugserver/lldb-server). As below:
When using debugserver:
![image](https://user-images.githubusercontent.com/6175648/38628649-7ab513d8-3de4-11e8-8d1e-24d9fe6d3b7c.png)
![image](https://user-images.githubusercontent.com/6175648/38628705-9be7ba7e-3de4-11e8-843f-201e1b1bc07b.png)
When using lldb-server: Got a segmentation error
![image](https://user-images.githubusercontent.com/6175648/38628680-90b812a2-3de4-11e8-8dfd-552e963653ff.png)

5. What did you expect to see?
Normal debug

6. What did you see instead?
When using debugserver, got "could not launch process: stub exited while waiting for connection: exit status 0"
When using lldb-server, got segmentation error

Please kindly take a look.

**Comment by curelyreas** [comment]
Same result when try to debug other binary:
![image](https://user-images.githubusercontent.com/6175648/38629164-e0d5230a-3de5-11e8-9205-59edb6328e27.png)

**Comment by aarzilli** [comment]
This should all be reported to Apple, there's nothing we can do about it.

**Comment by evenluo** [comment]
Why this issue closed? Any solution? 
I have the same problem. And debug info is not enough to figure it out.
