### ISSUE TITLE
revision: ea335b3, Why `go test -run TestFindReturnAddress` not passed?

### ISSUE THREAD

**Issue by hitzhangjie** [derekparker/delve#1181]
Hi, I am learning how to develop a golang debugger, I have read the DWARF document and tracked your git commit log to learn little by little. The commit revision: ea335b3, I run TestFindReturnAddress to test whether the CFA is calculated correctly.

The test case doesn't pass, rsp+ret minus sizeof(uintptr)  can offer the right CFA which holds the caller return address. Please look at following pictures.

![issue](https://user-images.githubusercontent.com/3725760/38677061-b15ac26a-3e8f-11e8-9678-215ab96864cb.png)

Shouldn't the CFA points to the address which holds return address? In this test case, rsp + ret == CFA? Why have to minus sizeof(uintptr)?

I am confused with this, please help me! Thanks in advance!

**Comment by hitzhangjie** [comment]
Also, I noticed fde.CIE.ReturnAddressRegister == 16? It means R16? There's no that register in x86_64.
I read the DWARF document, it says CIE.return_address_register may not correspond to an actual machine register? So fde.CIE.ReturnAddressRegister means no such thing or something else?

Please help!

**Comment by aarzilli** [comment]
Yes, the answer is in the CIE:

```
00000000 0000000000000010 ffffffff CIE
  Version:               3
  Augmentation:          ""
  Code alignment factor: 1
  Data alignment factor: -4
  Return address column: 16

  DW_CFA_def_cfa: r7 (rsp) ofs 8
  DW_CFA_offset_extended: r16 (rip) at cfa-8
  DW_CFA_nop
```

This is the CIE that Go uses. Note how the return address column is 16 and that register 16 is at cfa-8. The mapping between dwarf register numbers and actual architecture registers can be found in "System V Application Binary Interface / AMD64 Architecture Processor Supplement" for linux_amd64.

**Comment by hitzhangjie** [comment]
@aarzilli Thanks very much, now I understand.
