### ISSUE TITLE
Non backwards-compatible change to --log

### ISSUE THREAD

**Issue by worrel** [derekparker/delve#1188]
1. What version of Delve are you using (`dlv version`)? 1.0.0
2. What version of Go are you using? (`go version`)? go1.10.1
3. What operating system and processor architecture are you using? MacOS 10.13.4
4. What did you do?

A week ago I was using Delve successfully to remote debug my Go app in Docker.  The Delve binary is pulled into the Docker image on each build using `go get` so it tracks the latest version at all times.  Recently (the last 2 days or so), it has stopped working with the error referenced in the title.

I ran a local test (outside Docker) where I still had the old Delve binary from a week ago.  I first attempted to run my debugging with the old binary (it worked), I then did `go get -u` to get latest Delve & attempted to run it again immediately - it failed.  Here's the shell output (which includes the Delve build IDs).  Note I've elided my company's package names.

```
➜  go build github.com/...<elided>.../cmd/server
➜  pwd
/Users/rory/code/go/src/github.com/.....<elided>
➜  dlv debug --headless --listen=:2345 --log github.com/...<elided>...
2018/04/18 18:37:14 server.go:73: Using API v1
2018/04/18 18:37:14 debugger.go:98: launching process with args: [/Users/rory/code/go/src/github.com/...<elided>..../debug]
API server listening at: [::]:2345
^C%                                                                                                                                                                                         ➜  dlv version
Delve Debugger
Version: 1.0.0
Build: a708d00e78bc9e6d344d66b4428820c061d35d83
➜  which dlv
/Users/rory/code/go/bin/dlv
```

Then I updated & tried again: 
```
➜  go get -u github.com/derekparker/delve/cmd/dlv
➜ dlv version
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
➜  dlv debug --headless --listen=:2345 --log github.com/...<elided>.../cmd/server
can't load package: package github.com/...<elided>.... no Go files in /Users/rory/code/go/src/github.com/...<elided>....
exit status 1
```

**Comment by worrel** [comment]
Hmm I believe the issue is actually that 4e177bb99acc511897f9cdbfc6cbc50d92ae4725 changed the `--log` CLI flag from a bool to a comma-separated string.

Changing the command line to the following fixes it:
```
dlv debug --headless --listen=:2345 --log=debugger github.com/...<elided>.../cmd/server
```

Note the `--log=debugger` instead of just `--log`

**Comment by aarzilli** [comment]
@derekparker I didn't consider that --log could be used without argument before, should we change --log back and add a different option?

**Comment by derekparker** [comment]
Yeah that’s very true, I definitely think we should reinstate the old behavior and add a new option.
