### ISSUE TITLE
CommandLineTools macOS

### ISSUE THREAD

**Issue by offwork** [derekparker/delve#1194]
1. dlv version: 1.0.0
2. go version go1.10 darwin/amd64
3. macOS - 2,5 GHz Intel Core i7
4. **I just want to be sure.** Does Delve have a specific path expectation for the command-line tool? So, is there any difference between /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin or Users/[user]/Library/Developer/CommandLineTools?

**Comment by aarzilli** [comment]
It looks for debugserver at /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver

**Comment by aarzilli** [comment]
Closed, no feedback

**Comment by ffffwh** [comment]
@aarzilli Would you consider to add a fall-back path
```
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver
```
