### ISSUE TITLE
Understand compressed debug info

### ISSUE THREAD

**Issue by dgryski** [derekparker/delve#1202]
1.11 will support zlib compressed debug info.

Upstream bug here: https://github.com/golang/go/issues/11799

**Comment by aarzilli** [comment]
AFAIK `debug/elf` already decompresses when needed and that should take care of it.

**Comment by dgryski** [comment]
Yup, the docs at https://golang.org/pkg/debug/elf seem to agree.  I guess I'll close this and reopen if there's any breakage when the patches land.

**Comment by heschik** [comment]
We're probably going to switch to zlib-gnu, i.e. `.zdebug_*`. `debug/elf` also supports that, but only in `(*elf.File).DWARF`. Some changes in bininfo.go will be necessary if we do compress.
