### ISSUE TITLE
Allow loading of separate debuginfo files

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#1206]
Right now Delve expects all DWARF debug info to be in the binary being executed. That isn't always the case as many Linux distributions ship the debug info files in their own packages which are installed separately.

**Comment by slp** [comment]
I have a working implementation for this, but as some distros apply dwz compression in addition to extracting the DWARF sections, I'm waiting for dwz support to be merged first. Otherwise, Delve would find the separate debug info file, but crash while opening, so it could be misleading.
