### ISSUE TITLE
which current IDEs support delve ?

### ISSUE THREAD

**Issue by knasim** [derekparker/delve#1207]
Are there any IDEs out there that support delve go debugger ?

**Comment by thanhhh** [comment]
You can use VS Code to debugging Go code. 
More detail here: https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code

**Comment by dlsniper** [comment]
All of them support Delve, see https://github.com/derekparker/delve/blob/master/Documentation/EditorIntegration.md
