### ISSUE TITLE
Vscode Debug : could not launch process: malformed qfThreadInfo response

### ISSUE THREAD

**Issue by shyamvenkat92** [derekparker/delve#1219]
could not launch process: malformed qfThreadInfo response (Mac)

**Comment by aarzilli** [comment]
I need to see the output of `--log --log-output=gdbwire`.

**Comment by shyamvenkat92** [comment]
dlv debug main.go --log --log-output=gdbwire
<- +
<- $QStartNoAckMode#b0
-> +
-> $OK#9a
<- +
<- $QThreadSuffixSupported#e4
-> $OK#00
<- $qSupported:swbreak+;hwbreak+;no-resumed+;xmlRegisters=i386#c5
-> $PacketSize=20000#00
<- $qRegisterInfo0#72
-> $name:rax;bitsize:64;offset:0;encoding:uint;format:hex;set:General Purpose Registers;gcc:0;dwarf:0;invalidate-regs:0,15,...
<- $qRegisterInfo1#73
-> $name:rbx;bitsize:64;offset:8;encoding:uint;format:hex;set:General Purpose Registers;gcc:3;dwarf:3;invalidate-regs:1,16,...
<- $qRegisterInfo2#74
-> $name:rcx;alt-name:arg4;bitsize:64;offset:16;encoding:uint;format:hex;set:General Purpose Registers;gcc:2;dwarf:2;generi...
<- $qRegisterInfo3#75
-> $name:rdx;alt-name:arg3;bitsize:64;offset:24;encoding:uint;format:hex;set:General Purpose Registers;gcc:1;dwarf:1;generi...
<- $qRegisterInfo4#76
-> $name:rdi;alt-name:arg1;bitsize:64;offset:32;encoding:uint;format:hex;set:General Purpose Registers;gcc:5;dwarf:5;generi...
<- $qRegisterInfo5#77
-> $name:rsi;alt-name:arg2;bitsize:64;offset:40;encoding:uint;format:hex;set:General Purpose Registers;gcc:4;dwarf:4;generi...
<- $qRegisterInfo6#78
-> $name:rbp;alt-name:fp;bitsize:64;offset:48;encoding:uint;format:hex;set:General Purpose Registers;gcc:6;dwarf:6;generic:...
<- $qRegisterInfo7#79
-> $name:rsp;alt-name:sp;bitsize:64;offset:56;encoding:uint;format:hex;set:General Purpose Registers;gcc:7;dwarf:7;generic:...
<- $qRegisterInfo8#7a
-> $name:r8;alt-name:arg5;bitsize:64;offset:64;encoding:uint;format:hex;set:General Purpose Registers;gcc:8;dwarf:8;generic...
<- $qRegisterInfo9#7b
-> $name:r9;alt-name:arg6;bitsize:64;offset:72;encoding:uint;format:hex;set:General Purpose Registers;gcc:9;dwarf:9;generic...
<- $qRegisterInfoa#a3
-> $name:r10;bitsize:64;offset:80;encoding:uint;format:hex;set:General Purpose Registers;gcc:10;dwarf:10;invalidate-regs:a,...
<- $qRegisterInfob#a4
-> $name:r11;bitsize:64;offset:88;encoding:uint;format:hex;set:General Purpose Registers;gcc:11;dwarf:11;invalidate-regs:b,...
<- $qRegisterInfoc#a5
-> $name:r12;bitsize:64;offset:96;encoding:uint;format:hex;set:General Purpose Registers;gcc:12;dwarf:12;invalidate-regs:c,...
<- $qRegisterInfod#a6
-> $name:r13;bitsize:64;offset:104;encoding:uint;format:hex;set:General Purpose Registers;gcc:13;dwarf:13;invalidate-regs:d...
<- $qRegisterInfoe#a7
-> $name:r14;bitsize:64;offset:112;encoding:uint;format:hex;set:General Purpose Registers;gcc:14;dwarf:14;invalidate-regs:e...
<- $qRegisterInfof#a8
-> $name:r15;bitsize:64;offset:120;encoding:uint;format:hex;set:General Purpose Registers;gcc:15;dwarf:15;invalidate-regs:f...
<- $qRegisterInfo10#a3
-> $name:rip;alt-name:pc;bitsize:64;offset:128;encoding:uint;format:hex;set:General Purpose Registers;gcc:16;dwarf:16;gener...
<- $qRegisterInfo11#a4
-> $name:rflags;alt-name:flags;bitsize:64;offset:136;encoding:uint;format:hex;set:General Purpose Registers;generic:flags;#00
<- $qRegisterInfo12#a5
-> $name:cs;bitsize:64;offset:144;encoding:uint;format:hex;set:General Purpose Registers;#00
<- $qRegisterInfo13#a6
-> $name:fs;bitsize:64;offset:152;encoding:uint;format:hex;set:General Purpose Registers;#00
<- $qRegisterInfo14#a7
-> $name:gs;bitsize:64;offset:160;encoding:uint;format:hex;set:General Purpose Registers;#00
<- $qRegisterInfo15#a8
-> $name:eax;bitsize:32;offset:0;encoding:uint;format:hex;set:General Purpose Registers;container-regs:0;invalidate-regs:0,...
<- $qRegisterInfo16#a9
-> $name:ebx;bitsize:32;offset:8;encoding:uint;format:hex;set:General Purpose Registers;container-regs:1;invalidate-regs:1,...
<- $qRegisterInfo17#aa
-> $name:ecx;bitsize:32;offset:16;encoding:uint;format:hex;set:General Purpose Registers;container-regs:2;invalidate-regs:2...
<- $qRegisterInfo18#ab
-> $name:edx;bitsize:32;offset:24;encoding:uint;format:hex;set:General Purpose Registers;container-regs:3;invalidate-regs:3...
<- $qRegisterInfo19#ac
-> $name:edi;bitsize:32;offset:32;encoding:uint;format:hex;set:General Purpose Registers;container-regs:4;invalidate-regs:4...
<- $qRegisterInfo1a#d4
-> $name:esi;bitsize:32;offset:40;encoding:uint;format:hex;set:General Purpose Registers;container-regs:5;invalidate-regs:5...
<- $qRegisterInfo1b#d5
-> $name:ebp;bitsize:32;offset:48;encoding:uint;format:hex;set:General Purpose Registers;container-regs:6;invalidate-regs:6...
<- $qRegisterInfo1c#d6
-> $name:esp;bitsize:32;offset:56;encoding:uint;format:hex;set:General Purpose Registers;container-regs:7;invalidate-regs:7...
<- $qRegisterInfo1d#d7
-> $name:r8d;bitsize:32;offset:64;encoding:uint;format:hex;set:General Purpose Registers;container-regs:8;invalidate-regs:8...
<- $qRegisterInfo1e#d8
-> $name:r9d;bitsize:32;offset:72;encoding:uint;format:hex;set:General Purpose Registers;container-regs:9;invalidate-regs:9...
<- $qRegisterInfo1f#d9
-> $name:r10d;bitsize:32;offset:80;encoding:uint;format:hex;set:General Purpose Registers;container-regs:a;invalidate-regs:...
<- $qRegisterInfo20#a4
-> $name:r11d;bitsize:32;offset:88;encoding:uint;format:hex;set:General Purpose Registers;container-regs:b;invalidate-regs:...
<- $qRegisterInfo21#a5
-> $name:r12d;bitsize:32;offset:96;encoding:uint;format:hex;set:General Purpose Registers;container-regs:c;invalidate-regs:...
<- $qRegisterInfo22#a6
-> $name:r13d;bitsize:32;offset:104;encoding:uint;format:hex;set:General Purpose Registers;container-regs:d;invalidate-regs...
<- $qRegisterInfo23#a7
-> $name:r14d;bitsize:32;offset:112;encoding:uint;format:hex;set:General Purpose Registers;container-regs:e;invalidate-regs...
<- $qRegisterInfo24#a8
-> $name:r15d;bitsize:32;offset:120;encoding:uint;format:hex;set:General Purpose Registers;container-regs:f;invalidate-regs...
<- $qRegisterInfo25#a9
-> $name:ax;bitsize:16;offset:0;encoding:uint;format:hex;set:General Purpose Registers;container-regs:0;invalidate-regs:0,1...
<- $qRegisterInfo26#aa
-> $name:bx;bitsize:16;offset:8;encoding:uint;format:hex;set:General Purpose Registers;container-regs:1;invalidate-regs:1,1...
<- $qRegisterInfo27#ab
-> $name:cx;bitsize:16;offset:16;encoding:uint;format:hex;set:General Purpose Registers;container-regs:2;invalidate-regs:2,...
<- $qRegisterInfo28#ac
-> $name:dx;bitsize:16;offset:24;encoding:uint;format:hex;set:General Purpose Registers;container-regs:3;invalidate-regs:3,...
<- $qRegisterInfo29#ad
-> $name:di;bitsize:16;offset:32;encoding:uint;format:hex;set:General Purpose Registers;container-regs:4;invalidate-regs:4,...
<- $qRegisterInfo2a#d5
-> $name:si;bitsize:16;offset:40;encoding:uint;format:hex;set:General Purpose Registers;container-regs:5;invalidate-regs:5,...
<- $qRegisterInfo2b#d6
-> $name:bp;bitsize:16;offset:48;encoding:uint;format:hex;set:General Purpose Registers;container-regs:6;invalidate-regs:6,...
<- $qRegisterInfo2c#d7
-> $name:sp;bitsize:16;offset:56;encoding:uint;format:hex;set:General Purpose Registers;container-regs:7;invalidate-regs:7,...
<- $qRegisterInfo2d#d8
-> $name:r8w;bitsize:16;offset:64;encoding:uint;format:hex;set:General Purpose Registers;container-regs:8;invalidate-regs:8...
<- $qRegisterInfo2e#d9
-> $name:r9w;bitsize:16;offset:72;encoding:uint;format:hex;set:General Purpose Registers;container-regs:9;invalidate-regs:9...
<- $qRegisterInfo2f#da
-> $name:r10w;bitsize:16;offset:80;encoding:uint;format:hex;set:General Purpose Registers;container-regs:a;invalidate-regs:...
<- $qRegisterInfo30#a5
-> $name:r11w;bitsize:16;offset:88;encoding:uint;format:hex;set:General Purpose Registers;container-regs:b;invalidate-regs:...
<- $qRegisterInfo31#a6
-> $name:r12w;bitsize:16;offset:96;encoding:uint;format:hex;set:General Purpose Registers;container-regs:c;invalidate-regs:...
<- $qRegisterInfo32#a7
-> $name:r13w;bitsize:16;offset:104;encoding:uint;format:hex;set:General Purpose Registers;container-regs:d;invalidate-regs...
<- $qRegisterInfo33#a8
-> $name:r14w;bitsize:16;offset:112;encoding:uint;format:hex;set:General Purpose Registers;container-regs:e;invalidate-regs...
<- $qRegisterInfo34#a9
-> $name:r15w;bitsize:16;offset:120;encoding:uint;format:hex;set:General Purpose Registers;container-regs:f;invalidate-regs...
<- $qRegisterInfo35#aa
-> $name:ah;bitsize:8;offset:1;encoding:uint;format:hex;set:General Purpose Registers;container-regs:0;invalidate-regs:0,15...
<- $qRegisterInfo36#ab
-> $name:bh;bitsize:8;offset:9;encoding:uint;format:hex;set:General Purpose Registers;container-regs:1;invalidate-regs:1,16...
<- $qRegisterInfo37#ac
-> $name:ch;bitsize:8;offset:17;encoding:uint;format:hex;set:General Purpose Registers;container-regs:2;invalidate-regs:2,1...
<- $qRegisterInfo38#ad
-> $name:dh;bitsize:8;offset:25;encoding:uint;format:hex;set:General Purpose Registers;container-regs:3;invalidate-regs:3,1...
<- $qRegisterInfo39#ae
-> $name:al;bitsize:8;offset:0;encoding:uint;format:hex;set:General Purpose Registers;container-regs:0;invalidate-regs:0,15...
<- $qRegisterInfo3a#d6
-> $name:bl;bitsize:8;offset:8;encoding:uint;format:hex;set:General Purpose Registers;container-regs:1;invalidate-regs:1,16...
<- $qRegisterInfo3b#d7
-> $name:cl;bitsize:8;offset:16;encoding:uint;format:hex;set:General Purpose Registers;container-regs:2;invalidate-regs:2,1...
<- $qRegisterInfo3c#d8
-> $name:dl;bitsize:8;offset:24;encoding:uint;format:hex;set:General Purpose Registers;container-regs:3;invalidate-regs:3,1...
<- $qRegisterInfo3d#d9
-> $name:dil;bitsize:8;offset:32;encoding:uint;format:hex;set:General Purpose Registers;container-regs:4;invalidate-regs:4,...
<- $qRegisterInfo3e#da
-> $name:sil;bitsize:8;offset:40;encoding:uint;format:hex;set:General Purpose Registers;container-regs:5;invalidate-regs:5,...
<- $qRegisterInfo3f#db
-> $name:bpl;bitsize:8;offset:48;encoding:uint;format:hex;set:General Purpose Registers;container-regs:6;invalidate-regs:6,...
<- $qRegisterInfo40#a6
-> $name:spl;bitsize:8;offset:56;encoding:uint;format:hex;set:General Purpose Registers;container-regs:7;invalidate-regs:7,...
<- $qRegisterInfo41#a7
-> $name:r8l;bitsize:8;offset:64;encoding:uint;format:hex;set:General Purpose Registers;container-regs:8;invalidate-regs:8,...
<- $qRegisterInfo42#a8
-> $name:r9l;bitsize:8;offset:72;encoding:uint;format:hex;set:General Purpose Registers;container-regs:9;invalidate-regs:9,...
<- $qRegisterInfo43#a9
-> $name:r10l;bitsize:8;offset:80;encoding:uint;format:hex;set:General Purpose Registers;container-regs:a;invalidate-regs:a...
<- $qRegisterInfo44#aa
-> $name:r11l;bitsize:8;offset:88;encoding:uint;format:hex;set:General Purpose Registers;container-regs:b;invalidate-regs:b...
<- $qRegisterInfo45#ab
-> $name:r12l;bitsize:8;offset:96;encoding:uint;format:hex;set:General Purpose Registers;container-regs:c;invalidate-regs:c...
<- $qRegisterInfo46#ac
-> $name:r13l;bitsize:8;offset:104;encoding:uint;format:hex;set:General Purpose Registers;container-regs:d;invalidate-regs:...
<- $qRegisterInfo47#ad
-> $name:r14l;bitsize:8;offset:112;encoding:uint;format:hex;set:General Purpose Registers;container-regs:e;invalidate-regs:...
<- $qRegisterInfo48#ae
-> $name:r15l;bitsize:8;offset:120;encoding:uint;format:hex;set:General Purpose Registers;container-regs:f;invalidate-regs:...
<- $qRegisterInfo49#af
-> $name:fctrl;bitsize:16;offset:168;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo4a#d7
-> $name:fstat;bitsize:16;offset:170;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo4b#d8
-> $name:ftag;bitsize:8;offset:172;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo4c#d9
-> $name:fop;bitsize:16;offset:173;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo4d#da
-> $name:fioff;bitsize:32;offset:175;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo4e#db
-> $name:fiseg;bitsize:16;offset:179;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo4f#dc
-> $name:fooff;bitsize:32;offset:181;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo50#a7
-> $name:foseg;bitsize:16;offset:185;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo51#a8
-> $name:mxcsr;bitsize:32;offset:187;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo52#a9
-> $name:mxcsrmask;bitsize:32;offset:191;encoding:uint;format:hex;set:Floating Point Registers;#00
<- $qRegisterInfo53#aa
-> $name:stmm0;bitsize:80;offset:195;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:33;dwarf:33;#00
<- $qRegisterInfo54#ab
-> $name:stmm1;bitsize:80;offset:205;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:34;dwarf:34;#00
<- $qRegisterInfo55#ac
-> $name:stmm2;bitsize:80;offset:215;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:35;dwarf:35;#00
<- $qRegisterInfo56#ad
-> $name:stmm3;bitsize:80;offset:225;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:36;dwarf:36;#00
<- $qRegisterInfo57#ae
-> $name:stmm4;bitsize:80;offset:235;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:37;dwarf:37;#00
<- $qRegisterInfo58#af
-> $name:stmm5;bitsize:80;offset:245;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:38;dwarf:38;#00
<- $qRegisterInfo59#b0
-> $name:stmm6;bitsize:80;offset:255;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:39;dwarf:39;#00
<- $qRegisterInfo5a#d8
-> $name:stmm7;bitsize:80;offset:265;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:40;dwarf:40;#00
<- $qRegisterInfo5b#d9
-> $name:xmm0;bitsize:128;offset:275;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:17;dwarf:17;#00
<- $qRegisterInfo5c#da
-> $name:xmm1;bitsize:128;offset:291;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:18;dwarf:18;#00
<- $qRegisterInfo5d#db
-> $name:xmm2;bitsize:128;offset:307;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:19;dwarf:19;#00
<- $qRegisterInfo5e#dc
-> $name:xmm3;bitsize:128;offset:323;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:20;dwarf:20;#00
<- $qRegisterInfo5f#dd
-> $name:xmm4;bitsize:128;offset:339;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:21;dwarf:21;#00
<- $qRegisterInfo60#a8
-> $name:xmm5;bitsize:128;offset:355;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:22;dwarf:22;#00
<- $qRegisterInfo61#a9
-> $name:xmm6;bitsize:128;offset:371;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:23;dwarf:23;#00
<- $qRegisterInfo62#aa
-> $name:xmm7;bitsize:128;offset:387;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:24;dwarf:24;#00
<- $qRegisterInfo63#ab
-> $name:xmm8;bitsize:128;offset:403;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:25;dwarf:25;#00
<- $qRegisterInfo64#ac
-> $name:xmm9;bitsize:128;offset:419;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:26;dwarf:26;#00
<- $qRegisterInfo65#ad
-> $name:xmm10;bitsize:128;offset:435;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:27;dwarf:27;#00
<- $qRegisterInfo66#ae
-> $name:xmm11;bitsize:128;offset:451;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:28;dwarf:28;#00
<- $qRegisterInfo67#af
-> $name:xmm12;bitsize:128;offset:467;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:29;dwarf:29;#00
<- $qRegisterInfo68#b0
-> $name:xmm13;bitsize:128;offset:483;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:30;dwarf:30;#00
<- $qRegisterInfo69#b1
-> $name:xmm14;bitsize:128;offset:499;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:31;dwarf:31;#00
<- $qRegisterInfo6a#d9
-> $name:xmm15;bitsize:128;offset:515;encoding:vector;format:vector-uint8;set:Floating Point Registers;gcc:32;dwarf:32;#00
<- $qRegisterInfo6b#da
-> $name:trapno;bitsize:32;offset:531;encoding:uint;format:hex;set:Exception State Registers;#00
<- $qRegisterInfo6c#db
-> $name:err;bitsize:32;offset:535;encoding:uint;format:hex;set:Exception State Registers;#00
<- $qRegisterInfo6d#dc
-> $name:faultvaddr;bitsize:64;offset:539;encoding:uint;format:hex;set:Exception State Registers;#00
<- $qRegisterInfo6e#dd
-> $E45#00
<- $QListThreadsInStopReply#21
-> $OK#00
<- $qGDBServerVersion#9b
-> $name:debugserver;version:@(#)P
<- $_M100,rwx#ca
-> ROGRAM:debugserver  PROJECT:debugserver-320.4.160...
<- $qfThreadInfo#bb
-> $4765000#00
could not launch process: malformed qfThreadInfo response

**Comment by aarzilli** [comment]
It looks like you are using a version of debugserver that is broken beyond what we can conceivably work around.

**Comment by shyamvenkat92** [comment]
Where i can get the stable build.

**Comment by aarzilli** [comment]
Closing, some old versions of debugserver are sending us a malformed version packet and there's nothing we can do about it.
