### ISSUE TITLE
Unable to debug Golang in VScode - invalid instruction at 0x91

### ISSUE THREAD

**Issue by LegoFriends** [derekparker/delve#1221]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?  
v0.12.2
2. What version of Go are you using? (`go version`)? 
go1.10.2 darwin/amd64
3. What operating system and processor architecture are you using?
MAC OS High Sierra 10.13.4
2.6GHz Inter core i7
4. What did you do?
I run my Golang project in VSCode. I am not able to see values of variables when i expand over them during debugging. If I add a watch the error says "Unable to evaluate expression : Invalid instruction at 0x91"
![screen shot 2018-05-31 at 4 55 40 pm](https://user-images.githubusercontent.com/23193856/40810559-c1c547f8-64f3-11e8-82b3-9256c0c9347e.png)

5. What did you expect to see?
I would like to see the variables expanded with their values while debugging
6. What did you see instead?
Variable values do not expand when i hover over them. If I add a watch, I see an error "Invalid Instruction at 0x91"

**Comment by aarzilli** [comment]
The VSCode-go plugin is maintained at https://github.com/Microsoft/vscode-go you either need to replicate this from the command line or post a log of the messages exchanged between VSCode-go and delve.

**Comment by LegoFriends** [comment]
@aarzilli can you please guide as to how do it " post a log of the messages exchanged between VSCode-go and delve."...i'm a novice at go and vscode...is it what i see in debugger or something else ?

**Comment by aarzilli** [comment]
>is it what i see in debugger or something else ?
No, it's the messages exchanged on the TCP/IP connection between VSCode-go and delve, I don't know how you would get them.

**Comment by alanjds** [comment]
> No, it's the messages exchanged on the TCP/IP connection between VSCode-go and delve, I don't know how you would get them.

The hard way is to use Wireshark or any tcpdump-like tool and capture the thing on the network "card" level.

Should be easier to get from VSCode, but the digging needed makes me inclined to do the Wireshark way.

**Comment by aarzilli** [comment]
Closing, no feedback.
