### ISSUE TITLE
error.go:36:2: no Go files in

### ISSUE THREAD

**Issue by jamesdenney** [derekparker/delve#1222]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.0.0
2. What version of Go are you using? (`go version`)? go version go1.10.2 linux/amd64
3. What operating system and processor architecture are you using? Ubuntu amd64
4. What did you do? 
Trying to debug a program in with vsCode using delve that is built using Bazel.  
5. What did you expect to see?
Debug the program
6. What did you see instead?
The Program contains a simple protocol buffer that Bazel converts into a library.  Program builds and runs successfully, but when debugging receive error.go:36:2: no Go files in referencing the library referencing the protocol buffer.

Error referenced in /sdk/utilities/error/protoo

package main

import (
	"fmt"
	"/sdk/utilities/error/proto"
)

func main() {
	var hello = "Hello"

	fmt.Printf(hello)
	fmt.Printf(proto.ErrorCode_SUCCESS.String())
}

**Comment by aarzilli** [comment]
Delve will build everything using the go command. If you are using another build system (for example bezel) you need to configure that build system to output a non-optimized binary and then debug the binary directly using `dlv exec`.
