### ISSUE TITLE
Updating to latest version of dlv on Windows platform

### ISSUE THREAD

**Issue by sekeroth** [derekparker/delve#1225]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? Version: 1.0.0-rc.2
2. What version of Go are you using? (`go version`)? 1.10.2
3. What operating system and processor architecture are you using? Windows 10/AMD64
4. What did you do? I am using VS Code and the go plug-in. I attempted to update the tools using the built-in command Go: install/update tools. I also attempted to update using the command line: "go get -u github.com/derekparker/delve/cmd/dlv", but dlv remains at Version: 1.0.0-rc.2. Based on the timestamps, the files are being updated, just not to the latest version.
5. What did you expect to see? Version: 1.0.0
6. What did you see instead? Version: 1.0.0-rc.2

The gopath is set correctly and everything seems to function, except that I am not on the latest version.

Any suggestions? TIA

**Comment by aarzilli** [comment]
`go install github.com/derekparker/delve/cmd/dlv`

**Comment by aarzilli** [comment]
You are probably running dlv from somewhere other than $GOPATH/bin.

**Comment by sekeroth** [comment]
@aarzilli Thank you, I rechecked the path environment and indeed found the duplicate.
