### ISSUE TITLE
Cannot see values of *<string> anymore

### ISSUE THREAD

**Issue by AlexRRR** [derekparker/delve#1228]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
2. What version of Go are you using? (`go version`)?
go version go1.10 darwin/amd64
3. What operating system and processor architecture are you using?
Mac OS X High Sierra 10.13.5
4. What did you do?
Using VSCode I placed a breakpoint in the line with the `if` in this snippet
```go
	expectedVolID := "vol-aaaaaaa"
	volID := awsEC2.getVolumeID("foo")
	if *volID != expectedVolID {
		t.Errorf("volID is not the same\t voldId: %v Expected %s", *volID, expectedVolID)
	}
```
5. What did you expect to see?
Before I was able to see the value of `volID` even if it was a pointer in the debug `variables` window.
6. What did you see instead?
```
volID: *<string>
```
and if I use the debug Terminal and try to print the values I get `not available`

I might be misunderstanding something very basic of how Delve (or even golang as I am newbie) works, but I recall this working before the whole problem with XCode Command line tools.

**Comment by aarzilli** [comment]
The plugin for VSCode is maintained [here](https://github.com/Microsoft/vscode-go). They recently switched to our v2 API, which may have caused this bug. If you have reasons to believe this is a bug with delve and not vscode-go you should reproduce this with the command line client of delve or capture the packet exchange between delve and vscode using tcpdump/wireshark.

**Comment by AlexRRR** [comment]
Thanks @aarzilli , It seems I am barking at the wrong tree.  From the console:
```    
    54:		volID := awsEC2.getVolumeID("foo")
=>  55:		if *volID != expectedVolID {
...

(dlv) print volID
*"vol-aaaaaaa"
```

This is what I was expecting to see, also thank you for pointing me to the correct place to discuss the problem.
