### ISSUE TITLE
Trojan:Script/Cloxer.D!cl

### ISSUE THREAD

**Issue by NlaakStudios** [derekparker/delve#1238]
Please answer the following before submitting your issue:

Was working on a GO program, and started getting Windows Defender Threat Warning Trojan:Script/Cloxer.D!cl detected in Delve executable. I deleted the folder and used go get again and the same thing. I have been using it for a week with no issue until now.

1. What version of Delve are you using (`dlv version`)? latest
2. What version of Go are you using? (`go version`)? go1.10 
3. What operating system and processor architecture are you using? windows10/amd64
4. What did you do? Nothing! Just started.
5. What did you expect to see? No Virus?
6. What did you see instead? A Virus! LOL

**Comment by dlsniper** [comment]
Report this to your anti-virus of choice as a false positive, after you audit the code that compiled that binary and see there's no virus in it.
