### ISSUE TITLE
can not hit breakpoints in multi-goroutine 

### ISSUE THREAD

**Issue by xujintao** [derekparker/delve#1241]
1. dlv version
Delve Debugger
Version: 1.0.0

2. go version
go version go1.9.2 

3. What operating system and processor architecture are you using?
windows/amd64

4. What did you do?
my test code looks like this:
```
1. package main
2. 
3. import (
4. 	"fmt"
5. 	"sync"
6. )
7. 
8. func main() {
9. 	var wg sync.WaitGroup
10. 	wg.Add(1)
11. 	go func() {
12. 		for i := 0; i < 100; i++ {
13. 			fmt.Printf("[%s:%d] ", "g1", i)
14. 		}
15. 		wg.Done()
16. 	}()
17. 
18. 	wg.Add(1)
19. 	go func() {
20. 		for i := 0; i < 100; i++ {
21. 			fmt.Printf("[%s:%d] ", "g2", i)
22. 		}
23. 		wg.Done()
24. 	}()
25. 
26. 	wg.Wait()
27. 	fmt.Println("end")
28. }
````
I add breakpoint on line 12, 20 and 26, then run it with vscode. After that, I tried dlv CLI debugger.

5. What did you expect to see?
When run into a goroutine, it should hit the breakpoint.

6. What did you see instead?

vscode, 
press F5, 
it hit breakpoint 12, 
next
hit breakpoint 20, 
next
it run away, and the console print "Failed to next".

dlv CLI, 
continue,
it hit breakpoint 12,
next
it just keep run 'for loop' in g1(the first go routine), and never hit breakpoint 20, but the second goroutine  do actually run and execute the fmt.Printf statement even output the result to stdout.
Several nexting, it run away finally and I can not use quit command to end, only ctrl+c force.

**Comment by aarzilli** [comment]
Without either a trace of the messages exchanged between dlv and VSCode or a transcript of the interaction with the command line client it's hard to say for sure that there is a delve bug here.

> press F5,
> it hit breakpoint 12,
> next
> hit breakpoint 20,
> next
> it run away, and the console print "Failed to next".

This doesn't surprise me, it just sounds like VSCode can't handle breakpoints during a next operation. If that's the case it's a bug with VSCode.

> it just keep run 'for loop' in g1(the first go routine), and never hit breakpoint 20, but the second goroutine do actually run and execute the fmt.Printf statement even output the result to stdout.

This is by design. With the command line client if you request next you will stay on the same goroutine, if another breakpoint is hit during next it will be print but execution of the program will not stop.

**Comment by xujintao** [comment]
@aarzilli 

> This is by design. With the command line client if you request next you will stay on the same goroutine, if another breakpoint is hit during next it will be print but execution of the program will not stop.

Dlv cli can only keep track with  a unique goroutine, and it do not jump into breakpoints which come from others goroutine.
Whether my understand is correct?

**Comment by aarzilli** [comment]
No, delve keeps track of all goroutines but `next` , `step` and `stepout` in the command line client will keep you in the same goroutine, just notifying of breakpoints that happen in other goroutines.

**Comment by xujintao** [comment]
1. Put 3 breakpoints, then continue and goroutines.

> $ dlv debug main.go
b main.go:12
b main.go:20
b main.go:26
c
-> main.main.func1() E:/GoPath/src/test/testdlv/main.go:12 (hits goroutine(18):1 total:1) (PC: 0x4b8026)
     7:
     8: func main() {
     9:         var wg sync.WaitGroup
    10:         wg.Add(1)
    11:         go func() {
=>  12:                 for i := 0; i < 100; i++ {
    13:                         fmt.Printf("[%s:%d] ", "g1", i)
    14:                 }
    15:                 wg.Done()
    16:         }()
    17:
goroutines
[6 goroutines]
  Goroutine 1 - User: E:/GoPath/src/test/testdlv/main.go:26 main.main (0x4b7f54) (thread 17188)
  Goroutine 2 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 3 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 17 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
->Goroutine 18 - User: E:/GoPath/src/test/testdlv/main.go:12 main.main.func1 (0x4b8026) (thread 15656)
  Goroutine 19 - User: E:/GoPath/src/test/testdlv/main.go:19 main.main.func2 (0x4b81b0)
goroutines
[6 goroutines]
  Goroutine 1 - User: E:/GoPath/src/test/testdlv/main.go:26 main.main (0x4b7f54) (thread 17188)
  Goroutine 2 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 3 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 17 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
->Goroutine 18 - User: E:/GoPath/src/test/testdlv/main.go:12 main.main.func1 (0x4b8026) (thread 15656)
  Goroutine 19 - User: E:/GoPath/src/test/testdlv/main.go:19 main.main.func2 (0x4b81b0)

Now g1, g18, g19 begin work, dlv cli selected g18 maybe because g18 got thread.

2. g18 next and goroutines.

> n
-> main.main.func1() E:/GoPath/src/test/testdlv/main.go:13 (PC: 0x4b8041)
     8: func main() {
     9:         var wg sync.WaitGroup
    10:         wg.Add(1)
    11:         go func() {
    12:                 for i := 0; i < 100; i++ {
=>  13:                         fmt.Printf("[%s:%d] ", "g1", i)
    14:                 }
    15:                 wg.Done()
    16:         }()
    17:
    18:         wg.Add(1)
goroutines
[6 goroutines]
  Goroutine 1 - User: E:/GoPath/src/test/testdlv/main.go:26 main.main (0x4b7f54) (thread 17188)
  Goroutine 2 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 3 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 17 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
->Goroutine 18 - User: E:/GoPath/src/test/testdlv/main.go:13 main.main.func1 (0x4b8041) (thread 15656)
  Goroutine 19 - User: E:/GoPath/src/test/testdlv/main.go:19 main.main.func2 (0x4b81b0)

Dlv cli  keeps track with g18 resulted in g18 goes to line 13, nothing special happened.

3. g18 next and goroutines again.

>n
> main.main() E:/GoPath/src/test/testdlv/main.go:26 (hits goroutine(1):1 total:1) (PC: 0x4b7f53)
        breakpoint hit during next, continuing...
> main.main.func2() E:/GoPath/src/test/testdlv/main.go:20 (hits goroutine(19):1 total:1) (PC: 0x4b81e6)
        breakpoint hit during next, continuing...
[g2:0] [g2:1] [g2:2] [g2:3] [g2:4] [g2:5] [g2:6] [g2:7] [g2:8] [g2:9] [g2:10] [g2:11] [g2:12] [g2:13] [g2:14] [g2:15] [g2:16] [g2:17] [g2:18] [g2:19] [g2:20] [g2:21] [g2:22] [g2:23] [g2:24] [g2:25] [g2:26] [g2:27] [g2:28] [g2:29] [g2:30] [g2:31] [g2:32] [g2:33] [g2:34] [g2:35] [g2:36] [g2:37] [g2:38] [g2:39] [g2:40] [g2:41] [g2:42] [g2:43] [g2:44] [g2:45] [g2:46] [g2:47] [g2:48] [g2:49] [g2:50] [g2:51] [g2:52] [g2:53] [g2:54] [g2:55] [g2:56] [g2:57] [g2:58] [g2:59] [g2:60] [g2:61] [g2:62] [g2:63] [g2:64] [g2:65] [g2:66] [g2:67] [g2:68] [g2:69] [g2:70] [g2:71] [g2:72] [g2:73] [g2:74] [g2:75] [g2:76] [g2:77] [g2:78] [g2:79] [g2:80] [g2:81] [g2:82] [g2:83] [g2:84] [g2:85] [g2:86] [g2:87] [g2:88] [g2:89] [g2:90] [g2:91] [g2:92] [g2:93] [g2:94] [g2:95] [g2:96] [g2:97] [g2:98] [g2:99] [g1:0] > main.main.func1() E:/GoPath/src/test/testdlv/main.go:12 (PC: 0x4b8154)
     7:
     8: func main() {
     9:         var wg sync.WaitGroup
    10:         wg.Add(1)
    11:         go func() {
=>  12:                 for i := 0; i < 100; i++ {
    13:                         fmt.Printf("[%s:%d] ", "g1", i)
    14:                 }
    15:                 wg.Done()
    16:         }()
    17:
goroutines
[5 goroutines]
  Goroutine 1 - User: C:/Go/src/runtime/sema.go:56 sync.runtime_Semacquire (0x43bdd0)
  Goroutine 2 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 3 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 17 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
->Goroutine 18 - User: E:/GoPath/src/test/testdlv/main.go:12 main.main.func1 (0x4b8154) (thread 17164)

The output log shows that g1 and g19 both "breakpoint hit during next, continuing..." which result in g1 block and g19 done, exit. 
Why dlv cli can not switch to g1 or g19? For both of them got thread at this point. Once what i understand is that when a thread got cpu, it should be executed and be tracked by IDE or any debugger.

4. Put another breakpoint, then continue and goroutines

>b main.go:27
Breakpoint 4 set at 0x4b7f61 for main.main() E:/GoPath/src/test/testdlv/main.go:27
c
[g1:1] [g1:2] [g1:3] [g1:4] [g1:5] [g1:6] [g1:7] [g1:8] [g1:9] [g1:10] [g1:11] [g1:12] [g1:13] [g1:14] [g1:15] [g1:16] [g1:17] [g1:18] [g1:19] [g1:20] [g1:21] [g1:22] [g1:23] [g1:24] [g1:25] [g1:26] [g1:27] [g1:28] [g1:29] [g1:30] [g1:31] [g1:32] [g1:33] [g1:34] [g1:35] [g1:36] [g1:37] [g1:38] [g1:39] [g1:40] [g1:41] [g1:42] [g1:43] [g1:44] [g1:45] [g1:46] [g1:47] [g1:48] [g1:49] [g1:50] [g1:51] [g1:52] [g1:53] [g1:54] [g1:55] [g1:56] [g1:57] [g1:58] [g1:59] [g1:60] [g1:61] [g1:62] [g1:63] [g1:64] [g1:65] [g1:66] [g1:67] [g1:68] [g1:69] [g1:70] [g1:71] [g1:72] [g1:73] [g1:74] [g1:75] [g1:76] [g1:77] [g1:78] [g1:79] [g1:80] [g1:81] [g1:82] [g1:83] [g1:84] [g1:85] [g1:86] [g1:87] [g1:88] [g1:89] [g1:90] [g1:91] [g1:92] [g1:93] [g1:94] [g1:95] [g1:96] [g1:97] [g1:98] [g1:99] > main.main() E:/GoPath/src/test/testdlv/main.go:27 (hits goroutine(1):1 total:1) (PC: 0x4b7f61)
    22:                 }
    23:                 wg.Done()
    24:         }()
    25:
    26:         wg.Wait()
=>  27:         fmt.Println("end")
    28: }
goroutines
[4 goroutines]
->Goroutine 1 - User: E:/GoPath/src/test/testdlv/main.go:27 main.main (0x4b7f61) (thread 17164)
  Goroutine 2 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 3 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)
  Goroutine 17 - User: C:/Go/src/runtime/proc.go:288 runtime.gopark (0x42edd4)

g18 done and exit too, dlv cli switches current goroutine to g1 and keeps track with g1.

**Comment by aarzilli** [comment]
> Why dlv cli can not switch to g1 or g19?

it could but it's designed not to when you use next.

**Comment by xujintao** [comment]
@aarzilli thanks.

**Comment by aarzilli** [comment]
You're welcome.
