### ISSUE TITLE
Continue command prints nothing on error if there is no current file

### ISSUE THREAD

**Issue by kinwyb** [derekparker/delve#1244]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: 9add777235d3e7c1b1897a4a7cf3bbdf60fc82ea

2. What version of Go are you using? (`go version`)?
go version go1.10.3

3. What operating system and processor architecture are you using?
macOS 10.13.4

4. What did you do?
```
func main(t *testing.T) {
	var p *objs.ArchivesPostDB
	fmt.Print(p.Name)
}
```
5. What did you expect to see?
print painc information

6. What did you see instead?
program is clog up I can not see anything or doing anything

**Comment by kinwyb** [comment]
sorry, this problem because I not use--backend=native

**Comment by aarzilli** [comment]
you should be more specific about the output you are getting.

**Comment by kinwyb** [comment]
@aarzilli Thank you for your reply
The problem is that when panic occurs, the whole program stops blocking, I can't see any output, I can't operate anything, I can only stop the program running

**Comment by aarzilli** [comment]
Run with `--log --log-output=gdbwire` and copy the output here.

**Comment by kinwyb** [comment]
@aarzilli  Command failed: bad access
[dlv.log](https://github.com/derekparker/delve/files/2336802/dlv.log)

**Comment by aarzilli** [comment]
Because of #852 the execution of the target will stop immediately after a SIGSEGV is received, it's strange that it doesn't print the listing of the program. What happens if you give the `list` command?

**Comment by kinwyb** [comment]
@aarzilli print 
DEBU[0058] -> $00600f00c000000000a00f00c000000070630f00c0000000ffffffffffffffff000000000000000000605100c000000000ec1300c0000000288f0f0...  layer=gdbconn
Command failed: bad access
(dlv) list
DEBU[0064] <- $mc0000cef00,178#ea                        layer=gdbconn
DEBU[0064] -> $00600f00c000000000a00f00c000000070630f00c0000000ffffffffffffffff000000000000000000605100c000000000ec1300c0000000288f0f0...  layer=gdbconn
Stopped at: 0x7fff7046ba16
=>no source available
