### ISSUE TITLE
latest dlv version cannot debug go (VSCode hangs)

### ISSUE THREAD

**Issue by ywhlhy** [derekparker/delve#1245]
One days ago,I change system,I use command "go get -u github.com/derekparker/delve/cmd/dlv" to install the dlv ,i installed success.But I press F5 on visual studio code,it cannot run normal,the info msg as follows:

Verbose logs are written to:
C:\Users\mynam\AppData\Local\Temp\vscode-go-debug.txt
23:18:19, 2018-6-23
InitializeRequest
InitializeResponse
Using GOPATH: D:\GoProjects
Running: D:\GoProjects\bin\dlv.exe debug LearnGo --headless=true --listen=127.0.0.1:2345 --log=true --
time="2018-06-23T23:18:19+08:00" level=info msg="launching process with args: [D:\\GoProjects\\src\\LearnGo\\debug]" layer=debugger

**Comment by Ch3ck3r** [comment]
I can confirm this problem on a arch linux machine

```
~/go/src/github.com/derekparker/delve $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
```
go version
go version go1.10.3 linux/amd64
```

```
code -v
1.24.1
24f62626b222e9a8313213fb64b10d741a326288
x64
```

launch.json (basically auto-generated and not modified - except for the port)
```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "go",
			"request": "launch",
			"mode": "debug",
			"remotePath": "",
			"port": 7927,
			"host": "127.0.0.1",
			"program": "${fileDirname}",
			"env": {},
			"args": [],
			"showLog": true,
			"trace": "verbose"
		}
	]
}
```

Up on starting the debugger (in vscode) the following is printed in the console
```
Verbose logs are written to:
/tmp/vscode-go-debug.txt
03:57:53, 2018-6-24
InitializeRequest
InitializeResponse
Using GOPATH: $HOME/go
Running: $HOME/go/bin/dlv debug helloworld --headless=true --listen=127.0.0.1:7927 --log=true --
time="2018-06-24T03:57:53+02:00" level=info msg="launching process with args: [$HOME/go/src/helloworld/debug]" layer=debugger
```

Nothing happens after this output. The debugger just hangs and does nothing. If I enter anything in the debugging console (e.g. ``help``) the following output is printed:
```
help
Please start a debug session to evaluate
```

But I am not sure this is a delve bug. Maybe this is a bug in vscode or the golang extensions of vscode. Using standalone dlv from the command line works fine.

**Comment by Ch3ck3r** [comment]
For cross reference: https://github.com/Microsoft/vscode-go/issues/1752

**Comment by alexaung** [comment]
I am also facing same issue after reinstall go 1.10.3 and delve. Even I downgrade to go 1.9.7, click F5 and debugger is not start but hang. After a few minute, I got the "Launch/Request" time out.

**Comment by aarzilli** [comment]
VSCode-go is [maintained here](https://github.com/Microsoft/vscode-go). To determine if this is actually a problem with delve I would need to see delve's output when passing `--log --log-output=rpc`.

**Comment by Ch3ck3r** [comment]
I don't know of any way passing the --log-output=rpc parameter to delve from vscode. Specifying this parameter in launch.json's args property (``"args": ["--log-output=Rpc"]``) will pass it to the launched program, but not to delve itself.

```
Running: $HOME/go/bin/dlv debug helloworld --headless=true --listen=127.0.0.1:7927 --log=true -- --log-output=rpc
```

I still think this is a problem of vscode go plugin as you can find a temporary fix over in their issue https://github.com/Microsoft/vscode-go/issues/1752#issuecomment-399689880

**Comment by ywhlhy** [comment]
I change the lanuch.json:"args": ["--log-output=Rpc"],the debug info as follow:

Verbose logs are written to:
C:\Users\mynam\AppData\Local\Temp\vscode-go-debug.txt
08:49:19, 2018-6-25
InitializeRequest
InitializeResponse
Using GOPATH: D:\GoProjects
Running: D:\GoProjects\bin\dlv.exe debug GoLearns --headless=true --listen=127.0.0.1:2345 --log=true -- --log-output=Rpc
time="2018-06-25T08:49:22+08:00" level=info msg="launching process with args: [d:\\GoProjects\\src\\GoLearns\\debug --log-output=Rpc]" layer=debugger

**Comment by lggomez** [comment]
This comment gives some insight into the issue: https://github.com/Microsoft/vscode-go/issues/1752#issuecomment-399803563

So it seems that logrus' default stream is stderr, which breaks the vs code debug adapter as it awaits/initializes the rpc connection to delve via its stdout listener only

@aarzilli is there any reason to switch those messages to stderr aside from logrus having it as the default?

**Comment by ywhlhy** [comment]
I reinstall dlv by the command"go get -v -u github.com/peterh/linergithub.com/derekparker/delve/cmd/dlv",After I debug successed.

**Comment by dev-piyushkumar** [comment]
Facing same issue in latest delve in mac os Big Sur 11.3.1 in my MacBook Pro (Retina, 13-inch, Early 2015) with go version 1.15.7 and vscode version 1.56.2. Although if i remove `"port"` and `"host"` and set `"mode": "auto"` in `launch.json` then it works perfectly.

**Comment by hyangah** [comment]
@dev-piyushkumar This bug was from 2018, and it's likely a different issue. Your description of the issue sounds a lot like VSCode side integration issue. Do you mind filing an issue in github.com/golang/vscode-go repo? Please include your launch configuration `launch.json` and `"go.delveConfig"` setting from `settings.json` when you file a new issue. Thanks!
