### ISSUE TITLE
Go debugger does not single-step 

### ISSUE THREAD

**Issue by bhabermaas** [derekparker/delve#1246]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
2. What version of Go are you using? (`go version`)?
go version go1.10.1 darwin/amd64
3. What operating system and processor architecture are you using?
macOS High Sierra Intel Core I7

4. What did you do?  Debug under VSCode and set breakpoint.
5. What did you expect to see? to be able to single step statements
6. What did you see instead? single step seems to work the same a run to next breakpoint

I tried to update Delv but it fails with - 
==> Installing delve from go-delve/delve
==> Installing dependencies for go-delve/delve/delve: go
Error: Cannot link go
Another version is already linked: /usr/local/Cellar/go/1.10.1

**Comment by aarzilli** [comment]
The homebrew recipe is not supported anymore.
