### ISSUE TITLE
[Feature Request] support multiple files when build

### ISSUE THREAD

**Issue by hiberabyss** [derekparker/delve#1248]
We could specify multiple files when run test:

```
go test -c 695.max-area-of-island_test.go 695.max-area-of-island.go
```

However, when try to run this way with `dlv test`, there will be error:

```
dlv test 695.max-area-of-island_test.go 695.max-area-of-island.go
```

Seems the second file won't be considered. Could this be improved?

Thanks!

**Comment by aarzilli** [comment]
I don't think this is very useful.

**Comment by hiberabyss** [comment]
Hi @aarzilli ,

In case there are many go files in same directory, this will be very useful. It's also a good thing that the behavior of `go test` and `dlv test` keep consistent.

Thanks!

**Comment by chainhelen** [comment]
#1339
