### ISSUE TITLE
Cannot Start Debugging

### ISSUE THREAD

**Issue by Ritzpak** [derekparker/delve#1257]
1. What version of Delve are you using (`dlv version`)?
5cd86b1
2. What version of Go are you using? (`go version`)?
go1.10.3.windows-amd64
3. What operating system and processor architecture are you using?
Windows Server 2016 Datacenter x64
Visual Studio Code v1.24.1 x64
4. What did you do?
Followed the install instructions.
5. What did you expect to see?
Hitting a breakpoint.
6. What did you see instead?
Error message: Can not debug non-main package.

I can Start Without Debugging and get my Println message so I know it compiles, but when I try Start Debugging, I get an error.  I'm just getting started in Go and have only installed what is recommended so far.  Not sure if there are conflicts or what.  This should be extremely simple, but for some reason it won't run.
![vscerror](https://user-images.githubusercontent.com/1278990/42111627-0b0ca69c-7bb3-11e8-95eb-948dae186879.PNG)
![image](https://user-images.githubusercontent.com/1278990/42111698-4a3504f4-7bb3-11e8-9a38-b6edfc981db4.png)

**Comment by gertcuykens** [comment]
Try using `dlv debug` on the command line and see if you can reproduce to make sure it's not vscode

**Comment by aarzilli** [comment]
Problems with VSCode-go should be reported [here](https://github.com/Microsoft/vscode-go).
