### ISSUE TITLE
unable to process inlined functions (go1.11)

### ISSUE THREAD

**Issue by hyangah** [derekparker/delve#1261]
<pre>
package main

import "fmt"

func main() {
        x := &X{Foo: 10}          // line 6
        y := InlineThis(x, "bar") // line 7
        fmt.Printf("Y = %+v\n", y)
}

type X struct {
        Foo int
}

func InlineThis(x *X, s string) *X {
        xx := &X{}
        xx.Foo = x.Foo + len(s) // line 17
        return xx
}
</pre>

I expect dlv to do the right thing with optimized binaries when compiled with go1.11
but currently it is still unhappy about inlined functions.

 - funcs command doesn't recognize the inlined functions
 - can't set break point to the line where the inlined function is called (line 7).
 
I could set break points inside the inlined function though (line 16 or line 17).
'bt' from there (inside the inlined func) seemed reasonable.

<pre>
$ go build main.go
$ dlv exec ./main
Type 'help' for list of commands.
(dlv) funcs InlineThis
(dlv) b main.go:6
Breakpoint 1 set at 0x485f21 for main.main() ./main.go:6
(dlv) b main.go:7
Command failed: could not find /usr/local/google/home/hakim/go/src/s/main.go:7
(dlv) b main.go:8
Breakpoint 2 set at 0x485f4b for main.main() ./main.go:8
(dlv) b main.go:17
Breakpoint 3 set at 0x485f3f for main.main() ./main.go:17
</pre>

The versions of go, dlv I used.

<pre>
$ go version
go version devel +23ce272bb1 Mon Jul 2 17:50:00 2018 +0000 linux/amd64
$ dlv version
Delve Debugger
Version: 1.0.0
Build: bdcbd8a846eb7d4953449725ef6a23959198acf1
</pre>

**Comment by derekparker** [comment]
I've figured out why this is happening. When we parse the DWARF information we store it in memory to avoid reading / seeking / etc later. During this process, for subprograms, we have a predicate that the subprogram tag must contain a PC range, which obviously an inlined routine would not. I'll work on this.

**Comment by derekparker** [comment]
We're also not using the abstract / concrete inline information. Since the line number table technically doesn't have an entry for `main.go:7` once that function call has been inlined, we have to use the concrete `DW_TAG_inlined_subroutine` high/low PC and call file/line. 

I'm working on a patch for this now, but likely won't finish today and I'll be on holiday tomorrow. Should have this fixed by Thursday.

**Comment by derekparker** [comment]
Had to divert into other work, but expect to finish this up tomorrow.

**Comment by derekparker** [comment]
Been working on this when I can in between $WORK projects, but that load has lightened up a bit so I expect to have plenty of time to hack on this tomorrow.
