### ISSUE TITLE
Detach command doesnt clean up the debug binary that delve creates if the program being debugged spawns processes of its own

### ISSUE THREAD

**Issue by ramya-rao-a** [derekparker/delve#1270]
The debug adapter in the Go extension for VS Code calls the `Detach` method on the api server in the end of the debugging session expecting delve to clean up the debug binary it created and close all the processes it might have spawned.

The cleaning up of the debug binary does happen as long as the program being debugged is a simple one that does not spawn any processes. The spawned processes get killed only in Windows and not in Mac.

I've tried both v1 and v2 of the apis. Same result.

The code I have used for testing are in the repo https://github.com/golang/example
- The simple hello program (the debug binary gets cleared up without issues)
- The outyet program that spawns a web server. (the debug binary doesnt get cleared in both Mac and Windows. The spawned process for web server is not killed in Mac)

1. What version of Delve are you using (`dlv version`)?
1.0.0 (c98a142125d0b17bb11ec0513bde346229b5f533)
2. What version of Go are you using? (`go version`)?
1.9 on Windows, 1.10.3 on Mac
3. What operating system and processor architecture are you using?
windows/amd64 and darwin/amd64
4. What did you do?,  5. What did you expect to see?, 6. What did you see instead?
All explained above

**Comment by ramya-rao-a** [comment]
Note: If you use VS Code to get a repro for the above, please follow the below instructions. I havent released an update with the changes that uses the `Detach` command.

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by aarzilli** [comment]
Can't reproduce this on macOS using the command line client with a headless (accept-multiclient) instance. The process gets killed and the debug binary cleaned up. Judging from https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L457 I'm wondering if you aren't sending the Detach call while the target is running: that won't work, the target needs to be stopped, either at a breakpoint or manually by using the halt command.

There is a known problem with the windows backend not deleting the debug binary sometimes (but not systematically) that we could never figure out.

**Comment by ramya-rao-a** [comment]
> that won't work, the target needs to be stopped, either at a breakpoint or manually by using the halt command.

That was it! By halting and then detaching, I can confirm that not only do the binaries get cleaned up but the spawned processes get killed as well. Thanks!

Please consider a PR to add the above to your docs #1272
