### ISSUE TITLE
Single step not working

### ISSUE THREAD

**Issue by bhabermaas** [derekparker/delve#1277]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
2. What version of Go are you using? (`go version`)?
go version go1.10.1 darwin/amd64
3. What operating system and processor architecture are you using?
macOS High Sierra Version 10.13.5
4. What did you do?
Tried to debug and single step Go program
5. What did you expect to see?
Step to next statement after breakpoint encountered
6. What did you see instead?
Single step didn't work and program ran to next breakpoint

**Comment by derekparker** [comment]
The homebrew formula is deprecated. Can you refer to the documentation in the repo to install the latest from source and try to reproduce? If you can still reproduce, please give along an example program that reproduces the problem on your system if possible.

**Comment by bhabermaas** [comment]
I'll give it a try.

**Comment by bhabermaas** [comment]
Tried go get -- made no different. 
Tried make install -
[~/d/go/src/github.com/derekparker/delve]: make install
scripts/gencert.sh || (echo "An error occurred when generating and installing a new certificate"; exit 1)
go install -ldflags="-s -X main.Build=c8fcc3c5b21fb0fa314acdf7578dcc6a62e505be" github.com/derekparker/delve/cmd/dlv
codesign -s "dlv-cert"  /Users/bihaber/d/go:/usr/local/go/bin/dlv
/Users/bihaber/d/go:/usr/local/go/bin/dlv: No such file or directory
make: *** [install] Error 1
[~/d/go/src/github.com/derekparker/delve]:

**Comment by bhabermaas** [comment]
it created the dlv executable but the cert setup failed.

**Comment by derekparker** [comment]
What's your `go env` output? It's very off that it seems to be looking for the `dlv` binary in the path that seems to be your `GOROOT`.

**Comment by bhabermaas** [comment]
[~/d/go/src/github.com/derekparker/delve]: go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bihaber/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/bihaber/d/go:/usr/local/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/20/p__0l5d94cg34gnh6byf4nqr0000gn/T/go-build346091398=/tmp/go-build -gno-record-gcc-switches -fno-common"
[~/d/go/src/github.com/derekparker/delve]:

**Comment by derekparker** [comment]
There's something wrong with how you're pasting the text because it pretty much all has a strikethrough, but regardless, why have `/usr/local/go` in your `GOPATH`?

**Comment by bhabermaas** [comment]
The multiple folders on gopath is necessary separate standard go src from company src. However it seems single step works for a simple program but not for a complex program.  They are both using the same gopath. Unfortunately the failing code is part of a proprietary software product so I can't provide sample code.

**Comment by aarzilli** [comment]
This is likely to be a problem with the pcln table, it could be better with go1.11.

**Comment by aarzilli** [comment]
Problem with multiple GOPATH entries was fixed, the problem with stepping is too lacking in detail to be actionable.
