### ISSUE TITLE
Can't set breakpoint on certain lines

### ISSUE THREAD

**Issue by paulsc** [derekparker/delve#1282]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $

2. What version of Go are you using? (`go version`)?
go version go1.10.3 darwin/amd64

3. What operating system and processor architecture are you using?
macOS High Sierra 10.13.6 - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz

4. What did you do?
(dlv) break frontendsettings.go:107

5. What did you expect to see?
"Breakpoint set" message. 

6. What did you see instead?
Command failed: could not find /Users/paul/go/src/github.com/grafana/grafana/pkg/api/frontendsettings.go:107

Hello,

I'm at the end of my wits. Breakpoints don't work on _certain_ files only. They work on some files:

```
(dlv) break /Users/paul/go/src/github.com/grafana/grafana/pkg/api/index.go:50
Breakpoint 1 set at 0x4eabb7f for github.com/grafana/grafana/pkg/api.setIndexViewData() ./pkg/api/index.go:50
```
Not on others. I get a "could not find [file]" error. But the file exists, and shows up in the "source" command:

```
(dlv) break frontendsettings.go:107
Command failed: could not find /Users/paul/go/src/github.com/grafana/grafana/pkg/api/frontendsettings.go:107
(dlv) sources /Users/paul/go/src/github.com/grafana/grafana/pkg/api/frontendsettings.go
/Users/paul/go/src/github.com/grafana/grafana/pkg/api/frontendsettings.go
```

Any help appreciated. Thanks!

**Comment by aarzilli** [comment]
How did you build the executable you are debugging? Can you post the executable?

**Comment by paulsc** [comment]
I am just running 

```
dlv debug github.com/grafana/grafana/pkg/cmd/grafana-server
```
so I assume delve is handling the build ? 

I posted the executable [here](https://www.dropbox.com/s/9r1wva82u0aqcsn/debug?dl=0)

**Comment by paulsc** [comment]
It looks like you found an issue ? Should I give it another go ?

**Comment by aarzilli** [comment]
The patch hasn't been merged yet, if you want to test it you'll need to apply it manually (it does fix your problem).

**Comment by paulsc** [comment]
Got it. Thanks a bunch!
