### ISSUE TITLE
go get -u all   - generates the following internal package error

### ISSUE THREAD

**Issue by jcastill0** [derekparker/delve#1290]
go1.10.3
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533

MacOS

go get -u all
../../../golang/src/github.com/derekparker/delve/vendor/golang.org/x/crypto/ssh/cipher.go:21:2: use of internal package not allowed

**Comment by aarzilli** [comment]
Yes, that command can't work.
