### ISSUE TITLE
Can't install delve, compile error finding sort.Slice

### ISSUE THREAD

**Issue by aviaviavi** [derekparker/delve#1291]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? current master (22af38364b4fe71ba10604cf0f771ed628f0005b as of filling)
2. What version of Go are you using? (`go version`)? 1.7
3. What operating system and processor architecture are you using? Ubuntu 16.04.4 LTS
4. What did you do? Tried to install (via both `go get`, and directly via `make install`)
5. What did you expect to see? A successful installation
6. What did you see instead? 
```
go install -ldflags="-X main.Build=22af38364b4fe71ba10604cf0f771ed628f0005b" github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/pkg/proc
/go/src/github.com/derekparker/delve/pkg/proc/fncall.go:292: undefined: sort.Slice
Makefile:52: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by dlsniper** [comment]
You should upgrade to Go 1.8 or newer in order for this to work. My recommendation is to use Go 1.10.

**Comment by aviaviavi** [comment]
Ok. While upgrading would be nice, many companies won't be able to just easily upgrade their go versions at will. Breaking delve a release version of the language (which, according to the docs should still be working) seems like a substantial regression

**Comment by dlsniper** [comment]
Go 1.7 is not supported officialy by the Go team for 2 years now, which means no security patches.

Surely that should be a good enough reason to upgrade this, if all the performance gains and improvements in debugging offered by Go alone do not justify it.

You can also just use a different Go version to compile Delve and then continue using internally whatever you need to.

**Comment by aarzilli** [comment]
We are currently testing against 1.8 - 1.11 which is one more than the Go team. You can still use delve with a executables from a previous version of go, you'll just need a newer version to compile it.
