### ISSUE TITLE
could not launch process: stub exited while waiting for connection: exit status 0

### ISSUE THREAD

**Issue by yangliCypressTest** [derekparker/delve#1295]
In interlliJ IDE, I can't launch the debug mode, the error just like title said

1. What version of Delve are you using (`dlv version`)?
1.0.0-rc.1
2. What version of Go are you using? (`go version`)?
go1.9 darwin/amd64
3. What operating system and processor architecture are you using?
Mac OS 10.11.6
4. What did you do?
Just debug a file
5. What did you expect to see?
can launch the debug mode
6. What did you see instead?

**Comment by aarzilli** [comment]
Run it with `--log --log-output=lldbout,gdbwire` so that we can figure out why.

**Comment by yangliCypressTest** [comment]
I can debug by delve in command line, but not in IntelliJ IDEA, so where to add above configuration when launch debug in IntelliJ?

**Comment by dlsniper** [comment]
IDEA will tell you what it runs in the section at the beginning named "go setup. Expand it and you'll see the command line used. Then you can change as needed.

**Comment by aarzilli** [comment]
> I can debug by delve in command line, but not in IntelliJ IDEA

Then you are probably hit by an old bug and you should update the copy of dlv that IDEA uses. I imagine it's the bug with the 'g' packet that newer versions of delve work around.

**Comment by yangliCypressTest** [comment]
It is strange that the debug mode is out of work suddenly without any change of IDEA on version and configuration

**Comment by aarzilli** [comment]
You probably updated XCode.

**Comment by yangliCypressTest** [comment]
If this is the root cause, how can I fix it? which is the correct version of XCode, I can double check it.

**Comment by dlsniper** [comment]
If you tell me the plugin version I can check if it's the latest or not. We keep track of delve progress/bug fixes and ship the latest we can whenever we release the IDE/plugin.

**Comment by yangliCypressTest** [comment]
![image](https://user-images.githubusercontent.com/32126386/43796628-c6adbaae-9a52-11e8-9538-0437133eee48.png)

**Comment by yangliCypressTest** [comment]
Is this info enough for you to dig the rc?

**Comment by dlsniper** [comment]
@yangliCypressTest what version of XCode do you use?

**Comment by yangliCypressTest** [comment]
7.3.1

**Comment by dlsniper** [comment]
Latest stable is 9.4.1, please upgrade to that. Also, this is pretty similar to https://youtrack.jetbrains.com/issue/GO-4733#focus=streamItem-27-3004631-0-0 so I would recommend continuing the discussion there.

**Comment by yangliCypressTest** [comment]
The versions of Xcode and OS are managed and controlled by IT, and I also confirmed with my colleague, we have the same version of OS, Xcode, golang, and IntelliJ IDEA, and debug mode can be launched successfully, and I didn't upgrade any of softwares before my debug env out of work.

**Comment by KleonV** [comment]
osx 10.13.6   Xcode 9.4.1
With ` $dlv debug`,  I ran into the same problem. But I can launch the debug mode, if change to the Native backend.
$ dlv debug --backend native
ps:
	Flags:
      --backend string       Backend selection:
	default		Uses lldb on macOS, native everywhere else.
	native		Native backend.
	lldb		Uses lldb-server or debugserver.
	rr		Uses mozilla rr (https://github.com/mozilla/rr).

**Comment by csquire** [comment]
In case this helps someone else, I found that having a missing/botched `127.0.0.1     localhost` entry in /etc/hosts will also cause this error.

**Comment by aarzilli** [comment]
Likely not a problem with delve.

**Comment by Thommil** [comment]
> In case this helps someone else, I found that having a missing/botched `127.0.0.1 localhost` entry in /etc/hosts will also cause this error.

Just removed some hosts add the end of the line commented using # and it works, many thanks !
