### ISSUE TITLE
OSX installation docs are confusing as to which method to use

### ISSUE THREAD

**Issue by tleyden** [derekparker/delve#1297]
1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
```

2. What version of Go are you using? (`go version`)?

```
go version go1.9.2 darwin/amd64
```

3. What operating system and processor architecture are you using?

OSX 

4. What did you do?

Read https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md

5. What did you expect to see?

A clear explanation of what this means:

> With this method you will not be able to use delve's native backend.

6. What did you see instead?

I think the docs would be improved if it explained the advantage of using delve's native backend.  Also, it might be better to explicitly reference which method, like "With the go get method .. ", since it's hard to tell if it's talking about the preceding or the following method.

[edrozenberg was confused by it too](https://github.com/derekparker/delve/issues/1201#issuecomment-387140430), so it's not just me.

**Comment by SteelPhase** [comment]
You can technically simplify the instructions into the below steps. Using `-d` the `go get` command will stop before it installs the binary in the bin directory, and you don't have to go out of your way to clone the repo into the right place for `make install`. While the `make install` step isn't strictly necessary, it does populate the Build value in `delve version`

1. Clone delve `go get -u -d github.com/derekparker/delve/cmd/dlv`
2. move to directory `cd $GOPATH/src/github.com/derekparker/delve`
3. install delve `make install`

**Comment by aarzilli** [comment]
I think we clarified this sufficiently in 910f90.
