### ISSUE TITLE
dlv not running in OS X Sierra

### ISSUE THREAD

**Issue by protocos** [derekparker/delve#1299]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $

2. What version of Go are you using? (`go version`)?

go version go1.10.3 darwin/amd64

3. What operating system and processor architecture are you using?

macOS Sierra 10.12.6

4. What did you do?

Ran the command `dlv debug` in a hello world project

5. What did you expect to see?

delve debugging the program

6. What did you see instead?

flag provided but not defined: -l
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
exit status 1

**Comment by aarzilli** [comment]
What's the output of:

1. `go env`
2. `env`
3. `file $(which go)`

**Comment by aarzilli** [comment]
You have some kind of wrapper script for the go command. It's broken.
