### ISSUE TITLE
Include the help instruction in readme

### ISSUE THREAD

**Issue by chenkirk** [derekparker/delve#130]
I've just started using delve. The first problem I encountered was trying to delete a breakpoint. Eventually I figured out from the source code and then found out in delve you can just type help.

I think it would be great to include at least the help command in README.md

I could help with modifying the README if you'd like.

**Comment by derekparker** [comment]
Agreed, the command should be in the README. If you'd like to put a PR together to add it, I'd certainly merge it in.
