### ISSUE TITLE
How to manually install delve?

### ISSUE THREAD

**Issue by wangyufeng0615** [derekparker/delve#1304]
What version of Delve are you using (dlv version)?
1.0.0

What version of Go are you using? (go version)?
1.10.3

What operating system and processor architecture are you using?
linux/amd64

4. What did you do?
I want to run delve on OpenWRT for remote debugging. Since OpenWRT lacks runtime, I need to compile delve on Ubuntu then copy to OpenWRT.

5. What did you expect to see?
Run  `dlv debug --headless --listen=:2345 --api-version=2` and delve work well.

6. What did you see instead?
I am now able to compile a "dlv" binary that I can run on OpenWRT, but when running any dlv command such as "dlv debug":
```
Could not create config directory: user: lookup userid 0: no such file or directory.can't load package: package .: no Go files in /root
```

I guess, delve's running conditions not only copy just "dlv" file. How do I manually complete this install process? 

Thank you.

**Comment by aarzilli** [comment]
You can probably ignore the error about creating the config directory. I think your problem is that you are running dlv in a directory without go files.

**Comment by derekparker** [comment]
Closing due to lack of response. The given solution seems reasonable, please reopen if there is more to be done.
