### ISSUE TITLE
debug show "Failed to continue."

### ISSUE THREAD

**Issue by yunfengsay** [derekparker/delve#1305]
hello every, i found i could not debug now , i can do it a few days before.

1. What version of Delve are you using (`dlv version`)?
  Delve Debugger
  Version: 1.0.0
Build: 22af38364b4fe71ba10604cf0f771ed628f0005b
2. What version of Go are you using? (`go version`)?
go version go1.10.2 darwin/amd64
3. What operating system and processor architecture are you using?
macos

![image](https://user-images.githubusercontent.com/15527378/44031928-144a91c6-9f38-11e8-9850-f24859d736b8.png)

**Comment by aarzilli** [comment]
You need to post the output produced with `--log --log-output=rpc`

**Comment by yunfengsay** [comment]
It is caused by my own error what break the program../
