### ISSUE TITLE
The wiki still talks about installing delve using homebrew

### ISSUE THREAD

**Issue by ramya-rao-a** [derekparker/delve#1306]
Homebrew was removed as an option to install delve on mac back in March via https://github.com/derekparker/delve/commit/fbd152f6a87ed67c02006f31e2be0afdc06c5d00

But the wiki [Installation on OSX](https://github.com/derekparker/delve/wiki/Installation-on-OSX) still talks about it

**Comment by derekparker** [comment]
Fixed, thanks for pointing that out!
