### ISSUE TITLE
Release anytime soon?

### ISSUE THREAD

**Issue by jason-riddle** [derekparker/delve#1307]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
`v1.0.0`
2. What version of Go are you using? (`go version`)?
`go version devel +f1c7faacf0 Sun Aug 12 19:56:28 2018 +0000 darwin/amd64` (go1.11beta3)
3. What operating system and processor architecture are you using?
OS: Darwin
Arch: amd64

## Report

v1.0.0 has a bug where it's passing only one argument to `x86asm.GNUSyntax`

https://github.com/derekparker/delve/blob/v1.0.0/pkg/proc/disasm_amd64.go#L46

```go
text = x86asm.GNUSyntax(x86asm.Inst(*inst.Inst))
```

but this was corrected in Master

https://github.com/derekparker/delve/blob/master/pkg/proc/disasm_amd64.go#L46

```go
text = x86asm.GNUSyntax(x86asm.Inst(*inst.Inst), inst.Loc.PC, bi.symLookup)
```

Unfortunately, I've been testing out using go1.11beta3 to version tool dependencies via a separate `tools.go` file. The issue is the go modules uses the latest tagger version of a module if a version is not specified. In this case, the latest version is 1.0.0. The bug is triggered upon cross-compiling.

### Steps to Reproduce

`main.go`

```go
package main

import (
	"fmt"
)

func main() {
    fmt.Println("hello world")
}
```

`tools.go`

```go
package main

import (
	_ "github.com/derekparker/delve/cmd/dlv"
)
```

`go.mod`

```
module sample
```

Run the following which fails

```
GO111MODULE=on GOARCH=amd64 GOOS=linux go build -o bin/debugger/dlv github.com/derekparker/delve/cmd/dlv

# github.com/derekparker/delve/pkg/proc
../.go/pkg/mod/github.com/derekparker/delve@v1.0.0/pkg/proc/disasm_amd64.go:46:26: not enough arguments in call to x86asm.GNUSyntax
	have (x86asm.Inst)
	want (x86asm.Inst, uint64, x86asm.SymLookup)
../.go/pkg/mod/github.com/derekparker/delve@v1.0.0/pkg/proc/disasm_amd64.go:50:28: not enough arguments in call to x86asm.IntelSyntax
	have (x86asm.Inst)
	want (x86asm.Inst, uint64, x86asm.SymLookup)
```

### Solution

One workaround is to explicit pin the version to use the latest version of master with `go get github.com/derekparker/delve@master`. As a precaution, I've also excluded this version with `go mod edit -exclude github.com/derekparker/delve@v1.0.0`. With that in-place, are there any plans to release a new version of delve anytime soon?

**Comment by komuw** [comment]
ran into this also while using Go from tip; `go version devel +4fc7b93ad7 Mon Aug 13 19:04:16 2018 +0000 darwin/amd64`

**Comment by aarzilli** [comment]
Yes, probably this month.

**Comment by komuw** [comment]
I think it would make sense to release slightly after Go1.11 comes out or at the same time.

I have been testing making function calls in a debugging session (that is in delve master and Go1.11RC) and it is a really nice experience. Kudos to everyone.

**Comment by derekparker** [comment]
New release out.
