### ISSUE TITLE
Need to update required version of golang in installation wiki delve for linux.

### ISSUE THREAD

**Issue by dhruv459** [derekparker/delve#1311]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Current-master as of now.

2. What version of Go are you using? (`go version`)?
1.7.1 

3. What operating system and processor architecture are you using?
linux/amd64

4. What did you do?
Installing delve from installation wiki at https://github.com/derekparker/delve/blob/master/Documentation/installation/linux/install.md

I followed the steps of manual installation instead of using "go get".

5. What did you expect to see?
Compilation without error while executing "make install". 

6. What did you see instead?
# github.com/derekparker/delve/pkg/proc
pkg/proc/fncall.go:292: undefined: sort.Slice
Makefile:52: recipe for target 'install' failed
make: *** [install] Error 2

I found a thread which tells delve runs on go 1.8 or higher. https://github.com/derekparker/delve/issues/1291

Can this be posted on the main wiki of installation. This may be a cosmetic defect but a simple warning could save guide someone to the right way.

**Comment by aarzilli** [comment]
I believe the problem is https://github.com/derekparker/delve/wiki/Installation. I'd vote for replacing it with a link to the (equivalent section) documentation. I forgot we had it and we haven't been updating it in two years.

**Comment by dhruv459** [comment]
Yes, I agree with @aarzilli , the documentation wiki should/can mention the version limitation up front.

**Comment by dlsniper** [comment]
I see now.
@aarzilli what do you think about updating the page with this message:

<hr>

This page is here for historical reasons.

If you need up to date documentation on how to install Delve and what are the current requirements, please visit the documentation section in the repository: [Documentation/Installation](https://github.com/derekparker/delve/tree/master/Documentation/installation).

**Comment by dhruv459** [comment]
I'll close the issue as the version limitation is already mentioned under delve/Documentation/installation/.
