### ISSUE TITLE
Getpagesize redeclared in this block

### ISSUE THREAD

**Issue by xyproto** [derekparker/delve#132]
Hi,

I'm using `go version go1.4.2 linux/amd64` on 64-bit Arch Linux.

When trying to go get delve, this is the output I get:

~~~bash
% go get github.com/derekparker/delve/cmd/dlv
# golang.org/x/sys/unix
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:65: Getpagesize redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:73
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:70: TimespecToNsec redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:87
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:72: NsecToTimespec redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:89
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:78: TimevalToNsec redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:95
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:80: NsecToTimeval redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:97
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:87: Pipe redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:106
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:100: Pipe2 redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:119
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:111: (*PtraceRegs).PC redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:130
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:113: (*PtraceRegs).SetPC redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:132
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:115: (*Iovec).SetLen redeclared in this block
	previous declaration at ../../go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:134
../../go/src/golang.org/x/sys/unix/syscall_linux_arm64.go:115: too many errors
~~~

I can't make any sense of the error message. The paths look identical to me.

Best regards,
   Alexander F Rødseth

**Comment by derekparker** [comment]
Have you recently upgraded by chance? Or maybe build Delve with an older version of Go before?

I've seen these type issues before when the local environment gets messed up. The "fix" ended up being `rm -rf $GOPATH/pkg/linux_amd64/golang.org/x/sys`, or worse case `rm -rf $GOPATH/pkg`.

Let me know whether that clears things up for you.

**Comment by pnasrat** [comment]
golang.org/x/sys/unix currently won't build with go 1.4 due to arm64 and
ppc64 being added - see

https://github.com/golang/go/issues/10854

**Comment by pnasrat** [comment]
Actually it should be fixed if you update your golang.org/x/sys/unix repo

golang/sys@8bcc2dbee456eb666777c384158fb033c05fa03e

**Comment by xyproto** [comment]
Thanks, I'll try updating the golang.org/x/sys/unix repo.

And thanks for creating delve in the first place, it's really useful!

**Comment by derekparker** [comment]
@xyproto thanks!

Did you ever get this figured out?

**Comment by xyproto** [comment]
This is kind of a headache for me, as I'm not only interested in fixing this for myself, but also for the users of the go package for Arch Linux, which I maintain. I would like to fix this issue for everyone, preferably without patching anything (since that is against the Arch Linux philosophy). It may look like the solution (for the go package) is to wait for the next release. I'll consider applying the golang/sys@8bcc2db commit as a patch to the official package, if there is no other way, but it's not optimal.

**Comment by xyproto** [comment]
Works now!
