### ISSUE TITLE
Delve not installing for Golang 1.11

### ISSUE THREAD

**Issue by pd93** [derekparker/delve#1323]
I updated to Golang v1.11 today and was prompted as usual to update my 'go tools' when opening a `.go` file in VSCode. All tools installed successfully with the exception of Delve.

1. What version of Delve are you using (`dlv version`)?
```sh
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $
```
2. What version of Go are you using? (`go version`)?
```sh
go version go1.11 windows/386
```
3. What operating system and processor architecture are you using?
Windows x86_64
4. What did you do?
Updated to Golang 1.11 (from 1.10.3) and updated the 'go tools' in VSCode
(Same result when running `go.exe get -u -v github.com/derekparker/delve/cmd/dlv` from a terminal
5. What did you expect to see?
SUCCESS
6. What did you see instead?
```sh
C:\dev\go\bin\go.exe get -u -v github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
github.com/derekparker/delve/pkg/proc
# github.com/derekparker/delve/pkg/proc
C:\Users\pete\dev\src\github.com\derekparker\delve\pkg\proc\disasm.go:11:14: undefined: ArchInst
```

**Comment by dlsniper** [comment]
Delve doesn't work on 386 platforms, see https://github.com/derekparker/delve/issues/656

You should install the 64bit version of Go (amd64) if your CPU supports it and it will likely work as expected.

**Comment by pd93** [comment]
Somehow managed to install the 32bit version by accident 🙃 
All working now!

Thanks

**Comment by lkelemen** [comment]
hi,
I'm trying to install delve on dragonboard but it is not successful:
(classic)lkelemen@localhost:~/go/src/github.com/derekparker/delve$ make install
go install "-ldflags=-X main.Build=79a0e216ab2650c3460afbd87668fa38be9fffb2" github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/pkg/proc
pkg/proc/disasm.go:12:14: undefined: archInst
exit status 1
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 1
(classic)lkelemen@localhost:~/go/src/github.com/derekparker/delve$ lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
CPU max MHz:           1209.6000
CPU min MHz:           200.0000
Hypervisor vendor:     horizontal
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
