### ISSUE TITLE
Unable to cast interface{} to map[string]interface{}

### ISSUE THREAD

**Issue by lieut-data** [derekparker/delve#1328]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```

2. What version of Go are you using? (`go version`)?
```
go version go1.11 darwin/amd64
```

3. What operating system and processor architecture are you using?
OSX 10.13.6, amd64

4. What did you do?
```
(dlv) print input.(map[string]interface {})
(dlv) print input.(map[string]interface{})
(dlv) print ("map[string]interface {}")(input)
(dlv) print ("map[string]interface{}")(input)
```
and just for kicks:
```
(dlv) print input.(map[string]string)
```

5. What did you expect to see?
`input` cast to `map[string]interface{}`

6. What did you see instead?
```
Command failed: no type entry found, use 'types' for a list of valid types
Command failed: no type entry found, use 'types' for a list of valid types
Command failed: can not convert "input" to map[string]interface {}
Command failed: no type entry found, use 'types' for a list of valid types
```
The last command confirmed that `input` is indeed a `map[string]interface{}`:
```
Command failed: interface conversion: interface {} is map[string]interface {}, not map[string]string
```

According to https://github.com/derekparker/delve/issues/455, an issue with a similar title, this was fixed by https://github.com/derekparker/delve/pull/434, but I'm unable to figure out how exactly to achieve this.

**Comment by aarzilli** [comment]
We don't support converting an `interface {}` to a non-empty interface at the moment, that's why it doesn't work. The type assertion should work, it's weird that it doesn't. 
Why do you want to do this?

**Comment by lieut-data** [comment]
I'm trying to inspect a deeply nested map exposed to me as an `interface{}` at each level of the tree. Printing the interface gets me the first few levels, but as documented, obscures the remaining levels. I can't index into the map at a specific key because I can't cast the `interface{}` to the `map[string]interface{}` that it actually is.

Here's a minimal use case illustrating the problem:
```go
package main

import (
	"fmt"
	"runtime"
)

func obscure(m map[string]interface{}) interface{} {
	return m
}

func main() {
	m := obscure(map[string]interface{}{
		"a": obscure(map[string]interface{}{
			"1": obscure(map[string]interface{}{
				"x": 1,
				"y": 2,
			}),
		}),
	})

	runtime.Breakpoint()
	fmt.Printf("%+v\n", m)
}
```

and debugging:
```
dlv debug main.go
Type 'help' for list of commands.
(dlv) run
Command failed: command not available
(dlv) c
> main.main() ./main.go:23 (PC: 0x10b1c8d)
    18:                         }),
    19:                 }),
    20:         })
    21:
    22:         runtime.Breakpoint()
=>  23:         fmt.Printf("%+v\n", m)
    24: }
(dlv) print m
interface {}(map[string]interface {}) [
        "a": map[string]interface {} [
                "1": *(*"interface {}")(0xc00008c1a8),
        ],
]
(dlv) print m["a"]
Command failed: expression "m" (interface {}) does not support indexing
(dlv) print m.(map[string]interface{})["a"]
Command failed: no type entry found, use 'types' for a list of valid types
(dlv)
```

**Comment by lieut-data** [comment]
(I realized the description of my issue was inaccurate: updated!)

**Comment by derekparker** [comment]
Closing this as it's been inactive for some time. If the provided solution and associated PR adding `iface.(data)` do not help or solve the problem please reopen with a comment.

**Comment by lumixraku** [comment]
I have the same problem.

when i try to use item.(types.ExternalActionItem)
it says " no type entry found, use 'types' for a list of valid types  "

**Comment by RubenGarcia** [comment]
I am still getting the same problem.
Delve Debugger
Version: 1.4.0
Build: $Id: 67422e6f7148fa1efa0eac1423ab5594b223d93b $
go version go1.14.2 linux/amd64


print (res.Payload[i].Metadata.CustomMetadata.(map[string]interface{})[0]["address"])
Command failed: no type entry found, use 'types' for a list of valid types

**Comment by cuishuang** [comment]
Any progress?
