### ISSUE TITLE
pass environment to process

### ISSUE THREAD

**Issue by ansel1** [derekparker/delve#133]
It seems `dlv run` doesn't pass the system environment to the debugged app.  This makes it tricky to debug 12-factor apps.

Workaround: `dlv run` to build `debug`, exit, run `debug` directly, then `dlv attach`

**Comment by derekparker** [comment]
Thanks! Just pushed up fix.

My assumption was you were on OSX, is that correct? If this is also an issue on Linux, and still an issue after pulling down the latest code, feel free to reopen this.

**Comment by ansel1** [comment]
Yup, I'm OS X. Thanks for the fix!
