### ISSUE TITLE
Installation Error (Windows 10)

### ISSUE THREAD

**Issue by elforce001** [derekparker/delve#1337]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? None

2. What version of Go are you using? (`go version`)? 1.10.3

3. What operating system and processor architecture are you using?
 Windows 10 - 64bits

4. What did you do? 
I'm trying to manually install dlv with the command:
```go get -u github.com/derekparker/delve/cmd/dlv```

5. What did you expect to see? Successful installation.

6. What did you see instead?
``` cd C:\Users\erick\go\src\github.com\derekparker\delve; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master```

**Comment by aarzilli** [comment]
Try deleting `$GOPATH/src/github.com/derekparker/delve/` and then doing the `go get` again. Either way this is a problem with your setup, not a bug in delve.
