### ISSUE TITLE
go get delve fails 

### ISSUE THREAD

**Issue by kkarakk** [derekparker/delve#1349]
Karans-MacBook-Pro:~$go get -u github.com/derekparker/delve/cmd/dlv
_gives me:_

> \# cd .; git clone https://github.com/derekparker/delve /Users/karanharshwardhan/go/src/github.com/derekparker/delve
> Cloning into '/Users/karanharshwardhan/go/src/github.com/derekparker/delve'...
> error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> package github.com/derekparker/delve/cmd/dlv: exit status 128 

_go env results:_

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/karanharshwardhan/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/karanharshwardhan/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/Cellar/go/1.11/libexec"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f5/bvrf08j101jcbc1yd70z91lh0000gn/T/go-build483208167=/tmp/go-build -gno-record-gcc-switches -fno-common"
> 

_go version gives me_ 

> go version go1.11 darwin/amd64

**Comment by derekparker** [comment]
This is a problem with downloading during the `git clone` operation, this has nothing to do with Delve itself. Are you able to clone other repos, or `git clone` and build the project manually without `go get`?

**Comment by kkarakk** [comment]
i apologize it happened a couple of times in a row and other(smaller) repos were getting cloned with no errors in the meanwhile.  must have been because of network issues
