### ISSUE TITLE
dlv attach <pid> <binary location> in windows gives "Access is denied error"

### ISSUE THREAD

**Issue by vikaspushkar** [derekparker/delve#1357]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
**PS C:\Users\******> dlv version
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $**

2. What version of Go are you using? (`go version`)?

**PS C:\Users\*******> go version
go version go1.10.3 windows/amd64**

3. What operating system and processor architecture are you using?
**OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.15063 N/A Build 15063
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 69 Stepping 1 GenuineIntel ~2095 Mhz**
4. What did you do?
**PS C:\Users\********> dlv.exe attach 9704**
5. What did you expect to see?
**debugging should have started**
6. What did you see instead?
**could not attach to pid 9704: Access is denied.**
i got the PID from task manager and crosschecked it with ps -ef command in windows powershell

**Comment by aarzilli** [comment]
I think it just means what it says, you don't have the privileges necessary to debug the process you are trying to debug. Could be some kind of security software, could be just the permissions set on your user.

**Comment by rdhillbb** [comment]
This can be closed. create a clean go environment. All good now.
