### ISSUE TITLE
Blue highlighting is nearly unreadable on a black screen

### ISSUE THREAD

**Issue by eric-s-raymond** [derekparker/delve#1367]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

1.1.0

2. What version of Go are you using? (`go version`)?

1.10.1

3. What operating system and processor architecture are you using?

ia64, Linux

dlv uses blue highlighting for some of its display elements.  On many monitors (including mine) the contrast with a black background is so low that the result is eyestrain.

The fix: choose highlight colors with reasonable contrast against both white and black backgrounds.

Or you could document this as a known problem and give a workaround of setting a non-color terminal type as TERM when running dlv.  

One or the other of these things should happen.

**Comment by aarzilli** [comment]
See #1364

**Comment by Russtopia** [comment]
#1364 merged. Use source-list-line-color to set whatever ANSI color you prefer.

**Comment by aarzilli** [comment]
I think 4e4ed0294807c7be65513112bde18dd70c0f165f fixes this problem.
