### ISSUE TITLE
Listing breakpoints always shows panic with go 1.11.1

### ISSUE THREAD

**Issue by jinmatt** [derekparker/delve#1369]
Please answer the following before submitting your issue:
- Listing breakpoints always shows panic with go 1.11.1
```
Breakpoint unrecovered-panic at 0x10318b0 for runtime.fatalpanic() /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:681 (0)
	print runtime.curg._panic.arg
Breakpoint 1 at 0x1e3e87b for lib/api/http.agentHandler.login() ./api/http/agent_handler.go:214 (1)
....
```
1. What version of Delve are you using (`dlv version`)?
```
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c
```
2. What version of Go are you using? (`go version`)?
```
go version go1.11.1 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
macOS Mojave 10.14
```
4. What did you do?
```
Tried to list breakpoints and ends with this error always. VS code debugger stopped working because of this IMO
```

**Comment by aarzilli** [comment]
The "unrecovered-panic" in the first line is the name of the breakpoint, not an actual panic.

**Comment by jinmatt** [comment]
@aarzilli  Agreed, but why is there always a breakpoint created that the point, also unable to clear that breakpoint:

```
(dlv) bp
Breakpoint unrecovered-panic at 0x10318b0 for runtime.fatalpanic() /usr/local/go/src/runtime/panic.go:681 (0)
	print runtime.curg._panic.arg
```

```
(dlv) clear usr/local/go/src/runtime/panic.go:681
Command failed: no breakpoint with name usr/local/go/src/runtime/panic.go:681
```

**Comment by derekparker** [comment]
@jinmatt that breakpoint is created by Delve so that when the target actually does panic and it is not recovered, we can stop the process and let the user inspect what's going on before it actually exits.
