### ISSUE TITLE
compile: version "go1.9.3" does not match go tool version "go1.10.1"

### ISSUE THREAD

**Issue by bhabermaas** [derekparker/delve#1370]
Please answer the following before submitting your issue:

Debugging did work. I tried to uninstall and reinstall without solving the problem.  In general it would work with some projects and not others.  Now it is a solid failure.

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: c8fcc3c5b21fb0fa314acdf7578dcc6a62e505be
2. What version of Go are you using? (`go version`)?
go version go1.10.1 darwin/amd64
3. What operating system and processor architecture are you using?
macOS Sierra 10.13.6
4. What did you do?
Tried to run debugger under vscode
5. What did you expect to see?
Should have stopped at first breakpoint
6. What did you see instead?
# errors
compile: version "go1.9.3" does not match go tool version "go1.10.1"
go tool asm: exit status 2
flag provided but not defined: -V
usage: asm [options] file.s ...
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -o string
    	output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
exit status 2
Process exiting with code: 1

**Comment by aarzilli** [comment]
Your install of Go is broken.
