### ISSUE TITLE
Checkpoint command ignores an argument

### ISSUE THREAD

**Issue by nd** [derekparker/delve#1373]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: 4fea15832f50a16a74d0a443cbad3441f1f41449
```
2. What version of Go are you using? (`go version`)?
```
go version go1.11 linux/amd64
```
3. What operating system and processor architecture are you using?
```
Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
4. What did you do?

The `check help` command indicates that it is possible to specify a place to put a checkpoint:
```
(dlv) help check
Creates a checkpoint at the current position.

        checkpoint [where]
```
I've run `checkpoint main.go:24` while staying at some other position.
The `checkpoints` command output seems to confirm that checkpoint was set:
```
(dlv) checkpoints
ID  When  Where
c1  361   main.go:20
c2  481   main.go:24
c3  631   main.go:16
```
5. What did you expect to see?

I expected `restart c2` will start executing from `main.go:24`.

6. What did you see instead?

The `restart c2` started executing from the location where the `checkpoint main.go:24` was entered.

If I understand correctly specifying a location is not supported and checkpoint is always created at the current location. Maybe it make sense to remove `[where]` from the `help checkpoint` output.

**Comment by aarzilli** [comment]
It's just a way to name the checkpoint, the documentation should just be clarified.

**Comment by nd** [comment]
Thanks, the behavior makes total sense if the argument to `checkpoint` is name instead of location.
