### ISSUE TITLE
Exception 0x406d1388 in a Windows DLL

### ISSUE THREAD

**Issue by BenLubar** [derekparker/delve#1383]
Full example (`dlv debug` after downloading will reproduce the issue, `go run .` will not):

https://gist.github.com/BenLubar/089abe8fd044c1b908bf9969b7f79edc

If you don't trust the DLL, you can download it from the [Steamworks website](https://partner.steamgames.com/downloads/steamworks_sdk_142.zip) or copy any `steam_api64.dll` that's included with one of your Steam games.

1. What version of Delve are you using (`dlv version`)?
    ```
    Delve Debugger
    Version: 1.1.0
    Build: d0f0a872a7ef545977dc7bc58c032b446a94a51b
    ```
2. What version of Go are you using? (`go version`)?
    ```
    go version go1.11.1 windows/amd64
    ```
3. What operating system and processor architecture are you using?
   ```
   Windows 10 Home 1803 (build 17134.345)
   Intel i7-4770k (64-bit x86)
   ```
4. What did you do?
   ```
   I ran the program in the gist using "dlv debug" followed by "c"
   ```
5. What did you expect to see?
    ```
    > go run .
    Setting breakpad minidump AppID = 480
    Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198013565588 [API loaded no]
    ```
    (the Steam ID will be different for you as you are not logged into my account)
6. What did you see instead?
    ```
    > dlv debug
    Type 'help' for list of commands.
    (dlv) c
    Exception 0x406d1388 0x7ffb00001000 0x7ffb985c05c8 0x7ffbe07fa388
    PC=0x7ffbe07fa388
    
    runtime: unknown pc 0x7ffbe07fa388
    stack: frame={sp:0x7aec40, fp:0x0} stack=[0x0,0x7afdf0)
    [omitted memory dump in case it contains sensitive information]
    runtime: unknown pc 0x7ffbe07fa388
    stack: frame={sp:0x7aec40, fp:0x0} stack=[0x0,0x7afdf0)
    [omitted memory dump in case it contains sensitive information]
    
    goroutine 1 [syscall]:
    main._Cfunc_SteamAPI_Init(0x0)
            _cgo_gotypes.go:46 +0x4d
    main.SteamAPI_Init(0x433d00)
            C:/Users/Owner/go/src/gist.github.com/089abe8fd044c1b908bf9969b7f79edc/cgo.go:17 +0x2e
    main.main()
            C:/Users/Owner/go/src/gist.github.com/089abe8fd044c1b908bf9969b7f79edc/main.go:4 +0x29
    [omitted register dump in case it contains sensitive information]
    Process 23320 has exited with status 2
    ```

**Comment by aarzilli** [comment]
I suspect this is part of steam_api's debugger countermeasures, you can try using this branch:

https://github.com/derekparker/delve/pull/1384

also try running the program under WinDbg, to see what happens there.

**Comment by BenLubar** [comment]
Both that PR and WinDbg are able to run the example program without crashing.

I doubt Valve would intentionally put anything to try to mess with debuggers in their SDK given that it's an SDK. It looks like this weirdness is the Microsoft-recommended way to set a thread name: https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2017

```
> dlv debug
Type 'help' for list of commands.
(dlv) c
MS_VC_EXCEPTION seen and ignored
Setting breakpad minidump AppID = 480
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198013565588 [API loaded no]
Process 9372 has exited with status 0
(dlv) exit
Process 9372 has exited with status 0
```

**Comment by aarzilli** [comment]
cc @alexbrainman: I can't tell if this is a bug in the go runtime, delve or steam_api64.dll.
steam_api64.dll is trying to use a weird MS protocol to set the thread name in the debugger by raising a special exception (code: 0x406d1388). In theory steam_api64.dll should be setting an exception handler and it should be fine for delve to send back the exception. In practice if we do the program crashes. 
Do you have any clue whether this is (a) steam_api64.dll implementing the protocol wrong, (b) the go runtime messing this up, or (c) somehow delve interfering with the go runtime and messing this up?

**Comment by alexbrainman** [comment]
@aarzilli ,

I knew nothing about 0x406d1388 before you called. But quick googling, I find this https://blogs.msdn.microsoft.com/stevejs/2005/12/20/naming-threads-in-win32-and-net It looks like C library discovered that the process is getting debugged, and is trying to be helpful - it is trying to provide thread names of debugged process.

Your https://github.com/derekparker/delve/pull/1384 seems like fixes the problem.

You could, probably, do even better - if you look at the article, you will see how Windows exception is raised, and you should be able to get to the thread name via THREADNAME_INFO struct. I am not sure, if that is something you mind find useful for Delve.

If you are interested, maybe we could do something similar for every Go program on Windows - we could make Go runtime send 0x406d1388 for whatever threads you find interesting. I am not  sure how interesting that is ...

Alex

**Comment by aarzilli** [comment]
I was under the impression that the `__except(EXCEPTION_CONTINUE_EXECUTION)` would prevent the target from crashing if we send the exception back. Do you think it's steam_api64.dll that's not doing it or do you think it's the go runtime that's preventing it from doing it?

We don't have a concept of thread names anywhere in delve, we could add it but given how threads are used by the average go program I don't think it's especially useful.

**Comment by BenLubar** [comment]
Since WinDbg doesn't crash, I'd assume this isn't the Go runtime breaking it.

**Comment by alexbrainman** [comment]
> I was under the impression that the `__except(EXCEPTION_CONTINUE_EXECUTION)` would prevent the target from crashing if we send the exception back.

That is the theory. In reality, C / C++ programs that use exceptions, require compiler and linker generate particular stack frames / exception information. I doubt Cgo generates these properly. So I wouldn't be surprised that these crash. But I am just guessing, I do not really know.

> We don't have a concept of thread names anywhere in delve, we could add it but given how threads are used by the average go program I don't think it's especially useful.

I agree.

Alex

**Comment by aarzilli** [comment]
>That is the theory. In reality, C / C++ programs that use exceptions, require compiler and linker generate particular stack frames / exception information. I doubt Cgo generates these properly. So I wouldn't be surprised that these crash. But I am just guessing, I do not really know.

Got it, thank you.
