### ISSUE TITLE
Need help: No backtrace in VS Code

### ISSUE THREAD

**Issue by Biter777** [derekparker/delve#1385]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
Version: 1.1.0
Build: d0f0a872a7ef545977dc7bc58c032b446a94a51b

2. What version of Go are you using? (`go version`)?
go version go1.11.1 linux/amd64

3. What operating system and processor architecture are you using?
Ubuntu 16.04.5 LTS
core: 4.4.0-137-generic

3.1. Visual Studio Code:
Version: 1.28.2
Build: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Arch: x64

Lunch:
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }

4. What did you do?
I run golang code:
panic("message")

5. What did you expect to see?
I expected to see a backtrace.

6. What did you see instead?
No backtrace, only program output messages.

I tried to reinstall the vs-code, delve and go.
Without success.

Please help!

**Comment by chainhelen** [comment]
You should opened one issue in [vscode-go](https://github.com/Microsoft/vscode-go/issues) first.

```
tmp2.go

package main

func main() {
	panic("message")
}
```
```
$ dlv debug tmp2.go
Type 'help' for list of commands.
(dlv) c
> [unrecovered-panic] runtime.fatalpanic() /usr/local/go/src/runtime/panic.go:681 (hits goroutine(1):1 total:1) (PC: 0x425de0)
Warning: debugging optimized function
	runtime.curg._panic.arg: interface {}(string) "message"
   676:	// fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
   677:	// that if msgs != nil, fatalpanic also prints panic messages and decrements
   678:	// runningPanicDefers once main is blocked from exiting.
   679:	//
   680:	//go:nosplit
=> 681:	func fatalpanic(msgs *_panic) {
   682:		pc := getcallerpc()
   683:		sp := getcallersp()
   684:		gp := getg()
   685:		var docrash bool
   686:		// Switch to the system stack to avoid any stack growth, which
(dlv) c
panic: message

goroutine 1 [running]:
main.main()
	/root/workspace/go/src/tmp2.go:4 +0x39
Process 15783 has exited with status 2
```

**Comment by aarzilli** [comment]
Closing, what @chainhelen said.
