### ISSUE TITLE
Targetting 1.5

### ISSUE THREAD

**Issue by pkieltyka** [derekparker/delve#139]
Hi,

Thanks for the work on delve! Just wondering, does delve work with 1.5? After listening to Rob Pike's talk last night about Go 1.5 (video+slides: http://www.reddit.com/r/golang/comments/37fcxo/go_in_go_15/) .. it sounds like the toolchain can do a much easier job of introspecting on programs across architectures. It makes sense that a debugger would be designed for 1.5+ specifically to make use of all of this.. how does delve fit with the new Go compiler?

**Comment by derekparker** [comment]
Thanks for checking it out!

No, currently Delve does not work with the latest development branch of Go. Won't be too much work to fix the issues though, I should have full support merged in soon.

**Comment by derekparker** [comment]
Update on this issue, Delve support for Go1.5 is currently help up by https://github.com/golang/go/issues/11887.

**Comment by derekparker** [comment]
Supported as of: https://github.com/derekparker/delve/commit/a506bb7d8e33e85878866152ba738206dbef9209
