### ISSUE TITLE
Novice Installation: Errors building delve

### ISSUE THREAD

**Issue by rdhillbb** [derekparker/delve#1390]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
cloned 
https://github.com/derekparker/delve.git

2. What version of Go are you using? (`go version`)?
version go1.11.1 darwin/amd64
3. What operating system and processor architecture are you using?
OSX 10.14
4. What did you do?
make install
5. What did you expect to see?
6. What did you see ?
go install -ldflags="-s -X main.Build=8f1fc63da82b4d4ca77c3992571b67c4f16bf43f" github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/vendor/gopkg.in/yaml.v2
vendor/gopkg.in/yaml.v2/decode.go:70:4: undefined: failf
vendor/gopkg.in/yaml.v2/decode.go:96:2: undefined: failf
vendor/gopkg.in/yaml.v2/decode.go:196:34: undefined: MapIt

"_thread_count", referenced from:
      __cgo_d95edd3737fb_Cfunc_thread_count in _x002.o
     (maybe you meant: __cgo_d95edd3737fb_Cfunc_thread_count)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [install] Error 2

**Comment by aarzilli** [comment]
Your install of Go seems broken, try reinstalling it and following the instructions [here](https://golang.org/doc/code.html) and [here](https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md)
