### ISSUE TITLE
Connecting to localhost:4000/ causes headless dlv to exit

### ISSUE THREAD

**Issue by gm42** [derekparker/delve#1393]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```
2. What version of Go are you using? (`go version`)?
`go version go1.11 linux/amd64`
3. What operating system and processor architecture are you using?
Linux/amd64, it is already in (2)
4. What did you do?
Start server with:
```
$ dlv --listen=:4000 --headless=true --api-version=2 exec myprogram
```
Then run:
```
$ curl http://localhost:4000/
```
5. What did you expect to see?
The service replying with 400.
6. What did you see instead?
Service returns empty reply and exits.

**Comment by derekparker** [comment]
This is because by default the client will exit after the first connection closes. You must use `--accept-multiclient` to stay alive after a client closes the connection.
