### ISSUE TITLE
Fail to install dlv on ubuntu with go 1.11

### ISSUE THREAD

**Issue by sebglon** [derekparker/delve#1394]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
go version go1.11.1 linux/amd64

3. What operating system and processor architecture are you using?
go version go1.11.1 linux/amd64

4. What did you do?
Install dlv with cmd 
```
go get -u github.com/derekparker/delve/cmd/dlv
```
5. What did you expect to see?
dlv is installed
6. What did you see instead?
```
$ go get -u github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/cmd/dlv
2018/10/30 15:29:36 /usr/lib/go-1.11/pkg/linux_amd64/compress/zlib.a(__.PKGDEF/): unexpected end at 44938, want 4941

```

**Comment by aarzilli** [comment]
You probably have a network problem.

**Comment by adler99** [comment]
I've exactly the same error, don't think it's a network problem. Same go version, ubuntu OS...

**Comment by sebglon** [comment]
This come only when i have installed golang with apt (on ubuntu)
Now i have installed golang from source and all is OK for me.
I sink it's a bug on golang builded package for ubuntu.

**Comment by sebglon** [comment]
And of course, it's not a network problem, because i have the same with your github repo and make install
