### ISSUE TITLE
Enable configuration

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#140]
Delve should be able to read in a configuration file, with certain configuration defaulted, and configuration should be modifiable at runtime.

**Comment by derekparker** [comment]
Enable configuration of path length when printing current location (full path vs shortened). \cc @ignatov

**Comment by ignatov** [comment]
May be for the first time a command line will be OK?

**Comment by ignatov** [comment]
@derekparker What do you think about adding a command line parameter for full/short file paths? I believe that for other visual debuggers such option would be useful.

**Comment by derekparker** [comment]
I think that makes sense. I could have a patch adding that feature up
today.

**Comment by ignatov** [comment]
Nice to here that!
