### ISSUE TITLE
dlv debug got "could not launch process: could not find __debug_line section in binary"

### ISSUE THREAD

**Issue by iceEvening** [derekparker/delve#1406]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0
Build: $Id: c98a142125d0b17bb11ec0513bde346229b5f533 $

2. What version of Go are you using? (`go version`)?
go version go1.11.1 darwin/amd64

3. What operating system and processor architecture are you using?
ProductName:    Mac OS X
ProductVersion: 10.14
BuildVersion:   18A391

4. What did you do?
dlv debug main.go

5. What did you expect to see?
Correct information

6. What did you see instead?
could not launch process: could not find __debug_line section in binary

I installed delve through "https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md".
But I got a "could not launch process: could not find __debug_line section in binary" error.

**Comment by aarzilli** [comment]
You need version 1.1.0 of delve to debug go 1.11 executables.

**Comment by chainhelen** [comment]
#https://github.com/golang/go/issues/27362

**Comment by iceEvening** [comment]
@aarzilli it works, thank you!
