### ISSUE TITLE
Build ID seems ambiguous

### ISSUE THREAD

**Issue by SteelPhase** [derekparker/delve#1411]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```
2. What version of Go are you using? (`go version`)?
`go version go1.11 windows/amd64`
3. What operating system and processor architecture are you using?
Windows 10 and macOS 10.13.6
4. What did you do? 
`dlv version`
5. What did you expect to see?
A build ID that could be tied back to the git repo
6. What did you see instead?
```
dlv version
Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
```

Is there a method to tie this blob SHA git attribute back to a git commit in this repo?

**Comment by aarzilli** [comment]
If delve was built with make: yes (it is a commit id). If it was built with go get/go build: no. Git doesn't have a way to write the commit id to a file on checkout and go doesn't have a way to store the commit id to a variable on build automatically.

**Comment by SteelPhase** [comment]
Thanks for verifying that, I was assuming it was a bug on my end at first.
