### ISSUE TITLE
Can't install on Ubuntu 16.04 Go 1.8.7

### ISSUE THREAD

**Issue by ozlevka-ericom** [derekparker/delve#1424]
/opt/go/src/github.com/derekparker/delve/pkg/dwarf/op/op.go:4: import /opt/go/pkg/linux_amd64/bytes.a: object is [linux amd64 go1.8.7 X:framepointer] expected [linux amd64 go1.6.2 X:none]
# github.com/derekparker/delve/pkg/dwarf/line
/opt/go/src/github.com/derekparker/delve/pkg/dwarf/line/line_parser.go:4: import /opt/go/pkg/linux_amd64/bytes.a: object is [linux amd64 go1.8.7 X:framepointer] expected [linux amd64 go1.6.2 X:none]
# github.com/derekparker/delve/pkg/dwarf/frame
/opt/go/src/github.com/derekparker/delve/pkg/dwarf/frame/entries.go:4: import /opt/go/pkg/linux_amd64/encoding/binary.a: object is [linux amd64 go1.8.7 X:framepointer] expected [linux amd64 go1.6.2 X:none]
# github.com/derekparker/delve/vendor/golang.org/x/crypto/ssh/terminal
/opt/go/src/github.com/derekparker/delve/vendor/golang.org/x/crypto/ssh/terminal/terminal.go:8: import /opt/go/pkg/linux_amd64/bytes.a: object is [linux amd64 go1.8.7 X:framepointer] expected [linux amd64 go1.6.2 X:none]
# github.com/derekparker/delve/pkg/config
/opt/go/src/github.com/derekparker/delve/pkg/config/config.go:4: import /opt/go/pkg/linux_amd64/fmt.a: object is [linux amd64 go1.8.7 X:framepointer] expected [linux amd64 go1.6.2 X:none]
# github.com/derekparker/delve/vendor/github.com/spf13/cobra
/opt/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/bash_completions.go:4: import /opt/go/pkg/linux_amd64/fmt.a: object is [linux amd64 go1.8.7 X:framepointer] expected [linux amd64 go1.6.2 X:none]

**Comment by aarzilli** [comment]
Your Go install is broken, not a bug with delve.

**Comment by ozlevka-ericom** [comment]
Cool way to close bag... I will use this way... Thank you for lesson
