### ISSUE TITLE
Incorrectly detected goroutine ID with cgo tests (linux/amd64)

### ISSUE THREAD

**Issue by aarzilli** [derekparker/delve#1428]
1. `go get -u github.com/lfittl/pg_query_go`
2. `dlv test`
3. `b parse_test.go:707`
4. `c`

Expected: code is running a current goroutine
What happens: no current goroutine

Additionally we should treat `GoroutineID == 0` in api.EvalScope as selecting the current thread if the current thread is not running a goroutine.

Bug originally reported as: https://youtrack.jetbrains.com/issue/GO-6497

**Comment by aarzilli** [comment]
cc @heschik

there's a problem with the code in `setGStructOffsetElf`, since you originally contributed it I was wondering if you had any insight on who's to blame here between delve and the linker.

How to reproduce:

1. clone the above repository
2. compile with `go test -c -gcflags='all=-N -l'`

the offset detected by `setGStructOffsetElf` ([currently residing here](https://github.com/derekparker/delve/blob/master/pkg/proc/bininfo.go#L723)) is 0xfffffffffffffa0c, however disassembling github.com/lfittl/pg_query_go_test.TestParseError gives this:

	parse_test.go:707	0x701790	64488b0c2508faffff		mov rcx, qword ptr fs:[0xfffffa08]
	parse_test.go:707	0x701799	488d8424a8feffff		lea rax, ptr [rsp+0xfffffea8]
	parse_test.go:707	0x7017a1	483b4110			cmp rax, qword ptr [rcx+0x10]
...

where the g struct offset is clearly different. Happens with 1.11 as well as tip.

runtime.tlsg address is 0x158 

PT_TLS program header is:

     TLS off    0x000000000071c118 vaddr 0x0000000000d1c118 paddr 0x0000000000d1c118 align 2**3
         filesz 0x0000000000000156 memsz 0x000000000000074c flags r--

which matches what we are calculating in `setGStructOffsetElf`

**Comment by heschik** [comment]
Works on my machine with GNU ld 2.30, I'm afraid. What linker are you using?

https://github.com/golang/go/blob/71f9f4b84b2974acf723ea78c1c6eb82d6755794/src/cmd/link/internal/ld/data.go#L236 is the relevant part of the Go linker. It might help to look at the relocations in `__go__.o` and make sure they aren't surprising.

**Comment by aarzilli** [comment]
```
GNU ld (GNU Binutils for Ubuntu) 2.30
```

the relocations look good. The one for the `mov` in `main.main` is:

```
000000000022b195 R_X86_64_TPOFF32  runtime.tlsg
```

which seems like it's the right thing. Is the size of PT_TLS emitted on your machine a multiple of 0x8? As you can see above for me it isn't, and looking through the code of  GNU binutils I found this:

```
 static bfd_vma
elf_x86_64_tpoff (struct bfd_link_info *info, bfd_vma address)
{
  struct elf_link_hash_table *htab = elf_hash_table (info);
  const struct elf_backend_data *bed = get_elf_backend_data (info->output_bfd);
  bfd_vma static_tls_size;

  /* If tls_segment is NULL, we should have signalled an error already.  */
  if (htab->tls_sec == NULL)
    return 0;

  /* Consider special static TLS alignment requirements.  */
  static_tls_size = BFD_ALIGN (htab->tls_size, bed->static_tls_alignment);
  return address - static_tls_size - htab->tls_sec->vma;
}
```

**Comment by heschik** [comment]
Yeah, it is a multiple of 8. I checked with Ian Taylor and he said rounding the address was probably the thing to do.

**Comment by aarzilli** [comment]
I've scanned through the ELF TLS ABI document and I couldn't find anything that talks about this but I guess it's true.
