### ISSUE TITLE
[Feature] Support docker API server debugging workflow

### ISSUE THREAD

**Issue by shiro** [derekparker/delve#1430]
**1. What version of Delve are you using (`dlv version`)?**
```
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c2
```
**2. What version of Go are you using? (`go version`)?**
`go version go1.11.2 linux/amd64`
**3. What operating system and processor architecture are you using?**
`windows 64x with docker on go:alpine`

**4. What did you do?**

I attempted to use delve for debugging an API server in a docker container.

Like many other people I am developing with docker and some sort of hot-reloading.
How would I go about using delve without having to attach a debugger in order for the app to start, but rather attach later?

I tried all the combinations with `--init` (which obviously does not work with headless), `--accept-multiclient` (still waits for a client first) and without `--headless` (which does not open a remote server.

Also, no matter what I try, I can only connect to the delve debugger once (with Jetbrains IntelliJ IDE). Once I try to reconnect the server shuts down and the process is terminated.

Building micro-services in docker and IntelliJ GoLand seems to be getting more popular and it would be great to support this kind of workflow.

**5. What did you expect to see?**

Allow for a way to setup a dev docker container with hot reloading, debugging, auto start and the ability to re-attach to the debugger host on a running server.

**6. What did you see instead?**

The hot reloading part can be achieved using an external, hot reloading binary (although this feels hackish), but the server waits for a delve client before starting.

This is related to #952, which does not seem to have been resolved.

**Comment by aarzilli** [comment]
> How would I go about using delve without having to attach a debugger in order for the app to start, but rather attach later?

Pass `--headless` and `--accept-multiclient` to one instance of dlv then invoke dlv a second time like this: `dlv --init <(echo "exit -c") connect ...`.

> Also, no matter what I try, I can only connect to the delve debugger once (with Jetbrains IntelliJ IDE). Once I try to reconnect the server shuts down and the process is terminated.

That depends on what IntelliJ does, the accept-multiclient stuff was broken for a long time it may not support it correctly.

**Comment by dlsniper** [comment]
cc @zolotov, please have a look at the thread.

**Comment by shiro** [comment]
@aarzilli also tried this already.
After the first connect and `exit -c` the server starts, but after attempting to connect to the session again (in the same CLI, no IntelliJ) it just freezes and there is no output.

Is there some other flag that has to be used here or is it a bug?

**Comment by aarzilli** [comment]
See pull request.

**Comment by shiro** [comment]
I tested your branch and as far as I can tell the following is fixed:
- with a second session (still a hack imo) it's possible to continue the process after server start
- it is possible to reconnect multiple times with the CLI, server keeps running (nice)

The following things still do not work:
- after the server is running and has been "continued" by the CLI, IntelliJ won't connect
- the server stops when IntelliJ finishes a debug session

With some bash scripting it is now possible to achieve a hot-reloading server with debugging, although it would be a big hack (restart process on stop, initial "continue" by second subshell...)

**Comment by aarzilli** [comment]
We can't fix the behavior of IntelliJ.

**Comment by shiro** [comment]
Yep, will create an issue in the Jetbrains issue tracker later.
Any chance the initial continue could be performed with some kind of flag or with `--init`?

Anything is better than having to spawn 2 subshells to get a debug-capable server running.

Thanks again for the PR, saved my day! 😃

**Comment by aarzilli** [comment]
I don't see why starting a subshell is a problem when you are initializing a whole container every time.

**Comment by shiro** [comment]
Personally for me it's not a big problem, since I have to write the script once.

I just imagine that not everyone is building complex docker containers,
If something works without having to research how to write a script that will start a server it is a very good thing IMO. 😃

Just my humble opinion though, in some way the issue can be considered "fixed", thanks!
