### ISSUE TITLE
dlv debug says "Cannot find package"

### ISSUE THREAD

**Issue by imrandurani** [derekparker/delve#1437]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
    **1.1.0**
2. What version of Go are you using? (`go version`)?
    **go1.11 linux/amd64**
3. What operating system and processor architecture are you using?
    **Ubuntu 16.04 LTS / amd64**
4. What did you do?
    **I am trying to debug geth with delve**
5. What did you expect to see?
   **I expect to see debug shouldn't prompt with import packages errors, since they are working fine without debug**
6. What did you see instead?
   **main.go:31:2: cannot find package "github.com/elastic/gosigar" in any of:
	/home/user/tools/go/src/github.com/elastic/gosigar (from $GOROOT)
	/home/user/tools/gopath/src/github.com/elastic/gosigar (from $GOPATH)**
This is just a sample error, there are many import packages like this in my main.go and it is failing to find all of them. 

here are my go and gopath configurations:

export GOROOT=$HOME/tools/go
export GOPATH=$HOME/tools/gopath
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

However, my project files are located in my $HOME/git directory. 
When I type *dlv* and *go* it works fine prompting with the info in the terminal. That means there is nothing wrong with go and delve setup and configuration. 

What I am trying to do is to initialize geth with dlv debug. However, I already have initialized genesis separately. Since my delve and go settings are fine then why geth is failing to find import packages while executing with delve?

dlv debug -- --datadir=`dirname --rpcapi="something" --rpc --rpcaddr " ..... 

A quick help would be appreciated.

**Comment by derekparker** [comment]
The issue as I understand it is that you are trying to debug a project that is checked out to `~/git` while your `$GOPATH` is `~/tools/gopath`. You should have your project checked out under your gopath following import conventions.

**Comment by imrandurani** [comment]
@derekparker It helped, Thank You!
