### ISSUE TITLE
Error installing Delve on Windows 10 x64 (Go v.1.11.4)

### ISSUE THREAD

**Issue by tms320** [derekparker/delve#1446]
go version: go1.11.4 windows/amd64
OS: Windows 10 x64
I try to install delve using the following command:
go get -u -v github.com/derekparker/delve/cmd/dlv
But during installation I get the following output:
```
github.com/derekparker/delve (download)
github.com\derekparker\delve\pkg\proc\arch.go:6:2: found packages frame (entries.go) and frame_test (parser_test (2).go) in C:\Users\MyName\Programming\Go\src\github.com\derekparker\delve\pkg\dwarf\frame
```
(the return code of 'go get ...' command mentioned above is 1)
The same error I get if install Delve via VSCode.
My %GOPATH% variable is:
C:\Users\MyName\Programming\Go

**Comment by aarzilli** [comment]
Your checkout of delve is corrupted, there is no file called "parser_test (2).go" in the repository. Delete it and start from the beginning.
