### ISSUE TITLE
how to pass multi parameters

### ISSUE THREAD

**Issue by xiazemin** [derekparker/delve#1447]
I need 3 parameters 
`autotest -all -w ./`
but, this ` dlv debug autotest/main.go -- -all=true -w=true -template_dir="./"
` dosn't work, why ?

**Comment by chainhelen** [comment]
1. You should read [`Filing issues`](https://github.com/derekparker/delve/blob/master/CONTRIBUTING.md#filing-issues) first. 

2. The usage of  "--" seem to be all right, maybe something else wrong.

**Comment by aarzilli** [comment]
works for me:

```
% cat args.go
package main

import (
	"os"
	"fmt"
)

func main() {
	fmt.Printf("args: %q\n", os.Args)
}
% dlv debug args.go -- autotest -all -w ./
Type 'help' for list of commands.
(dlv) c
args: ["/home/a/temp/debug" "autotest" "-all" "-w" "./"]
Process 17536 has exited with status 0
```
