### ISSUE TITLE
Refactor: cleanup method duplication

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#146]
\cc @ironcladlou (your familiar with these sections of the code) & @kerlyn-bsd3 because I know you've felt some of this pain with the code you're writing.

As it currently stands, any time a new command is added, at least 4 places _must_ be updated:

1. A method must be added to `proc.DebuggedProcess`.
2. A method must be added to `debugger.Debugger`.
3. A method must be added to the client(s).
4. An entry must be made in the commands map, and a function must be created for that command.

I would like to work on refactoring this in order to DRY the code up, ideally eliminating `debugger.Debugger`. I have pushed up patches recently that made any method on `DebuggedProcess` that _needed_ to be run on a specific thread (ptrace syscall) now completely safe, so that reasoning for `debugger.Debugger` is gone. The main purpose of that struct has become simply to convert from `proc` types to `api` types.

A couple of ideas I have to eliminate `debugger.Debugger`:

* Have any `proc.DebuggedProcess` method that a client would call return a full state struct. This gets slightly complicated however for methods such as `Break` which currently return information on the new breakpoint that was just added. The new scheme could put more burden on the client.
* Merge the JSON annotations in `api.Types` into their corresponding `proc` type. This eliminates having to do any conversions at all as we could simply marshal those types directly back to the client.

I'd really appreciate feedback and any help I can get with this refactor (pull requests!).

**Comment by ironcladlou** [comment]
Great ideas. I'll try and find time in the next few days to digest them and revisit the codebase. I've been slammed lately.

**Comment by derekparker** [comment]
As I think through this more, I feel that `debugger.Debugger` should stay, as it's nice to have a higher level of abstraction over what's provided in `proc`. Also, it can handle the things needed by clients but not needed in the lower level `proc` package, and types like `proc.DebuggedProcess`.

I still feel there is a too many steps required to add a new command, but I do not have a strong idea of how to DRY things up nicely.
