### ISSUE TITLE
Failures of TestStacktrace

### ISSUE THREAD

**Issue by aarzilli** [derekparker/delve#152]
I've been noticing some failures in TestStacktrace. What happens is that sometimes the line:
```nbp.Temp = bp.Temp```
at proc/threads.go:86 results in a nil pointer dereference (note: this happens sporadically).

This doesn't seem to have anything to do with Stacktrace itself, it seems to be a problem when Continue is called when the program is sitting on a breakpoint.

Further investigation reveals that Process.setHardwareBreakpoints fails with "no such process" error. The "no such process" part is a lie, the process exists *but* sometimes not all the processes inside Process.Threads are in "tracing stop" state when Process.setBreakpoint calls Process.setHardwareBreakpoint and ptrace probably doesn't like that. I don't know why this happens, but it is a bug.

Aside: I see that you have added a call to runtime.GOMAXPROCS(2) in init, I think it would be better to also os.Setenv("GOMAXPROCS", "2") so that spawned test programs inherit it.

**Comment by derekparker** [comment]
Should be fixed by c15f23a7beee15f6f4b1353736f0147b14560500.
