### ISSUE TITLE
How to use the RPC server interface?

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#157]
Hi,

I'm having issues using the RPC server outside of Go and I'm not sure how to proceed.

start delve:
```bash
dlv -addr="127.0.0.1:6663" -log -headless run ./u.go
```

run request
```bash
curl -i http://127.0.0.1:6663 \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
--data-binary '{"method": "RPCServer.State", "params": [], "id": 1}'
curl: (52) Empty reply from server
```

delve logs
```
2015/06/28 22:18:01 /home/florinp/golang/src/github.com/derekparker/delve/service/debugger/debugger.go:53: launching process with args: [./debug ./u.go]
2015/06/28 22:18:10 /usr/local/go/src/net/rpc/server.go:300: method Run has wrong number of ins: 1
2015/06/28 22:18:10 /usr/local/go/src/net/rpc/server.go:300: method Stop has wrong number of ins: 2
```

Another problem is that after the above curl, if I send a new one like this:

```bash
curl -i http://127.0.0.1:6663 \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
--data-binary '{"method": "RPCServer.State", "id": 1}'
```

the curl process is going to be stuck and there's no output from delve.
If I restart delve and run the curls in reverse order the result is the same.
Moreover, I think the error that delve is reporting about method Run and Stop are valid errors from the RPC server but I have zero experience with doing such a server so I don't know where to start debugging this.

I'll have a look in the coming days but if someone else can point me in the right direction that would be awesome. Thank you!

EDIT:
I've turned on long file names in delve for logging as I wasn't sure from where the error comes from.
Delve revision: 29ed16984851be78fadf8e70ad908d37cd3c47f3

**Comment by derekparker** [comment]
So the implementation I'm using is not going over HTTP, it's just JSON-RPC over a socket.

Could you try using a JSON-RPC client in your language of choice? A quick search turned up a Python implementation (https://www.artima.com/weblogs/viewpost.jsp?thread=333589) [NOTE: I have not vetted this to see if it works].

If you still run into issues after using a client in a scripting language let me know, and I can dig into it a bit more.

Also, `dlv run` does not take arguments, it assumes it needs to compile (i.e. run `go build`).

**Comment by derekparker** [comment]
Additionally here is a list of JSON-RPC implementations in other languages: https://en.wikipedia.org/wiki/JSON-RPC#Implementations

**Comment by derekparker** [comment]
@dlsniper going to close this issue. If you're still running into issues, ping me in the gitter chat.
