### ISSUE TITLE
[OSX 10.8.5] Can't seem to be able to debug a program 

### ISSUE THREAD

**Issue by henry-zhuang** [derekparker/delve#160]
Running a process
```
dlv run
could not launch process: could not fork/exec
[Hope I was of service hunting your bug!]
```

**Comment by flike** [comment]
+1

**Comment by derekparker** [comment]
Seems related to #159. Have you signed the binary as per: https://github.com/derekparker/delve/wiki/Building#os-x ?

**Comment by henry-zhuang** [comment]
@derekparker 

>  Run the following: CERT=$mycert make install, which will install the binary and codesign it.

Does it mean enter `codesign -s dlv-cert $(which dlv)`?

**Comment by derekparker** [comment]
@henry-zhuang yes, you must codesign the dlv binary before using it on OSX.

**Comment by henry-zhuang** [comment]
@derekparker 
```
 ~/ codesign -s dlv-cert $(which dlv)
/Users/MasterMac/.gvm/pkgsets/system/global/bin/dlv: is already signed
 ~/ dlv run hello.go
Could not compile program: exit status 1
[Hope I was of service hunting your bug!]
```

**Comment by derekparker** [comment]
Looks like `go build` is failing. Can you compile the program normally?

**Comment by henry-zhuang** [comment]
@derekparker Yes, I enter `go build hello.go`

It succeed and run normally.

**Comment by derekparker** [comment]
Hmmm, can you send a gist of hello.go? Also `dlv run` does not take
arguments.

**Comment by henry-zhuang** [comment]
@derekparker Thank you. It works.

It must run in the only `hello.go` folder.

**Comment by mikepc** [comment]
I'm on 10.9.5, I have followed all of the instructions and I'm still receiving this error. Looking for ideas.  I signed dlv successfully but it is still giving me the same issue. Works fine on my later version mac at home, but at work (I work for Nordstrom corporate) we are locked on OS 10.9.5 

I receive the same error when I run as root as well as sudo. 

- The private key is accessible by all applications (make install runs without an issue)
- The certificate is set to "Always Trust" for everything.

What else can I try?

**Comment by britannic** [comment]
If you haven't already checked, make sure you don't have multiple versions of dlv installed, "which -a" is very useful, e.g.:

`| => which -a dlv
/usr/local/bin/dlv
/usr/local/bin/dlv
/usr/local/go/bin/dlv
/usr/local/go/bin/dlv`

**Comment by mikepc** [comment]
x74f@M00973121:~$ source ~/.terminal_startup
x74f@M00973121:~$ cd $GOPATH/src/asf
x74f@M00973121:~/goapi/src/asf$ dlv debug
could not launch process: could not fork/exec
x74f@M00973121:~/goapi/src/asf$  which -a dlv /usr/local/bin/dlv /usr/local/bin/dlv /usr/local/go/bin/dlv /usr/local/go/bin/dlv
/usr/local/bin/dlv
/usr/local/bin/dlv
/usr/local/bin/dlv
x74f@M00973121:~/goapi/src/asf$ codesign -s dlv-cert $(which dlv)
/usr/local/bin/dlv: is already signed

**Comment by britannic** [comment]
Is " /usr/local/go/bin/dlv" signed also? Its possible that when you execute dlv, " /usr/local/go/bin/dlv" get called before your signed version (if it isn't already signed the same as "/usr/local/bin/dlv").

**Comment by mikepc** [comment]
Sorry, there is only one, that was part of the other one

x74f@M00973121:~/goapi/src/asf$ which -a dlv
/usr/local/bin/dlv
x74f@M00973121:~/goapi/src/asf$

**Comment by mikepc** [comment]
sudo GOPATH=/Users/x74f/goapi dlv debug
Password:
could not launch process: invalid magic number in record at byte 0x0

**Comment by mikepc** [comment]
Reading https://github.com/derekparker/delve/issues/474 now

**Comment by mikepc** [comment]
I uninstalled all versions of delve, and deleted the certificate starting over with a HomeBrew installation.

Now I get the could not launch process: invalid magic number in record at byte 0x0 error consistently.

**Comment by mikepc** [comment]
Native only.

**Comment by mikepc** [comment]
I *am* able to run dlv exec to get the (dlv) prompt, I just can't run dlv debug

**Comment by mikepc** [comment]
Found it.. package main

I'm good to go. Thank you!
