### ISSUE TITLE
Can't start the debug process successfully

### ISSUE THREAD

**Issue by NanXiao** [derekparker/delve#161]
(1) The version of delve:   

        [root@Fedora ~]# delv -v 
        delv 9.10.2-RedHat-9.10.2-1.fc22

(2) The version of Go:  

        [root@Fedora ~]# go version
        go version go1.4.2 linux/amd64

(3) OS and processor architecture:  

	[root@Fedora ~]# uname -a
	Linux Fedora 4.0.4-301.fc22.x86_64 #1 SMP Thu May 21 13:10:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

(4) Issue description:  

I doubt the this issue is related to my computer changes network IP, but not sure.

1) Debug the program using full path:  

	[root@Fedora ~]# delv /root/syncWait
	;;   validating ./NSEC: got insecure response; parent indicates it should be secure
	;;   validating ./NSEC: got insecure response; parent indicates it should be secure
	;; no valid RRSIG resolving '/root/syncWait/DS/IN': 16.110.135.51#53
	;;   validating ./NSEC: got insecure response; parent indicates it should be secure
	;; no valid RRSIG resolving '/root/syncWait/DS/IN': 16.110.135.52#53
	;; no valid DS resolving '/root/syncWait/A/IN': 16.110.135.51#53
	;;   validating ./NSEC: got insecure response; parent indicates it should be secure
	;; validating /root/syncWait/A: bad cache hit (/root/syncWait/DS)
	;; broken trust chain resolving '/root/syncWait/A/IN': 16.110.135.52#53
	;; resolution failed: broken trust chain

2) Debug the program using relative path:   

        [root@Fedora ~]# pwd
        /root
        [root@Fedora ~]# delv ./syncWait
        ;; failed to convert QNAME ./syncWait: empty label

**Comment by pnasrat** [comment]
`delv` is not the correct command you need to install `dlv` as per https://github.com/derekparker/delve/wiki/Building 

The `delv` binary you are running is part of the `bind` package 

http://pkgs.fedoraproject.org/cgit/bind.git/tree/bind.spec?h=f22#n857 

Man page ftp://ftp.isc.org/isc/bind/cur/9.10/doc/arm/man.delv.html

**Comment by derekparker** [comment]
@pnasrat is correct. Invoke with `dlv`.
