### ISSUE TITLE
proc.(*Thread).GetG does not work on linux/go1.4.2 when the debugged process uses cgo (even indirectly)

### ISSUE THREAD

**Issue by aarzilli** [derekparker/delve#163]
proc.(*Thread).GetG assumes that the pointer to the g struct happens at address FS:-16, this is true as long as the program was linked by go itself, which is the most common case, however if the program (or one of its dependencies) uses cgo the linking will be done externally by ld and the g struct will end up at address FS:-8.

This can be verified by writing a simple program that uses cgo and then use gdb to disassemble runtime.stackcheck, the very first instruction (an access to the g struct) will be ```mov rax,QWORD PTR fs:0xfffffffffffffff8```, on internally linked programs it's: ```mov rax,QWORD PTR fs:0xfffffffffffffff0```.

There are two possible things that can be done about this:

1. Make delve check the dwarf information after attaching to a process, if it finds a compile unit that suggests cgo use switch the offset from -16 to -8
2. Do nothing. If I read [this](https://github.com/golang/go/issues/9913) correctly this idiosyncrasy will be removed in go 1.5 (however delve will need to change -16 to -8 to work with go 1.5).

**Comment by derekparker** [comment]
The ideal solution here would be to determine the offset at runtime. I think we could get away with attempting to verify the type of binary we're dealing with.

For the cgo case, we can check `runtime.iscgo` in the attached binary, which is a boolean. For Go1.4 / Go1.5 differences, I'm not sure off the top of my head. I'd have to do some digging to see how we could determine that.

**Comment by derekparker** [comment]
Fixed by https://github.com/derekparker/delve/pull/177
