### ISSUE TITLE
Document JSON-RPC service

### ISSUE THREAD

**Issue by joefitzgerald** [derekparker/delve#164]
@derekparker I am the author of [`go-plus`](https://github.com/joefitzgerald/go-plus), and will also be building a general / extensible debugging package for Atom - [debugger](https://github.com/atom-community/debugger) which will incorporate the Chromium developer tools' debugging UI.

I would like to begin integrating delve as part of this, but I'm unsure of the status of `dlv` regarding its ability to be driven programmatically / its ability to accept / return structured output that could be used for the integration. Can we explore this in more detail in this issue?

**Comment by derekparker** [comment]
It's not well documented, but there is facilities for communicating with a Delve debug server via JSON-RPC.

I can provide more information on this, and I'll be working on some documentation as well, however in the meantime take a look at what the client is doing in `service/rpc/client.go`, or feel free to reach out to me here or on gitter.

I'll keep this thread open in the meantime until the documentation is put together.

**Comment by derekparker** [comment]
I renamed this issue to be more generically applicable to those seeking to integrate with the JSON-RPC service externally.

**Comment by metal3d** [comment]
@joefitzgerald I was near to open an issue on go-plus to ask you if you can provide interface to delve :) so I put a +1 here ;)

**Comment by frapposelli** [comment]
@joefitzgerald the folks at Microsoft integrated `delve` with their VS IDE, this is the relevant part in their repo: https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter

**Comment by lloiser** [comment]
@joefitzgerald have you made any progress? it seems that the development on https://github.com/atom-community/debugger has stopped a while ago ...

Btw I have created a package around the rpc server over the last few days and it works fine. I will create a github and atom package for it in the next few days. Maybe I will try to integrate the chrome dev tools too ...

**Comment by joefitzgerald** [comment]
@lloiser frankly the debugger project remains a placeholder - I never got the time to make progress there. I would be happy to review a pull request / add you as a contributor to that project.
