### ISSUE TITLE
New processes are stopped immediately after fork, many commands return weird error messages in this state

### ISSUE THREAD

**Issue by alaska** [derekparker/delve#165]
After following the instructions for OSX, including self-signing the app, building it and testing it (all passed), I get the following when I try to debug a simple program:

```
$ pwd
/Users/andy/go/src/test/delve
$ ls
main.go
$ cat main.go
package main

import "fmt"

func main() {
    fmt.Println("Hello, Delve!")
}
$ dlv run
Type 'help' for list of commands.
(dlv) n
Command failed: error derefing defer could not read memory
(dlv) 
```

**Comment by derekparker** [comment]
I think I know the underlying issue here, however this brings about another issue: currently a brand new process will be stopped immediately after it is forked. Would it make sense instead to advance the program to the "main.main" function, essentially landing the user in a useful stop by default?

I'd like some feedback on this, but it seems like the right thing to do.

**Comment by alaska** [comment]
Aside from perhaps ```init()``` functions, is there anything the average user can even reasonably do about anything that comes before main.main? If not, I'd consider skipping directly to it.

**Comment by derekparker** [comment]
@alaska exactly, and the answer there is: not really. A flag would be a reasonable option, for stopping immediately after forking.

I'll take this into consideration, bearing `init()` functions in mind. Essentially what would be nice is to put the user at the first instance of "user" code being executed.

**Comment by iverberk** [comment]
First time user of Delve and I'm hitting this issue. I thought I should start with a simple program but I'm immediately hitting this error. I can't quite understand what's going on here. Is there a way to debug a simple hello world program: make it stop on the first (and only line) in the main function?

**Comment by aarzilli** [comment]
Set a breakpoint on main with `break main.main`, then `continue`. It should stop on the first line of main. If it doesn't work it's a bug (a different bug from this one).

**Comment by iverberk** [comment]
Awesome, it works, thanks!

**Comment by ThreeBearsDan** [comment]
@aarzilli Thanks ur answer. It works correctly now. But I still doubt for it. U know, when I set a breakpoint first, then I run it again, use restart command in delve. It should works normally. But it doesn't work. In gdb, it works like this. U can set a breakpoint first and then run it again.
