### ISSUE TITLE
Debugger crashes immediately on OS X 10.11 SeaLion with Kill 9 error

### ISSUE THREAD

**Issue by tonyconstantinides** [derekparker/delve#168]
I followed instructions and was able to build and install from source and also to create a self signed cert.
All that worked. When I run the debugger it crashes with a kill 9 message. When I set a breakpoint using the runtime class and type "dlv run hello.go" it crashes with a kill 9 error

**Comment by derekparker** [comment]
Do you mean 10.11 El Capitan? I do not have 10.11 installed on my machine, however maybe I could look into this. However, `dlv run` does not take an argument. It is meant to be run standalone. This is actually a common point of confusion, so I'm considering dropping `run` altogether and just assume the default behavior when executing `dlv`.

**Comment by lamielle** [comment]
@tonyconstantinides is it possible that the binary was not signed properly? On 10.10 I was seeing an error, "unable to fork/exec" when running "dlv run".  Once I rebuilt the binary and followed the signing steps fully that stopped happening.  I did not check the exit code but I suspect it was probably SIGKILL.

**Comment by tonyconstantinides** [comment]
Hi,
Yes I mean I running 10.11 El Capitan. I also using the 1.5 beta 1 which I know you do not support yet.
I really should of read more issues before filing this one. Feel free to ignore this issue until you have a chance to catch up with Go and OS X changes. I did try "dlv run mygoapp". I have carefully created the cert last night making sure I complete all the details so I do not  believe its a cert issue.(I may be wrong:).
I running OS X 10.11 its gone through I appStore update)
                 Go 1.5 beta1
                 Self signed cert dlv-cert like the example
                 2012 MacBook Pro retina with core i7 and 16gb of memory and 256 sad
                 GOROOT set to the 1.5beta1

**Comment by derekparker** [comment]
Closing this as it's a result of https://github.com/golang/go/issues/11887
