### ISSUE TITLE
Improve installation experience for OSX users

### ISSUE THREAD

**Issue by lamielle** [derekparker/delve#169]
Per my brief gophercon discussion with Derek I'm filing this issue to track discussion/changes around improving the installation experience for OSX users.  Specifically, the 'dlv' binary is required to be signed to comply with OSX security features.  Ideally the OSX install experience would be a simple as Linux, just run go get.

A few ideas around automating the binary signing when installing dlv:

1. Use a possibly non-existent 'go build' hook to run a signing script when go get is run (probably doesn't exist, but need to confirm)
2. Build an 'official' binary that is signed by Derek (?) and is trusted already.  I am unfamiliar with the process, but I expect it would not be possible use 'go get' to install the package.  Maybe getting a homebrew package in place would be an option?
3. Ask OSX users to install an intermediate binary, dlv-install, which when run would automate the building of the final dlv binary including signing the binary.

I'd guess option 3 is the mostly likely given that it seems possible and would maintain usage or running 'go get'.

@derekparker any comments or ideas based on some of the approaches I've suggested above?  I am not very familiar with the OSX mechanisms related to signing binaries so I should probably do some research to understand the problem space a little more.

**Comment by lamielle** [comment]
Some references I've found during some research:

GDB has the same issue on OSX: http://stackoverflow.com/questions/13913818/how-to-get-a-codesigned-gdb-on-osx  Solutions presented are to self-sign the binary (what we do for dlv already) or to disable the cert checks in OSX.  I don't think disabling the checks is a good idea to suggest to dlv users.

Relevant homebrew issue discussing this topic in the context of kernel extensions: https://github.com/Homebrew/homebrew/issues/31164  The solution they ended up using was to use an upstream pre-compiled binary for the tuntap extension which was pre-signed.

**Comment by derekparker** [comment]
I've decided to create a mailing list as a central place to discuss the design, proposals, and process regarding Delve development. Please continue this discussion here: https://groups.google.com/forum/#!topic/delve-dev/po4vRMx4zwc
