### ISSUE TITLE
info locals causes panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by etsuo** [derekparker/delve#171]
**Summary**
Running `info locals` causes: "runtime error: makeslice: len out of range". This consistently reproducible on my end.

**Environment**
1. Delve version: 0.5.0.beta
2. Go version go1.4 darwin/amd64
3. OS/X version 10.10.4 (14E46)

**Steps to Reproduce**
```
$ dlv run
(dlv) b main.main
(dlv) c
current loc: main.main /Users/jpoveda/dev/go/src/github.com/etsuo/hello/hello.go:8

    3:	import (
    4:		"fmt"
    5:		"sync"
    6:	)
    7:
=>  8:	func main() {
    9:		g := "hello delve"
   10:
   11:		wg := sync.WaitGroup{}
   12:		wg.Add(1)
   13:		go func() {

(dlv) info locals
panic: runtime error: makeslice: len out of range
```

**Comment by derekparker** [comment]
This has been during implementation of: https://github.com/derekparker/delve/commit/3cee10d8bc5331bde18f350be3ff33414dba2cc2.
