### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by quarnster** [derekparker/delve#182]
It'd be helpful if I could specify aliases for commands, preferably in a global and/or local config file.
Like
```
alias bt=stack
alias quit=exit
```

**Comment by joeshaw** [comment]
:+1: both of these have bit me recently.  I'll write up a patch for them now.

**Comment by derekparker** [comment]
Re-opening because alias command / external config not implemented.

**Comment by tylerb** [comment]
I think I'll take a stab at this.

@derekparker do you have a preferred config file format for this? Also, as there are many packages that deal with reading/writing config files, I feel it would be a good idea to use one of them. Are you averse to using a package for this?
