### ISSUE TITLE
`info locals` shows uninitialized value for as-yet undeclared variable

### ISSUE THREAD

**Issue by joeshaw** [derekparker/delve#186]
Running Delve 0.6.0.beta (a506bb7d8e33e85878866152ba738206dbef9209) and go version go1.4.2 darwin/amd64.  With the following test program:

``` go
package main

import "fmt"

func main() {
    fmt.Println("hello world")
    x := 100
    fmt.Println(x)
}
```

```
$ dlv run
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x2022 for main.main ./foo.go:6
(dlv) c
> main.main() ./foo.go:6

    1:  package main
    2:
    3:  import "fmt"
    4:
    5:  func main() {
=>  6:      fmt.Println("hello world")
    7:      x := 100
    8:      fmt.Println(x)
    9:  }

(dlv) info locals
x = 8589934592
```

`x` is undeclared at this point.  I'd expect either that it wouldn't display at `info locals` at all or that it'd say something like `x = (undeclared)`.  Once I step past the declaration/assignment, it has the correct value of `x = 100`.

**Comment by derekparker** [comment]
Related to https://github.com/derekparker/delve/issues/106, with similar issues for fixing.
