### ISSUE TITLE
`info break` for displaying breakpoints

### ISSUE THREAD

**Issue by joeshaw** [derekparker/delve#187]
I was a little surprised when I restarted a program and it lost my breakpoints.  (That could possibly be a separate issue to file?)  I use `info break` in gdb a lot to list the currently assigned breakpoints and I see that Delve doesn't have that.  It would be nice to have.

**Comment by aarzilli** [comment]
the `breakpoints` command is the `info break` equivalent

**Comment by joeshaw** [comment]
@aarzilli Ah, cool, thanks.  I find the difference between the `info` commands and the non-`info` ones (`breakpoints`, `goroutines`, `threads`) a little confusing because they seem arbitrary.  Why not have `locals` be a toplevel command too?

**Comment by derekparker** [comment]
I agree losing breakpoints upon using the `restart` command is surprising. I'll create a separate issue for that.

**Comment by derekparker** [comment]
@joeshaw I agree. I plan on moving all `info` subcommands to be top-level.

**Comment by joeshaw** [comment]
@derekparker awesome, thanks!
