### ISSUE TITLE
Cross compilation support?

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#195]
Hi, do you have any plans for cross compilation for delve?
Right now I can't manage it via `gox` and `go 1.5 b3` for instance:
```
gox -osarch="linux/amd64 darwin/amd64" -cgo github.com/derekparker/delve/cmd/dlv
Number of parallel builds: 2

-->    darwin/amd64: github.com/derekparker/delve/cmd/dlv
-->     linux/amd64: github.com/derekparker/delve/cmd/dlv

1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/derekparker/delve/proc
In file included from gopkg/src/github.com/derekparker/delve/proc/proc_darwin.go:3:0:
proc_darwin.h:2:21: fatal error: libproc.h: No such file or directory
 #include <libproc.h>
                     ^
compilation terminated.
# net
could not determine kind of name for C.AI_MASK
```

**Comment by derekparker** [comment]
I do plan to eventually start releasing official prebuilt binaries (possibly starting soon, and just start releasing nightly builds) - however I don't think proper cross-compilation could ever be supported. The OSX versions rely on OSX/mach specific header files.

**Comment by ignatov** [comment]
> I do plan to eventually start releasing official prebuilt binaries (possibly starting soon, and just start releasing nightly builds)
Nice to here that.
