### ISSUE TITLE
exec.Command(...).Wait() hangs forever

### ISSUE THREAD

**Issue by tylerb** [derekparker/delve#197]
When using delve to debug a program that runs an external program, delve will hang forever while waiting for the external program to terminate. The included sample application demonstrates this behavior:

```go
package main

import (
	"bufio"
	"fmt"
	"log"
	"os/exec"
)

func main() {
	cmd := exec.Command("date")
	reader, err := cmd.StdoutPipe()
	if err != nil {
		log.Fatalln(err)
	}
	scanner := bufio.NewScanner(reader)
	go func() {
		for scanner.Scan() {
			fmt.Println(scanner.Text())
		}
		reader.Close()
	}()
	cmd.Start()
	cmd.Wait()
}
```

**Comment by derekparker** [comment]
Working on this issue, have it reproduced locally. I have an idea of what's causing it, should have fix up before the end of the day.
