### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by frederich** [derekparker/delve#198]
Add support for Windows.

**Comment by ip** [comment]
Also need this

**Comment by jpop32** [comment]
Is there any work being done on this? With support for delve recently pulled into IntelliJ plugin this suddenly became a very interesting issue.

**Comment by derekparker** [comment]
Not that I am aware of, at the moment.

If somebody would be willing to take on this endeavor that would be great,
otherwise I will write the port as soon as I can.

**Comment by 0x003e** [comment]
+1

**Comment by knightyzj** [comment]
+1

**Comment by thanzen** [comment]
+1

**Comment by MikeGCV** [comment]
+1

**Comment by anidotnet** [comment]
+1

**Comment by yourchanges** [comment]
+1

**Comment by yaoshuangxi** [comment]
+1

**Comment by PapaStifflera** [comment]
+1

**Comment by sekeroth** [comment]
+1

**Comment by delaneyj** [comment]
I'm well aware this doesn't help but... +1

**Comment by ip** [comment]
Crowd of typical Windows users :D

**Comment by luiscarrasco** [comment]
G+1

**Comment by mrz1836** [comment]
+1

**Comment by ioanvapi** [comment]
+5 (... & some friends)

**Comment by ChristianPV** [comment]
+1

**Comment by Ekranos** [comment]
+1

**Comment by mantzas** [comment]
+1

**Comment by hatuan** [comment]
+1

**Comment by dimchansky** [comment]
+1

**Comment by yougg** [comment]
+1024

**Comment by ZloyDyadka** [comment]
+1

**Comment by LitixThomas** [comment]
+4096

**Comment by walfud** [comment]
+1

**Comment by chai2010** [comment]
+`(1/0)`

**Comment by akevinbailey** [comment]
+1

**Comment by seriallink** [comment]
+1

**Comment by derekparker** [comment]
Update: There is great work actively being done on this issue by @lukehoban, with functionality already successfully ported over.

**Comment by lukehoban** [comment]
Thanks @derekparker.  I've opened #276 to track the work on this port. 

Here's a preview of some of the currently supported functionality in that PR:

![rrl3i9no89](https://cloud.githubusercontent.com/assets/223467/10555617/b59581ca-7426-11e5-81ad-3a7dcc25d212.gif)

**Comment by himulawang** [comment]
+1

**Comment by GameXG** [comment]
+1

**Comment by ZhandosKz** [comment]
+1

**Comment by shrids** [comment]
+1

**Comment by mistbow-git** [comment]
+1 for Me)

**Comment by foxundermoon** [comment]
+10086

**Comment by davidwudv** [comment]
+10086

**Comment by hsen-dev** [comment]
+39

**Comment by jdzapata** [comment]
+1

**Comment by cedarwu** [comment]
+1

**Comment by JoshZA** [comment]
:+1:

**Comment by asampaleanu** [comment]
Is there a writeup on the steps to build this? I switched to the Windows branch and tried to build as per readme, but got:
```
$ GO15VENDOREXPERIMENT=1 make install
go install -ldflags="-X main.Build=bddb712a6b8e408d3da78e1f2d399661f074f7e9" github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/proc
c:\dev\projects\_go\src\github.com\derekparker\delve\proc\proc.go:52: undefined: OSProcessDetails
c:\dev\projects\_go\src\github.com\derekparker\delve\proc\threads.go:21: undefined: unix.WaitStatus
Makefile:44: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by asampal** [comment]
Or, if building on Windows is still not doable, does the CI box produce usable artifacts for this? I didn't see any at a glance.

**Comment by zanven42** [comment]
You Should look at the wip windows pull request.

**Comment by asampal** [comment]
I did, but how does that help? I tried what @joelday and@kolkov mentioned they did and still get output similar to the above.

**Comment by zanven42** [comment]
It's 4am for me. I'm sure if you write your exact issue someone will help you. #276 should have enough info to setup a build. 

Just make sure lukehoban's windows branch is in the correct folder and not the master branch. Since the above errors I saw when I did not use the windows build.

**Comment by kolkov** [comment]
@asampal @asampaleanu  I do not use vendor and GO15VENDOREXPERIMENT=1.
I only go to cmd/dlv folder and run go build. May be it's wrong? but it's worked for me!

**Comment by asampal** [comment]
@kolkov, I am using the Windows branch on @lukehoban's repo, but as you'll note above, the complaint comes from @derekparker's source. Thanks for the pre-built binary you provided in the Google group. I'd still like to be able to build this myself, though.

@zanven42 all I'm doing is cloning @lukehoban's repo, switching to the Windows branch, and following the build steps there for Linux, but using Bash under MSYS2/MingW-w64. I had to manually `go get` the dependencies as mentioned in the readme since without that I was getting errors about them being missing.

**Comment by lukehoban** [comment]
@asampal The errors you are seeing suggest that you haven't correctly checked out the `windows` branch from my fork.  Both of those errors refer to things which are in master but not in the PR branch.

**Comment by asampal** [comment]
@lukehoban does this look OK?
```
adi@serenity MINGW64 /c/dev/projects/_go/src/github.com/lukehoban
$ git clone https://github.com/lukehoban/delve.git
Cloning into 'delve'...
remote: Counting objects: 5804, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 5804 (delta 8), reused 0 (delta 0), pack-reused 5771
Receiving objects: 100% (5804/5804), 9.52 MiB | 3.03 MiB/s, done.
Resolving deltas: 100% (3608/3608), done.
Checking connectivity... done.

adi@serenity MINGW64 /c/dev/projects/_go/src/github.com/lukehoban
$ cd delve

adi@serenity MINGW64 /c/dev/projects/_go/src/github.com/lukehoban/delve
$ git checkout -b origin/windows
Switched to a new branch 'origin/windows'

adi@serenity MINGW64 /c/dev/projects/_go/src/github.com/lukehoban/delve
$ git status
On branch origin/windows
nothing to commit, working directory clean

adi@serenity MINGW64 /c/dev/projects/_go/src/github.com/lukehoban/delve
$ GO15VENDOREXPERIMENT=1 make install
go get -u github.com/peterh/liner
go get -u github.com/spf13/cobra
go get -u golang.org/x/sys/unix
go get -u github.com/davecheney/profile
go get -u gopkg.in/yaml.v2
go install  github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/proc
c:\dev\projects\_go\src\github.com\derekparker\delve\proc\proc.go:52: undefined: OSProcessDetails
c:\dev\projects\_go\src\github.com\derekparker\delve\proc\threads.go:21: undefined: unix.WaitStatus
Makefile:42: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by zanven42** [comment]
Put lukehobans files in Derek's folder and replace them. You are still building master and not the windows build.

**Comment by kolkov** [comment]
@asampal 
![image](https://cloud.githubusercontent.com/assets/3740898/12533200/6f331b00-c239-11e5-966d-d8274f448380.png)
![image](https://cloud.githubusercontent.com/assets/3740898/12533205/883798e2-c239-11e5-9f67-e07309abca4b.png)

**Comment by lukehoban** [comment]
Windows support is now available in master. :zap:

I've updated the wiki with build instructions for Windows: https://github.com/derekparker/delve/wiki/Building#windows.

There are a handful of known issues and not yet implemented features - which are being tracked in https://github.com/derekparker/delve/issues/363.  But generally speaking, the majority of Delve's functionality should be working on Windows.

Going forward, if you see issues uniquely on Windows, feel free to mention me in issue reports and I can help take a look.

**Comment by hatuan** [comment]
I have a problem with delve on WebStorm 11.0.3, breakpoint in HelloController it don't work.

/*------ main.go ---*/
router := routers.InitRoutes()
router.PathPrefix("/").Handler(http.StripPrefix("/", fileHandler))

n := negroni.Classic()
n.UseHandler(router)

/*--- route.go ---*/
func InitRoutes() *mux.Router {
	router := mux.NewRouter()
	router = SetAuthenticationRoutes(router)
	router = SetHelloRoutes(router)

	return router
}
func SetHelloRoutes(router *mux.Router) *mux.Router {
	router.Handle("/api/hello",
		negroni.New(
			negroni.HandlerFunc(authentication.RequireTokenAuthentication),
			negroni.HandlerFunc(controllers.HelloController),
		)).Methods("GET")

	return router
}

/*---- hello_controller.go ---*/
func HelloController(w http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
	w.Write([]byte("Hello, World!"))
}
If I set breakpoint in HelloController it don't work.

Breakpoint in HelloController work on Visual Studio Code.

**Comment by kolkov** [comment]
@hatuan what version of plugin you are using?

**Comment by hatuan** [comment]
@kolkov I have used both Go-0.10.SNAPSHOT.zip (http://kolkov.ru/share/dlv/dalve.rar) and update 0.10.607

**Comment by kolkov** [comment]
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1922#issuecomment-174260756
I think it's not a delve issue. It's plugin issue.
24 янв. 2016 г. 1:11 PM пользователь "Tuan Hoang Anh" <
notifications@github.com> написал:
