### ISSUE TITLE
Unable to get started with delve 

### ISSUE THREAD

**Issue by hackintoshrao** [derekparker/delve#200]
I did a `go get go get -u github.com/derekparker/delve/cmd/dlv` to fetch delve , then in the bin of my $GOPATH i could see the dlv binary on my linux machine , but `dlv <pathToMyProgram>` doesnt seem to doing anything . I tried `dlv run` too . Can anyone help me get started with delve ?

**Comment by aarzilli** [comment]
What error message are you getting?

**Comment by kraoadori** [comment]
No error messages at all , it just doesnt do anything !

**Comment by Karthic-Hackintosh** [comment]
No error message , it just doesnt do anything !

**Comment by aarzilli** [comment]
does it hang or do you get the bash prompt back? Try `dlv --log=true`

**Comment by Karthic-Hackintosh** [comment]
I get the bash prompt back , it doesnt hang

**Comment by aarzilli** [comment]
what happens if you pass `--log=true`?

**Comment by derekparker** [comment]
Do you get an error message when you use `dlvl run`? Are you using that command in the directory that you would run `go build` from? `dlv run` does not take arguments, it does not work in the same way that `go run` does.

There is a bug currently in cmd/dlv/main.go where it does not expect a path to a binary, like it used to. I can fix this and get a patch up soon.

**Comment by Karthic-Hackintosh** [comment]
1.No , I dont get an error message when i use `dlv run` 
2.Yes , I'm using dlv run from the directory of my project where i build it 
3.I'm running the dlv by giving the absolute path of dlv binary which is in the bin of my GOPATH

**Comment by derekparker** [comment]
@Karthic-Hackintosh can you still reproduce this issue with the current code on master? If so, what is the output of `--log=true` as @aarzilli suggested?

**Comment by Karthic-Hackintosh** [comment]
@derekparker  : The attached screenshot displays the output 
![screenshot from 2015-09-05 20 38 24](https://cloud.githubusercontent.com/assets/2609511/9699852/269464e2-540e-11e5-8cfe-efd6fdfe21de.png)

**Comment by derekparker** [comment]
Run this: `dlv debug --log=true`.

**Comment by Karthic-Hackintosh** [comment]
@derekparker  : I dont see any output after executing ` dlv debug --log=true`

**Comment by aarzilli** [comment]
how was `main` compiled?

**Comment by derekparker** [comment]
@Karthic-Hackintosh are you s till experiencing this issue?

**Comment by Karthic-Hackintosh** [comment]
I had given up on solving it and had started using GDB, I'll give it a try and ping back, thank you for the response.

**Comment by derekparker** [comment]
Going to close this, please re open if it is still an issue.
