### ISSUE TITLE
Linux 2.6.x kernel: Breakpoints hang, program unresponsive

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#209]
On the Linux 2.6.x kernel, after setting a breakpoint in the traced process and continuing it, Delve will hang instead of registering the breakpoint. Further inspection shows the traced process is not running.

This could be a ptrace(2) bug on that version of the kernel, or a bug with Delve. Requires further investigation.

**Comment by derekparker** [comment]
Broken out from https://github.com/derekparker/delve/issues/203

**Comment by joegrasse** [comment]
@derekparker I created #453 to fix this issue.
