### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by gedw99** [derekparker/delve#212]
i have the latest DLV installed. Cert signing done.

OSX productVersion: 10.10.5
go version: go1.5rc1 darwin/amd64

The commands seem to work fine.
dlv debug main.go

I can list the funcs, etc All works

Now, after playing with the various commands offers, I am wondering how to set a break point for example, or other standad debugging operations.

Here is main.go, a simple program for trying out Delve.

package main

import (
	"fmt"
	"strconv"
	"time"
)

var pizzaNum = 0
var pizzaName = ""

func makeDough(stringChan chan string) {
	pizzaNum++
	pizzaName = "Pizza #" + strconv.Itoa(pizzaNum)
	fmt.Println("Make Dough and send for Sauce")
	stringChan <- pizzaName
	time.Sleep(time.Millisecond * 10)
}

func addSauce(stringChan chan string) {
	pizza := <-stringChan
	fmt.Println("Add Sause and Send", pizza, "for toppings.")
	stringChan <- pizzaName
	time.Sleep(time.Millisecond * 10)
}

func addToppings(stringChan chan string) {
	pizza := <-stringChan
	fmt.Println("Add Topping to", pizza, "and Ship.")
	time.Sleep(time.Millisecond * 10)
}

func main() {
	stringChan := make(chan string)
	for i := 0; i < 3; i++ {
		fmt.Println("  ")
		fmt.Println("Round", strconv.Itoa(i))
		go makeDough(stringChan)
		go addSauce(stringChan)
		go addToppings(stringChan)
		time.Sleep(time.Millisecond * 5000)
	}
}

**Comment by derekparker** [comment]
So, you don't need to pass an argument to `dlv debug`. It expects you to be in the directory where your `main` package lives, essentially the directory you'd run `go build` from.

In order to set breakpoints use the `break` command. Check out: https://github.com/derekparker/delve/wiki/Commands for more information on the various commands and usage.

**Comment by gedw99** [comment]
thanks.

I got it working on the example, stepping through and inspecting goroutines.
