### ISSUE TITLE
dlv: process instantly killed

### ISSUE THREAD

**Issue by obscuren** [derekparker/delve#216]
Any command issued is instantly killed (`version`, `exec`, etc)

Binary has been signed

* **Commit**: `8c1853d1930294dcc745c2a14f59095add7c4a91`
* **OS**: `OS X`
* **Go version**: `go version go1.5 darwin/amd64`

**Comment by derekparker** [comment]
How did you install, did you use the `make install` command? If not, use it
and try again. Delve must be built with certain flags on OSX due to a
linker/code sign issue.

**Comment by obscuren** [comment]
I first tried `CERT=dlv-cert make`, unfortunately it stopped doing "something". I wanted to report the problem but figured I'd first try to build it manually.

Here's the output using `make`:

```
CERT=dlv-cert make                                                                                                                                                                ~/go/src/github.com/derekparker/delve
go get -u github.com/peterh/liner
go get -u github.com/spf13/cobra
go get -u golang.org/x/sys/unix
go get -u github.com/davecheney/profile
go get -u gopkg.in/yaml.v2
go test github.com/derekparker/delve/terminal github.com/derekparker/delve/dwarf/frame github.com/derekparker/delve/dwarf/op github.com/derekparker/delve/dwarf/util github.com/derekparker/delve/source github.com/derekparker/delve/dwarf/line
ok  	github.com/derekparker/delve/terminal	0.011s
ok  	github.com/derekparker/delve/dwarf/frame	0.011s
ok  	github.com/derekparker/delve/dwarf/op	0.011s
ok  	github.com/derekparker/delve/dwarf/util	0.013s
ok  	github.com/derekparker/delve/source	0.013s
ok  	github.com/derekparker/delve/dwarf/line	0.525s
go test -c -ldflags="-s" github.com/derekparker/delve/proc && codesign -s dlv-cert ./proc.test && ./proc.test  -test.v && rm ./proc.test
=== RUN   TestExit
Hello, World!
--- PASS: TestExit (0.44s)
=== RUN   TestHalt
past main
--- PASS: TestHalt (0.41s)
=== RUN   TestStep
--- PASS: TestStep (0.42s)
=== RUN   TestBreakpoint
--- PASS: TestBreakpoint (0.07s)
=== RUN   TestBreakpointInSeperateGoRoutine
--- PASS: TestBreakpointInSeperateGoRoutine (0.48s)
=== RUN   TestBreakpointWithNonExistantFunction
--- PASS: TestBreakpointWithNonExistantFunction (0.04s)
=== RUN   TestClearBreakpointBreakpoint
--- PASS: TestClearBreakpointBreakpoint (0.04s)
=== RUN   TestNextGeneral
foo
--- PASS: TestNextGeneral (1.70s)
=== RUN   TestNextConcurrent
hi 4
hi 1
hi 3
hi 5
hi 5
hi 6
hi 7
hi 7
hi 8
hi 8
hi 9
hi 3
hi 9
hi 1
hi 2
hi 2
hi 0
hi 0
hi 4
hi 6
```

**Comment by aarzilli** [comment]
`make install` or `make build` will skip the tests (that's the "something" you are getting stuck on).

**Comment by derekparker** [comment]
@obscuren yeah, there is a flickering test on OSX right now that I'm working on. Refer to @aarzilli comment above about how to install. (`make` by itself won't install anyway, just runs tests).

**Comment by obscuren** [comment]
Alright, thank you very much

**Comment by andradei** [comment]
I'm getting this problem with go1.5.3 on OSX 10.11.2
I went through all of the steps to get certs setup before running `GO15VENDOREXPERIMENT=1 CERT=dlv-cert make install`

**Comment by andradei** [comment]
Deleting $GOPATH/bin/dlv and running `GO15VENDOREXPERIMENT=1 CERT=dlv-cert make install` again solved the issue for me.
