### ISSUE TITLE
Debugging halts during initialisation

### ISSUE THREAD

**Issue by obscuren** [derekparker/delve#217]
I've been playing around with the `dlv` program using some simple code. After successful iterations I tried debugging a [larger program](https://github.com/ethereum/go-ethereum/tree/develop/cmd/geth) without much success. Unfortunately I've not been able to reproduce the issue using a simple example - and therefor can not provide one - and I haven't tried debugging on a different OS other than my own.

**OS**: `OS X`
**Go**: `go version go1.5 darwin/amd64`
**Commit**: `8c1853d1930294dcc745c2a14f59095add7c4a91`

Upon running `dlv debug` it eventually returns the `(dlv)` prompt. When `c`ontinuing it just halts; when pressing `<C-c>` it appears to be waiting in `runtime.mach_semaphore_timedwait() /usr/local/go/src/runtime/sys_darwin_amd64.s:417`

Any clue what's wrong or how I could provide more meaning information?

**Comment by aarzilli** [comment]
Just for reference, this bug can not be reproduced in linux.

**Comment by jussij** [comment]
This reads a lot like the #372 Step Command Hangs issue which was closed and replaced by #374.

**Comment by derekparker** [comment]
This should be fixed now, closing.
