### ISSUE TITLE
Support printing nested struct member

### ISSUE THREAD

**Issue by ThomasMoinel** [derekparker/delve#220]
Can't print nested struct member, see error below with example code.
```
% dlv debug 
Type 'help' for list of commands.
(dlv) b main.main:3
Breakpoint 1 set at 0x400c37 for main.main ./nestedstruct.go:15
(dlv) c
> main.main() ./nestedstruct.go:15
	
   10:	}
   11:	
   12:	func main() {
   13:		b := B{A{42}}
   14:	
=> 15:		fmt.Println(b)
   16:	}

(dlv) print b
main.B {a: main.A {val: 42}}
(dlv) print b.a
main.A {val: 42}
(dlv) print b.a.val
Command failed: b has no member a.val
(dlv) 
```

nestedstruct.go
``` go
package main

import "fmt"

type A struct {
	val int
}
type B struct {
	a A
}

func main() {
	b := B{A{42}}

	fmt.Println(b)
}
```

**Comment by ThomasMoinel** [comment]
A more complete example where every print give the same _Command failed: b has no member *_
```go
package main

import "fmt"

type A struct {
	val int
}
type B struct {
	A
	a   A
	ptr *A
}

func main() {
	b := B{A: A{-314}, a: A{42}, ptr: &A{1337}}

	// print b.val
	// print b.A.val
	// print b.a.val
	// print b.ptr.val

	fmt.Println(b)
}
```

I think a correct way is to make a recursive call in proc/variable.go evaluateStructMember.
I'm trying to make it work but I struggle to learn dwarf and delve internals. If I find out a way, I'll make a pull request.

**Comment by derekparker** [comment]
@aarzilli or @ebfe any interest in this?

**Comment by aarzilli** [comment]
The current code uses a special case to extract the address of a member field, so supporting this is not easy. When I refactored variables.go to split address extraction and evaluation I also rewrote this part to be more general. Once I commit that it should be easy to add a for loop and go any number of levels deep, as a provisional measure, until we have a more general expression evaluator.

**Comment by ThomasMoinel** [comment]
From the last example print embedded struct value doesn't work:
```
print b.val
print b.A.val
```

**Comment by aarzilli** [comment]
This should be reopened, we have to figure out how embedded structs are stored in dwarf.

**Comment by lukehoban** [comment]
I've opened a new PR (#261) adds support for embedded structs and a test case that includes the full example from @ThomasMoinel.
