### ISSUE TITLE
erro on linux mint 17.1

### ISSUE THREAD

**Issue by 7belrhalmia** [derekparker/delve#221]
it give me this error :+1: 

![gifrecord_2015-09-06_042138](https://cloud.githubusercontent.com/assets/13202562/9702317/ff3af23a-544e-11e5-891b-b84480fd00ff.gif)

**Comment by aarzilli** [comment]
It seems that go is trying to simultaneously build linux and solaris implementation of `x/sys/unix`. Either the version of go you are using is very old or it has some problem.

**Comment by derekparker** [comment]
Can you try deleting everything under `$GOPATH/pkg/golang.org/x/sys/unix` and try again?

**Comment by 7belrhalmia** [comment]
@derekparker  i didn't find sys under x

**Comment by derekparker** [comment]
So you don't have `sys`? What happens if you run a `go get -u` instead of just `go get`? Or try to `go get` that `sys/unix` package directly?

**Comment by derekparker** [comment]
Any updates on this issue? @7belrhalmia

**Comment by 7belrhalmia** [comment]
@derekparker  i just update go and it work i have one probleme i don't now how to usit well @derekparker  plz man can you give me some ressources to me as a beginer to begin using this wonderful tool

**Comment by derekparker** [comment]
@7belrhalmia:

`dlv debug` to build a binary and begin debugging, or `dlv test` to build a test binary and begin debugging. From there you can type `help` for a list of commands. Set breakpoints, next, continue, etc...

Let me know if you need any more help.

**Comment by derekparker** [comment]
There currently are not guides on using Delve, however I intend to write up more documentation and guides as the project gets closer to 1.0.

**Comment by 7belrhalmia** [comment]
@derekparker  it will be very nice if you do a video to explain how to useit

**Comment by derekparker** [comment]
@7belrhalmia good idea.
