### ISSUE TITLE
Issue with make

### ISSUE THREAD

**Issue by AlexCHowle** [derekparker/delve#222]
Getting the following with both the original "go get", and also with a subsequent "make":

go get -u github.com/peterh/liner
package github.com/peterh/liner
	imports runtime: C source files not allowed when not using cgo or SWIG: atomic_amd64x.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c panic.c parfor.c proc.c runtime.c signal.c signal_amd64x.c signal_unix.c stack.c string.c sys_x86.c vdso_linux_amd64.c
make: *** [deps] Error 1

**Comment by aarzilli** [comment]
http://stackoverflow.com/questions/32115229/go-1-5-error-imports-runtime-c-source-files-not-allowed-when-not-using-cgo-o
