### ISSUE TITLE
go-lang-idea-plugin--485  debug  error

### ISSUE THREAD

**Issue by zld406504302** [derekparker/delve#224]
Error running go_demos: Cannot run program "/Users/zhanglida/Library/Application Support/IntelliJIdea14/intellij-go.jar/lib/dlv/mac/dlv" (in directory "/Users/zhanglida/go_path"): error=20, Not a directory

**Comment by ignatov** [comment]
Please report your issue to https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/new
