### ISSUE TITLE
Add variable watching support for tracepoints

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#246]
Tracepoints are very nice as it allows you to see when a program hits a certain line without interrupting.
However they are limited to just displaying when the line has been reached and no additional information.  I wonder if it would be possible to enable some sort of watch mechanism for variables (and later on expressions) for them so that when such a tracepoint it's reached then additional information is displayed in the context.

I could imagine a use case for a tracepoint with watches being monitoring of certain variables in a staging environment / during execution of the application without breaking the execution to stopping it to investigate.

**Comment by derekparker** [comment]
Do you mean conditional tracepoints, or just displaying variable information when a tracepoint is hit? If it's the latter, that already exists. You can invoke a tracepoint like so: `trace foo.go:12 i` where `i` is the name of a variable whose value you would like displayed.

I'm going to close this issue for now, if it's not solved feel free to re open.

**Comment by dlsniper** [comment]
> If it's the latter, that already exists.

That's the functionality I was looking for, but I didn't noticed it's supported already, the `help` command doesn't display that / wiki is a bit unclear on that. Thank you and sorry for the noise.
