### ISSUE TITLE
debug failure

### ISSUE THREAD

**Issue by zld406504302** [derekparker/delve#272]
/usr/local/go/bin/go build -o /private/var/folders/7q/h53xbfx93n97b2hpd363p64r0000gp/T/beego_study17go -gcflags "-N -l" /Users/xxx/go_path/src/beego_study/main.go
"/Users/xxx/Library/Application Support/IntelliJIdea14/Go/lib/dlv/mac/dlv" --listen=localhost:64419 --headless=true exec /private/var/folders/7q/h53xbfx93n97b2hpd363p64r0000gp/T/beego_study17go --
invalid spdelta  0x0 0x4030010 0x0 -1
invalid spdelta  0x0 0x402e8f3 0x0 -1
runtime: unexpected return pc for  called from 0x47878b000
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x46ec6d0, 0x11)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.gentraceback(0x40271d0, 0xc820028708, 0x0, 0xc820000180, 0x0, 0x0, 0x7fffffff, 0x4787748, 0x7fff5fbff6d0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:272 +0x11de
runtime.copystack(0xc820000180, 0x1000)
	/usr/local/go/src/runtime/stack1.go:616 +0x1a7
runtime.newstack()
	/usr/local/go/src/runtime/stack1.go:801 +0xb53
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:330 +0x7f

goroutine 1 [copystack, locked to thread]:
runtime.init.2()
	/usr/local/go/src/runtime/mstats.go:148 fp=0xc820028710 sp=0xc820028708
runtime.init()
	/usr/local/go/src/runtime/zversion.go:9 +0x36e fp=0xc820028770 sp=0xc820028710
invalid spdelta  0x0 0x402e8f3 0x0 -1
()
	?:0 +0x402e8f3 fp=0xc820028777 sp=0xc820028770

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

**Comment by aarzilli** [comment]
Please provide: go version, operating system, delve version and what you were trying to do. Also, is that the full stack trace?

**Comment by zld406504302** [comment]
I want to init mysql driver ,run success ,but failure when debug  in idea. Here is my code snippet.

package main
import (
	"github.com/astaxie/beego"
	_ "beego_study/routers"
	_ "beego_study/initial"
)
func main() {
	host := "localhost"
	port := "8080"
	beego.Run(host, port)
}

package initial 
func init()  {
	InitMysql()
}

package initial
import (
	_"github.com/go-sql-driver/mysql"
	"github.com/astaxie/beego/orm"
	"fmt"
)
func InitMysql() {
	orm.RegisterDataBase("default", "mysql", "xx:xx@/beego_study?charset=utf8", 1)
	orm.Debug = true
	orm.RunSyncdb("default", false, true)
}

**Comment by derekparker** [comment]
@zld406504302 as @aarzilli mentioned, is that the full stack trace? I don't see any mention of delve in that trace. Are you able to run the program fine without delve? Also could you provide the version of OSX as well, thanks.

**Comment by zld406504302** [comment]
Sorry, this should not be bug delve, this exception only after I import github.com/go-sql-driver/mysql, with delve debugging will throw this exception.
