### ISSUE TITLE
Suggestion: Use a "pure go" implementation of readline

### ISSUE THREAD

**Issue by raff** [derekparker/delve#29]
I have a package that was using (with success) libreadline on Linux, OSX and even Windows (if you managed to get libreadline for Windows). But recently (after Yosemite) I started having problem on OSX (control-C would make my terminal session unusable).

I found this package "github.com/peterh/liner" that is pure-go and works on all platforms (Windows include) with no changes and no dependencies. The history management and command completion is slightly different than libreadline, but it's pretty easy to rework (I did it for http://github.com/gobs/cmd). The only missing feature is that libreadline could automatically expand file names if your completion function returned null)

**Comment by jakecoffman** [comment]
+1

**Comment by shoenig** [comment]
+1
