### ISSUE TITLE
Does --build-flags work?

### ISSUE THREAD

**Issue by lukehoban** [derekparker/delve#298]
When I try to pass the `--build-flags` option, it doesn't seem to successfully parse the command line option. Instead it treats the argument to `--build-flags` as a package to try and load.

```
lukeh@Lukes-MacBook-Pro:~/dd/go/src/github.com/derekparker/delve/proc$ $GOPATH/bin/dlv debug --build-flags=foo
can't load package: package foo: cannot find package "foo" in any of:
	/usr/local/go/src/foo (from $GOROOT)
	/Users/lukeh/dd/go/src/foo (from $GOPATH)
```

Am I using this wrong, or is the hyphen in the option name causing the flag parser to not recognize this?

**Comment by derekparker** [comment]
Can you give an example trying to pass an actual flag? Additionally, you may have to quote the argument to the `--build-flags` flag.

For example, this works:

```
$ dlv debug --build-flags="-gcflags=-s"
```

That will correctly cause an error running Delve because that flag omits debug info, so the flag is being passed through to the compiler.

**Comment by lukehoban** [comment]
My bad - you are right that this works fine when you provide correct flags, and the error message makes sense once I realized it's coming from the build not from delve.
