### ISSUE TITLE
Do we need to use paths with symlinks or should resolve them?

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#299]
We've fixed the https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1880 in our Delve integration: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/pull/2023/files
Actually Delve says:
```
{"id":1,"result":null,"error":"unknown file: /Users/ignatov/src/symlink_test/SomeFolder/main.go"} 
```
So I have a question, do we need to resolve symlinked paths or not? Or maybe Delve can handle this scenario?

**Comment by derekparker** [comment]
Delve should handle this, I'll look into it.

**Comment by derekparker** [comment]
@ignatov can't reproduce locally. Please reopen if this is still an issue w/ Delve.
