### ISSUE TITLE
runtime.buildVersion is no longer available (Go tip)

### ISSUE THREAD

**Issue by kostya-sh** [derekparker/delve#301]
`runtime.buildVersion` became `runtime/internal/sys.BuildVersion`

See https://github.com/golang/go/commit/432cb66f16b2bb6a167725057168bbe4aefe5fb5

**Comment by kostya-sh** [comment]
The issue was fixed too fast ;)
runtime.buildVersion is there again: https://github.com/golang/go/commit/86f1944e86ae3e07651dcbfafee37f1e3b0a917d

**Comment by supernow** [comment]
Does this problem have solved? I have this problem now!
my go edition is 1.7.1

**Comment by aarzilli** [comment]
No version of go without runtime.buildVersion was ever released, your problem is different.
