### ISSUE TITLE
MacOSX installation/build did not work for me.

### ISSUE THREAD

**Issue by theider** [derekparker/delve#303]
My goal is to use Delve with LiteIDE to do Go development on a Mac.

I'm on Mac OSX Mavericks using Go 1.5.1 darwin/AMD64.

I followed the instructions for creating the cert and that seemed to work but running the makefile fails.  I tried setting GOROOT and GOPATH to the local folder for the project.  The Makefile seems to include absolute paths to github.com.

Just following the README I get this:

Timothys-MacBook-Pro-2:delve theider$ pwd
/Users/theider/instrument/google/delve

Timothys-MacBook-Pro-2:delve theider$ CERT=dlv-cert make install
go install -ldflags="-s" github.com/derekparker/delve/cmd/dlv
can't load package: package github.com/derekparker/delve/cmd/dlv: cannot find package "github.com/derekparker/delve/cmd/dlv" in any of:
	/usr/local/go/src/github.com/derekparker/delve/cmd/dlv (from $GOROOT)
	($GOPATH not set)
make: *** [install] Error 1
Timothys-MacBook-Pro-2:delve theider$

Thank you!

**Comment by aarzilli** [comment]
You don't need to set GOROOT and GOPATH should be set to your workspace (the parent directory of the `github.com` directory) and it shouldn't be the same directory as your install of go.
Refer to https://golang.org/doc/code.html

**Comment by theider** [comment]
Thanks for your reply.  I'm just getting started with Go.   I will try again.

**Comment by aarzilli** [comment]
No problem.
