### ISSUE TITLE
Unable to use the makefile out of the box with the package provided

### ISSUE THREAD

**Issue by NeilLamka** [derekparker/delve#304]
There are many, many include references that do not resolve to the proper directories when trying to build from the provided files. In all cases, the referenced items are someplace in the package just not where the include statement says that they are.  After some time in trying to go a go build, finding the errors and correcting them I was able to get a successful build to complete.

**Comment by derekparker** [comment]
What version of Go are you using? Do you have the GO15VENDOREXPERIMENT enabled? I suppose the Makefile could be updated to always set that env var.

**Comment by NeilLamka** [comment]
I’m using  go version go1.5.2 and did have GO15VENDOREXPERIMENT enabled although I am new to GO and not a expert so I may not have done that correctly or understood the instructions properly.  In the end I just ran the go install … command and manually corrected the include statements.

ThanksNeil
 

Neil LamkaSmarter HiresMobile: 206-931-0229Direct:   650-539-5442Fax:        928-832-3216

**Comment by derekparker** [comment]
@NeilLamka what import statements were messed up? External packages? That would seem to imply that the vendor experiment was not enabled correctly. Try:

`export GO15VENDOREXPERIMENT=1; make install` and reopen if you still run into issues.

**Comment by NeilLamka** [comment]
Specifying the environment variable correctly did fix my problem. Thanks for the help.

ThanksNeil
 

Neil LamkaSmarter HiresMobile: 206-931-0229Direct:   650-539-5442Fax:        928-832-3216
