### ISSUE TITLE
Unable to continue program if a breakpoint is set on line with func declaration

### ISSUE THREAD

**Issue by kostya-sh** [derekparker/delve#305]
Consider the following program:

    package main

    import "fmt"

    func sayTest() {
        fmt.Println("Test")
    }

    func main() {
        sayTest()
    }

If this program is debugged with `dlv debug` and breakpoint is set at line 5 (`func sayTest() {`) once the breakpoint is hit it is unable to continue program execution:

    $ dlv debug
    (dlv) b main.go:5
    Breakpoint 1 set at 0x401000 for main.sayTest ./main.go:5
    (dlv) c
    > main.sayTest() ./main.go:5 (hits goroutine(1):1 total:1)
    (dlv) c
    > main.sayTest() ./main.go:5 (hits goroutine(1):2 total:2)
    (dlv) n
    > main.sayTest() ./main.go:5 (hits goroutine(1):1 total:1)  <--- Why 1????
    (dlv) n
    > main.sayTest() ./main.go:5 (hits goroutine(1):3 total:3)
    (dlv) n
    > main.sayTest() ./main.go:5 (hits goroutine(1):1 total:1)  <--- 1 again!!!
    (dlv) c
    > main.sayTest() ./main.go:5 (hits goroutine(1):4 total:4)

**Comment by aarzilli** [comment]
I don't know why this is happening but it doesn't happen on PR #259 branch. Tried both 1.5.1 and 1.5.2.

**Comment by aarzilli** [comment]
Is this still happening?

**Comment by kostya-sh** [comment]
Yes, but it fails differently. For example:

    $ dlv test
    Type 'help' for list of commands.
    (dlv) b vlq_test.go:8
    Breakpoint 1 set at 0x47de90 for github.com/kostya-sh/sandbox/vlq.TestVarInt ./vlq_test.go:8
    (dlv) c
    > github.com/kostya-sh/sandbox/vlq.TestVarInt() ./vlq_test.go:8 (hits goroutine(19):1 total:1)
         7:	
    =>   8:	func TestVarInt(t *testing.T) {
         9:		tests := []struct {
    (dlv) n
    > github.com/kostya-sh/sandbox/vlq.TestVarInt() ./vlq_test.go:8
         7:	
    =>   8:	func TestVarInt(t *testing.T) {
         9:		tests := []struct {
    (dlv) n
    > github.com/kostya-sh/sandbox/vlq.TestVarInt() ./vlq_test.go:8 (hits goroutine(19):2 total:2)
         7:	
    =>   8:	func TestVarInt(t *testing.T) {
         9:		tests := []struct {
    (dlv) n
    Command failed: next while nexting
    (dlv) n
    Command failed: next while nexting
    (dlv) n
    Command failed: next while nexting
    (dlv) c
    > github.com/kostya-sh/sandbox/vlq.TestVarInt() ./vlq_test.go:8 (hits goroutine(19):3 total:3)
         7:	
    =>   8:	func TestVarInt(t *testing.T) {
         9:		tests := []struct {
    (dlv) c
    > github.com/kostya-sh/sandbox/vlq.TestVarInt() ./vlq_test.go:8 (hits goroutine(19):4 total:4)
         7:	
    =>   8:	func TestVarInt(t *testing.T) {
         9:		tests := []struct {
    (dlv) c
    > testing.tRunner.func1() ....../go/src/testing/testing.go:458
       453:		// When this goroutine is done, either because test.F(t)
       454:		// returned normally or because a test failure triggered
       455:		// a call to runtime.Goexit, record the duration and send
       456:		// a signal saying that the test is done.
       457:		defer func() {
    => 458:			t.duration += time.Now().Sub(t.start)
       459:			// If the test panicked, print any test output before dying.
       460:			err := recover()
       461:			if !t.finished && err == nil {
       462:				err = fmt.Errorf("test executed panic(nil) or runtime.Goexit")
       463:			}
    (dlv) c
    PASS
    Process 41698 has exited with status 0
    (dlv)

**Comment by aarzilli** [comment]
Fixed however it still [won't do what you think it should](https://gist.github.com/aarzilli/ef9f946b0262dd509078): the problem is that the breakpoint is set on the function prelude and it takes multiple steps to get through it (it's a loop)
