### ISSUE TITLE
source restricted to single-character filenames

### ISSUE THREAD

**Issue by jsh** [derekparker/delve#312]
In *terminal/command.go*, the test at the top of `sourceCommand()` seems overly restrictive:

```
805 func (cmds *Commands) sourceCommand(t *Term, args string) error {
806         if len(args) != 1 {
807                 return fmt.Errorf("wrong number of arguments: source <filename>")
808         }
809 
810         return cmds.executeFile(t, args)
811 }
```

(Single-character filenames work fine, but anything else returns an error.) I'm guessing the test is either left over from a time when `args` was declared as `[]string`, or foreshadows your intent to make it so.

**Comment by aarzilli** [comment]
My fault :(
