### ISSUE TITLE
delve hangs when debugging test

### ISSUE THREAD

**Issue by kostya-sh** [derekparker/delve#316]
This happens with Go tip, I haven't tested other versions

Steps to reproduce:

    $ go get github.com/kostya-sh/sandbox/vlq
    $ cd $GOPATH/src/github.com/kostya-sh/sandbox/vlq
    $ dlv test -- -test.run=TestVarInt
    (dlv) b TestVarInt
    (dlv) c

git bisect points to commit 48e13a9

**Comment by kostya-sh** [comment]
This is broken with Go 1.5.2 as well. The same commit seems to be at fault. I was running devle on Linux both for Go 1.5.2 and tip.

**Comment by kostya-sh** [comment]
Attaching stack trace obtained with kill -3 (Go 1.5.2).

SIGQUIT: quit
PC=0x4625e1 m=0

goroutine 0 [idle]:
runtime.futex(0xd47490, 0x0, 0x0, 0x0, 0xc800000000, 0x412bf7, 0x0, 0x0, 0x412e64, 0xd47490, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:288 +0x21
runtime.futexsleep(0xd47490, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os1_linux.go:39 +0x53
runtime.notesleep(0xd47490)
        /usr/local/go/src/runtime/lock_futex.go:142 +0xa4
runtime.stoplockedm()
        /usr/local/go/src/runtime/proc1.go:1276 +0xae
runtime.schedule()
        /usr/local/go/src/runtime/proc1.go:1598 +0x6e
runtime.park_m(0xc820001680)
        /usr/local/go/src/runtime/proc1.go:1706 +0x18b
runtime.mcall(0x7ffd420056d0)
        /usr/local/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 7 [chan receive, locked to thread]:
runtime.gopark(0xb688c8, 0xc82001aad8, 0xa737e0, 0xc, 0x17, 0x3)
        /usr/local/go/src/runtime/proc.go:185 +0x163 fp=0xc82054be40 sp=0xc82054be18
runtime.goparkunlock(0xc82001aad8, 0xa737e0, 0xc, 0x17, 0x3)
        /usr/local/go/src/runtime/proc.go:191 +0x54 fp=0xc82054be78 sp=0xc82054be40
runtime.chanrecv(0x8a2e20, 0xc82001aa80, 0xc82054bf88, 0x5d2201, 0x0)
        /usr/local/go/src/runtime/chan.go:448 +0x472 fp=0xc82054bf38 sp=0xc82054be78
runtime.chanrecv2(0x8a2e20, 0xc82001aa80, 0xc82054bf88, 0x101)
        /usr/local/go/src/runtime/chan.go:354 +0x2b fp=0xc82054bf68 sp=0xc82054bf38
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc8200b4460)
        /home/contained/src/github.com/derekparker/delve/proc/proc.go:696 +0xc3 fp=0xc82054bfb8 sp=0xc82054bf68
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82054bfc0 sp=0xc82054bfb8
created by github.com/derekparker/delve/proc.New
        /home/contained/src/github.com/derekparker/delve/proc/proc.go:71 +0x1d4

goroutine 1 [chan receive]:
github.com/derekparker/delve/terminal.cont(0xc8202ea1e0, 0x0, 0x0, 0x0, 0x0)
        /home/contained/src/github.com/derekparker/delve/terminal/command.go:459 +0x84
github.com/derekparker/delve/terminal.(*Term).Run(0xc8202ea1e0, 0x0, 0x0, 0x0)
        /home/contained/src/github.com/derekparker/delve/terminal/terminal.go:110 +0xab6
main.execute(0x0, 0xc82000fa00, 0x2, 0x2, 0xc8200400c0, 0x0)
        /home/contained/src/github.com/derekparker/delve/cmd/dlv/main.go:336 +0x598
main.main.func7.1(0xc82000f740, 0x1, 0x2, 0xc8200400c0, 0x0)
        /home/contained/src/github.com/derekparker/delve/cmd/dlv/main.go:241 +0x50d
main.main.func7(0xc8200ad200, 0xc82000f740, 0x1, 0x2)
        /home/contained/src/github.com/derekparker/delve/cmd/dlv/main.go:224 +0x3e
github.com/spf13/cobra.(*Command).execute(0xc8200ad200, 0xc82000f620, 0x2, 0x2, 0x0, 0x0)
        /home/contained/src/github.com/spf13/cobra/command.go:572 +0x869
github.com/spf13/cobra.(*Command).ExecuteC(0xc8200ac600, 0xc8200ad200, 0x0, 0x0)
        /home/contained/src/github.com/spf13/cobra/command.go:662 +0x54e
github.com/spf13/cobra.(*Command).Execute(0xc8200ac600, 0x0, 0x0)
        /home/contained/src/github.com/spf13/cobra/command.go:618 +0x2d
main.main()
        /home/contained/src/github.com/derekparker/delve/cmd/dlv/main.go:290 +0xd0f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 66 [IO wait]:
net.runtime_pollWait(0x7fc738715ad0, 0x72, 0xc820010180)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820016140, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820016140, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200160e0, 0xc8205c0001, 0x5ff, 0x5ff, 0x0, 0x7fc738710050, 0xc820010180)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82012a010, 0xc8205c0001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc8204b41a0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc8204b41a0, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc8204b41a0, 0x97a900, 0xc82055e020, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc82055e000, 0xc820438400, 0x0, 0x0)
        /usr/local/go/src/net/rpc/jsonrpc/server.go:66 +0x7c
net/rpc.(*Server).readRequestHeader(0xc8202bc000, 0x7fc7346e5050, 0xc82055e000, 0x0, 0x0, 0xc820438400, 0xc82045bc00, 0x0, 0x0)
        /usr/local/go/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc8202bc000, 0x7fc7346e5050, 0xc82055e000, 0xc8202bc000, 0xc8204b80a0, 0xc8202ca100, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc8202bc000, 0x7fc7346e5050, 0xc82055e000)
        /usr/local/go/src/net/rpc/server.go:462 +0x8c
github.com/derekparker/delve/service/rpc.(*RPCServer).Run.func1(0xc82000fe20)
        /home/contained/src/github.com/derekparker/delve/service/rpc/server.go:65 +0x485
created by github.com/derekparker/delve/service/rpc.(*RPCServer).Run
        /home/contained/src/github.com/derekparker/delve/service/rpc/server.go:66 +0x118

goroutine 67 [IO wait]:
net.runtime_pollWait(0x7fc738715b90, 0x72, 0xc820010180)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820140140, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820140140, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201400e0, 0xc8205c0601, 0x5ff, 0x5ff, 0x0, 0x7fc738710050, 0xc820010180)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202ae018, 0xc8205c0601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc82000c340, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82000c340, 0x1, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc82000c340, 0x97a840, 0xc8204ff7c8, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc8204ff780, 0xc820430000, 0x0, 0x0)
        /usr/local/go/src/net/rpc/jsonrpc/client.go:75 +0x8f
net/rpc.(*Client).input(0xc8205bd860)
        /usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
        /usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 68 [select, locked to thread]:
runtime.gopark(0xb68900, 0xc82003a728, 0xa655a0, 0x6, 0x431718, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82003a728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82003a728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 69 [chan receive]:
github.com/derekparker/delve/terminal.(*Term).Run.func1(0xc8205bdaa0, 0xc8202ea1e0)
        /home/contained/src/github.com/derekparker/delve/terminal/terminal.go:49 +0x6b
created by github.com/derekparker/delve/terminal.(*Term).Run
        /home/contained/src/github.com/derekparker/delve/terminal/terminal.go:55 +0x1c6

goroutine 74 [chan receive]:
net/rpc.(*Client).Call(0xc8205bd860, 0xc820438c60, 0x11, 0x88b060, 0xc820438c40, 0x88b0c0, 0xc8201260c0, 0x0, 0x0)
        /usr/local/go/src/net/rpc/client.go:315 +0xcd
github.com/derekparker/delve/service/rpc.(*RPCClient).call(0xc820145e00, 0xa5de38, 0x7, 0x88b060, 0xc820438c40, 0x88b0c0, 0xc8201260c0, 0x0, 0x0)
        /home/contained/src/github.com/derekparker/delve/service/rpc/client.go:234 +0xb4
github.com/derekparker/delve/service/rpc.(*RPCClient).Continue.func1(0xc820145e00, 0xc8205a0060)
        /home/contained/src/github.com/derekparker/delve/service/rpc/client.go:60 +0xea
created by github.com/derekparker/delve/service/rpc.(*RPCClient).Continue
        /home/contained/src/github.com/derekparker/delve/service/rpc/client.go:74 +0x5d

goroutine 75 [runnable]:
debug/dwarf.(*buf).entry(0xc820520480, 0xc82013f5f0, 0xc800000000, 0xc820c39920)
        /usr/local/go/src/debug/dwarf/entry.go:376 +0x2a9
debug/dwarf.(*Reader).Next(0xc820520480, 0xc820c39920, 0x0, 0x0)
        /usr/local/go/src/debug/dwarf/entry.go:579 +0xff
github.com/derekparker/delve/dwarf/reader.(*Reader).SeekToTypeNamed(0xc820b82670, 0xc820b82660, 0x9, 0x7fc738714a20, 0x0, 0x0)
        /home/contained/src/github.com/derekparker/delve/dwarf/reader/reader.go:151 +0x134
github.com/derekparker/delve/proc.(*Process).findType(0xc8200b4460, 0xc820b82660, 0x9, 0x0, 0x0, 0x0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/types.go:12 +0x5f
github.com/derekparker/delve/proc.(*Process).findTypeExpr(0xc8200b4460, 0x7fc7346666e0, 0xc820bc6860, 0x0, 0x0, 0x0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/types.go:31 +0xfa
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc8206a6d78, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1451 +0x832
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8206a6d78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8204ec000, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f31e0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2ea0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8208f2ea0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc8206a6578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8206a6578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c49b80, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f3040, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2820, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8208f2820)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820323d78, 0x2, 0x7fc7388c0901)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820323d78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c49900, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207c15f0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207c0ea0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8207c0ea0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820323578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820323578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c49680, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2f70, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2d00, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8208f2d00)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820322d78, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820322d78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c49400, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096dd40, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096dad0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc82096dad0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820322578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820322578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c49180, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2dd0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2c30, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8208f2c30)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820c01d78, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c01d78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c48f00, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f3e10, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f3ad0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8208f3ad0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820c01578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c01578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c48c80, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2a90, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207c1520, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8207c1520)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820c00d78, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c00d78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c48a00, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096dba0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096d930, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc82096d930)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc8207cfd78, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207cfd78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c48780, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096da00, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096d520, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc82096d520)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc8207cf578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207cf578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c48500, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096d790, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096d1e0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc82096d1e0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820c00578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c00578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c48280, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096d860, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc82096d6c0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc82096d6c0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc8207ced78, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207ced78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820959b80, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f2b60, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8208f29c0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8208f29c0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc8207ce578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207ce578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820959900, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207c1040, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207c0c30, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8207c0c30)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820c4bd78, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c4bd78, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820959680, 0x1)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207c0d00, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:783 +0xfd2
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc8207c08f0, 0x0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:752 +0xb1d
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc8207c08f0)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:739 +0x2a
github.com/derekparker/delve/proc.(*Variable).loadInterface(0xc820c4b578, 0x2, 0xd6ba01)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:1467 +0xcff
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc820c4b578, 0x2)
        /home/contained/src/github.com/derekparker/delve/proc/variables.go:788 +0x9d7
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:477 +0x4ac

rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xd47490
rsi    0x0
rbp    0x1
rsp    0x7ffd420055b0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x8
r13    0xb64632
r14    0x9
r15    0x8
rip    0x4625e1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
SIGTRAP: trace trap
PC=0x47e7df m=0

goroutine 18 [running]:
github.com/kostya-sh/sandbox/vlq.TestVarInt(0xc8200c2000)
        /home/contained/src/github.com/kostya-sh/sandbox/vlq/vlq_test.go:13 +0x9f fp=0xc820064f68 sp=0xc820064920
testing.tRunner(0xc8200c2000, 0x65a860)
        /usr/local/go/src/testing/testing.go:456 +0x98 fp=0xc820064fa0 sp=0xc820064f68
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820064fa8 sp=0xc820064fa0
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x5d25f0, 0x65a860, 0x4, 0x4, 0x4ce901)
        /usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200a40a0, 0x65a860)
        /usr/local/go/src/testing/testing.go:494 +0x70
main.main()
        github.com/kostya-sh/sandbox/vlq/_test/_testmain.go:76 +0xab

rax    0x0
rbx    0xc820064e00
rcx    0x0
rdx    0x0
rdi    0xc820064f60
rsi    0x5d43c0
rbp    0x65a860
rsp    0xc820064920
r8     0x0
r9     0x7f53473bf700
r10    0x0
r11    0xffffffffffdff000
r12    0x8
r13    0x5d023c
r14    0x1fffffffffffff
r15    0x39
rip    0x47e7df
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

**Comment by derekparker** [comment]
Thanks for the stack trace.
