### ISSUE TITLE
Test failure due to `map[string]int` not found?

### ISSUE THREAD

**Issue by lukehoban** [derekparker/delve#320]
When I pull in the latest from master into the Windows PR, I'm seeing a test failure in `TestEvalExpression` on this case:

```
{"(map[string]int)(0x4000)", false, "", "", "", fmt.Errorf("can not convert \"0x4000\" to *struct hash<string,int>")},
```

Instead of the expected error, I'm seeing "function calls are not supported".

This appears to be because the type `map[string]int` is not found in the call to `SeekToTypeNamed`.  Browsing through the types that are available in the DWARF metadata, I see `map[string]int64` but not `map[string]int`.  

I can't think of any reason this would be Windows-specific, but I'm not sure why this failure is not showing up on the Linux/OSX test runs. 

Note that I'm on Go 1.5.1 on `go version go1.5.1 windows/amd64`.  Perhaps this is an issue with 1.5.1?

**Comment by aarzilli** [comment]
Here's my guess. The type `map[string]int` is in the linux/os x builds because some arch specific thing uses a `map[string]int` variable but the windows equivalents don't.

Pull Request #322 could fix this.

**Comment by lukehoban** [comment]
Ahh - yeah, that would make sense.  Thanks for taking a look.
