### ISSUE TITLE
EvalExpression(i2 == 2.0) returned an error - can not convert 2 constant to int

### ISSUE THREAD

**Issue by fsomers** [derekparker/delve#327]
I've just done a clean install of 1a4250f (at Dec 19 14:57:48 2015 +0100) on OSX 10.11.2 (El Cap)
Cert setup and build completed as per https://github.com/derekparker/delve/wiki/Building

I decided to run the tests, and got a test failure in TestEvalExpression as shown below.

$ CERT=dlv-cert make install
go install -ldflags="-s -X main.Build=1a4250fb5147a9a06f608a5e89dccc4f62fd20c5" github.com/derekparker/delve/cmd/dlv
codesign -s dlv-cert /Users/frank/home/gosrc/bin/dlv

$ CERT=dlv-cert make test
go test -exec=/Users/frank/home/gosrc/src/github.com/derekparker/delve/scripts/testsign -ldflags="-s -X main.Build=1a4250fb5147a9a06f608a5e89dccc4f62fd20c5" github.com/derekparker/delve/cmd/dlv github.com/derekparker/delve/config github.com/derekparker/delve/dwarf/frame github.com/derekparker/delve/dwarf/line github.com/derekparker/delve/dwarf/op github.com/derekparker/delve/dwarf/reader github.com/derekparker/delve/dwarf/util github.com/derekparker/delve/proc github.com/derekparker/delve/proc/test github.com/derekparker/delve/service github.com/derekparker/delve/service/api github.com/derekparker/delve/service/debugger github.com/derekparker/delve/service/rpc github.com/derekparker/delve/service/test github.com/derekparker/delve/terminal
?   	github.com/derekparker/delve/cmd/dlv	[no test files]
?   	github.com/derekparker/delve/config	[no test files]
ok  	github.com/derekparker/delve/dwarf/frame	6.170s
ok  	github.com/derekparker/delve/dwarf/line	33.140s
ok  	github.com/derekparker/delve/dwarf/op	11.006s
?   	github.com/derekparker/delve/dwarf/reader	[no test files]
ok  	github.com/derekparker/delve/dwarf/util	5.997s
ok  	github.com/derekparker/delve/proc	52.899s
?   	github.com/derekparker/delve/proc/test	[no test files]
?   	github.com/derekparker/delve/service	[no test files]
?   	github.com/derekparker/delve/service/api	[no test files]
?   	github.com/derekparker/delve/service/debugger	[no test files]
?   	github.com/derekparker/delve/service/rpc	[no test files]
Hello, World!
Hello, World!
Hello, World!
foo
foo
Hello, World!
foo
Hello, World!
hi
hi
hi
hi
hi
hi
--- FAIL: TestEvalExpression (1.31s)
	integration_test.go:27: failed assertion at variables_test.go:558: EvalExpression(i2 == 2.0) returned an error - can not convert 2 constant to int
FAIL
FAIL	github.com/derekparker/delve/service/test	41.796s
ok  	github.com/derekparker/delve/terminal	5.158s
make: *** [test] Error 1

**Comment by aarzilli** [comment]
See #323

**Comment by kostya-sh** [comment]
It might be a regression in Go 1.6, I've created https://github.com/golang/go/issues/13719

**Comment by fsomers** [comment]
clarification: sory - I meant to add I am using go 1.6beta1 via homebrew

**Comment by aarzilli** [comment]
Should be fixed by c859a880b69bed3f630d57d23f3be508a93dc67c

**Comment by fsomers** [comment]
Thanks for the fix!
