### ISSUE TITLE
int slice nonsense

### ISSUE THREAD

**Issue by lloiser** [derekparker/delve#336]
![image](https://cloud.githubusercontent.com/assets/3003233/12057296/a480627a-af3f-11e5-8275-f14120361d4d.png)

Can someone explain me why `testSorted` contains this nonsense before it is used and `sorted` in the other file seems correct?

note: it occurred while debugging my server, so it is not `dlv test` related but also happens for `dlv debug` ...

```
dlv version
Version: 0.10.0-alpha
Build: d4bfd25a28cab4589808471d987e28ae6c6175c6

go version
go1.5.2 linux/amd64
```

gist for copy/paste: https://gist.github.com/lloiser/0679e03e0fa956dda99f

**Comment by aarzilli** [comment]
Because `testSorted` contains uninitialized memory at that point but `sorted` gets initialized as the first thing in `Weird`. It's evident if you disassemble them (with gdb, delve doesn't have a disassembler yet).

**Comment by lloiser** [comment]
thanks for the explanation!
