### ISSUE TITLE
Unable to run dlv on MaxOSX

### ISSUE THREAD

**Issue by ryanfollmer** [derekparker/delve#347]
Delve Version: [0.10.0-alpha] 2015-10-04
Go 1.5: go version go1.5.2 darwin/amd64
OSX Yosemite:  10.10.5 (14F1509)

Followed installation instructions to install and sign the binary. 

When attempting to run dlv in terminal, it returns: -bash: dlv: command not found

I tried running this from the /GoWorkspace/src/hello folder and also from the /GoWorkspace/bin folder.

Here is a screenshot of my workspace directory:
![screen shot 2016-01-13 at 3 08 38 pm](https://cloud.githubusercontent.com/assets/2651539/12306590/92852db6-ba08-11e5-8523-e7c59a42795e.png)

**Comment by derekparker** [comment]
This doesn't seem like an issue with Delve. It seems like there is an issue with your $PATH or something. What happens if your in your `GoWorkspace/bin` directory and you run `./dlv` (i.e. invoke relative to current path)?

**Comment by ryanfollmer** [comment]
Thank you for the quick response! That worked!

![screen shot 2016-01-13 at 3 57 22 pm](https://cloud.githubusercontent.com/assets/2651539/12307617/6238d666-ba0e-11e5-9a4a-d631a409669e.png)
