### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by OneOfOne** [derekparker/delve#355]
Let me know if you need anything else.

	➜ dlv version; go version
	Delve Debugger
	Version: 0.10.0-alpha
	Build: 98ae684096d7fd15942bdee9c30f70a9a4f07613
	go version devel +32fa667 2016-01-16 03:14:41 +0200 linux/amd64

	➜ dlv test -- -test.run=.
	Type 'help' for list of commands.
	(dlv) r
	Process restarted with PID 31868
	(dlv) c
	PASS
	Process 31868 has exited with status 0
	(dlv) bt
	panic: send on closed channel

	goroutine 83 [running]:
	github.com/derekparker/delve/proc.registers(0xc82057b940, 0x0, 0x0, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/proc/registers_linux_amd64.go:85 +0x11b
	github.com/derekparker/delve/proc.(*Thread).Registers(0xc82057b940, 0x0, 0x0, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/proc/registers.go:20 +0x54
	github.com/derekparker/delve/proc.(*Thread).Stacktrace(0xc82057b940, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/proc/stack.go:49 +0x51
	github.com/derekparker/delve/service/debugger.(*Debugger).Stacktrace(0xc820013fb0, 0xffffffffffffffff, 0xa, 0x8ebf00, 0x0, 0x0, 0x0, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/service/debugger/debugger.go:501 +0xf5
	github.com/derekparker/delve/service/rpc.(*RPCServer).StacktraceGoroutine(0xc820138420, 0xc820929a60, 0xc820929a80, 0x0, 0x0)
			/home/oneofone/code/go/src/github.com/derekparker/delve/service/rpc/server.go:120 +0x5d
	reflect.Value.call(0x9d4040, 0xacc5e8, 0x13, 0xaebb00, 0x4, 0xc820bf8ef8, 0x3, 0x3, 0x0, 0x0, ...)
			/usr/src/go/src/reflect/value.go:435 +0x120d
	reflect.Value.Call(0x9d4040, 0xacc5e8, 0x13, 0xc820bf8ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
			/usr/src/go/src/reflect/value.go:303 +0xb1
	net/rpc.(*service).call(0xc820438840, 0xc820438800, 0xc820535630, 0xc820541c80, 0xc82053e780, 0x8f1400, 0xc820929a60, 0x16, 0x8ebf40, 0xc820929a80, ...)
			/usr/src/go/src/net/rpc/server.go:383 +0x1c2
	created by net/rpc.(*Server).ServeCodec
			/usr/src/go/src/net/rpc/server.go:477 +0x49d

**Comment by derekparker** [comment]
Thanks for reporting. All commands should first check if the process has exited and return an error / message to the user. That's essentially what is causing this.
