### ISSUE TITLE
[OSX10.11.3] Can't debug : could not launch process: could not fork/exec

### ISSUE THREAD

**Issue by sub-mod** [derekparker/delve#357]
$ codesign -s dlv-cert $(which dlv)
/Users/mememe/development/golang/bin/dlv: is already signed

$ go build hello.go

$ dlv debug hello.go 
could not launch process: could not fork/exec

**Comment by aarzilli** [comment]
See Issues #300, #159, #134. Basically, it's not a bug with delve, you either you made a mistake following the install procedure correctly or the gods of OS X codesigning aren't smiling upon you. 

Don't feel bad, I had to do it three times before getting it to work.

**Comment by sub-mod** [comment]
Thanks, 
good to know it is not issue with delve.

I had to follow the steps again, But wherever i could see a "Trust” item I  set  to “Always Trust”.
This works now
:+1:

**Comment by aarzilli** [comment]
good.

**Comment by oknixus** [comment]
delete the GOPATH/bin/dlv, then the problem was solved.

**Comment by caibirdme** [comment]
@oknixus It works,thx

**Comment by ThreeBearsDan** [comment]
I addressed this by upgrading delve.
