### ISSUE TITLE
step out of a function

### ISSUE THREAD

**Issue by aybabtme** [derekparker/delve#358]
Heyo!

it would be cool to have the inverse of `step`, something that steps out of the current function.

**Comment by alvarolm** [comment]
first thanks @derekparker @aarzilli and everyone who has contributed to delve, out of curiosity, its there a date or timeline to merge @aarzilli s work ?

**Comment by lfrdreamman** [comment]
thanks all, when the step out can work?

**Comment by aarzilli** [comment]
Implemented by 0f4b5150c370467c6478bc73b7ed64b92d94af56
