### ISSUE TITLE
Step over goes off into space

### ISSUE THREAD

**Issue by asampal** [derekparker/delve#361]
Using a newly built delve under Windows 10 64 bit, Visual Studio Code with the [vscode-go](https://github.com/Microsoft/vscode-go) extension.

Aafter placing a breakpoint on line 42 with `listener, e := net.Listen("tcp", ":4321")` of this small SO example, delve stops at the breakpoint, but when step over (F10) is invoked, the debugger goes off somewhere, pause becomes enabled, and doesn't come back. If, on the other hand, a breakpoint is placed on line 67, with `if err != nil {`, stepping over works properly.

```
package main

import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"net"
	"net/http"
	"net/rpc"
	"net/rpc/jsonrpc"
)

// adapt HTTP connection to ReadWriteCloser
type HttpConn struct {
	in  io.Reader
	out io.Writer
}

func (c *HttpConn) Read(p []byte) (n int, err error)  { return c.in.Read(p) }
func (c *HttpConn) Write(d []byte) (n int, err error) { return c.out.Write(d) }
func (c *HttpConn) Close() error                      { return nil }

// our service
type CakeBaker struct{}

func (cb *CakeBaker) BakeIt(n int, msg *string) error {
	*msg = fmt.Sprintf("your cake has been bacon (%d)", n)
	return nil
}

func main() {

	fmt.Printf("TestHTTPServer\n")

	cb := &CakeBaker{}

	server := rpc.NewServer()
	server.Register(cb)

	listener, e := net.Listen("tcp", ":4321")
	if e != nil {
		log.Fatal("listen error:", e)
	}
	defer listener.Close()

	go http.Serve(listener, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		if r.URL.Path == "/bake-me-a-cake" {
			serverCodec := jsonrpc.NewServerCodec(&HttpConn{in: r.Body, out: w})
			w.Header().Set("Content-type", "application/json")
			w.WriteHeader(200)
			err := server.ServeRequest(serverCodec)
			if err != nil {
				log.Printf("Error while serving JSON request: %v", err)
				http.Error(w, "Error while serving JSON request, details have been logged.", 500)
				return
			}
		}

	}))

	resp, err := http.Post("http://localhost:4321/bake-me-a-cake", "application/json", bytes.NewBufferString(
		`{"jsonrpc":"2.0","id":1,"method":"CakeBaker.BakeIt","params":[10]}`,
	))
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()
	b, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}

	fmt.Printf("returned JSON: %s\n", string(b))

}
```

**Comment by derekparker** [comment]
@asampal can you verify if this is still an issue? `step` command has actually been reworked, I think just after this issue was posted.

**Comment by jussij** [comment]
I have the Delve code from about two days ago and I can replicate this issue in an even simpler example as described below.

I have this simple test file:

	// main.go
	package main

	import "fmt"

	type User struct {
		FirstName string
		LastName  string
	}

	func (user User) String() string {
		return fmt.Sprintf("%s %s", user.FirstName, user.LastName)
	}

	func main() {
		user := User{
			FirstName: "John",
			LastName:  "Smith",
		}

		message := FormatMessage(user, "Golang Weekly Newsletter #756")

		for index := 0; index < 3; index++ {
			fmt.Printf("Sending #%d message with %s\n", index, message)
		}
	}

	func FormatMessage(user User, message string) string {
		return fmt.Sprintf("body: %s by %s", message, user.String())
	}

If I run these commands:

    dlv.exe debug main.go

    break main.go:11

    continue

    step

At this point the debugger hangs.

The results are also repeatable.

Here is the complete details for that session:

    C:\Go\src\github.com\jussij\DelveTest>dlv.exe debug main.go
    Type 'help' for list of commands.
    (dlv) break main.go:11
    Breakpoint 1 set at 0x401040 for main.User.String C:/Go/src/github.com/jussij/DelveTest/main.go:11
    (dlv) continue
    > main.User.String() C:/Go/src/github.com/jussij/DelveTest/main.go:11 (hits goroutine(1):1 total:1)
         6: type User struct {
         7:         FirstName string
         8:         LastName  string
         9: }
        10:
    =>  11: func (user User) String() string {
        12:         return fmt.Sprintf("%s %s", user.FirstName, user.LastName)
        13: }
        14:
        15: func main() {
        16:         user := User{
    (dlv) step


Even after waiting several minutes the debugger does not return.

**Comment by derekparker** [comment]
Just tested this out on my machine (OSX) using @jussij example and got an error, although different. In my case trying to step causing the target program to panic for some reason. Will dig in further.

**Comment by derekparker** [comment]
Update: I actually think I may know what's causing this, hopeful to have a fix up soon.

**Comment by derekparker** [comment]
@jussij @asampal can you both try building off of this branch: https://github.com/derekparker/delve/pull/376 and let me know if the issue is resolved?

**Comment by jussij** [comment]
Using the changes from above fixes my earlier example.

Looking good :)
