### ISSUE TITLE
Display disassembly of a function

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#368]
We should have a command to display the assembly for a given function. Most likely the easiest path forward is to simply have Delve invoke `go tool objdump -s <symname>`. Either that or take a look at that tool and see if we can use the code there as a package and do it all programmatically.

**Comment by aarzilli** [comment]
Implemented in e7a9a3ea9a72d943a9e9012977d28419933f5896, Issue #415 tracks remaining feature request.
