### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by jussij** [derekparker/delve#369]
As per the Windows build instruction I downloaded and installed mingw-w64 (Windows 10, x64 machine)

I selected the options as per the Wiki, 5.3.0, x86_64, posix and seh.

I had the installation run into this folder location which is also in the PATH:

    C:\Program Files\mingw-w64\x86_64-5.3.0\mingw64\bin

But when I try to run the make it fails with these linker errors:

    C:\go\src\github.com\derekparker\delve>mingw32-make install
    process_begin: CreateProcess(NULL, uname, ...) failed.
    mingw32-make: Makefile:7: pipe: No error
    process_begin: CreateProcess(NULL, uname, ...) failed.
    mingw32-make: Makefile:22: pipe: No error
    go install -ldflags="-X main.Build=1bda586115ad3ca0daa6f5b7180a6bc662c72685" github.com/derekparker/delve/cmd/dlv
    # github.com/derekparker/delve/proc
    C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/lib/libmingwthrd.a when searching for -lmingwthrd
    C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/lib\libmingwthrd.a when searching for -lmingwthrd
    C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/lib/libmingwthrd.a when searching for -lmingwthrd
    C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwthrd
    ........
    C:/Program Files/mingw-w64/x86_64-5.3.0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt
    collect2.exe: error: ld returned 1 exit status
    Makefile:44: recipe for target 'install' failed
    mingw32-make: *** [install] Error 2

A Google search seems to suggest the 'skipping incompatible' message is a MingGW dual target issue, whereby a 32 bit lib is being linked against a 64 bit executable or vice versa.

Here is the link I found:

http://stackoverflow.com/questions/16304804/dual-target-mingw-w64-isnt-really-dual-target

Anyone know what is going wrong with this Windows Build?

**Comment by aarzilli** [comment]
cc: @lukehoban

**Comment by jussij** [comment]
I am closing this issue as it can be put it down to user error ;)

For those other user who are new to Go this is what I did wrong.

The compiler I installed was definitely the x64 version:

    C:\go\src\github.com\derekparker\delve>gcc --version
    gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.3.0
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

But the Go compiler installed was built from source and it was built using using a 32 bit version to the TDM-GCC comipler.

Hence the Go compiler installed was also 32 bit:

    C:\go\src\github.com\derekparker\delve>go version
    go version go1.5.1 windows/386

This created the 64/32 bit errors reported by the linker reported earlier.

So I replaced the Go compiler with a 64 bit version:

    D:\Projects\Utilities>go version
    go version go1.5.3 windows/amd64

With that new compiler in place the build worked fine :)

**Comment by lukehoban** [comment]
@jussij Good to hear you figured this out.

**Comment by dlsniper** [comment]
If others bump into this, I've made a small PowerShell script to install everything needed to compile delve on a Windows machine: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/1922#issuecomment-175333420

Maybe not the best script there is but it's my first PowerShell script. Hope it helps.
