### ISSUE TITLE
Breakpoint Locations should be case insensitve on Windows

### ISSUE THREAD

**Issue by jussij** [derekparker/delve#370]
I'm looking to add support for Delve to the Zeus IDE and came across the following issue.

As a test I create a Windows test Go application here:

    C:\Go\src\github.com\jussij\DelveTest\main.go

When I tried to set a breakpoint in that file at line 15 it failed because of the Windows (i.e non unix) format of the file name.
    
    break C:\Go\src\github.com\jussij\DelveTest\main.go:15

That was easy enough to to fix so I made a change to issue this command instead:

    break C:/Go/src/github.com/jussij/DelveTest/main.go:15

But that also failed as shown below:

    break C:/Go/src/github.com/jussij/DelveTest/main.go:15
    Command failed: Location "C:/Go/src/github.com/jussij/DelveTest/main.go:15" not found

I think the reason it is failing is because at line 315 in this delve file:

    C:\Go\src\github.com\derekparker\delve\service\debugger\locations.go

The file lookup code below is failing to find that file:

    func (loc *NormalLocationSpec) Find(d *Debugger, scope *proc.EvalScope, locStr string) ([]api.Location, error) {
        funcs := d.process.Funcs()
        files := d.process.Sources()

Then after lots of head scratching I found out that this command works:

    break c:/go/src/github.com/jussij/DelveTest/main.go:15
    Breakpoint 1 set at 0x401240 for main.main c:/go/src/github.com/jussij/DelveTest/main.go:15

I suspect this error is somehow related to the Windows file system being case in-sensitive where as the Linix file system is case sensitive and Delve is coded for Linux.

But what has me confused is the file correctly named on the Windows disk is as follows:

    C:\Go\src\github.com\jussij\DelveTest\main.go

Which gives this Unix version:

    C:/Go/src/github.com/jussij/DelveTest/main.go

Yet the break command is expecting this:

    c:/go/src/github.com/jussij/DelveTest/main.go:15

If run the delve sources command I get this:

    sources
    <autogenerated>
    c:/go/src/errors/errors.go
    c:/go/src/fmt/doc.go
    c:/go/src/fmt/format.go
    c:/go/src/fmt/print.go
    c:/go/src/fmt/scan.go
    c:/go/src/github.com/jussij/DelveTest/main.go
    ..............

So where did that lower case version of the c:/go/ folder come from?

If this is a case sensitivity issue, could the Windows file test be made case insensitive?

For example if all the sources where made lower case that would be easy enough to also do that at the IDE side:

    c:/go/src/github.com/jussij/delvetest/main.go

Zeus also talks to Subversion (which is also file case sensitive) and that behavior has cause no amount of trouble, only because users on Windows get into the habit of not worry about the case of files as Windows does not care.

**Comment by aarzilli** [comment]
> So where did that lower case version of the c:/go/ folder come from?

The go compiler probably.

**Comment by lukehoban** [comment]
Yeah, the casing and path structure in the elf/dwarf symbols come from the Go compiler. 

This same issue was raised by a user of the vscode Go plugin today as well. 

I expect there is an additional case conversion needed on Windows to make sure paths are case insensitive in marching break points. 

If you haven't tracked down the root cause of this yet, I'll take a look myself tomorrow.

**Comment by jussij** [comment]
> I expect there is an additional case conversion needed on Windows to make sure paths are case insensitive in marching break points. 

If all the file names used for the breakpoints were made lower case (or uppercase) that would work, as the same logic could be applied at the IDE side.

As a 'quick and dirty' work around, I'm just making the first five characters lower case and this is working great :)

But naturally, a cleaner solution is needed.

**Comment by jussij** [comment]
This is getting a bit strange :(

Where as earlier on the breakpoint code appeared to prefer this as the file prefix:

    c:/go/src

Now just a few hours later and it appears that prefix no longer works and now this is the preferred prefix:

    C:/Go/src

These earlier commands worked but now they don't:
    
    break c:/go/src/github.com/jussij/DelveTest/main.go:12
    Command failed: Location "c:/go/src/github.com/jussij/DelveTest/main.go:12" not found

Likewise these once failing commands now work just fine:

    break C:/Go/src/github.com/jussij/DelveTest/main.go:29
    Breakpoint 2 set at 0x401568 for main.FormatMessage C:/Go/src/github.com/jussij/DelveTest/main.go:29

**Comment by lukehoban** [comment]
@jussij I've opened a PR (https://github.com/derekparker/delve/issues/375) which should address this.  If you have a chance, feel free to try this out in your environment and let me know if you still see any issues.
