### ISSUE TITLE
How to set break points in dependency code

### ISSUE THREAD

**Issue by sub-mod** [derekparker/delve#379]
Can I step into a dependency code ?
I tried to step into a method(which was from another package) in my test code and it didnt work.
Is this feature supported ?

**Comment by aarzilli** [comment]
It should work, could you describe what you did and what happened? Thank you.

**Comment by aarzilli** [comment]
@derekparker: this issue is inscrutable to me and @sub-mod has not provided a way to reproduce the problem. Should we adopt a policy of closing such issues after a delay?

**Comment by sub-mod** [comment]
Sorry for delay.
I find this working for me now.
