### ISSUE TITLE
proc: next while nexting

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#387]
Running into an issue, testing out 'next'ing with multiple goroutines, and eventually I end up on the wrong goroutine, and when I try and 'next' again, I get the error: 'next while nexting'.

I have been able to repro on my OSX machine and a Linux VM.

Example code: 

```go

func dostuff(id int, wg *sync.WaitGroup) {
	fmt.Println("goroutine:", id)
	fmt.Println("goroutine:", id)
	wg.Done()
}

func main() {
	runtime.Breakpoint()

	var wg sync.WaitGroup
	wg.Add(10)
	for i := 0; i < 10; i++ {
		go dostuff(i, &wg)
	}
	wg.Wait()
}
```

Set a breakpoint on `dostuff` and then print id, next, print id, next and usually the third time it happens.

cc: @aarzilli - might not have time to track this down until later, but we need to get this fixed :).

**Comment by aarzilli** [comment]
I don't think this is a bug. `next` restarts all threads, if another goroutine hits a breakpoint before one of the temp breakpoints set by `proc.(*Process).Next` are hit you get a stop for that breakpoint.

Since a "next operation" is already in progress you can't `next` again, you have to `continue` until one of the breakpoints set by `next` is reached.

I don't think there is a way out of this, even if we restarted only a single thread the go runtime could still decide to switch us to a different goroutine while we are executing a `next` instruction, and that goroutine could hit a breakpoint.

Maybe make this more obvious in the UI?

**Comment by derekparker** [comment]
@aarzilli yeah, you're absolutely correct about the root cause. However, hitting the pre-existing breakpoint should not prevent executing further `next` commands. I think this warrants a bit of discussion from a usability standpoint. What's the better user experience while stepping through this type of code? Given, this example is pretty contrived (cooked it up for a talk, heh), it is still unexpected for a user to experience this.

Thoughts:

a) Ignore normal breakpoints during 'next' operations, letting you continue to examine the thread of execution you're obviously concerned with.
b) Keep existing behavior, but possibly make it more clear that we've switched threads/goroutines, and more importantly clear out the temp breakpoints that were previously set.

Honestly I am leaning more towards option a. If you set a breakpoint at a function, and then are explicitly executing the 'next' command, your intention is obviously to go to the next source line, not stop when another running threads hits that original breakpoint. The obvious implication here is that stepping over a function that has a breakpoint set in it will be ignored. However, if you really wanted to hit that breakpoint, a `continue` would be the more explicit way to achieve that. And furthermore, leaving the temp breakpoints around so that a 'continue' could _potentially_ pick up where you left off is very non intuitive for a typical user.

**Comment by aarzilli** [comment]
> hitting the pre-existing breakpoint should not prevent executing further `next` commands

Really doing this is going to be hard, next's breakpoints are goroutine specific, if we want multiple nexts to run we need the ability to have multiple breakpoints set at the same program location, all active, and when a breakpoint is cleared the underlying `INT 3` instruction only goes away if all the breakpoints using it are cleared (reference counting?).

>a) Ignore normal breakpoints during 'next' operations, letting you continue to examine the thread of execution you're obviously concerned with.

This is easy if we do it in `terminal/command` and could make for a good compromise between (a) and (b): if we hit a breakpoint while nexting we show it but automatically continue:

```
(dlv) next
> main.someFunction() ./somefile.go:13 (hits goroutine(2): 1 total: 5)
    breakpoint hit during next, continuing...
> main.someFunction() ./somefile.go:13 (hits goroutine(5): 1 total: 6)
    breakpoint hit during next, continuing...
> main.someOtherFunction() ./someotherfile.go:400
...file listing goes here...
(dlv) 
```

This way breakpoints hit during `next` aren't silently suppressed but they don't bother the user too much either.

**Comment by derekparker** [comment]
> Really doing this is going to be hard, next's breakpoints are goroutine specific, if we want multiple nexts to run we need the ability to have multiple breakpoints set at the same program location, all active, and when a breakpoint is cleared the underlying INT 3 instruction only goes away if all the breakpoints using it are cleared (reference counting?).

No, that's not what I meant, I just think that when we hit a breakpoint, and we decide to stop at said breakpoint (and expose the prompt to the user) they should not be prevented from `next`ing again. So, in order to do this, we must ensure that all temp breakpoints have been removed before showing prompt to user. This essentially "cancels" the next that _was_ in progress.

> This is easy if we do it in terminal/command and could make for a good compromise between (a) and (b): if we hit a breakpoint while nexting we show it but automatically continue:

Hmm... that seems reasonable.
