### ISSUE TITLE
Step Command Not Working

### ISSUE THREAD

**Issue by jussij** [derekparker/delve#402]
This issue is in regard to Delve running on Windows.

Consider this main.go example file:

    // main.go
    package main

    import "fmt"

    type User struct {
        FirstName string
        LastName  string
    }

    func (user User) String() string {
        return fmt.Sprintf("%s %s", user.FirstName, user.LastName)
    }

    func main() {
        user := User{
            FirstName: "John",
            LastName:  "Smith",
        }

        message := FormatMessage(user, "Golang Weekly Newsletter #756")

        for index := 0; index < 3; index++ {
            fmt.Printf("Sending #%d message with %s\n", index, message)
        }
    }

    func FormatMessage(user User, message string) string {
        return fmt.Sprintf("body: %s by %s", message, user.String())
    }

Run the debugger using this file:

    dlv debug main.go

Next set the break point at line 21 using this command:

    break main.go:21

That results in this output:

    (dlv) break main.go:21
    Breakpoint 1 set at 0x4012be for main.main C:/Go/src/github.com/jussij/DelveTest/main.go:21

Next issue the continue command which should hit that break point:

    continue

As you can see it does hits that break point and correctly stops as shown below:

    > main.main() C:/Go/src/github.com/jussij/DelveTest/main.go:21 (hits goroutine(1):1 total:1)
        16:         user := User{
        17:                 FirstName: "John",
        18:                 LastName:  "Smith",
        19:         }
        20:
    =>  21:         message := FormatMessage(user, "Golang Weekly Newsletter #756")
        22:
        23:         for index := 0; index < 3; index++ {
        24:                 fmt.Printf("Sending #%d message with %s\n", index, message)
        25:         }
        26: }

But look what happens if you then issue the next command which gives you this output:

    (dlv) next
    > main.FormatMessage() C:/Go/src/github.com/jussij/DelveTest/main.go:28
        23:         for index := 0; index < 3; index++ {
        24:                 fmt.Printf("Sending #%d message with %s\n", index, message)
        25:         }
        26: }
        27:
    =>  28: func FormatMessage(user User, message string) string {
        29:         return fmt.Sprintf("body: %s by %s", message, user.String())
        30: }

From the commands reference web page: https://github.com/derekparker/delve/wiki/Commands

It says next does this:

    Next - Step over to next source line.

In the example above example the **next** command has not stepped over the FormatMessage function but instead it stepped into that function

**Comment by aarzilli** [comment]
This should be fixed by b370e20cd5e8a8b1fc110b41f30a21315c8f78cc.

**Comment by derekparker** [comment]
@jussij please verify this is fixed as of the commit @aarzilli referenced and if so please close out the issue. Thanks!

**Comment by jussij** [comment]
I can confirm this is now working. Excellent  :)

    C:\Go\src\github.com\jussij\DelveTest>dlv debug main.go
    Type 'help' for list of commands.
    (dlv) break main.go:21
    Breakpoint 1 set at 0x4012be for main.main C:/Go/src/github.com/jussij/DelveTest/main.go:21
    (dlv) continue
    > main.main() C:/Go/src/github.com/jussij/DelveTest/main.go:21 (hits goroutine(1):1 total:1) (PC: 0x4012be)
        16:         user := User{
        17:                 FirstName: "John",
        18:                 LastName:  "Smith",
        19:         }
        20:
    =>  21:         message := FormatMessage(user, "Golang Weekly Newsletter #756")
        22:
        23:         for index := 0; index < 3; index++ {
        24:                 fmt.Printf("Sending #%d message with %s\n", index, message)
        25:         }
        26: }
    (dlv)
