### ISSUE TITLE
Delve crashes when receiving command on a non-stopped process in server mode

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#408]
Hi,

We've had this issue, https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2218, in the Go plugin for a while but I've now managed to fully replicate it.

What happens is that the IDE doesn't wait until the response from all commands is received before resuming the process which leads to the process crashing and leaving the debugged process running.

Log from the plugin: http://pastebin.com/Wy577dvD

Besides the proper fix for this (which I think it should be done in Delve) I wonder if it's possible to catch these crashes and kill the debugged process when they happen. What do you think?

Thank you!

**Comment by aarzilli** [comment]
Could you see if #421 improves anything?

**Comment by dlsniper** [comment]
@aarzilli sorry for delay in response, I'm a bit busy currently. I'll try and see in the coming days. Thank you!
