### ISSUE TITLE
Running debugger requires the working directory to be the same as the package / file directory

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#423]
Hi,

It seems that delve needs the working directory to be same as the directory where the package / file is located in otherwise it produces the following error:
```
could not launch process: fork/exec ./<binary>: no such file or directory
```

**Comment by derekparker** [comment]
@dlsniper this is a UX rough edge that needs to finally be taken care of.

I will submit a patch shortly to allow specifying a package to build and attach to, so delve doesn't assume current dir.
