### ISSUE TITLE
Print / get the value of unsafe.Pointer

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#426]
Hi,

In the following program:
```go
package main

import (
    "fmt"
    "github.com/go-ozzo/ozzo-config"
)

func main() {
    // create a Config object
    c := config.New()

    // load configuration from a JSON string
    c.LoadJSON([]byte(`{
        "Version": "2.0",
        "Author": {
            "Name": "Foo",
            "Email": "bar@example.com"
        }
    }`))

    // get the "Version" value, return "1.0" if it doesn't exist in the config
    version := c.GetString("Version", "1.0")

    var author struct {
        Name, Email string
    }
    // populate the author object from the "Author" configuration
    c.Configure(&author, "Author")

    fmt.Println(version) // set breakpoint here
    fmt.Println(author.Name)
    fmt.Println(author.Email)
    // Output:
    // 2.0
    // Foo
    // bar@example.com
}
```

it is not possible to get the value of `c.data.ptr` as `ptr` is an `unsafe.Pointer` type.
Would it be possible, for a not so near release of delve, to have delve evaluate the pointer and return the information for it?

(related issue: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2347, cc @kolkov)

Thank you.

**Comment by aarzilli** [comment]
Unsafe pointers do not have type information so we can not print nothing more than their address. If the user happens to know what the unsafe.Pointer happens to point to a type cast can be used

```
print *(*someType)(0x...)
```

if we are unable to resolve the type expression into a type name double quotes can be used:

```
print *(*"map[string]interface {}")(0x...)
```

introduced in a7a0cc75e128c696af0d90a811cd7235339074db.

**Comment by dlsniper** [comment]
I wonder if we (the delve "consumers") can automate that given we should know information about the type of pointers. What would be the API call in this case? `Eval`?

**Comment by aarzilli** [comment]
Yes, `Eval`. But in general you don't know the type either, unsafe.Pointer could contain an entirely arbitrary value.

**Comment by dlsniper** [comment]
Fair enough, I haven't read how that lib works until now. Thanks!
