### ISSUE TITLE
Delve panic on Windows 10 (x64) using Go 1.6

### ISSUE THREAD

**Issue by jussij** [derekparker/delve#430]
I built the latest Go 1.6 from source:

    C:\Go\src\github.com\jussij\hw>go version
    go version go1.6 windows/amd64

I also built Delve using the make.cmd batch file using the latest Git source:

    C:\Go\src\github.com\jussij\hw>dlv version
    Delve Debugger
    Version: 0.11.0-alpha
    Build:

I have this simple Go test file:

    C:\Go\src\github.com\jussij\hw>type main.go
    package main
    
    import "fmt"
    
    func main() {
            fmt.Printf("Hello world\n")
    }

Here is what happens if I try to debug that file:

    C:\Go\src\github.com\jussij\hw>dlv debug
    Type 'help' for list of commands.
    (dlv) break c:/go/src/github.com/jussij/hw/main.go:6
    Breakpoint 1 set at 0x40105a for main.main() C:/Go/src/github.com/jussij/hw/main.go:6
    (dlv) continue
    panic: runtime error: cgo argument has Go pointer to Go pointer
    
    goroutine 32 [running]:
    panic(0xa73680, 0xc0827e7d20)
            C:/Go/src/runtime/panic.go:464 +0x3f4
    github.com/derekparker/delve/proc.(*Thread).readMemory(0xc0821462d0, 0xc082020000, 0x168, 0x0, 0x0, 0x0, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/threads_windows.go:162 +0x1ad
    github.com/derekparker/delve/proc.cacheMemory(0x4d68968, 0xc0821462d0, 0xc082020000, 0x168, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/mem.go:52 +0x2a7
    github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc08215a380, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/variables.go:750 +0xf7c
    github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc08215a1c0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/variables.go:725 +0xd15
    github.com/derekparker/delve/proc.(*Variable).loadValue(0xc08215a1c0)
            C:/Go/src/github.com/derekparker/delve/proc/variables.go:711 +0x31
    github.com/derekparker/delve/proc.(*Variable).parseG(0xc08215a1c0, 0xc08215a1c0, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/variables.go:364 +0x77d
    github.com/derekparker/delve/proc.(*Thread).GetG(0xc0821462d0, 0xc0821462d0, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/threads.go:317 +0x70
    github.com/derekparker/delve/proc.(*Thread).SetCurrentBreakpoint(0xc0821462d0, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/threads.go:371 +0x195
    github.com/derekparker/delve/proc.(*Process).setCurrentBreakpoints(0xc08215a000, 0xc0821462d0, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/proc_windows.go:458 +0x34
    github.com/derekparker/delve/proc.(*Process).Continue(0xc08215a000, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/proc/proc.go:367 +0x208
    github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc08213a090, 0xc0822187a0, 0x0, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/service/debugger/debugger.go:316 +0x785
    github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc082144120, 0xc0822187a0, 0xc0827620f0, 0x0, 0x0)
            C:/Go/src/github.com/derekparker/delve/service/rpc/server.go:129 +0x46
    reflect.Value.call(0xa1d760, 0xb1fb98, 0x13, 0xb3efb8, 0x4, 0xc082189ed8, 0x3, 0x3, 0x0, 0x0, ...)
            C:/Go/src/reflect/value.go:435 +0x1214
    reflect.Value.Call(0xa1d760, 0xb1fb98, 0x13, 0xc082189ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
            C:/Go/src/reflect/value.go:303 +0xb8
    net/rpc.(*service).call(0xc082a0f580, 0xc082a0f540, 0xc082781218, 0xc082156e00, 0xc08293c2e0, 0x933bc0, 0xc0822187a0, 0x16, 0x933c20, 0xc0827620f0, ...)
            C:/Go/src/net/rpc/server.go:383 +0x1c9
    created by net/rpc.(*Server).ServeCodec
            C:/Go/src/net/rpc/server.go:477 +0x4a4

**Comment by lukehoban** [comment]
This is the same issue as #416.  It will be fixed once #425 is merged.

**Comment by aarzilli** [comment]
Closing as duplicate.
