### ISSUE TITLE
Are there any better/more current/working OSX installation instructions?

### ISSUE THREAD

**Issue by Nuclearfossil** [derekparker/delve#454]
Hey all,

Trying to install dlv on OSX 10.11.3 and having a hell of a time just getting it running.

1. This is off the master branch
2. followed the OSX instructions here (https://github.com/derekparker/delve/wiki/Building) however to explicity restate them:
  - created the cert as outlined.  Called it 'delve'.
  - rebooted
  - git cloned the delve repo
  - ran ```GO15VENDOREXPERIMENT=1 CERT=delve make install``` from the root of the cloned directory.
  - got this:
```
go build -ldflags="-s -X main.Build=c66c6408a5f32e84cc3955fe97302ad6d78df24e" github.com/derekparker/delve/cmd/dlv
can't load package: package github.com/derekparker/delve/cmd/dlv: cannot find package "github.com/derekparker/delve/cmd/dlv" in any of:
	/Users/amatheson/.gvm/gos/go1.5/src/github.com/derekparker/delve/cmd/dlv (from $GOROOT)
	/Users/amatheson/Code/research/delve/src/github.com/derekparker/delve/cmd/dlv (from $GOPATH)
make: *** [build] Error 1
```

yes, I'm using GVM to manage my go envs.

Go envs look like so:
```
$ echo $GOPATH
/Users/amatheson/Code/research/delve
$ echo $GOROOT
/Users/amatheson/.gvm/gos/go1.5
```

**Comment by Nuclearfossil** [comment]
So, may have gotten it going now on OSX without having to git clone.

1. from you current GOROOT
  - go get -v -u github.com/peterh/liner github.com/derekparker/delve/cmd/dlv
  - codesign -s delve bin/dlv
2. you should now be able to bin/dlv debug something.go

**Comment by derekparker** [comment]
This seems like a GOPATH issue to me, is the layout of `/Users/amatheson/Code/research/delve` correct, with a `src` dir, etc?

**Comment by Nuclearfossil** [comment]
delve has no src folder in the repo

**Comment by derekparker** [comment]
@Nuclearfossil right, so your $GOPATH should not be set to the Delve repo location, it should be set to a valid Go workspace directory. See https://golang.org/doc/code.html#GOPATH.

**Comment by Nuclearfossil** [comment]
I'm very confused.  How does that build the dlv binary?

**Comment by Nuclearfossil** [comment]
OK. So it doesn't put it into $GOROOT/bin, it puts it into each Go Project.

That could stand more clarification in the docs.

**Comment by derekparker** [comment]
Going to close this as not a Delve issue. I think you have your local setup configured incorrectly. Your $GOPATH should include a `src`, `pkg` and `bin` directory, into which Delve will be installed. `make install` will install into `$GOPATH/bin`. Programs that you build yourself should never end up in `$GOROOT/bin`, that's for the go tool, etc.

**Comment by Nuclearfossil** [comment]
I would disagree, I don't want to rebuild delve each time I create a new
project, which is what you're saying with this response.

**Comment by derekparker** [comment]
That is only a symptom of using GVM (as far as I can tell). I haven't used it before, but the typical Go development setup is a single $GOPATH where all your source is stored in `$GOPATH/src` and programs are compiled into `$GOPATH/bin`. Please refer to: https://golang.org/doc/code.html#Workspaces.

**Comment by Nuclearfossil** [comment]
Yes, for one project. I have many projects on the go which requires
changing the go path multiple times during the day. This means that for
each project you must rebuild and re sign the delve executable. That feels
incredibly wasteful imo.

**Comment by derekparker** [comment]
@Nuclearfossil no, in a typical setup you would not change your `$GOPATH` at all. You have a single `$GOPATH` which holds all of your projects. You don't need a `$GOPATH` per project. What your doing is closer to something like https://getgb.io/ which takes a project based approach to building Go programs.

**Comment by Nuclearfossil** [comment]
Yeah, that's very close to what I'm working with.  Using a single $GOPATH
and stuffing everything into it will not work for our organization (each
project has dependencies on separate external docker services such as
redis, kafka, zookeeper, etc) and what you propose simply will not work at
that scale. eg: project A requires redis, project b require
Zookeeper/kafka. For dev/test environments, they would need to be separate
and NOT live in the src folder as you suggest.

I would seriously suggest that you consider the option of adding
installation steps (on OSX at least) which centralizes the delve binary to
either $GOROOT or another mechanism.

-Ash

**Comment by derekparker** [comment]
I've created [this issue](https://github.com/derekparker/delve/issues/458) to track this, we can continue discussion there.
