### ISSUE TITLE
Unable to print map[string]interface{}

### ISSUE THREAD

**Issue by gotschmarcel** [derekparker/delve#455]
Hi,

I'm using delve 0.11.0-alpha and Go 1.5 on OS X 10.11.3. It seems that currently the debugger is not able to print maps of type `map[string]interface{}`:

```
(unreadable interface type "map[string]interface {}" not found for 0xc820115c18: no type entry found)
```

**Comment by aarzilli** [comment]
This is fixed by #434

**Comment by dlsniper** [comment]
I think this can be closed (the commit missed the `fix` from name to close it automatically)

**Comment by aarzilli** [comment]
I'd keep this open, ideally we should be able to do the conversion from expression to "type name as serialized by cmd/compile" ourselves.
