### ISSUE TITLE
Run to cursor leaves the debugger in limbo

### ISSUE THREAD

**Issue by asampal** [derekparker/delve#461]
Using IntelliJ Idea 15.0.4, Go 1.6, go-lang plugin 0.10.1189, Windows 10 64 bit, JDK 1.8.0_74, delve ff0ec8ce00

I was stopped at a breakpoint. I placed the cursor on a line of code past the breakpoint and selected "run to cursor" from the context menu. Delve started execution again, all frames were removed from the debugger view and the program seemed to be in an indeterminate state, not running to completion or stopping where I had put the cursor. I only had the option to stop debugging.

**Comment by aarzilli** [comment]
The plugin for IntelliJ is developed [here](https://github.com/go-lang-plugin-org/go-lang-idea-plugin).

cc @dlsniper

**Comment by dlsniper** [comment]
Please provide more context for the issue, especially a reproducible sample. And since the issue is opened here, can you replicate this with Delve or only in IntelliJ? Thank you.

**Comment by derekparker** [comment]
@asampal can you provide any more information, and whether this can be replicated by using Delve in CLI mode?

**Comment by asampal** [comment]
I think I should've opened this against the go-lang-plugin. My first thought was that it was a debugger related issue, but obviously a command-line tool like delve doesn't have the concept of a cursor so I'm not sure what I could attempt to replicate using the CLI. Doh!

**Comment by asampal** [comment]
Opened https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2401

**Comment by derekparker** [comment]
@asampal most likely what the plugin is doing under the hood is using the Delve API to reconcile a give file:line to a PC that it can set a break point on. What I would do to test this (to see if it is a Delve issue or not) is to try and manually set a break point where you had your cursor set at, continue, and see what happens.

If the program hangs or you get some sort of unexpected behavior we can try and track it down in Delve to see what's happening. That would help rule out a bug in Delve.

**Comment by asampal** [comment]
@derekparker when you say manually set a breakpoint, you mean to do it with the CLI, right?

**Comment by derekparker** [comment]
@asampal correct.

**Comment by asampal** [comment]
I tried the CLI and that went OK. Looks like the plugin is doing something not quite right.
