### ISSUE TITLE
Delve cannot attach and debug a simple http service

### ISSUE THREAD

**Issue by dwbuiten** [derekparker/delve#462]
## 1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:
```

Git revision: ff0ec8ce00fbac7f84859cf420b31bc3a513e43c

## 2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.6 linux/amd64
```

## 3. What operating system and processor architecture are you using?

```
$ uname -a
Linux vimeo-vm 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

## 4. What did you do?

```
$ cat test.go
package main

import (
        "fmt"
        "net/http"
)

func main() {
        http.HandleFunc("/bar", func(w http.ResponseWriter, r *http.Request) {
                fmt.Fprintf(w, "Hello")
        })

        http.ListenAndServe(":5555", nil)
}
$ go build
$ ./test &
[1] 23629
$ dlv attach 23629
Type 'help' for list of commands.
(dlv) stack
Command failed: could not find FDE for PC 0x91e800
```

I also tested with `go build -gcflags '-N -l'`.

## 5. What did you expect to see?

A backtrace.

## 6. What did you see instead?

An error.

**Comment by aarzilli** [comment]
There is a problem with stacktraces, they work fine for threads that are running goroutines, but apparently there is a bug for threads that aren't running any goroutine.

Anyway:

```
(dlv) stack
Command failed: could not find FDE for PC 0x91e800
(dlv) goroutines
[5 goroutines]
  Goroutine 1 - User: /usr/local/go/src/runtime/netpoll.go:160 net.runtime_pollWait (0x42762c)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x42d6c3)
  Goroutine 3 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x42d6c3)
  Goroutine 4 - User: /usr/local/go/src/runtime/proc.go:263 runtime.gopark (0x42d6c3)
  Goroutine 17 - User: /usr/local/go/src/runtime/asm_amd64.s:1999 runtime.goexit (0x45c5d1)
(dlv) goroutine 1 stack
 0  0x000000000042d6c3 in runtime.gopark
    at /usr/local/go/src/runtime/proc.go:263
 1  0x0000000000428146 in runtime.netpollblock
    at /usr/local/go/src/runtime/netpoll.go:341
 2  0x000000000042762c in net.runtime_pollWait
    at /usr/local/go/src/runtime/netpoll.go:160
 3  0x000000000058623f in net.(*pollDesc).Wait
    at /usr/local/go/src/net/fd_poll_runtime.go:73
 4  0x00000000005862af in net.(*pollDesc).WaitRead
    at /usr/local/go/src/net/fd_poll_runtime.go:78
 5  0x0000000000589f3f in net.(*netFD).accept
    at /usr/local/go/src/net/fd_unix.go:426
 6  0x00000000005a7861 in net.(*TCPListener).AcceptTCP
    at /usr/local/go/src/net/tcpsock_posix.go:254
 7  0x00000000004b71c3 in net/http.tcpKeepAliveListener.Accept
    at /usr/local/go/src/net/http/server.go:2427
 8  0x00000000004b634f in net/http.(*Server).Serve
    at /usr/local/go/src/net/http/server.go:2117
 9  0x00000000004b614f in net/http.(*Server).ListenAndServe
    at /usr/local/go/src/net/http/server.go:2098
10  0x00000000004b68af in net/http.ListenAndServe
    at /usr/local/go/src/net/http/server.go:2195
(dlv) 
```

**Comment by aarzilli** [comment]
PS. you should either let dlv compile the program or use `-gcflags='-N -l'`

**Comment by dwbuiten** [comment]
> There is a problem with stacktraces, they work fine for threads that are running goroutines, but apparently there is a bug for threads that aren't running any goroutine.

Not sure I entirely understand (shouldn't every system thread have at least one goroutine attached?), but hopefully it can be fixed.

> PS. you should either let dlv compile the program or use `-gcflags='-N -l'`

As noted, I did try to compile with `-gcflags='-N -l'` :wink:. 

I'd like to note however that requiring this diminishes the usefulness of delve for certain usescases, e.g. allowing you to attach to a broken long running process in a production environement, which is what I am currently using GDB for (and am looking to use delve instead), and which has no such restriction on optimizations when using the "Go Support" python extension.

**Comment by aarzilli** [comment]
>shouldn't every system thread have at least one goroutine attached?

Goroutine 0 is different

Re. gcflags: you don't have to use them but if you don't you'll get code with inline calls and registerized variables.

**Comment by dwbuiten** [comment]
> Re. gcflags: you don't have to use them but if you don't you'll get code with inline calls and registerized variables.

Gotcha.

**Comment by derekparker** [comment]
> which has no such restriction on optimizations when using the "Go Support" python extension.

FWIW the same restriction applies to _any_ debugger. Currently the Go compiler does not emit correct DWARF information for the optimizations it performs. This should be fixed soon.

> Not sure I entirely understand (shouldn't every system thread have at least one goroutine attached?), but hopefully it can be fixed.

Definitely fixable. I will dig into it as soon as I can, unless @aarzilli beats me to it.
