### ISSUE TITLE
proc: Fix Launch race condition on OSX

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#464]
The current implementation of fork/exec'ing the child process, and then trying to parse information out of the running process seems to be racy. It seems the child process is not fully initialized when we try and parse information from it.

We seem to get errors similar to:

`could not launch process: Could not determine version number: could not read string len could not read memory`

**Comment by derekparker** [comment]
I am working on a fix for this, I hope to have up soon.

**Comment by semistone** [comment]
Hi  
   I face some similar issue in mac
when start debug by dlv, it only work sometimes.

I trace syscall in dlv process, it will received the request  like 

`{"method":"RPCServer.CreateBreakpoint","params":[{"file":"/Users/yinchin.chen/go/src/demo/test/test.go","line":11}], "id":1}                
{"method":"RPCServer.Command","params":[{"Name":"continue"}],"id":2}`
and never response.
But if I run dlv manually like


`/usr/local/go/bin/go build -o "/private/var/folders/2r/42srpsns4c50jlcmyz5cn6prb0hb72/T/Build test.go and run1go" -gcflags "-N -l" /Users/yinchin.chen/go/src/demo/test/test.go
"/Users/yinchin.chen/Library/Application Support/IdeaIC2016.1/Go/lib/dlv/mac/dlv" --listen=localhost:53344 --headless=true exec "/private/var/folders/2r/42srpsns4c50jlcmyz5cn6prb0hb72/T/Build test.go and run1go" --
map[]`

and use telnet to send the command, it always properly.
It seem like dlv isn't ready when received those requests.

**Comment by corvino** [comment]
Saw some work happen on this recently and just wanted to offer encouragement. Would be great to see this issue resolved. Thanks!

**Comment by derekparker** [comment]
Currently working on this issue as we speak. I have some OSX fixes and
general refactoring / code cleanup patches I'll be submitting soon.
On Tue, Apr 26, 2016 at 1:58 PM Nathan Corvino <notifications@github.com>
wrote:

> Saw some work happen on this recently and just wanted to offer
> encouragement. Would be great to see this issue resolved. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/derekparker/delve/issues/464#issuecomment-214883908>
>
-- 
- Derek

**Comment by genez** [comment]
Hello, any progress on this issue?
I am experiencing the same problem with my IntelliJ IDE on my Mac (go development)
Even a workaround should be enough until it's fixed

Let me know if I can help with testing

Thanks for your work

**Comment by vazquezger** [comment]
hey, no progress on this one?

**Comment by derekparker** [comment]
This should be fixed on master.
