### ISSUE TITLE
Problem with work dlv

### ISSUE THREAD

**Issue by 3JIou** [derekparker/delve#474]
I was make it - 
```
go get -v -u github.com/peterh/liner github.com/derekparker/delve/cmd/dlv 
```
in my $GOPATH dir and get dlv, next i make [cert](http://take.ms/svzGo) and sing dlv like that:
```
batman ~/Documents/projects/go/golang 💩 $ codesign -s dlv-cert ../bin/dlv
```
and now I have a problem:
```
batman ~/Documents/projects/go/golang 💩 $ ../bin/dlv exec ./api.go
Killed: 9
batman ~/Documents/projects/go/golang 💩 $ ../bin/dlv --help
Killed: 9
```
dlv version - latest
go version - go version go1.6 darwin/amd64
OS and processor architecture - Darwin alahd-mac-batman 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64 i386 
Sorry for my English

**Comment by aarzilli** [comment]
You either made a mistake creating the certificate or didn't restart taskgated. Try following [this video](http://www.youtube.com/watch?v=4ndjybtBg74) again. Good luck Mr. Wayne.

**Comment by 3JIou** [comment]
ok. I did as shown in the video and have new problem! Now with banana taste!

**Comment by 3JIou** [comment]
oh... i make mistake. 
```
batman ~/PycharmProjects/go/golang_plays 💩 $ dlv debug ./api.go
Type 'help' for list of commands.
(dlv) ls
Stopped at: 0x7fff6c064000
=>no source available
(dlv)
```
now all work. thanks for the help

**Comment by aarzilli** [comment]
Great.

**Comment by wader** [comment]
@3JIou I have the same issue. What was the mistake?

**Comment by aarzilli** [comment]
@wader: [try using homebrew](https://github.com/derekparker/delve/issues/508)

**Comment by 3JIou** [comment]
I did as shown in the [this video](http://www.youtube.com/watch?v=4ndjybtBg74)

**Comment by wader** [comment]
@3JIou I think i follow the same guide on the delve homepage but must have done something wrong 😞 
@aarzilli Tried it but get same error... i guess something is left since i followed the guide how to do it manually

**Comment by aarzilli** [comment]
Try with homebrew: #508
