### ISSUE TITLE
Allow a 'run' command

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#484]
I like being able to start a debug session and simply type "continue" to continue the process, but that does not allow you to provide arguments to the process before starting it. You can provide args using `dlv debug -- your args`, however if you want to provide different args after using the `restart` command for instance, it's currently impossible. You would have to exit Delve and restart, and that can be annoying.

So, this is up for discussion as to what the best UX would be here. Potential options:

1) Add a `run` command, and make `continue` behave same as gdb (must `run` first)
2) Add `run` command, and alias `continue` to essentially "run if not started, and then continue"
3) Allow `restart` to take args (replace command line upon restart)
4) Some combination of the above

cc: @aarzilli

**Comment by joegrasse** [comment]
For what it is worth, I like the idea of keeping it as similar to gdb as possible.This would make it easier to use for those coming from gdb.

So for example

run arg1 arg2
set args arg1 arg2

**Comment by aarzilli** [comment]
The least disruptive way to do this would be to add command line arguments to the `Restart` API call and to the `restart` command then implement `run` as:

```
func runcmd(t *Term, ctx callContext, args string) error {
    if args == "" /* maybe also check that it's the first command? */ {
        cont(t, ctx, "")
    } else {
        restart(t, ctx, args)
        cont(t, ctx, "")
    }
}
```

**Comment by aarzilli** [comment]
The ability to specify arguments was added to restart a while ago.
