### ISSUE TITLE
cant run process when install

### ISSUE THREAD

**Issue by ngocthanhpham** [derekparker/delve#488]
dlv version pre 1.0
go version 1.6
win 10 pro 64
when i install my cmd notify this:
"** process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make: Makefile:7: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make: Makefile:22: pipe: No error
go install -ldflags="-X main.Build=e60942a39d2485275cc75f9518932a8208dc5e2d" github.com/derekparker/delve/cmd/dlv
can't load package: package github.com/derekparker/delve/cmd/dlv: cannot find package "github.com/derekparker/delve/cmd/dlv" in any of:
        C:\Go\src\github.com\derekparker\delve\cmd\dlv (from $GOROOT)
        D:\Source\Golang\src\github.com\derekparker\delve\cmd\dlv (from $GOPATH)
Makefile:44: recipe for target 'install' failed
mingw32-make: *** [install] Error 1** "

**Comment by aarzilli** [comment]
If you run `uname` do you get anything?

**Comment by ngocthanhpham** [comment]
i got clone to my local driver D, please help me, i just study golang

**Comment by aarzilli** [comment]
Did you put it inside `D:\Source\Golang\src`?

**Comment by ngocthanhpham** [comment]
yes, my directory D:\Source\Golang\src\delve

**Comment by aarzilli** [comment]
It needs to be `D:\Source\Golang\src\github.com\derekparker\delve`. Please read this: https://golang.org/doc/code.html

**Comment by ngocthanhpham** [comment]
i do that but now it notify
" D:\Source\Golang\src\github.com\derekparker\delve>mingw32-make install
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make: Makefile:7: pipe: No error
process_begin: CreateProcess(NULL, uname, ...) failed.
mingw32-make: Makefile:22: pipe: No error
go install -ldflags="-X main.Build=e60942a39d2485275cc75f9518932a8208dc5e2d" github.com/derekparker/delve/cmd/dlv "

**Comment by aarzilli** [comment]
Did it build `dlv` in `D:\Source\Golang\bin\dlv`?

**Comment by ngocthanhpham** [comment]
yes, dlv.exe already but why it notify failed, i dont understand

**Comment by aarzilli** [comment]
Because `uname` doesn't exist on windows? I think this was already known. It shouldn't matter.
