### ISSUE TITLE
delve on window no support "step out", why?

### ISSUE THREAD

**Issue by luweijie007** [derekparker/delve#497]
I use delve as plugin of visual studio code 
 I dot not kown how to check version of delve on win7(who can tell me?)
 go version go1.6.1 windows/amd64
I can use "step into " into funtion
but I can not "step out" and print this log: Step out is not yet supported

Is that delve not support "step out" or I need to other?

**Comment by aarzilli** [comment]
Duplicate of #358.
Not implemented yet, I'm working on it.

**Comment by luweijie007** [comment]
@aarzilli thanks your answer and your work on this tools
