### ISSUE TITLE
when make  return error

### ISSUE THREAD

**Issue by liumuqi** [derekparker/delve#506]
past main
foo
hi 8
hi 7
hi 7
hi 6
--- FAIL: TestNextConcurrent (0.99s)
        proc_test.go:395: Program did not continue to correct next location expected 10 was panic.go:507
hi 7
hi 3
hi 1
hi 8
--- FAIL: TestNextConcurrentVariant2 (0.29s)
        proc_test.go:63: failed assertion at proc_test.go:435: EvalVariable - could not find symbol value for n
foo
Hello, World!
bye
hi
--- FAIL: TestCGONext (1.08s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x409d458]

goroutine 162 [running]:
panic(0x44d1800, 0xc82000a140)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc820158000)
        /usr/local/go/src/testing/testing.go:467 +0x192
panic(0x44d1800, 0xc82000a140)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/derekparker/delve/proc.(*Variable).parseG(0xc8201e00e0, 0xc8201e00e0, 0x0, 0x0)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/variables.go:373 +0x958
github.com/derekparker/delve/proc.(*Thread).GetG(0xc8202a7900, 0xc8202a7900, 0x0, 0x0)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/threads.go:321 +0x69
github.com/derekparker/delve/proc.(*Thread).SetCurrentBreakpoint(0xc8202a7900, 0x0, 0x0)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/threads.go:378 +0x18e
github.com/derekparker/delve/proc.(*Process).setCurrentBreakpoints(0xc8201e0540, 0xc8202a7900, 0x0, 0x0)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/proc_darwin.go:358 +0xa3
github.com/derekparker/delve/proc.(*Process).Continue(0xc8201e0540, 0x0, 0x0)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/proc.go:369 +0x20b
github.com/derekparker/delve/proc.TestCGONext.func1(0xc8201e0540, 0x4572110, 0x7, 0xc8207600f0, 0x41, 0xc820760550, 0x47)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/proc_test.go:635 +0x27e
github.com/derekparker/delve/proc.withTestProcess(0x4572110, 0x7, 0x4d04920, 0xc820158000, 0xc82077bf20)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/proc_test.go:43 +0x2fd
github.com/derekparker/delve/proc.TestCGONext(0xc820158000)
        /Users/lmq/golibs/src/github.com/derekparker/delve/proc/proc_test.go:643 +0xcd
testing.tRunner(0xc820158000, 0x47ec590)
        /usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:582 +0x892
FAIL    github.com/derekparker/delve/proc       12.262s
?       github.com/derekparker/delve/proc/test  [no test files]
?       github.com/derekparker/delve/scripts    [no test files]
?       github.com/derekparker/delve/service    [no test files]
?       github.com/derekparker/delve/service/api        [no test files]
?       github.com/derekparker/delve/service/debugger   [no test files]
?       github.com/derekparker/delve/service/rpc1       [no test files]
?       github.com/derekparker/delve/service/rpc2       [no test files]

**Comment by aarzilli** [comment]
What version of go are you using? What version of Mac OS X?

**Comment by derekparker** [comment]
@liumuqi there are a few tests on OSX which are flaky, which I have been working to fix. I'm going to close this issue as it does not provide much information. Feel free to open another issue regarding OSX test flaky-ness with more information, please.
