### ISSUE TITLE
[contrib] Homebrew formula

### ISSUE THREAD

**Issue by steeve** [derekparker/delve#508]
Hey folks,

I just did a formula to install delve via homebrew:
```
$ brew install steeve/delve/delve
```
or
```
$ brew install steeve/delve/delve --HEAD
```

The formula lives at https://github.com/steeve/homebrew-delve and I'd be happy to transfer if need be.

It generates and properly codesigns the binary using a cert named `dlv-cert`.

**Comment by ebenoist** [comment]
This works great! Thanks!

**Comment by aarzilli** [comment]
I took a look at the formula, I don't use OS X anymore and never used homebrew, but if I understand it correctly you aren't just downloading and signing delve, you are also creating the certificate if it doesn't exist. 

If that's correct I think this should at least be mentioned [in the documentation](https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md), a lot of people fail the certificate creation ritual.

**Comment by steeve** [comment]
I'll add it to the `README` of `homebrew-delve`.
However, the formula clearly says it when it creates and installs it:
https://github.com/steeve/homebrew-delve/blob/master/Formula/delve.rb#L37
https://github.com/steeve/homebrew-delve/blob/master/Formula/delve.rb#L43

Also, it will sudo, so it needs one's password.

**Comment by aarzilli** [comment]
I meant to say that it (i.e. installing with homebrew) should be mentioned in *our* (i.e. delve's) documentation, not yours. Thank you for doing this.

**Comment by derekparker** [comment]
Thanks for this, I appreciate you automating the signing process, that is huge for new users!

I'm interested in incorporating this in our documentation, and possibly moving the formula into this repo or (finally) creating an org for delve and having our own tap which includes this formula.

Do users have to tap anything currently in order to use your formula?

**Comment by steeve** [comment]
Thanks for the kind words

They can add the tap, but it is done with brew install

Nothing else to do than brew install really (as in doc)

I'd be happy to move the repo into the organization.

However, the formula cannot live in this repo, as the repo has to be
prefixed by "homebrew-". Org is fine though.

**Comment by derekparker** [comment]
@steeve I'm going to create an org next week (somebody has the username delve on github so I'm talking with him now about letting us grab that for an org name), and then it would be great to transfer the formula to the org.

**Comment by steeve** [comment]
Sounds like a plan, ready when you are

**Comment by derekparker** [comment]
@steeve I've created the `go-delve` org which I plan on moving the Delve repo over to this week. Can you transfer the homebrew formula over to that org? Then we need to make sure the docs are up to date and start pushing for folks to use the formula in all our official documentation.

**Comment by steeve** [comment]
Sure thing

**Comment by steeve** [comment]
@derekparker you will need to add me to the org so that I can transfer it

**Comment by derekparker** [comment]
@steeve invitation sent.

**Comment by steeve** [comment]
There we go: https://github.com/go-delve/homebrew-delve

**Comment by derekparker** [comment]
@steeve awesome! Would you mind updating https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md with brew install instructions?

**Comment by derekparker** [comment]
@steeve I have a PR up now to update OSX install docs: https://github.com/derekparker/delve/pull/544

**Comment by steeve** [comment]
LGTM ! Sorry about the lag, we launched our app last week :)
