### ISSUE TITLE
command/debug: Unexpected error when 'main' package doesn't exist in current directory

### ISSUE THREAD

**Issue by robpike** [derekparker/delve#509]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 0.11.0-alpha
Build: f454207a340cc6b16b69f5924c647938b3c1a771
2. What version of Go are you using? (`go version`)?
go version devel +b57ac33 Wed Apr 20 15:31:42 2016 +0000 darwin/amd64
3. What operating system and processor architecture are you using?
darwin/amd64
4. What did you do?
cd go/src/fmt; dlv debug
5. What did you expect to see?
A working debugger.
6. What did you see instead?

Here is the trace. Note that I can do 'dlv exec' if I build the binary, and it works great, but 'dlv debug' gives me the dreaded fork/exec error. This makes me think it might be an actual bug rather than a codesigning issue.

dunnart=% dlv debug
could not launch process: could not fork/exec
dunnart=% dlv exec fmt.test
Type 'help' for list of commands.
(dlv) r
Process restarted with PID 85560
(dlv) break main.main
Breakpoint 1 set at 0x21a3 for main.main() fmt/_test/_testmain.go:192
(dlv) continue
> main.main() fmt/_test/_testmain.go:192 (hits goroutine(1):1 total:1) (PC: 0x21a3)
(dlv) stack
0  0x00000000000021a3 in main.main
   at fmt/_test/_testmain.go:192
1  0x0000000000027855 in runtime.main
   at /Users/r/go/src/runtime/proc.go:188
2  0x00000000000504b0 in runtime.goexit
   at /Users/r/go/src/runtime/asm_amd64.s:2013
(dlv) quit
dunnart=%

**Comment by aarzilli** [comment]
Just tested this with go1.6.1 and I think the problem is just that there is no main in go/src/fmt. `dlv test` should be used instead of `dlv debug` (the error message could use improvement, though).

**Comment by steeve** [comment]
In case this is a code signing issue, I made a homebrew formula that solves it once and for all at https://github.com/derekparker/delve/issues/508

**Comment by derekparker** [comment]
@aarzilli sounds right, we need to do a better job of detecting this and reporting the error.

@steeve although this isn't a codesign issue, I appreciate your work in packaging Delve for HomeBrew! Should hopefully make it easier for folks to get started with Delve on OSX. Also, for the next release we plan on including binaries along with the release, and hope to include a binary for OSX signed with an Apple Developer cert, which should remove all burden on the user for any codesigning tasks.
