### ISSUE TITLE
area/cli: Frame command has inaccurate/incomplete docs and should have different UX

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#510]
The current help output contains the following for frame:

`frame ----------------------- Sets current stack frame (0 is the top of the stack)`.

It does not mention that the command in fact accepts 2 arguments, both of which are (currently) required. We need to update the help output, and additionally I think it's worth taking a look at how the `frame` command behaves.

For instance, currently it requires a frame number and a command to execute within the context of that frame, but that is not mentioned at all in the help output. We should also allow that command to be used without a second argument to change the frame used in the internal command scope we use as the commands scope context.

I believe it used to work that way, and was changed, possibly at my behest, so my apologies if this is a change I suggested, but did not follow through on ensuring documentation was updated.

**Comment by derekparker** [comment]
cc: @aarzilli

**Comment by aarzilli** [comment]
This is the old discussion about this: https://github.com/derekparker/delve/pull/205.
