### ISSUE TITLE
ListLocalVars potentially broken when using API v2

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#513]
1. What version of Delve are you using (`dlv version`)? c4e01da5cab0afbf895d7513b5fdc514c06e20f2
2. What version of Go are you using? (`go version`)? go1.6.2 linux/amd64
3. What operating system and processor architecture are you using? Kubuntu 16.04 amd64
4. What did you do? Running ListLocalVars from RPC server via API v2
5. What did you expect to see? String values when running the call
6. What did you see instead? Empty string

From what I could see, the value is there in the breakpoint when it's hit, but running ListLocalVars will not produce it.

To debug this you can use IntelliJ Idea 2016.1 and install the plugin from here: https://www.dropbox.com/s/f5snw3cfbfua855/Go-0.11.SNAPSHOT-delve.zip?dl=0

The code I use to debug this is at `go get github.com/dlsniper/u` in ` dbg/3/demo3.go `. You can set a breakpoint there and run it. Unfortunately I have no other means to reproduce it.

The response the plugin gets from delve is always like this:

```
{"id":4,"result":{"Variables":[
{"name":"e","addr":859530616304,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":5,"cap":0,"children":[],"unreadable":""},
{"name":"d","addr":859530616320,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":5,"cap":0,"children":[],"unreadable":""},
{"name":"c","addr":859530616336,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":5,"cap":0,"children":[],"unreadable":""},
{"name":"b","addr":859530616352,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":5,"cap":0,"children":[],"unreadable":""},
{"name":"a","addr":859530616528,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":5,"cap":0,"children":[],"unreadable":""}
]},"error":null}
```

I've tried sending a `LoadConfig.MaxStringLen = 100` but I've got nothing (or tried sending the defaults, same issue).

Thank you.

**Comment by dlsniper** [comment]
This also seems to be the case only for strings, ints, structs and other types are working correctly.

**Comment by dlsniper** [comment]
Scratch that. Structs are also affected by an issue, they are reported like this:

```
{"id":8,"result":{"Variables":[
{"name":"c","addr":859530616328,"onlyAddr":false,"type":"struct struct { Demo bool; Demo2 float32 }","realType":"struct struct { Demo bool; Demo2 float32 }","kind":25,"value":"","len":2,"cap":0,"children":[],"unreadable":""},
{"name":"b","addr":859530616336,"onlyAddr":false,"type":"int","realType":"int","kind":2,"value":"123","len":0,"cap":0,"children":[],"unreadable":""},
{"name":"e","addr":859530616368,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":0,"cap":0,"children":[],"unreadable":""},
{"name":"d","addr":859530616384,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":4697234,"cap":0,"children":[],"unreadable":""},
{"name":"a","addr":859530616528,"onlyAddr":false,"type":"string","realType":"string","kind":24,"value":"","len":5,"cap":0,"children":[],"unreadable":""}
]},"error":null}
```

**Comment by aarzilli** [comment]
Wireshark says your plugin is sending this request:

```
{"method":"RPCServer.ListLocalVars","params":[{"Scope":{"GoroutineID":1,"Frame":0}}],"id":5}
```

for comparison this is the request sent by our frontend (without -v):

```
{"method":"RPCServer.ListLocalVars","params":[{"Scope":{"GoroutineID":-1,"Frame":0},"Cfg":{"FollowPointers":false,"MaxVariableRecurse":0,"MaxStringLen":64,"MaxArrayValues":0,"MaxStructFields":3}}],"id":3}
```

Also you may want to know that both the requests for ListLocalVars and ListFunctionArgs are repeated twice every time.

**Comment by dlsniper** [comment]
Hi, thanks for feedback. 
What is / where is / how can I run this frontend you've mentioned? It could be useful to compare the implementation parts.
I'll test out the same values that you suggested but I'm not sure if it will help (iirc I've done something similar). 
As for sending the requests twice, that's the IDE itself doing it but it should still not affect how we get the values back.
I'll reply by tonight with an update. 
Thanks.

**Comment by aarzilli** [comment]
`dlv` in normal mode (not headless) is the frontend in question. It still runs the server and uses api v2.
If you notice the Cfg field is completely missing from the requests your plugin is sending.

**Comment by dlsniper** [comment]
> If you notice the Cfg field is completely missing from the requests your plugin is sending. 

That's correct, the copy I've provided doesn't sebd those. Before opening the issue I did tried with those values as well but maybe I did something wrong. I'll check it again, make sure I send the same request and see what happens. 
Thanks.

**Comment by dlsniper** [comment]
I've had a quick look at this in the train and the situation improves a bit
sending those. I get back the values for the struct (even if they are
broken, they display the type of fields not the value of fields for
structs).
Unfortunately for strings this stays the same.
I've uploaded the new build of the plugin the same place (and pushed the
code for it).
Thanks.

**Comment by aarzilli** [comment]
This is what Wireshark shows me now:

```
{"method":"RPCServer.ListLocalVars","params":[{"Scope":{"GoroutineID":-1,"Frame":0,"Cfg":{"FollowPointers":false,"MaxStringLen":64,"MaxVariableRecurse":0,"MaxArrayValues":0,"MaxStructFields":3}}}],"id":4}
```

The Cfg parameter is inside the Scope parameter when it should be a sibling:

```
{
    "method": "RPCServer.ListLocalVars",
    "params": [
        {
            "Scope": {
                "GoroutineID": -1,
                "Frame": 0,
                "Cfg": {
                    "FollowPointers": false,
                    "MaxStringLen": 64,
                    "MaxVariableRecurse": 0,
                    "MaxArrayValues": 0,
                    "MaxStructFields": 3
                }
            }
        }
    ],
    "id": 4
}
```

**Comment by dlsniper** [comment]
Oh my... I'm stupid.
Indeed that's working. Ok, false alarm then. Thank you for helping out.
As for the values of the struct, I guess we need to do a better job on client side to represent those as this is something that happens in v1 as well.
Thank you once again for being so responsive.
Have an excellent week.
