### ISSUE TITLE
Failed to continue: "Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`."

### ISSUE THREAD

**Issue by shehantissera** [derekparker/delve#514]
I am new to VSCode. I want to debug Golang with **Delve**. I have been searching for days about this issue and there is no proper documentation where I could get this working.

I have installed the required components as displayed on the following link [here](https://github.com/derekparker/delve/blob/master/Documentation/installation/windows/install.md).

Finally on the instructions it says;
2) Make and install the dlv binary
`$ mingw32-make install`

This seems to fail. the error I am getting on the command prompt is:
> mingw32-make: *** No rule to make target 'install'.  Stop.

Has anybody gone through this already? Please I need help.

**Comment by aarzilli** [comment]
You probably just need to run the command from `%GOPATH%/src/github.com/derekparker/delve/`

**Comment by alexbrainman** [comment]
If you run
```
go get github.com/derekparker/delve/cmd/dlv
```
it will build dlv.exe and copy it into your %GOPATH%\bin directory.

Once that works, you would have to add %GOPATH%\bin directory to you PATH so VSCode (and other programs) can find dlv.exe. Alternatively you could copy dlv.exe from %GOPATH%\bin into another directory that is already in your PATH.

Alex

**Comment by shehantissera** [comment]
Thanks **alexbrainman!** that worked!! This part is not available in any of the links I checked.

**Comment by jay763190097** [comment]
Thanks @alexbrainman ! it worked!!

**Comment by ehouarn-perret** [comment]
Still having this error:.. aw

My environment variables
```
GOPATH=C:\Users\ehoua\go
Path=[...];;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Go\bin;C:\Users\ehoua\go\bi
```
I setup dvelve as suggested in many websites:
`go get github.com/derekparker/delve/cmd/dlv`

dlv.exe is located in `C:\Users\ehoua\go\bin`

My visual studio code Go files are located in:
`C:\Users\ehoua\Desktop\Github\EhouarnPerret.Go.Tour`

But when attempting to debug a simple such as `hello.go`:
```
package main

import "fmt"

func main() {
	name := "Michelle"
	fmt.Println("Hello", name)
}

```

Still getting:
```
Failed to continue: "Cannot find Delve debugger. 
Ensure it is in your `GOPATH/bin` or `PATH`."
```

Any idea?

**Comment by vitordm** [comment]
thanks @alexbrainman;  it worked!!

I just want to remind everyone, its need to configurate on your OS the "GOPATH" as @ehouarn-perret said.

**Comment by liuwenjincoco** [comment]
@ehouarn-perret ，I have the same problem as you。Did you solve it?

**Comment by ManishJainGitHubUser** [comment]
https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code

could not launch process: exec: "lldb-server": executable file not found in $PATH
This error can show up for Mac users using delve of version 0.12.2 or above. Not sure why, but doing a xcode-select --install has solved the problem for users who have seen this issue.

**Comment by bhabermaas** [comment]
I have tried just about everything to solve this on macOS
1. If I type dlv version in a terminal window I get the right version back
2. dlv is in ~/go/bin
3. PATH includes ~/go/bin
4. GOPATH is set to ~/go
5. I have added same PATH information in launch.json

Apparently vscode is loading this from someplace else
