### ISSUE TITLE
disasm.go:9: undefined: ArchInst

### ISSUE THREAD

**Issue by moolo** [derekparker/delve#516]
disasm.go:9: undefined: ArchInst

why??

**Comment by derekparker** [comment]
Please provide more details including your operating system and CPU architecture. Please use the provided template when creating issues next time.

**Comment by derekparker** [comment]
Going to close this issue as it does not provide enough information. Please feel free to open a new issue providing all information outlined in the (template)[https://github.com/derekparker/delve/blob/master/ISSUE_TEMPLATE.md].
