### ISSUE TITLE
OS X El Capitan install instructions ambiguity

### ISSUE THREAD

**Issue by dr2chase** [derekparker/delve#517]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
1. What version of Delve are you using (`dlv version`)?
   Version: 0.11.0-alpha
   Build: c4e01da5cab0afbf895d7513b5fdc514c06e20f2
2. What version of Go are you using? (`go version`)?
   go version devel +4d27f8e Tue Apr 26 11:59:01 2016 -0400 darwin/amd64
3. What operating system and processor architecture are you using?
   OS X El Capitan 10.11.4, Intel Core i7
4. What did you do?
   Following installation instructions at
   https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md
   I saw 
   [At least on Yosemite:] In keychains select category Keys -> dlv-cert -> right click -> GetInfo -> Access Control -> select "Allow all applications to access this item" -> Save Changes.
5. What did you expect to see?
   In Keychain Access, I expected to see a single choice of "dlv-cert" to right click.
6. What did you see instead?
   In Keychain Access, I saw two choices, the public dlv-cert key and the private dlv-cert key.
   The public key was already "allow all application to access this item", the private key is the private key, is that really the one I'm supposed to allow all applications to access?

**Comment by aarzilli** [comment]
Do you have homebrew? If you do: https://github.com/derekparker/delve/issues/508

**Comment by russmack** [comment]
It would be good to get that little bit of clarity on that little ambiguity, 'cos at the moment:
Can't brew info.
brew install fails at ==> make build BUILD_SHA=v0.11.0 with a number of missing packages.
brew install adds another, older, Go to my system, which I'd rather not.
