### ISSUE TITLE
Tests hanging / failing on OSX Yosemite

### ISSUE THREAD

**Issue by fsomers** [derekparker/delve#519]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
1. What version of Delve are you using (`dlv version`)?
   Version: 0.11.0-alpha
   Build: c4e01da5cab0afbf895d7513b5fdc514c06e20f2
2. What version of Go are you using? (`go version`)?
   go version go1.6.2 darwin/amd64
   (via homebrew)
3. What operating system and processor architecture are you using?
   OSX 10.10.5 (Yosemite)
   $ uname -a
   Darwin fsomers.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64
4. What did you do?
   $ CERT=dlv-cert make test
   Supply username/ pass 7-10 times. The process is correct; I repeat this for updates on a regular basis, and has worked with previous versions.
5. What did you expect to see?
   Tests should pass.
6. What did you see instead?
   Tests hang after 
   ...
   ?       github.com/derekparker/delve/dwarf/reader   [no test files]
   ok      github.com/derekparker/delve/dwarf/util 22.956s

Annoyingly, if I try to capture test output to logfile (CERT=dlv-cert make test 2>&1 | tee log), they hang every time.

Running to console output, they usually fail resulting in output in attached text file, followed by a hang rather than returning to the prompt. See: 
[dlv-test-failures.txt](https://github.com/derekparker/delve/files/240290/dlv-test-failures.txt)

**Comment by derekparker** [comment]
Thanks for reporting this. I'm working on some patches / refactoring right now that should clean up the test flakyness on OSX. I hope to resolve this issue shortly.

**Comment by derekparker** [comment]
Test runs are green now on master with new pluggable backends.
