### ISSUE TITLE
disasm.go:9: undefined: ArchInst

### ISSUE THREAD

**Issue by aodota** [derekparker/delve#535]
i install delve on my windows, i get this

1. go version: go version go1.5.2 windows/386
2. my system is: win10 64bit 1511
3. when i run `go get github.com/derekparker/delve/cmd/dlv` i got this error

please help me

**Comment by aarzilli** [comment]
We do not support 32bit systems, if you have 64bit windows you should also get the 64bit version of go.

**Comment by aodota** [comment]
thank you very much~
