### ISSUE TITLE
fork/exec permission denied

### ISSUE THREAD

**Issue by devtoro** [derekparker/delve#538]
Hello all, 

I have installed GO 1.6 on an ubuntu gnome 15 machine, along with the latest version of delve. I am trying to to run **godebug run < go file >** and I get the following result: 

`fork/exec /home/manolis/crypteia/gospace/src/tmp/godebug870803687/godebug.a.out: permission denied`

Any suggestions why this might happen? ( As you can see I changed the TEMPDIR, hoping that this issues will be solved, but with no luck )

**Comment by aarzilli** [comment]
godebug isn't delve, though...

**Comment by derekparker** [comment]
Closing this issue as not related to Delve. Feel free to try Delve out though and see if you have better luck!
