### ISSUE TITLE
Cannot run delve

### ISSUE THREAD

**Issue by zefciu** [derekparker/delve#540]
I am running delve Version: 0.11.0-alpha and go go1.6.1 linux/amd64 on ubuntu. I am trying to debug kubectl in kubernetes. I have GOPATH set to /home/spyzalski/Projekty. k8s in downloaded to /home/spyzalski/Projekty/src/k8s.io/kubernetes When I try to run:
`dlv debug`
in /home/spyzalski/Projekty/src/k8s.io/kubernetes/pkg/kubectl i get:
`could not launch process: fork/exec ./debug: permission denied`
I tried to move my TMPDIR to user directory or event inside my GOPATH, but it didn't help. What can be the reason for my problem?

**Comment by aarzilli** [comment]
Looking at kubernetes in github it doesn't look like that path contains a main package, you need to find the place where main is.

**Comment by zefciu** [comment]
Yep. The main function is in cmd/kubectl, not in pkg/kubectl. Thank you
