### ISSUE TITLE
Permission denied error on debug

### ISSUE THREAD

**Issue by devtoro** [derekparker/delve#541]
##Hello,

I am running on Ubuntu Gnome 15, GO 1.6 and I have installed delve as suggested on the installation page. I try to debug using the command "dlv debug <script_file_name> and I get a permission denied error.

`dlv debug ruleset.go`
`could not launch process: fork/exec ./debug: permission denied`

I believe I did not miss anything during installation. Any suggestions?

**Comment by aarzilli** [comment]
The argument of debug is a package, not a file.

**Comment by cbisnett** [comment]
@devtoro Are you running this inside a docker container? If so check out this issue for the answer: https://github.com/derekparker/delve/issues/515.

**Comment by derekparker** [comment]
@devtoro I've added some more language to the help output to clarify the usage of the commands: https://github.com/derekparker/delve/pull/543.

**Comment by devtoro** [comment]
No I am not running inside docker. Just ubuntu gnome installation on my laptop. I tried using the package as an arguement, still the same output.

Even if I run just `dlv debug`, with no arguments ( then I suppose the main  package of the directory I am in should start being debugged ), I still get the same error 

`dlv debug`
`could not launch process: fork/exec ./debug: permission denied`

I don't quite get it. Even if I export a new TEMPDIR, the result is still the same..

**Comment by aarzilli** [comment]
@devtoro are you sure there is a main package in your current directory? If you run `go build` in that directory do you get an executable?

**Comment by aarzilli** [comment]
Closing this since no further info was provided and the problem was likely that the package in the current directory wasn't main (a problem that was addressed in a different issue).
