### ISSUE TITLE
Dlv commands failing: error derefing *G Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

### ISSUE THREAD

**Issue by andrewrgoss** [derekparker/delve#546]
I am experiencing errors when using the Delve debugger for Go on my Windows machine. To install, I used the standard `go get` method: `go get github.com/derekparker/delve/cmd/dlv`
per the documentation for Windows: https://github.com/derekparker/delve/blob/master/Documentation/installation/windows/install.md
- I am using the following version of Delve:

```
$ dlv version
Delve Debugger
Version: 0.11.0-alpha
```
- I am using this Go version: `go version go1.5.1 windows/amd64`

I created a (very) simple Go program to simply test `dlv` debugging on:

``` go
package main

import (
    "log"
    "time"
)

func main() {
    now := time.Now()
    log.Println("yyyy-mm-dd date format : ", now.Format("2006-01-02"))
}
```

When using Atom or Visual Studio Code with Go extensions, the interactive debugging features that rely on Delve do not work - it's not possible to actually step into any code. This is the output console from Atom:

```
Starting delve with "C:\Users\andgoss\GoLangCode\src\_ag_working\debugging\gocode_print_yyyymmdd.go" with "debug"
Delve output: 2016/05/19 11:08:46 server.go:41: Using API v1
2016/05/19 11:08:46 debugger.go:61: launching process with args: [./debug]
Started delve with "C:\Users\andgoss\GoLangCode\src\_ag_working\debugging\gocode_print_yyyymmdd.go" with "debug"
Adding breakpoint: C:\Users\andgoss\GoLangCode\src\_ag_working\debugging\gocode_print_yyyymmdd.go:25
API server listening at: 127.0.0.1:2345
Delve output: 2016/05/19 11:08:46 debugger.go:235: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x401066, File:"C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go", Line:25, FunctionName:"main.main", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
Added breakpoint: C:\Users\andgoss\GoLangCode\src\_ag_working\debugging\gocode_print_yyyymmdd.go:25
Executing command step
Delve output: 2016/05/19 11:08:58 debugger.go:413: stepping
```

When trying to run `dlv` through the command line I get the following errors, which are quite vague:

```
$ dlv debug
Type 'help' for list of commands.
break main.main
Breakpoint 1 set at 0x40105f for main.main() C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go:23
next
Command failed: error derefing *G Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
continue
Stopped at: 0x7fefd6ba06d
=>no source available
```

Any ideas on why I am getting these errors and what can be done to fix them so I can properly use `dlv`?

**Comment by lukehoban** [comment]
I don't see any actual bugs here.  The trace of `dlv` running just shows the expected error because Delve starts paused before executing any code, so you can't use `next` yet.  I think there was an issue tracking whether that's the ideal behaviour and/or error message (it seems to confuse a lot of users).

You mention debugging problems in Atom/VSCode as well, but not clear those are related.

```
c:\Users\Luke\dd\go\src\github.com\lukehoban\test>dlv debug
Type 'help' for list of commands.
(dlv) c
2016/05/29 14:36:02 yyyy-mm-dd date format :  2016-05-29
Process 4644 has exited with status 0
(dlv)
```

**Comment by aarzilli** [comment]
It seems that on `continue` he's getting the:

```
Stopped at: 0x7fefd6ba06d
=>no source available
```

like #556.

**Comment by andrewrgoss** [comment]
@aarzilli @lukehoban that is precisely it, exactly like [#556](https://github.com/derekparker/delve/issues/556). again, this is a very vague error so I have no idea how to troubleshoot it:

```bash
/cygdrive/c/Users/andgoss/GoLangCode/src/_ag_working/debugging
$ dlv debug
Type 'help' for list of commands.
c
Stopped at: 0x7fefdb0a06d
=>no source available
```

**Comment by aarzilli** [comment]
@andrewrgoss if you run a `go build` in the same directory the executable you get is 32bit or 64bit?

**Comment by andrewrgoss** [comment]
The executable file is 64bit, as is my machine:

```
$ file gocode_print_yyyymmdd.exe
gocode_print_yyyymmdd.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by alexbrainman** [comment]
@andrewrgoss please post copy of gocode_print_yyyymmdd.exe somewhere so we could try debugging it on our computers. Thank you.

Alex

**Comment by andrewrgoss** [comment]
I posted a copy of the code when I first opened this issue, but here it is again. It is a very simple program, I just wanted to test `dlv` on it:

```go
package main

import (
    "log"
    "time"
)

func main() {
    now := time.Now()
    log.Println("yyyy-mm-dd date format : ", now.Format("2006-01-02"))
}
```

**Comment by aarzilli** [comment]
@andrewrgoss the compiled executable, not the source.

**Comment by andrewrgoss** [comment]
Compiled .exe is in this .zip file:
[gocode_print_yyyymmdd.zip](https://github.com/derekparker/delve/files/352244/gocode_print_yyyymmdd.zip)

**Comment by alexbrainman** [comment]
Thanks for the exe. I can reproduce the issue if I change my delve version to v0.11.0-alpha

```
c:\dev\src\github.com\derekparker\delve\cmd\dlv>git checkout v0.11.0-alpha
HEAD is now at 6774a6c... all: Bump to version 0.11.0-alpha

c:\dev\src\github.com\derekparker\delve\cmd\dlv>go build

c:\dev\src\github.com\derekparker\delve\cmd\dlv>dlv exec u:\gocode_print_yyyymmdd.exe
Type 'help' for list of commands.
(dlv) break main.main
Breakpoint 1 set at 0x401066 for main.main C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go:25
(dlv) next
Command failed: error derefing *G could not read memory
(dlv) continue
> main.main() C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go:25 (hits goroutine(1):1 total:1)
(dlv) continue
2016/07/08 15:28:02 yyyy-mm-dd date format :  2016-07-08
Process 3972 has exited with status 0
(dlv) quit
Process 3972 has exited with status 0
```

The `error derefing *G could not read memory` message is not the same, but close enough (I suspect you are running sligtly different version of delve).

If I update to the current tip:

```
c:\dev\src\github.com\derekparker\delve\cmd\dlv>git checkout master
Previous HEAD position was 6774a6c... all: Bump to version 0.11.0-alpha
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

c:\dev\src\github.com\derekparker\delve\cmd\dlv>go build

c:\dev\src\github.com\derekparker\delve\cmd\dlv>dlv exec u:\gocode_print_yyyymmdd.exe
Type 'help' for list of commands.
(dlv) break main.main
Breakpoint 1 set at 0x40105f for main.main() C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go:23
(dlv) next
Command failed: could not find FDE for PC 0x77af8aa1
(dlv) continue
> main.main() C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go:23 (hits goroutine(1):1 total:1) (PC: 0x40105f)
(dlv) continue
2016/07/08 15:30:00 yyyy-mm-dd date format :  2016-07-08
Process 4972 has exited with status 0
(dlv) quit
Process 4972 has exited with status 0

c:\dev\src\github.com\derekparker\delve\cmd\dlv>
```

So the error message looks different - `could not find FDE for PC 0x77af8aa1`. I don't understand what new message means, but I suspect this is something expected. I also don't understand what is the point of issuing `next` command at the start. You, probably, just want to do `continue` once you set breakpoint and debugger will run your program until breakpoint hits.

So I am not sure if there is anything to do here for your command line session (displayed above). But your original problem seems to be using delve with Atom or Visual Studio Code. I have no idea what these do under covers. Maybe you should update your delve to the latest version:
```
go get -u github.com/derekparker/delve/cmd/dlv
```
and try again. A lot of code changed since v0.11.0-alpha.

Alex

**Comment by andrewrgoss** [comment]
Tried updating to the latest version of `delve` and the problem remains the same as when I first opened this issue: it is not possible to step into any code using the debugger. I'm trying this with VS code, so like you said it must be a problem with the extension @lukehoban created:

```
2016/07/18 11:09:42 server.go:71: Using API v1
2016/07/18 11:09:42 debugger.go:61: launching process with args: [./debug]
API server listening at: 127.0.0.1:2345
2016/07/18 11:09:42 debugger.go:238: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x40108f, File:"C:/Users/andgoss/GoLangCode/src/_ag_working/debugging/gocode_print_yyyymmdd.go", Line:26, FunctionName:"main.main", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2016/07/18 11:09:42 debugger.go:393: continuing
```

**Comment by andrewrgoss** [comment]
I think the core of the problem lies with the `delve` configuration on my machine as it doesn't work through the command line interface either:

```bash
$ dlv debug
Type 'help' for list of commands.
(dlv) c
Command failed: command not available
c
Stopped at: 0x7fefcc4a06d
=>no source available
```

**Comment by alexbrainman** [comment]
> Command failed: command not available

That is not what I am seeing here (with current version of delve). I see this:
```
c:\>cd %GOPATH%\src\github.com\derekparker\delve\cmd\dlv

c:\dev\src\github.com\derekparker\delve\cmd\dlv>git remote -v
origin  https://github.com/derekparker/delve (fetch)
origin  https://github.com/derekparker/delve (push)

c:\dev\src\github.com\derekparker\delve\cmd\dlv>git pull
Already up-to-date.

c:\dev\src\github.com\derekparker\delve\cmd\dlv>git rev-parse HEAD
16f16cf86d4b1ce7e10c7de52389dc1268b63bc5

c:\dev\src\github.com\derekparker\delve\cmd\dlv>git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

c:\dev\src\github.com\derekparker\delve\cmd\dlv>go install

c:\dev\src\github.com\derekparker\delve\cmd\dlv>type %GOPATH%\src\t\main.go
package main

import "fmt"

func main() {
        fmt.Printf("Hello\n")
}

c:\dev\src\github.com\derekparker\delve\cmd\dlv>%GOPATH%\bin\dlv.exe debug %GOPATH%\src\t\main.go
Type 'help' for list of commands.
(dlv) c
Hello
Process 2284 has exited with status 0
(dlv) q
Process 2284 has exited with status 0

c:\dev\src\github.com\derekparker\delve\cmd\dlv>
```

Please, run the commands, just like I did, and show us what your output is. Thank you.

Alex

**Comment by aarzilli** [comment]
@andrewrgoss your `$` prompt looks unusual for a windows box. Are you using some kind of terminal emulator? Can you try using cmd.exe?

**Comment by andrewrgoss** [comment]
I had been using Cygwin as a terminal emulator, but even when running this through the standard Windows command prompt I get the same error:

```
C:\Users\andgoss\GoLangCode\bin>dlv.exe debug %GOPATH%\src\_ag_working\debugging\gocode_print_yyyymm
dd.go
Type 'help' for list of commands.
(dlv) c
Stopped at: 0x7fefd7fa06d
=>no source available
(dlv) q
```

**Comment by andrewrgoss** [comment]
I was able to resolve this issue several months ago by reinstalling Delve altogether - it had originally conflicted with an existing library in the first installation. The cryptic error message wasn't too helpful obviously - figured out the underlying problem through guess-and-check basically. Closing this issue now.
