### ISSUE TITLE
The arrow points to the same line of code twice.

### ISSUE THREAD

**Issue by NanXiao** [derekparker/delve#550]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
1. What version of Delve are you using (`dlv version`)? 
   0.11.0-alpha.
2. What version of Go are you using? (`go version`)? 
   go1.6.2.
3. What operating system and processor architecture are you using?
   linux/amd64.
4. Issue:
   I debug the following program in step mode:  

```
package main

import (
    "fmt"
)

func addTail(s []int)  {
    var ns [][]int
    for _, v := range []int{1, 2} {
        ns = append(ns, append(s, v))
    }
    fmt.Println(ns)
}

func main() {
    s1 := []int{0, 0}
    s2 := append(s1, 0)

    for _, v := range [][]int{s1, s2} {
        addTail(v)
    }
}

```

I set breakpoint on `addTail` function, and find in step mode, the arrow points to `ns = append(ns, append(s, v))` twice. I don't think it make sense:

```
(dlv) b addTail
Breakpoint 1 set at 0x40101b for main.addTail() ./sl.go:7
(dlv) c
> main.addTail() ./sl.go:7 (hits goroutine(1):1 total:1) (PC: 0x40101b)
     2:
     3: import (
     4:     "fmt"
     5: )
     6:
=>   7: func addTail(s []int)  {
     8:     var ns [][]int
     9:     for _, v := range []int{1, 2} {
    10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
(dlv) n
> main.addTail() ./sl.go:8 (PC: 0x401022)
     3: import (
     4:     "fmt"
     5: )
     6:
     7: func addTail(s []int)  {
=>   8:     var ns [][]int
     9:     for _, v := range []int{1, 2} {
    10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
(dlv) n
> main.addTail() ./sl.go:9 (PC: 0x40103c)
     4:     "fmt"
     5: )
     6:
     7: func addTail(s []int)  {
     8:     var ns [][]int
=>   9:     for _, v := range []int{1, 2} {
    10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
    14:
(dlv) n
> main.addTail() ./sl.go:10 (PC: 0x401102)
     5: )
     6:
     7: func addTail(s []int)  {
     8:     var ns [][]int
     9:     for _, v := range []int{1, 2} {
=>  10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
    14:
    15: func main() {
(dlv) n
> main.addTail() ./sl.go:10 (PC: 0x40139c)
     5: )
     6:
     7: func addTail(s []int)  {
     8:     var ns [][]int
     9:     for _, v := range []int{1, 2} {
=>  10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
    14:
    15: func main() {
(dlv) n
> main.addTail() ./sl.go:9 (PC: 0x401217)
     4:     "fmt"
     5: )
     6:
     7: func addTail(s []int)  {
     8:     var ns [][]int
=>   9:     for _, v := range []int{1, 2} {
    10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
    14:
(dlv) n
> main.addTail() ./sl.go:10 (PC: 0x401102)
     5: )
     6:
     7: func addTail(s []int)  {
     8:     var ns [][]int
     9:     for _, v := range []int{1, 2} {
=>  10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
    14:
    15: func main() {
(dlv) n
> main.addTail() ./sl.go:10 (PC: 0x40139c)
     5: )
     6:
     7: func addTail(s []int)  {
     8:     var ns [][]int
     9:     for _, v := range []int{1, 2} {
=>  10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
    14:
    15: func main() {
(dlv) n
> main.addTail() ./sl.go:9 (PC: 0x401217)
     4:     "fmt"
     5: )
     6:
     7: func addTail(s []int)  {
     8:     var ns [][]int
=>   9:     for _, v := range []int{1, 2} {
    10:         ns = append(ns, append(s, v))
    11:     }
    12:     fmt.Println(ns)
    13: }
    14:
(dlv) q

```

**Comment by hyangah** [comment]
I couldn't reproduce the same problem with the program any more. Probably it's because Go produces different code now. However, the similar problem still exists. 

 Delve version: 1.0.0-rc.1
 Go version: go1.8

Test Program:
<pre>
$ cat /tmp/sketch.go
package main

import (
	"fmt"
	"sync/atomic"
)

var inited uint32

func main() {

	if atomic.LoadUint32(&inited) != 0 {
		return
	}
	if !atomic.CompareAndSwapUint32(&inited, 0, 1) {
		panic("main called twice???")
	}
	fmt.Println("inited = %v", atomic.LoadUint32(&inited))
}
</pre>

In the following session log, we can see the line 12 visited twice.

<pre>

$ dlv exec ./sketch
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x47c4f8 for main.main() /tmp/sketch.go:10
(dlv) c
> main.main() /tmp/sketch.go:10 (hits goroutine(1):1 total:1) (PC: 0x47c4f8)
     5:		"sync/atomic"
     6:	)
     7:	
     8:	var inited uint32
     9:	
=>  10:	func main() {
    11:	
    12:		if atomic.LoadUint32(&inited) != 0 {
    13:			return
    14:		}
    15:		if !atomic.CompareAndSwapUint32(&inited, 0, 1) {
(dlv) s
> main.main() /tmp/sketch.go:12 (PC: 0x47c50f)
     7:	
     8:	var inited uint32
     9:	
    10:	func main() {
    11:	
=>  12:		if atomic.LoadUint32(&inited) != 0 {
    13:			return
    14:		}
    15:		if !atomic.CompareAndSwapUint32(&inited, 0, 1) {
    16:			panic("main called twice???")
    17:		}
(dlv) s
> main.main() /tmp/sketch.go:12 (PC: 0x47c52f)
     7:	
     8:	var inited uint32
     9:	
    10:	func main() {
    11:	
=>  12:		if atomic.LoadUint32(&inited) != 0 {
    13:			return
    14:		}
    15:		if !atomic.CompareAndSwapUint32(&inited, 0, 1) {
    16:			panic("main called twice???")
    17:		}
</pre>
Looking into disassembler output, it seems the non-linear source line number info is related to this.
Both PC 0x47c50f and 0x47c52f (branched from 0x47c51d) belong to sketch.go:12, but they are not adjacent. I think we need to make delve handle such cases and continue until the next instruction with different source location is met.

<pre>
(dlv) disass
...
	sketch.go:10	0x47c507	488dac24c0000000		lea rbp, ptr [rsp+0xc0]
	sketch.go:12	0x47c50f	8b0d4ba80900			mov ecx, dword ptr [rip+0x9a84b]
	sketch.go:12	0x47c515	894c243c			mov dword ptr [rsp+0x3c], ecx
	sketch.go:12	0x47c519	85c9				test ecx, ecx
	sketch.go:12	0x47c51b	7502				jnz 0x47c51f
	sketch.go:12	0x47c51d	eb10				jmp 0x47c52f
	sketch.go:13	0x47c51f	488bac24c0000000		mov rbp, qword ptr [rsp+0xc0]
	sketch.go:13	0x47c527	4881c4c8000000			add rsp, 0xc8
	sketch.go:13	0x47c52e	c3				ret
	sketch.go:12	0x47c52f	eb00				jmp 0x47c531
	sketch.go:12	0x47c531	31c0				xor eax, eax
=>	sketch.go:15	0x47c533	488d0d26a80900			lea rcx, ptr [rip+0x9a826]
</pre>
