### ISSUE TITLE
no such file or directory textflag.h : delve doesn't build out of the box

### ISSUE THREAD

**Issue by glycerine** [derekparker/delve#56]
tried to "go get" delve just now, but its build is broken:

~~~
jaten@c:~/go/src/github.com/derekparker/delve:master$ go get github.com/derekparker/delve/cmd/dlv
# golang.org/x/sys/unix
/home/jaten/go/src/golang.org/x/sys/unix/asm.s:6 6a: No such file or directory: textflag.h
jaten@c:~/go/src/github.com/derekparker/delve:master$ sudo locate textflag.h
/var/mailgun/cutlass/jaten/pkg/go1.2.1/go/src/cmd/ld/textflag.h
/var/mailgun/cutlass/jaten/pkg/go1.2.1with_http_improved/go/src/cmd/ld/textflag.h
/var/mailgun/cutlass/jaten/pkg/go1.3.1/go/src/cmd/ld/textflag.h
/var/mailgun/cutlass/jaten/pkg/go1.3.3/go/src/cmd/ld/textflag.h
/var/mailgun/cutlass/jaten/pkg/go1.4/go/pkg/linux_amd64/textflag.h
/var/mailgun/cutlass/jaten/pkg/go1.4/go/src/cmd/ld/textflag.h
jaten@c:~/go/src/github.com/derekparker/delve:master$ 

~~~

 3.11.0-26-generic #45~precise1-Ubuntu SMP
linux/amd64

**Comment by derekparker** [comment]
Hmm, that's a problem with the `sys` package, not Delve. What version of Go are you using? Also, maybe `rm -rf $GOPATH/src/github.com/derekparker/delve` first and do a fresh `go get`?

**Comment by glycerine** [comment]
using go1.4.1, with a fresh (go get -u ) pull of delve.  I copied the textflag.h file over to fix sys package, but then I hit a 2nd build error:

~~~
jaten@c:~/go/src/github.com/derekparker/delve/cmd/dlv:master$ go build
# github.com/derekparker/delve/proctl
/home/jaten/go/src/github.com/derekparker/delve/proctl/variables.go:684: undefined: dwarf.UnspecifiedType
~~~

I commented out variables.go:684-5 to get a build.

**Comment by pnasrat** [comment]
What is the output of `go env`, how did you install go 1.4.1?

**Comment by glycerine** [comment]
hmm... I think I mixed go1.3 with go1.4. I deleted everything, made sure I was on go1.4.1, and now install goes fine. Probably a local problem. Closing issue.
