### ISSUE TITLE
How to set breakpoint for function whose name may be ambiguous?

### ISSUE THREAD

**Issue by NanXiao** [derekparker/delve#560]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
1. What version of Delve are you using (`dlv version`)?
   0.11.0-alpha
2. What version of Go are you using? (`go version`)?
   1.6.2
3. What operating system and processor architecture are you using?
   linux/amd64
4. Issue: Can't set breakpoint of function.

I want to debug `swarm`, and use "`readelf`" command can get function name:  

```
# readelf -s -W bin/swarm | grep create
....
7091: 0000000000467290  1184 FUNC    GLOBAL DEFAULT    1 github.com/docker/swarm/cli.create
....
```

But I can't set breakpoints of the `create` function:  

```
(dlv) b create
Command failed: Location "create" ambiguous: github.com/docker/swarm/cli.create, github.com/docker/swarm/vendor/github.com/hashicorp/consul/api.(*Session).create, github.com/docker/swarm/vendor/github.com/golang/glog.create…
(dlv) b cli.create
Command failed: Location "cli.create" not found
(dlv) ^C
(dlv) b github.com/docker/swarm/cli.create
Command failed: Location "github.com/docker/swarm/cli.create" not found
```

**Comment by aarzilli** [comment]
This is caused by a bug in go standard library: #528

**Comment by xianlubird** [comment]
I happen to have the same error. How do you solve this ? @NanXiao

**Comment by NanXiao** [comment]
@xianlubird #528 refers a workaround.

**Comment by renannprado** [comment]
the issue golang/go#15675 so this must be working now?

**Comment by aarzilli** [comment]
Yes.
