### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by RoarkeRandall** [derekparker/delve#568]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 0.11.0-alpha
2. What version of Go are you using? (`go version`)? 1.6.2 darwin/amd64
3. What operating system and processor architecture are you using? Mac OSX 11.11.4
4. What did you do? 
 Try to debug my go application and stop at a break point
5. What did you expect to see?
 The application to start up and stop at the break point. If I run the application without the debugger, I have no fatal errors or panics.
6. What did you see instead?

fatal error: concurrent map writes
goroutine 38 [running]:
runtime.throw(0x4758940, 0x15)
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc820b9f768 sp=0xc820b9f750
runtime.mapassign1(0x4518be0, 0xc82012aba0, 0xc820b9f858, 0xc820b9f888)
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/hashmap.go:445 +0xb1 fp=0xc820b9f810 sp=0xc820b9f768
github.com/derekparker/delve/proc.(*Process).setBreakpoint(0xc8200981c0, 0x3d03, 0x39f324, 0x39f300, 0xc820cace00, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/breakpoints.go:108 +0x547 fp=0xc820b9f910 sp=0xc820b9f810
github.com/derekparker/delve/proc.(*Process).SetBreakpoint(0xc8200981c0, 0x39f324, 0x5a, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/proc.go:239 +0x48 fp=0xc820b9f950 sp=0xc820b9f910
github.com/derekparker/delve/service/debugger.(*Debugger).CreateBreakpoint(0xc820013d20, 0xc820b92000, 0x4a982c0, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:167 +0xe8 fp=0xc820b9f9f0 sp=0xc820b9f950
github.com/derekparker/delve/service/rpc.(*RPCServer).CreateBreakpoint(0xc8200d1a00, 0xc820b92000, 0xc820b92080, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:134 +0x3f fp=0xc820b9fa30 sp=0xc820b9f9f0
runtime.call64(0xc820a9a000, 0x46c5a68, 0xc820aa0000, 0x1800000028)
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:473 +0x3e fp=0xc820b9fa78 sp=0xc820b9fa30
reflect.Value.call(0x45cdb60, 0x46c5a68, 0x13, 0x46e54f8, 0x4, 0xc820b9fef8, 0x3, 0x3, 0x0, 0x0, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d fp=0xc820b9fdc8 sp=0xc820b9fa78
reflect.Value.Call(0x45cdb60, 0x46c5a68, 0x13, 0xc820b9fef8, 0x3, 0x3, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1 fp=0xc820b9fe28 sp=0xc820b9fdc8
net/rpc.(*service).call(0xc820fb8f40, 0xc820fb8f00, 0xc820b73bc0, 0xc820f8d080, 0xc820b78a00, 0x44eb0c0, 0xc820b92000, 0x16, 0x44eb0c0, 0xc820b92080, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2 fp=0xc820b9ff48 sp=0xc820b9fe28
runtime.goexit()
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820b9ff50 sp=0xc820b9ff48
created by net/rpc.(*Server).ServeCodec
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d

... 

goroutine 35 [runnable]:
debug/gosym.(*LineTable).uintptr(0xc820088000, 0xc820804ff8, 0x113c0, 0x1bea28, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:147
debug/gosym.(*LineTable).go12LineToPC(0xc820088000, 0xc820b675c0, 0x5b, 0x14, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:412 +0x162
debug/gosym.(*Table).LineToPC(0xc82036e000, 0xc820b675c0, 0x5b, 0x14, 0x0, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/symtab.go:515 +0x172
github.com/derekparker/delve/proc.(*Process).FindFileLocation(0xc8200981c0, 0xc820b675c0, 0x5b, 0x14, 0x28, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/proc.go:165 +0x75
github.com/derekparker/delve/service/debugger.(*Debugger).CreateBreakpoint(0xc820013d20, 0xc820f8db80, 0x4a97e10, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:152 +0x8b
github.com/derekparker/delve/service/rpc.(*RPCServer).CreateBreakpoint(0xc8200d1a00, 0xc820f8db80, 0xc820f8dc00, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:134 +0x3f
reflect.Value.call(0x45cdb60, 0x46c5a68, 0x13, 0x46e54f8, 0x4, 0xc820ba3ef8, 0x3, 0x3, 0x0, 0x0, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45cdb60, 0x46c5a68, 0x13, 0xc820ba3ef8, 0x3, 0x3, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc820fb8f40, 0xc820fb8f00, 0xc820b73bc0, 0xc820f8d080, 0xc820b78780, 0x44eb0c0, 0xc820f8db80, 0x16, 0x44eb0c0, 0xc820f8dc00, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d

goroutine 36 [runnable]:
debug/gosym.(*LineTable).uintptr(0xc820088000, 0xc8208b87e8, 0x10b238, 0x10b238, 0xcc7e8)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:147
debug/gosym.(*LineTable).go12LineToPC(0xc820088000, 0xc820b67620, 0x5a, 0x8b, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:413 +0x1ba
debug/gosym.(*Table).LineToPC(0xc82036e000, 0xc820b67620, 0x5a, 0x8b, 0x0, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/symtab.go:515 +0x172
github.com/derekparker/delve/proc.(*Process).FindFileLocation(0xc8200981c0, 0xc820b67620, 0x5a, 0x8b, 0x28, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/proc.go:165 +0x75
github.com/derekparker/delve/service/debugger.(*Debugger).CreateBreakpoint(0xc820013d20, 0xc820f8dd00, 0x0, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:152 +0x8b
github.com/derekparker/delve/service/rpc.(*RPCServer).CreateBreakpoint(0xc8200d1a00, 0xc820f8dd00, 0xc820f8dd80, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:134 +0x3f
reflect.Value.call(0x45cdb60, 0x46c5a68, 0x13, 0x46e54f8, 0x4, 0xc820b9bef8, 0x3, 0x3, 0x0, 0x0, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45cdb60, 0x46c5a68, 0x13, 0xc820b9bef8, 0x3, 0x3, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc820fb8f40, 0xc820fb8f00, 0xc820b73bc0, 0xc820f8d080, 0xc820b788c0, 0x44eb0c0, 0xc820f8dd00, 0x16, 0x44eb0c0, 0xc820f8dd80, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d

goroutine 37 [runnable]:
reflect.typedmemmove(0x46a07e0, 0xc820aae080, 0xc820aae000)
/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mbarrier.go:201
reflect.packEface(0x46a07e0, 0xc820aae000, 0x199, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:113 +0x120
reflect.valueInterface(0x46a07e0, 0xc820aae000, 0x199, 0x1, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:938 +0x1ec
reflect.Value.Interface(0x46a07e0, 0xc820aae000, 0x199, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:908 +0x48
fmt.(*pp).printValue(0xc8200d4f70, 0x46a07e0, 0xc820aae000, 0x199, 0xc800000076, 0x1, 0xdeaddeaddeaddead)
/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:842 +0x372
fmt.(*pp).printReflectValue(0xc8200d4f70, 0x44eb0c0, 0xc820aae000, 0x16, 0x76, 0x0, 0x4504900)
/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:1009 +0x351e
fmt.(*pp).printArg(0xc8200d4f70, 0x44eb0c0, 0xc820aae000, 0x76, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:810 +0x540
fmt.(*pp).doPrintf(0xc8200d4f70, 0x4758d40, 0x17, 0xc820b879b0, 0x1, 0x1)
/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:1238 +0x1dcd
fmt.Sprintf(0x4758d40, 0x17, 0xc820b879b0, 0x1, 0x1, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:203 +0x6f
log.Printf(0x4758d40, 0x17, 0xc820b879b0, 0x1, 0x1)
/usr/local/Cellar/go/1.6.2/libexec/src/log/log.go:289 +0x49
github.com/derekparker/delve/service/debugger.(*Debugger).CreateBreakpoint(0xc820013d20, 0xc820f8de80, 0x0, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:177 +0x238
github.com/derekparker/delve/service/rpc.(*RPCServer).CreateBreakpoint(0xc8200d1a00, 0xc820f8de80, 0xc820f8df00, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:134 +0x3f
reflect.Value.call(0x45cdb60, 0x46c5a68, 0x13, 0x46e54f8, 0x4, 0xc820b87ee8, 0x3, 0x3, 0x0, 0x0, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45cdb60, 0x46c5a68, 0x13, 0xc820b87ee8, 0x3, 0x3, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc820fb8f40, 0xc820fb8f00, 0xc820b73bc0, 0xc820f8d080, 0xc820b78960, 0x44eb0c0, 0xc820f8de80, 0x16, 0x44eb0c0, 0xc820f8df00, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d

goroutine 39 [runnable]:
debug/gosym.(*LineTable).readvarint(0xc820088000, 0xc82003a788, 0xc800000522)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:252
debug/gosym.(*LineTable).step(0xc820088000, 0xc82003a788, 0xc82003a780, 0xc82003a764, 0xc820fb8f01, 0x4013600)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:288 +0x74
debug/gosym.(*LineTable).findFileLine(0xc820088000, 0x47c9a0, 0x1b0cd5001b0cd1, 0x5500000069, 0x1b0cd5)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:331 +0x114
debug/gosym.(*LineTable).go12LineToPC(0xc820088000, 0xc820def650, 0x61, 0x55, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/pclntab.go:416 +0x319
debug/gosym.(*Table).LineToPC(0xc82036e000, 0xc820def650, 0x61, 0x55, 0x0, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/debug/gosym/symtab.go:515 +0x172
github.com/derekparker/delve/proc.(*Process).FindFileLocation(0xc8200981c0, 0xc820def650, 0x61, 0x55, 0x28, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/proc/proc.go:165 +0x75
github.com/derekparker/delve/service/debugger.(*Debugger).CreateBreakpoint(0xc820013d20, 0xc820b92180, 0x4a974b0, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/debugger/debugger.go:152 +0x8b
github.com/derekparker/delve/service/rpc.(*RPCServer).CreateBreakpoint(0xc8200d1a00, 0xc820b92180, 0xc820b92200, 0x0, 0x0)
/private/tmp/delve-20160516-35000-480jwk/delve-0.11.0-alpha/src/github.com/derekparker/delve/service/rpc/server.go:134 +0x3f
reflect.Value.call(0x45cdb60, 0x46c5a68, 0x13, 0x46e54f8, 0x4, 0xc82003aef8, 0x3, 0x3, 0x0, 0x0, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x45cdb60, 0x46c5a68, 0x13, 0xc82003aef8, 0x3, 0x3, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.6.2/libexec/src/reflect/value.go:303 +0xb1
net/rpc.(*service).call(0xc820fb8f40, 0xc820fb8f00, 0xc820b73bc0, 0xc820f8d080, 0xc820b78aa0, 0x44eb0c0, 0xc820b92180, 0x16, 0x44eb0c0, 0xc820b92200, ...)
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:383 +0x1c2
created by net/rpc.(*Server).ServeCodec
/usr/local/Cellar/go/1.6.2/libexec/src/net/rpc/server.go:477 +0x49d

**Comment by aarzilli** [comment]
This was caused by `debugger.(Debugger).CreateBreakpoint`  being executed simultaneously by two goroutines, my guess is that this bug happened with some editor plugin, not with the dlv command line client. Regardless since 82ef3cce7802cfd518fafa9f809fa3ff47e5fa30 `debugger.(Debugger).CreateBreakpoint` acquires a mutex, fixing this bug.
