### ISSUE TITLE
Building Delve on Windows

### ISSUE THREAD

**Issue by rytutis** [derekparker/delve#570]
Hi,

As instructed I set GO15VENDOREXPERIMENT=1 and try to get Delve to build. Is there something more that needs doing? I'm on Windows 8, Go 1.6.

Thank you

C:\Users\Rytis>go get github.com/derekparker/delve/cmd/dlv
 github.com/derekparker/delve/proctl
E:\Projects\goenv\src\github.com\derekparker\delve\proctl\proctl.go:38: undefined: OSProcessDetails

C:\Users\Rytis>echo %GO15VENDOREXPERIMENT%
1

**Comment by aarzilli** [comment]
I think you have a very old version of delve already downloaded, I suggest either deleting it or using `go get -u`.

**Comment by rytutis** [comment]
That was it! Thank you very much.

I can debug Go :astonished:
