### ISSUE TITLE
Cannot set a breakpoint if copy-pasting a function from funcs output

### ISSUE THREAD

**Issue by zefciu** [derekparker/delve#572]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
Using dlv 0.11.0-alpha with go 1.6.1 on ubuntu. After attaching to k8s apiserver I issue:
```
(dlv) funcs flex
...
k8s.io/kubernetes/pkg/volume/flexvolume.(*flexVolumePlugin).Name
...
```
so the `funcs` finds a function Name() with a certain signature. However then I issue:
```
(dlv) b k8s.io/kubernetes/pkg/volume/flexvolume.(*flexVolumePlugin).Name
Command failed: Location "k8s.io/kubernetes/pkg/volume/flexvolume.(*flexVolumePlugin).Name" not found
```
Now the function cannot be found. In general I cannot set a breakpoint in a function that doesn't have an unambigous name. Is there a different syntax for ``breakpoint`` than the syntax that ``funcs`` outputs? In this case it is undocumented and confusing. Or is there some bug that causes this?

**Comment by zefciu** [comment]
Sorry, didn't see this is a duplicate

**Comment by aarzilli** [comment]
It's also [in the documentation](https://github.com/derekparker/delve/blob/master/Documentation/KnownBugs.md). You can still set a breakpoint using the file:line syntax.
