### ISSUE TITLE
Add command to list current location in source

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#58]
When stopped in a debug session, have a command to show source code around the current location this (or any arbitrary) thread is stopped at. Should have a default (5 lines above/below or similar) but also accept an argument to display more source code context.

**Comment by kerlyn-bsd3** [comment]
I am working on this.   Kerry Lynn <kerlyn@ieee.org>

**Comment by derekparker** [comment]
@kerlyn-bsd3 any progress on this? Let me know if you run into any issues or have any questions.

**Comment by kerlyn-bsd3** [comment]
Sorry, been swamped at work.  Should have a PR tonight or tomorrow.

**Comment by quarnster** [comment]
Isn't this almost working already? Stopping appears to print the source code so there's just missing a "list" command for manual source print?

**Comment by derekparker** [comment]
@quarnster correct. The part this is not implemented yet, however, is the ability to print out sections of different source files outside of your current position.
