### ISSUE TITLE
"Time-travel" / "reverse" / "omniscient" debugging

### ISSUE THREAD

**Issue by binary132** [derekparker/delve#584]
This is not a bug, but a feature request / RFC.  I didn't see an Issue for it, closed or open, so pardon me if this is redundant.

> Disclaimer: Since Go's concurrent runtime scales into the hundreds of thousands of goroutines or more, distributed across cores, this behavior should be explicitly opt-in and concern should be had for such cases from the beginning.

A good [time-traveling debugger](http://www.gnu.org/software/gdb/news/reversible.html) would be an amazing feature for Delve.  It would also be complicated, but maybe a good MVP implementation would be very useful without too much complexity.  I have not analyzed how complicated a gimped MVP would be.

There is quite a bit of research on this topic and it's very important for some advanced language use-cases.  My question is inspired by having seen [this talk](https://qconnewyork.com/system/files/presentation-slides/nathan_taylor.pdf) which has very rich references, and a subsequent Google search showing that no, this technology appears not to exist in the Go ecosystem.

Many of us are probably not paid researchers but perhaps there might be some interest in this direction since Go is getting quite popular!

**Comment by derekparker** [comment]
This is supported in `v1.0.0-rc.1` via integration with Mozilla RR as a backend. If you'd like more thatn what that can provide, please reopen.
