### ISSUE TITLE
problem with cgo

### ISSUE THREAD

**Issue by goloveychuk** [derekparker/delve#588]
1. What version of Delve are you using (`dlv version`)?

Version: 0.11.0-alpha
Build: v0.11.0
2. What version of Go are you using? (`go version`)?

go version go1.6 darwin/amd64
3. What operating system and processor architecture are you using?

mac os x 10.11.4, core i5
4. What did you do?

run debug session in vscode (I think it doesn't matter)

```
 "env": {"GOPATH": "${workspaceRoot}/../../",
                    "CC": "GCC",
                    },
"buildFlags": "-ldflags=-linkmode=internal -race",
```
1. What did you expect to see?

start of debug session
6. What did you see instead?

if starting for a much longer time and writes
`debugger.go:55: launching process with args:` and nothing else

This happen  first when I changed several lines of cgo project. So dlv rebuilding it and don't start.
But when I go to project, run `go install .`, dlv uses cached version (from `pkg` dir)  - it's okay. 
Example of cgo project. 
https://github.com/pebbe/zmq4

**Comment by derekparker** [comment]
What happens when you try and use Delve from the command line? Can you update with any output you get?

**Comment by goloveychuk** [comment]
what I should run?
dlv debug produces no interesting output

**Comment by derekparker** [comment]
Closing this issue, please reopen if not solved.

**Comment by goloveychuk** [comment]
Once more, maybe someone faced with this problem too, I'm fixing by running
`go install` with same flags that I'm running delve build. In this case with `-race` flag.
