### ISSUE TITLE
The dlv can't display source code

### ISSUE THREAD

**Issue by NanXiao** [derekparker/delve#597]
What version of Delve are you using (`dlv version`)?  

```
# dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:
```

What version of Go are you using? (`go version`)?   

```
# go version
go version go1.6.3 linux/amd64
```

What operating system and processor architecture are you using?
linux/amd64

What did you do?
This issue is referenced from NVIDIA/nvidia-docker#144. I modify `Dockerfile.build` to build `nvidia-docker` using following command:   

```
 ......
CMD go install -v  -gcflags "-N -l" -ldflags="-X main.Version=$VERSION" ./...
```
But the `dlv` still can't debug `nvidia-docker`:  

```
# dlv exec tools/bin/nvidia-docker
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x407e3b for main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:46
(dlv) c
> main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:46 (hits goroutine(1):1 total:1) (PC: 0x407e3b)
(dlv) n
> main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:47 (PC: 0x407e54)
(dlv)
> main.main() /go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go:48 (PC: 0x407e9d)
(dlv)
```

So could someone give any comment? Thanks very much in advance!

**Comment by aarzilli** [comment]
I suspect the reason is that the path `/go/src/github.com/NVIDIA/nvidia-docker/tools/src/nvidia-docker/main.go` doesn't exist on your machine, am I wrong?

**Comment by NanXiao** [comment]
@aarzilli Yeah, the `/go/src/github.com/NVIDIA/nvidia-docker` is specified in `nvidia-docker` Dockerfile. The simplest solution is also keeping `nvidia-docker` source code in `/go/src/github.com/NVIDIA/` path on host machine.  

Thanks very much again for your great help! You can always resolve `delve` related issues!
