### ISSUE TITLE
The QQ security process actually prohibit the whole system CreateProcess DEBUG_PROCESS, leading to delve appears Access is denied

### ISSUE THREAD

**Issue by dunmengjun** [derekparker/delve#600]
As the title  
my system is windows10 
go version is go 1.7
Run go get github.com/derekparker/delve/cmd/dlv   in cmd 

run delve debug --log main.go is error
that is information 
`delve is debugger.go:61: launching process with args: [./debug] could not launch process: Access is denied`

Is not OSX has this problem?? window also have??
i am chinese,  English  is poor . Please help me with this problem

I will use Google translate view your answer，Thank you

**Comment by derekparker** [comment]
@alexbrainman @lukehoban any thoughts on this?

**Comment by alexbrainman** [comment]
> any thoughts on this?

I cannot reproduce it here. But I use latest version of delve. You can get it if you run
```
go get -u github.com/derekparker/delve/cmd/dlv
```
I also use Windows 7, not Windows 10.

I see:
```
c:\Users\Alex\dev\src\a>type main.go
package main

import "fmt"

func main() {
        fmt.Printf("Alex\n")
}
c:\Users\Alex\dev\src\a>dlv debug --log main.go
ALEX: fp=c:\Users\Alex\dev\src\a\debug
2016/07/23 11:26:40 server.go:71: Using API v1
2016/07/23 11:26:40 debugger.go:61: launching process with args: [./debug]
Type 'help' for list of commands.
(dlv) c
2016/07/23 11:26:41 debugger.go:393: continuing
Alex
Process 288 has exited with status 0
(dlv) q
Process 288 has exited with status 0

c:\Users\Alex\dev\src\a>
```

Delve uses `./debug` to launch executable. But all Windows executables have .exe extension. Maybe we should use delve.exe instead of delve for executable name. Perhaps Windows 10 refuses to run it because it has no .exe.

Perhaps you have some antivirus program that meddle here.

Also having ./ at the start of Windows executable path is wrong too. Windows uses \ for path delimiters, so it should be .\delve.exe. And Windows always look for executable in current directory first anyway, so instead of .\delve.exe it can be just delve.exe. Or you could just use absolute path instead. You calculate absolute path anyway, so you could delete executable on exit.

Unrelated to this problem, but I noticed that sometimes (quite often) `delve` file does not get deleted after dlv.exe exits. The problem is that you cannot delete executable while it is running. If your debugged app exits before dlv.exe, I see no delve file left behind. But if I, for example, quit immediately after startup, the debug file is left behind.

Also maybe it is good idea to create debug file in /tmp?

Alex

**Comment by dunmengjun** [comment]
@alexbrainman 

If I want to modify the code，Modify the generated file where the debug，Plus .exe suffix，I should be how to do, where to modify?
Be sure to help me look，Thank you

**Comment by aarzilli** [comment]
@dunmengjun you could compile manually with `go build -gcflags='-N -l' main.go` then run delve with: `dlv exec <executable file>`

**Comment by dunmengjun** [comment]
I modify the code  Plus the .exe suffix，The resulting file is debug.exe
then I run 
`dlv debug --log main.go`
Or the error
```
2016/07/23 12:13:29 server.go:71: Using API v1
2016/07/23 12:13:30 debugger.go:61: launching process with args: [./ebug.exe]
could not launch process: Access is denied.
```
then I modify the ./ to .\\
 Or the error
```
2016/07/23 12:13:29 server.go:71: Using API v1
2016/07/23 12:13:30 debugger.go:61: launching process with args: [.\ebug.exe]
could not launch process: Access is denied.
```
Next, I will debug.exe into tmp folder
However, I think we should still get this error
wait me
I guess, it is a permissions issue, but I still do not know the specific
Really going to cry！！！

**Comment by dunmengjun** [comment]
@aarzilli
Let me try，Thank you

**Comment by dunmengjun** [comment]
@aarzilli
I use 
`go build -gcflags="-N -l" main.go`
then
` dlv exec main.exe`
Or the error
```
2016/07/23 12:30:47 server.go:71: Using API v1
2016/07/23 12:30:47 debugger.go:61: launching process with args: [main.exe]
could not launch process: Access is denied.
```
I'm really going to cry！！

**Comment by aarzilli** [comment]
Make sure that the user you are using has the "Debug programs" right: https://technet.microsoft.com/en-us/library/dn221963(v=ws.11).aspx

**Comment by dunmengjun** [comment]
@aarzilli 
I do not know how I confirm that the user have the "Debug programs" right  
Can you tell me how to do it? ?
and if the user is not have this
What can I do?
thank you very much

**Comment by aarzilli** [comment]
follow the instructions on the link and check that the user you are using or one of the groups that user belongs to is listed after "Debug programs", I don't have a simpler way to explain it.

**Comment by dunmengjun** [comment]
thank you  @aarzilli
but I'm sure this is not a problem
I look at my group policy, Debug programs value is Administrators, It is a user group includes my current login user,Even so，I tried my login users to join Debug programs.
then I repeat dlv operation
But useless，Still errors
```
2016/07/23 13:48:46 server.go:71: Using API v1
2016/07/23 13:48:46 debugger.go:61: launching process with args: [./debug]
could not launch process: Access is denied.
```

**Comment by dunmengjun** [comment]
@derekparker @alexbrainman  @aarzilli
After I carefully check the code，I found the error is generated here
```
proc/proc_window.go:98
err = sys.CreateProcess(argv0, cmdLine, nil, nil, true, DEBUGONLYTHISPROCESS, nil, nil, si, pi)
```
sys.CreateProcess generated the error
then I find this func at https://github.com/golang/sys/blob/master/windows/zsyscall_windows.go
```
func CreateProcess(appName *uint16, commandLine *uint16, procSecurity *SecurityAttributes, threadSecurity *SecurityAttributes, inheritHandles bool, creationFlags uint32, env *uint16, currentDir *uint16, startupInfo *StartupInfo, outProcInfo *ProcessInformation) (err error) {
	var _p0 uint32
	if inheritHandles {
		_p0 = 1
	} else {
		_p0 = 0
	}
	r1, _, e1 := syscall.Syscall12(procCreateProcessW.Addr(), 10, uintptr(unsafe.Pointer(appName)), uintptr(unsafe.Pointer(commandLine)), uintptr(unsafe.Pointer(procSecurity)), uintptr(unsafe.Pointer(threadSecurity)), uintptr(_p0), uintptr(creationFlags), uintptr(unsafe.Pointer(env)), uintptr(unsafe.Pointer(currentDir)), uintptr(unsafe.Pointer(startupInfo)), uintptr(unsafe.Pointer(outProcInfo)), 0, 0)
	if r1 == 0 {
		if e1 != 0 {
			err = error(e1)
		} else {
			err = syscall.EINVAL
		}
	}
	return
}
```
find
`procCreateProcessW                     = modkernel32.NewProc("CreateProcessW")`
CreateProcessW  is Access is denied
I do not know how to do it

**Comment by alexbrainman** [comment]
What happens if you change:
```
err = sys.CreateProcess(argv0, cmdLine, nil, nil, true, DEBUGONLYTHISPROCESS, nil, nil, si, pi)
```
with
```
err = sys.CreateProcess(argv0, cmdLine, nil, nil, true, 0 nil, nil, si, pi)
```
?

Thank you.

Alex

**Comment by dunmengjun** [comment]
I change with 
`err = sys.CreateProcess(argv0, cmdLine, nil, nil, true, 0 nil, nil, si, pi)`

but 
```
2016/07/23 15:23:10 server.go:71: Using API v1
2016/07/23 15:23:10 debugger.go:61: launching process with args: [./debug]
could not launch process: The handle is invalid.
chan is null
hello
hello
chan is null
hello
hellohello
```
the progrem is run 
However, errors or

**Comment by dunmengjun** [comment]
@alexbrainman

**Comment by alexbrainman** [comment]
Thank you.

It seems Windows does not allow you to use DEBUG_ONLY_THIS_PROCESS flag with CreateProcess API. I do not know why. I need to think about it.

Alex

**Comment by dunmengjun** [comment]
@alexbrainman If you have the answer, please be sure to tell me. thank you very much

**Comment by alexbrainman** [comment]
> If you have the answer, please be sure to tell me.

I will not forget you. But I really do not know what to do here. Sorry.
Maybe @lukehoban knows more.

Alex

**Comment by dunmengjun** [comment]
@alexbrainman  Thank you 
@lukehoban please help

**Comment by dunmengjun** [comment]
I guess I found out why！
Now, I have been able to run delve
The reason is that I uninstalled the 360 security guards，Then restart the computer.
360 security guards is a security software, its implementation is invaded windows kernel.
The operation of the process debugger is very dangerous, because of the uncertainty whether the operator is a dangerous software, so the 360 block of this operation

For the above reasons is my guess, wrong place, please correct me, but it really is because 360 can not run led to delve
hanks to all who helped me

thank you very much @alexbrainman @aarzilli @derekparker

**Comment by dunmengjun** [comment]
I was wrong
By chance, I found that when I play LOL, delve actually appeared Access is denied error
So, I go through repeated tests and found that safety procedures LZ actually banned CreateProcess DEBUG_PROCESS call the whole system
I have been to check how he did it, and whether there are counter-measures。
But still no gain
You, I was wrong, I was wrong 360
@alexbrainman @aarzilli @derekparker If you have any way, be sure to send me to tell
I now play games and write c procedures can not be performed at the same time，

**Comment by aarzilli** [comment]
Does LOL here stand for League of Legends?

**Comment by dunmengjun** [comment]
Yes， LOL is the League of Legends
but I also was wrong
Because this problem is not caused by LOL.You know Tencent acquired LOL it?In China, LOL start at the same time will start the process QQ Safety,This is the cause of CreateProcess DEBUG mode is disabled.Because, Tencent do not want any other program to bundle its program.
Now, I have not take QQ and LOL, because I could not find a way to prevent QQ security process starts.
tragedy!!!!

**Comment by dunmengjun** [comment]
@aarzilli

**Comment by aarzilli** [comment]
Good that you figured it out, I'm closing this issue since there's nothing we can do about it.
