### ISSUE TITLE
use  dlv.exe debug report “could not launch process: Access is denied.”

### ISSUE THREAD

**Issue by czxichen** [derekparker/delve#601]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
C:\Users\Administrator>dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:
2. What version of Go are you using? (`go version`)?
C:\Users\Administrator>go version
go version go1.7rc1 windows/amd64
3. What operating system and processor architecture are you using?
Windows7 
4. What did you do?

package main

import (
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"

	http "github.com/valyala/fasthttp"
)

func main() {
	fmt.Println(Listen("http", ":1789", "", ""))
}

func Listen(proto, ip, crt, key string) (err error) {
	File, err := os.Create("run.log")
	if err != nil {
		return err
	}
	defer File.Close()
	s := server(http.CompressHandler(Router), log.New(File, "", log.LstdFlags))
	switch proto {
	case "http":
		err = s.ListenAndServe(ip)
	case "https":
		err = s.ListenAndServeTLS(ip, crt, key)
	default:
		err = errors.New("Not found proto")
	}
	return
}

func server(handle http.RequestHandler, lg http.Logger) *http.Server {
	return &http.Server{Handler: handle, Logger: lg}
}

var fs = &http.FS{Root: "./src", AcceptByteRange: true}
var fileHandler = fs.NewRequestHandler()

func Router(ctx *http.RequestCtx) {
	switch string(ctx.Path()) {
	case "/":
		ctx.WriteString("Please Login in.")
	case "/download", "/download/":
		download(ctx)
	default:
		ctx.NotFound()
	}
}

func download(ctx *http.RequestCtx) {
	path := string(ctx.FormValue("file"))
	if len(path) <= 0 {
		ctx.Error("Request error", http.StatusNotFound)
		return
	}
	filename := filepath.Base(path)
	ctx.Response.Header.Set("Content-Disposition", "attachment; filename="+filename)
	ctx.Request.SetRequestURI(path)
	fmt.Println(string(ctx.RequestURI()))
	fileHandler(ctx)
}

5. What did you expect to see?
how i can debug this code.
6. What did you see instead?

**Comment by aarzilli** [comment]
League of Legends? See #600 for other reasons you may be getting access is denied. If none applies reopen this issue.
