### ISSUE TITLE
The dlv will hang when input "step" command at the beginning of debugging.

### ISSUE THREAD

**Issue by NanXiao** [derekparker/delve#602]
What version of Delve are you using (`dlv version`)?  

```
# dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:

```

What version of Go are you using? (`go version`)?  

`go version go1.6.3 linux/amd64`

What operating system and processor architecture are you using?  

`linux/amd64`

What is the problem?
When debugging a program, if press `s` directly, the `dlv` will hang there, like this:  

```
# dlv exec ./swarmd
Type 'help' for list of commands.
(dlv) s
```

Maybe it is better to prompt something instead of hanging.

**Comment by aarzilli** [comment]
#603 should improve this.

**Comment by aarzilli** [comment]
This doesn't happen anymore, the behavior of step/next/stepout may be counter-intuitive, but it is correct.
