### ISSUE TITLE
How to display the interface value?

### ISSUE THREAD

**Issue by NanXiao** [derekparker/delve#604]
What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 0.11.0-alpha
Build:

What version of Go are you using? (`go version`)?
go version go1.6.3 linux/amd64

What operating system and processor architecture are you using?
linux/amd64

Problem:

Source code is like this:  

```
package main

import (
        "os"
        "fmt"
)

func main()  {
        if err := os.MkdirAll("/a/b/b", 0777); err != nil {
                fmt.Println(err)
        }
}
```

I use `dlv` to debug the program in step mode, and when there an error occurs, I find `dlv` can't print the value of `error` interface:  

```
(dlv) c
> main.main() ./myError.go:8 (hits goroutine(1):1 total:1) (PC: 0x401013)
     3: import (
     4:         "os"
     5:         "fmt"
     6: )
     7:
=>   8: func main()  {
     9:         if err := os.MkdirAll("/a/b/b", 0777); err != nil {
    10:                 fmt.Println(err)
    11:         }
    12: }
(dlv) n
> main.main() ./myError.go:9 (PC: 0x401017)
     4:         "os"
     5:         "fmt"
     6: )
     7:
     8: func main()  {
=>   9:         if err := os.MkdirAll("/a/b/b", 0777); err != nil {
    10:                 fmt.Println(err)
    11:         }
    12: }
(dlv)
> main.main() ./myError.go:10 (PC: 0x40104c)
     5:         "fmt"
     6: )
     7:
     8: func main()  {
     9:         if err := os.MkdirAll("/a/b/b", 0777); err != nil {
=>  10:                 fmt.Println(err)
    11:         }
    12: }
(dlv) p err
(unreadable invalid interface type)
(dlv) p (PathError*)err
Command failed: 1:12: expected operand, found ')'


```

Is there any method of displaying interface value? Such as "`type cast`"? Thanks very much in advance!

**Comment by aarzilli** [comment]
I can not reproduce this, 0.11 is a bit old I suggest you try using a version compiled from master.
Regarding typecasts, they are supported (in a limited form) however:

1. `(PathError*)err` has two syntax errors and you didn't specify the package name, it should be `(*os.PathError)(err)`
2. It wouldn't work anyway because an interface value can not be cast to its concrete type, what you want is a type assertion: `err.(*os.PathError)`. This will work in go as well as in delve.

**Comment by NanXiao** [comment]
@aarzilli I follow [Installation on Linux](https://github.com/derekparker/delve/blob/master/Documentation/installation/linux/install.md) method:  

`go get github.com/derekparker/delve/cmd/dlv`

And the installed version is `0.11.0-alpha`. Is there something wrong? Thanks!

**Comment by aarzilli** [comment]
Try `go get -u github.com/derekparker/delve/cmd/dlv`. See what `git log -n 1` tells you  in `$GOPATH/src/github.com/derekparker/delve/`.

**Comment by NanXiao** [comment]
@aarzilli 

```
# git log -n 1
commit c3ade94b86bf9033403a493977047df8dbe5ccdd
Author: guo <ggndnn@163.com>
Date:   Mon May 16 20:22:40 2016 +0800

    proc: fix could not read process comm name error
    fix #531
```

**Comment by aarzilli** [comment]
Are you 100% sure that the executable you are running was built with that code? i.e. can you reproduce the issue after doing `make build` and using the `dlv` executable in `$GOPATH/src/github.com/derekparker/delve`?

**Comment by NanXiao** [comment]
@aarzilli It seems right now. But I still have one doubt:  When executing "`go get -u github.com/derekparker/delve/cmd/dlv`", the newest `dlv` should be installed in `$GOPATH/bin`, right? If it is right, the `dlv` in master branch seems always outputs "`Version: 0.11.0-alpha`".

**Comment by aarzilli** [comment]
Yes, you are right about that. The commit id is only included if the binary is built with `make`.

**Comment by NanXiao** [comment]
@aarzilli Got it! Thanks very much for your reply!
