### ISSUE TITLE
Setting breakpoints fails when using symlinks leading out of the GOPATH

### ISSUE THREAD

**Issue by targodan** [derekparker/delve#608]
## To tick the boxes
- dlv version: 0.11.0-alpha
- go version: go1.6.3 linux/amd64
- Running Arch Linux in an oracle VirtualBox with Windows 7 64bit as the host.

## The issue
I recently tried my luck on go-plus for atom and ran into a problem with symlinks. See lloiser/go-debug#44 for more information about it. The problem turned out to (at least partially) be in delve and not actually in go-plus.

This issue may also relate to #299.

The problem occurs when you have your project somewhere outside of your GOPATH but have a symlink in `$GOPATH/src` to that project. It only occurs if you try to create symlinks using the absolute path to the original folder (not the symlink) and you get a `Command failed: Location "..." not found` error.

This might start a little discution, as I came up with an idea in lloiser/go-debug#44:

>  I am not sure if this is the desired behaviour. As go is (from what I have learned so far) very dependant on the GOPATH this might be ok in order to force/teach people to work in the GOPATH. If so the error message should be changed to something more verbose. Maybe something like "The given location is not part of the GOPATH folder. Please move the folder.".

Assuming this is desired behaviour I would suggest to maybe change the error message. Assuming it is not, I would classify this as a bug.

### Reproduction
To reproduce the problem follow these steps:

1. Create a new folder somewhere outside of your GOPATH. Let's name it myproject for now.
2. Navigate to `$GOPATH/src`.
3. Create a symlink to the project folder `ln -sf PATH_TO_PROJECT myproject`
4. Navigate to `PATH_TO_PROJECT`.
5. Create two files `test.go` and `dependancy.go`.
6. Implement say a main function in `test.go` which calls some function in `dependancy.go`.
7. Now execute delve `dlv debug test.go`.
8. Try to add a break point using the absolute path to your original project folder (*not* to the symlink) `break PATH_TO_PROJECT/dependancy.go:LINE`.
9. Observe the error `Command failed: Location "PATH_TO_PROJECT/dependancy.go:LINE" not found`

To answer the question "Why would you do that?" beforehand: I personally prefere to have all my projects in the same folder (which is not in the GOPATH as I use different languages as well) but go has problems finding the packages, if the folder is not part of the GOPATH. As to why you would use an absolute path, and one to the original at that: go-plus for atom does for one and there might be others out there.

Of course you could say this is unimportant and go-plus should just use relative paths. I discovered just discovered it and thought I should tell you guys.

**Comment by aarzilli** [comment]
This issue has nothing to do with $GOPATH nor with absolute paths and can be easily reproduced anywhere:

```
$ cat hello.go
package main

import "fmt"

func main() {
	fmt.Printf("hello world")
}
$ ln -s hello.go blah.go
$ go build -gcflags='-N -l' blah.go
$ dlv exec ./blah
Type 'help' for list of commands.
(dlv) b hello.go:6
Command failed: Location "hello.go:6" not found
(dlv) 
```

The reason is that source files go into the executable with the path the compiler found them at, not with their absolute path and we don't do any symlink resolution. 

IMHO this isn't a bug, this behavior is simple and predictable and I'm not sure resolving symlinks would be as predictable. 

BTW if you are symlinking your project in GOPATH and compiling it from inside GOPATH you *are* using GOPATH.

**Comment by targodan** [comment]
Ok, right. I didn't think about the fact that the compiler actually saves the path into the executables debug info.

I guess that makes sense. Thanks for your time.
