### ISSUE TITLE
Support printing of map types

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#61]
Should follow same semantics as printing a struct, i.e. limiting nesting depth.

**Comment by pnasrat** [comment]
I'm curious about the separation here it looks like the array length is hard coded- I'd have thought eg proctl should support passing in the limit and callers (eg the debugger itself pass in the limits).

**Comment by derekparker** [comment]
Do you mean the nesting depth / array limit for printing? Yeah currently it's hard coded but it should definitely be a runtime configuration. There were some discussions concerning that in #55.

**Comment by aarzilli** [comment]
Implemented by 943c12030ac66730f1a1ce2aa32e57a2b397064e
