### ISSUE TITLE
brew install fails on 10.12

### ISSUE THREAD

**Issue by mcphailtom** [derekparker/delve#616]
1. What version of Delve are you using (`dlv version`)? N/A
2. What version of Go are you using? (`go version`)? go version go1.7 darwin/amd64
3. What operating system and processor architecture are you using? macOS 10.12
4. What did you do? brew install go-delve/delve/delve
5. What did you expect to see? dlv installed
6. What did you see instead?

```
==> Installing delve from go-delve/delve
==> Downloading https://github.com/derekparker/delve/archive/v0.11.0-alpha.tar.gz
Already downloaded: /Users/tommcphail/Library/Caches/Homebrew/delve-0.11.0.tar.gz
==> dlv-cert is already installed, no need to create it
==> make build BUILD_SHA=v0.11.0
Last 15 lines from /Users/tommcphail/Library/Logs/Homebrew/delve/01.make:
2016-08-20 08:20:30 +1000

make
build
BUILD_SHA=v0.11.0

go build -ldflags="-s -X main.Build=v0.11.0" github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/proc
ld: weak import of symbol '_voucher_mach_msg_set' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build] Error 2
```

I'm not sure I understand the idiosyncrasies but could this be related https://github.com/Homebrew/brew/pull/741

**Comment by mcphailtom** [comment]
https://github.com/go-delve/homebrew-delve/pull/2

**Comment by mcphailtom** [comment]
The Homebrew folks have added a directive to allow weak imports to be flagged. Added to PR on delve formula and tested.
https://github.com/go-delve/homebrew-delve/pull/2

**Comment by praveenkumar** [comment]
Looks like this issue is fixed @aarzilli if you have required access can you close it?
