### ISSUE TITLE
Print contents of registers

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#62]
Should be able to print contents of registers for current thread, and any other arbitrary thread.

**Comment by pnasrat** [comment]
@derekparker  are these just place holders for you or are they up for grabs (I suggest the help wanted label tag)

**Comment by derekparker** [comment]
@pnasrat definitely up for grabs. Good idea on the help wanted tag.

**Comment by derekparker** [comment]
Something along the lines of adding a `String` method to the various architecture specific register structs should be the way to go.
