### ISSUE TITLE
dlv crashes on Go 1.7 with "panic: runtime error: makeslice: len out of range"

### ISSUE THREAD

**Issue by jabley** [derekparker/delve#621]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0

2. What version of Go are you using? (`go version`)?

go version go1.7 darwin/amd64

3. What operating system and processor architecture are you using?

OSX 10.11.6 amd64

4. What did you do?

Entered `vars` or `locals`

5. What did you expect to see?

Normal output of the `vars` or `locals` command.

6. What did you see instead?

A panic and crash in the terminal.

See https://gist.github.com/jabley/64a4c836361bf2fc8dc4cacb83a1f159

**Comment by aarzilli** [comment]
It looks like you are using an old version of delve, I fixed a similar bug a while ago and the fix already exists in master. Can you update to master and see if the issue still exists?

**Comment by jabley** [comment]
Tried with master, and that has resolved the issue. Thanks!

**Comment by aarzilli** [comment]
Great, closing this then.

**Comment by marknalepka** [comment]
@aarzilli any chance you can do a new release?  The current version in homebrew has the problem.

**Comment by aarzilli** [comment]
I don't know how to do releases and I think only @derekparker can.
