### ISSUE TITLE
Brew install failing on 10.11

### ISSUE THREAD

**Issue by andrewschreiber** [derekparker/delve#624]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? N/A
2. What version of Go are you using? (`go version`)? 1.7
3. What operating system and processor architecture are you using? macOS 10.11 darwin/amd64
4. What did you do? `brew install go-delve/delve/delve` 
5. What did you expect to see? Successful install
6. What did you see instead?
![screen shot 2016-08-25 at 11 58 16 pm](https://cloud.githubusercontent.com/assets/1892071/17996801/e77e66fc-6b1f-11e6-92e9-3ac57054481c.png)

**Comment by aarzilli** [comment]
Are you sure you are using 1.7? Your GOROOT says 1.5.1 and it doesn't seem to be using the vendor directory.

**Comment by andrewschreiber** [comment]
You're right, thanks!
