### ISSUE TITLE
appengine local package error

### ISSUE THREAD

**Issue by Morrowless** [derekparker/delve#628]
go version 1.7
dlv version 0.11.0

given package models inside root appengine directory:

`import "models"`

Appengine compiles this successfully. However delve cannot find package because root is not added to GOPATH. But, I don't want to put models inside root/src/. How can I work around this?

**Comment by aarzilli** [comment]
I'm not familiar with the appengine workflow, does appengine build an executable? If it does and you can figure out a way to pass compiler flags to it then build with `-gcflags='-N -l'` then debug the executable with `dlv exec ./filename`.

**Comment by bpt6576** [comment]
This seems related to [Google App Engine issue 35901233](https://issuetracker.google.com/issues/35901233)

**Comment by aarzilli** [comment]
Closing, no feedback and it doesn't look like there's anything we could do about this.
