### ISSUE TITLE
Print current stack trace

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#63]

**Comment by pnasrat** [comment]
I assume you mean similar to `bt` in `gdb`

**Comment by derekparker** [comment]
@pnasrat yeah - just printing a formatted stack trace.

**Comment by sandlerben** [comment]
What is the status of this feature? I am working on a Go tool which would really benefit from this.

**Comment by derekparker** [comment]
@sandlerben there's some infrastructure there under the hood to support this, but the actual command hasn't been implemented. I can start working on this later today and should be able to have a commit in by tomorrow or so.

**Comment by sandlerben** [comment]
It would be incredibly useful. I'm not very knowledgeable in the area, but I can help if possible. 

What infrastructure under the hood supports this? Do you have ptrace set up to generate the stack trace?
