### ISSUE TITLE
delve does not work on windows 10 with version 0.11.0-alpha.

### ISSUE THREAD

**Issue by wuceyang** [derekparker/delve#633]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
D:\Go>dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:

2. What version of Go are you using? (`go version`)?
D:\Go>go version
go version go1.7.1 windows/amd64

3. What operating system and processor architecture are you using?
win10  x64-based PC

4. What did you do?

debug via vscode. test.go

`package main

import "fmt"

func main() {
	fmt.Println("123")
}
`
a). press F5, the console shows:
can't load package: package internal: no buildable Go source files in D:\Program Files\Go\src\internal
can't load package: package .: no buildable Go source files in d:\Go
exit status 1

b).in the command line, i input "dlv debug",returns "D:\Go>dlv debug
can't load package: package internal: no buildable Go source files in D:\Program Files\Go\src\internal
can't load package: package .: no buildable Go source files in D:\Go
exit status 1"

c). gopath = "D:\Go", and there are 4 folders in this directory: ".vscode"、"bin"、"pkg" AND "src".  test.go is in the D:/Go/src. in .vscode/launch.json, the program value is "${workspaceRoot}"

d). I build and run the file in command line, they is no error.

5. What did you expect to see?
debug the go program

6. What did you see instead?

**Comment by aarzilli** [comment]
The vscode plugin is developed [here](https://github.com/Microsoft/vscode-go).

**Comment by wuceyang** [comment]
@aarzilli , but there is error while i run  "dlv debug" in command line, why?
 maybe there is a bug with devel?

**Comment by aarzilli** [comment]
If there is an error when you run delve from the command line then there may be a problem with delve, you should copy the error here.

**Comment by wuceyang** [comment]
i'v got the latest version of 4d8daeb1(2013-09-13), and there is a bug here.and then "chcekout e4c7df14" and go install, is ok now
thanks
