### ISSUE TITLE
can't load package: package internal

### ISSUE THREAD

**Issue by huwpascoe** [derekparker/delve#634]
delve 0.11.0-alpha
go1.7 windows/amd64
Windows 10

dlv debug
"can't load package: package internal: no buildable Go source files in C:\Go\src\internal" exit code 1

**Comment by TomasB** [comment]
just wanted to add that it seems it got broken recently:
http://stackoverflow.com/questions/39458526/how-to-fix-delve-cant-load-package-package-internal-error

**Comment by alexbrainman** [comment]
What are the steps for me to reproduce your problem? What did you do to install Delve? What is the program that you are debugging? Please provide full output from all commands. Thank you.

Alex

**Comment by huwpascoe** [comment]
The result is the same on any program. Even the most basic
```
package main

func main() {
}
```

It was installed with go get.

**Comment by huwpascoe** [comment]
ok I've tested it with the previous commit to head that @TomasB linked to, it seems this one is to blame for the error: https://github.com/derekparker/delve/commit/2fad5abe74b311c853838ae4e00d83b9232f1a8a

**Comment by aarzilli** [comment]
@huwpascoe: Thanks.

**Comment by wildfire810** [comment]
Who can give an approved review?
Merging is blocked

dlv: bugfix: Allow quoting in build flags argument by aarzilli · Pull Request #639 · derekparker/delve
https://github.com/derekparker/delve/pull/639
