### ISSUE TITLE
dlv connect : Command failed: connection is shut down

### ISSUE THREAD

**Issue by JCzz** [derekparker/delve#635]
Hi there

Basically I just wanted this sample code from [github](https://github.com/lukehoban/webapp-go/tree/debugging) to work with "$GOPATH/src/app". The sample code does work and able to debug, if I dont use "$GOPATH/src/app".

And thanks for a great debugger for go! I am having some problems connecting to a headless debugger. Hope you can reproduce or better explain why it does not work.

Thanks
1. What version of Delve are you using (`dlv version`)?
   // Client
   Delve Debugger
   Version: 0.11.0-alpha
   Build: v0.11.0
   // Server
   Delve Debugger
   Version: 0.11.0-alpha
   Build:
2. What version of Go are you using? (`go version`)?
   // server:
   go version go1.7.1 linux/amd64
   // client
   go version go1.7 darwin/amd64
3. What operating system and processor architecture are you using?
   // Client machine
   MacBook Pro (Retina, 15-inch, Mid 2015)
   Processor: 2,2 GHz Intel Core i7
   // Docker container from Kitematic cli / terminal
   // Docker file begin

FROM golang:1.7
RUN go get -u -v github.com/derekparker/delve/cmd/dlv
EXPOSE 2345

VOLUME ["/go/src/app"]
RUN mkdir -p /go/src/app
WORKDIR /go/src/app
COPY src/app /go/src/app

RUN go-wrapper download
RUN go-wrapper install

EXPOSE 8080

// Dockerfile end

And then start the container with:
docker run -d --name webapp-go --privileged -p 8080:8080 -p 2345:2345 webapp-go
1. What did you do?
   dlv debug --headless=true --listen=127.0.0.1:2345 --log --api-version=2
   dlv connect 127.0.0.1:2345
   And then just pressed "c"
2. What did you expect to see?
   A running debugger
3. What did you see instead?
   (dlv) c
   Command failed: connection is shut down

Note:
Running two cli/terminals in the container is working.
cli_1: dlv debug --headless=true --listen=127.0.0.1:2345 --log --api-version=2
cli_2: dlv connect "127.0.0.1:2345"

And then I can curl 127.0.0.1 from my mac(Kinematic cli) to debug on the container.

I have run telnet 127.0.0.1:2345
And it gives me:
nodename nor servname provided, or not known

**Comment by aarzilli** [comment]
The correct syntax for telnet is `telnet 127.0.0.1 2345`, the error "nodename nor servname provided, or not known" is because of that. Try again with the correct syntax.

What does the headless instance of delve print? You may need to pass `--listen=0.0.0.0:2345` to delve.

**Comment by harsh61426** [comment]
@JCzz I seem to have a similar issue "Command failed: connection is shut down". Were you able to fix it by using `--listen=0.0.0.0:2345` ?  If not, how did you fix the problem?

**Comment by elmeyer** [comment]
In case anyone stumbles upon this, my issue was that I was trying to attach to a headless `dlv` run as `root` with a `dlv` **not** run as `root`. In my case, the solution was to run the client `dlv` as `root` as well.
