### ISSUE TITLE
Installing delve on Windows gives an error

### ISSUE THREAD

**Issue by tinaschrepfer** [derekparker/delve#638]
Please answer the following before submitting your issue:

C:\GoPath>go get github.com/derekparker/delve/cmd/dlv
# github.com/derekparker/delve/proc
src\github.com\derekparker\delve\proc\disasm.go:9: undefined: ArchInst

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)? go1.7.1 windows/386
3. What operating system and processor architecture are you using? Windows 10 x64
4. What did you do? Tried to install delve
5. What did you expect to see? Install successful
6. What did you see instead? Seems like an compilation error in one of the source files.  See above.

**Comment by joegrasse** [comment]
Delve only works with 64bit not 32bit.

**Comment by alexbrainman** [comment]
FYI

@tinaschrepfer given that you are running 64bit operating system (you said it is Windows 10 x64), you should be able to install Go windows/amd64 (64bit version of Go). This will allow you to run Delve debugger.

Alex

**Comment by tinaschrepfer** [comment]
Thanks!  That fixed part of my issue.  When I debug on VSCode using the latest version of delve I'm getting the following error:

can't load package: package internal: no buildable Go source files in C:\GoWork\src\internal

Seems like others are having the same issue: http://stackoverflow.com/questions/39458526/how-to-fix-delve-cant-load-package-package-internal-error

I worked around it by copying over an older version of delve.  Is this a known issue?  

Thanks!

Tina

**Comment by alexbrainman** [comment]
> I'm getting the following error:

If you run `go env` command what does it output?
Also, can you build some simple go programs from command line? Can you try and debug one such program from command line. Tell us what you did - what your program looks like, what output you see.

Thank you.

Alex

**Comment by tinaschrepfer** [comment]
Here's the go env output
C:\GoWork\bin>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoWork
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

If i debug from command line using the latest delve, I get the following:
C:\GoWork\scratch>..\bin\dlv.exe debug
can't load package: package internal: no buildable Go source files in C:\Go\src\internal
exit status 1

But if I switch to older version of delve, it seems to work okay:
C:\GoWork\scratch>..\bin\dlv.exe debug
Type 'help' for list of commands.
(dlv)

My source code is pretty simple, just some printlns and a sort:

package main

import "fmt"

func main() {
	strs := []string{"c", "a", "b"}
	fmt.Println("testing")
	fmt.Println("sorted strings: ", strs)
	fmt.Println("test")

	i := 1
	for i <= 3 {
		fmt.Println("current i = ", i)
		i = i + 1
	}
}

**Comment by alexbrainman** [comment]
Yes it is broken on the tip.

2fad5abe74b311c853838ae4e00d83b9232f1a8a is the first bad commit
commit 2fad5abe74b311c853838ae4e00d83b9232f1a8a
Author: Koichi Shiraishi <k@zchee.io>
Date:   Tue Sep 13 03:13:21 2016 +0900

    cmd: Support space separate flags for build-flags (#619)

    Signed-off-by: Koichi Shiraishi <zchee.io@gmail.com>

Alex

**Comment by aarzilli** [comment]
PR #639 should fix this.

**Comment by alexbrainman** [comment]
> PR #639 should fix this.

Sure. I was bisecting as you have sent the PR. :-)

Alex

**Comment by aarzilli** [comment]
Alright, thanks anyway :)

**Comment by tinaschrepfer** [comment]
I'm not seeing the fix reflected when I run "go get github.com/derekparker/delve/cmd/dlv".  Is there a different command to use to get the fix?

**Comment by alexbrainman** [comment]
> I'm not seeing the fix reflected when I run "go get github.com/derekparker/delve/cmd/dlv".

The fix is PR https://github.com/derekparker/delve/pull/639. The PR is still opened. It is not part of github.com/derekparker/delve repo. You can apply the PR to your repo localy to try it (google for instructions on how to apply a github PR). Or you can wait until PR is merged or rejected.

> Is there a different command to use to get the fix?

Once change is in github.com/derekparker/delve/cmd/dlv, you could use "-u" flag
```
go get -u github.com/derekparker/delve/cmd/dlv
```
to update your local master branch to whatever github.com/derekparker/delve will be at the time. See `go help get` for correspondent help.

Alternatively you can use whatever git commands you know to update you local source.

Alex

**Comment by aarzilli** [comment]
>google for instructions on how to apply a github PR

[Download the patch](https://patch-diff.githubusercontent.com/raw/derekparker/delve/pull/639.patch) then use `git apply`, this is one way to do it, but then your checkout will be out of sync with the remote and `go get -u` may stop working.

**Comment by wildfire810** [comment]
Who can merge it?

**Comment by aarzilli** [comment]
Fixed by 5d78c04
