### ISSUE TITLE
How do I actually print what I need to see

### ISSUE THREAD

**Issue by charlie-ht** [derekparker/delve#646]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
~? dlv version
Delve Debugger
Version: 0.11.0-alpha
Build
2. What version of Go are you using? (`go version`)?
~? go version
go version go1.6.2 linux/amd64
3. What operating system and processor architecture are you using?
See above
4. What did you do?
print <variable>
5. What did you expect to see?
The entire contents of the variable
6. What did you see instead?
A truncated output that looked like this,
p cmdStr
"[silk -no-flutter -no-event-log -stdout-events -brain.cache_rost...+325 m

Is there an option to expand this? It's annoying getting truncated results when you want to see what state your program is in, especially when help print gives you zero hints about how to adjust that.

**Comment by aarzilli** [comment]
you can't load the whole variable but you can see other parts of the variable using the slice syntax: `p cmdStr[64:]`.

**Comment by charlie-ht** [comment]
Thanks!
