### ISSUE TITLE
can't load package: package internal: no buildable Go source files in C:\ (when source is located on other drive)

### ISSUE THREAD

**Issue by zais** [derekparker/delve#647]
I believe there is an issue when Go compiler located on one disk (C:\Go in my case),
and code your are trying to debug is on another disk (D:\... in my case).

I've tried to move my code and delve to C:\GOPATH, and it fixes the issue.

1. What version of Delve are you using (`dlv version`)?
`Version: 0.11.0-alpha`

2. What version of Go are you using? (`go version`)?
`go version go1.7.1 windows/amd64`
go env
```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Documents\Seafile\Development\Go\code
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

3. What operating system and processor architecture are you using?
`Win 10 x64 (latest updates applied)`

4. What did you do?
Try debug in Atom (but i believe same issue present if you use delve stand-alone)

5. What did you expect to see?
Expecting debugger to work :)

6. What did you see instead?
```
Starting delve with "D:\Documents\Seafile\Development\Go\code\src\github.com\zais\pmpcli\pmpcli.go" with "debug"
Delve output: can't load package: package internal: no buildable Go source files in C:\Go\src\internal
Delve output: exit status 1
delve closed with code 1
```

**Comment by aarzilli** [comment]
This sounds like the same problem as issue #638, it should be fixed, make sure your delve is updated.

**Comment by joefitzgerald** [comment]
The key difference between #638 and this issue is that @zais has a `GOPATH` on the `D:\` drive, and not the `C:\` drive. @zais indicated to me a few hours ago that `go get -u github.com/derekparker/delve/cmd/dlv` had been run. It is possible that @lloiser needs to make some changes to [`go-debug`](https://atom.io/packages/go-debug), but perhaps @zais can show the invocation of delve directly from the terminal instead of invoking it in atom?

**Comment by zais** [comment]
looks like issue is fixed already, and that was just local problem with setup.
runnig `go get -u github.com/derekparker/delve/cmd/dlv` from Git for Windows shell fixed issue for me.
