### ISSUE TITLE
Debugged process can't read from stdin

### ISSUE THREAD

**Issue by ivarg** [derekparker/delve#65]
A traced program will read its stdin from os.DevNull instead of os.Stdin, since in proctl.Launch() it is only stderr and stdout. I can't figure out the reason for this, and simply adding `proc.Stdin = os.Stdin` in the Launch() function will make a simple test program behave as expected.

**Comment by ebfe** [comment]
If dlv and the target process share a stdin, which process will read your keystrokes?

**Comment by pnasrat** [comment]
Note gdb manages to do this - earlier today I was running `gdb --args ./dlv ./outyet` - start in gdb, load a fixed`runtime-gdb.py` run - the prompt for dlv appears and dlv and readline work fine - could Ctrl-R search set a delve breakpoint and continue, etc.

**Comment by ivarg** [comment]
That was my initial thought as well, but I can't see why they can't share stdin. Perhaps I'm missing something obvious... the only time they will possibly race for stdin is when the program is waiting for input.

**Comment by ebfe** [comment]
It doesn't work in the general case. Try:

    package main
    
    import (
    	"io"
    	"os"
    )

    func main() {
    	io.Copy(os.Stdout, os.Stdin)
    }

and step over the `io.Copy` line.

**Comment by ivarg** [comment]
I see what you mean. 
However, I don't see that as the general case, but rather a bit contrived. There are quite a few use cases that can't be addressed if stdin is unavailable.

**Comment by ebfe** [comment]
On Fri, Feb 06, 2015 at 03:19:53PM -0800, Ivar Gaitan wrote:
> I see what you mean. 
> However, I don't see that as the general case, but rather a bit contrived. There are quite a few use cases that can't be addressed if stdin is unavailable.

I'm not against adding support for sharing stdin or providing other
means to provide input the the debugged process (e.g. -stdin <file>).
Just pointing out that sharing stdin has it's own set of problems. There
are other cases where things can/will go wrong (e.g. hitting a
breakpoint in a readline callback/while terminal is in raw mode etc.).

**Comment by binary132** [comment]
This is blocking the use of Delve for me as well.  Perhaps a Delve command like `attach <some io.Reader>`?

**Comment by aarzilli** [comment]
@binary132 as a workaround you can compiler your program with -gcflags="-N -l", start it and then on another terminal run:
```
dlv attach $(pgrep -fn yourprogram)
```

A headless dlv plus `dlv connect` should also work, IMHO, but it doesn't at the moment. There are many options available to multiplex terminals, I'm not sure that having delve do it provides any value besides conformity to how debuggers have worked traditionally.

**Comment by binary132** [comment]
Thanks @aarzilli!  Good point

**Comment by michaljaros84** [comment]
@aarzilli thanks for pointing me towards this thread. Still, do you have any hints why issue seems to be system dependent? The headless approach you mention seems to be working on windows but not linux.
Command: dlv --listen=localhost:55608 --headless=true exec "C:\Build" gives you exactly the behavior you would expect.

**Comment by aarzilli** [comment]
Linux closes stdin in headless mode.

**Comment by paulrd** [comment]
+1 I can't debug my program that requires input from stdin - is there a workaround for linux?

**Comment by dlsniper** [comment]
@aarzilli do you know if osx (specifically High Sierra or newer) is affected by this as well? Thank you.

**Comment by aarzilli** [comment]
@dlsniper yes, probably

**Comment by dlsniper** [comment]
Cool, thank you!

**Comment by dlsniper** [comment]
I'm working on a solution for this which allows remove clients (not the CLI ones) to send stdin input to debugged applications.

However, I've noticed that on Windows stdin is already piped to the debugged process. The patch will disable that as well in order to allow delve to behave the same regardless of the OS.

Furthermore, the new API will be available only the the API Version 2, so that we can start moving clients to it, deprecate and remove API Version 1 and thus simplify Delve and the code maintenance for supporting multiple API versions.

The patch should land in the next few days.

**Comment by aarzilli** [comment]
I think a better approach would be to let the target process access whatever delve's stdin is, if delve is in headless mode. Adding an API to send input to the target process wouldn't work for programs that expect their stdin to be a teletype (anything doing "curses" style UIs, or trying to turn off line discipline).

**Comment by dlsniper** [comment]
> Adding an API to send input to the target process wouldn't work for programs that expect their stdin to be a teletype (anything doing "curses" style UIs, or trying to turn off line discipline).

Good point.

> I think a better approach would be to let the target process access whatever delve's stdin is, if delve is in headless mode.

That's a lot easier to handle. I'll send out the patch later on (as I said, this allows me to learn more of delve's internals and be more helpful in the future). Thank you!

**Comment by pturley0** [comment]
FYI, GoLand's issue [GO-4264](https://youtrack.jetbrains.com/issue/GO-4264) points here.
