### ISSUE TITLE
win10 vscode debugging, can't add/remove breakpoint.

### ISSUE THREAD

**Issue by wildfire810** [derekparker/delve#660]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 0.11.0-alpha
Build:

2. What version of Go are you using? (`go version`)?
go version go1.7.1 windows/amd64

3. What operating system and processor architecture are you using?
win10 64bit

4. What did you do?
At the debugging time, add/remove breakpoint

5. What did you expect to see?
added breakpoint can pause, and removed breakpoint should pass

6. What did you see instead?
contrary, until restart debug, all that will be valid

**Comment by aarzilli** [comment]
Can you post example code and steps to reproduce this?

**Comment by wildfire810** [comment]
The problem is on any code...
Step is debug and then add/remove breakpoint, don't stop running

**Comment by aarzilli** [comment]
The plugin for vscode is [maintained on another repository](https://github.com/Microsoft/vscode-go). Setting and removing breakpoints from the command line client works for me on w10:

```
$ dlv exec ./test.exe
Type 'help' for list of commands.
(dlv) list main.main
   1:   package main
   2:
   3:   import "fmt"
   4:
   5:   func main() {
   6:           for i := 0; i < 10; i++ {
   7:                   fmt.Println("iteration", i)
   8:           }
   9:   }
  10:
(dlv) b test.go:7
Breakpoint 1 set at 0x401091 for main.main() C:/Users/CICCIO~1/AppData/Local/Temp/test.go:7
(dlv) c
> main.main() C:/Users/CICCIO~1/AppData/Local/Temp/test.go:7 (hits goroutine(1):1 total:1) (PC: 0x401091)
     2:
     3: import "fmt"
     4:
     5: func main() {
     6:         for i := 0; i < 10; i++ {
=>   7:                 fmt.Println("iteration", i)
     8:         }
     9: }
    10:
(dlv) c
iteration 0
> main.main() C:/Users/CICCIO~1/AppData/Local/Temp/test.go:7 (hits goroutine(1):2 total:2) (PC: 0x401091)
     2:
     3: import "fmt"
     4:
     5: func main() {
     6:         for i := 0; i < 10; i++ {
=>   7:                 fmt.Println("iteration", i)
     8:         }
     9: }
    10:
(dlv) clear 1
Breakpoint 1 cleared at 0x401091 for main.main() C:/Users/CICCIO~1/AppData/Local/Temp/test.go:7
(dlv) c
iteration 1
iteration 2
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7
iteration 8
iteration 9
Process 180 has exited with status 0
(dlv) q
Process 180 has exited with status 0
```

**Comment by wildfire810** [comment]
https://github.com/Microsoft/vscode-go/issues/580#issuecomment-257151589

read this.
maybe the problem is not delve
