### ISSUE TITLE
`regs` should allow printing the extended registers

### ISSUE THREAD

**Issue by dgryski** [derekparker/delve#666]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 0.11.0-alpha

2. What version of Go are you using? (`go version`)?
go version go1.7.3 linux/amd64

3. What operating system and processor architecture are you using?
Linux kamek 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

4. What did you do?
I was attempting to single-step through some SSE code ( https://github.com/dgryski/go-bloomindex/blob/master/query_amd64.s ) I had generated with https://github.com/Maratyszcza/PeachPy

I used the `regs` command hoping to see the values of all the registers (including the SSE ones: X0, X1, ...).

5. What did you expect to see?

The values of all the registers.

6. What did you see instead?

The `regs` command only prints the standard registers, not the SEE ones :( 

I ended up using gdb and `info all-registers` to see the full register set, but that made the rest of the debugging experience painful.

**Comment by aarzilli** [comment]
We can get these registers on linux using `PTRACE_GET_FPREGS`, we need to figure out how to do this on windows and macOS

**Comment by alexbrainman** [comment]
> we need to figure out how to do this on windows

I think these are stored in data returned by GetContextThread. Googling some I find this https://maximumcrack.wordpress.com/2011/08/07/fpu-mmx-xmm-and-bbq/

Alex
