### ISSUE TITLE
go get -v github.com/derekparker/cmd/dlv failed

### ISSUE THREAD

**Issue by summitxf** [derekparker/delve#669]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? want to install
2. What version of Go are you using? (`go version`)? go1.7.3 windows/amd64
3. What operating system and processor architecture are you using? win7 64
4. What did you do? install
5. What did you expect to see? successful
6. What did you see instead? failed

```
go get -v github.com/derekparker/cmd/dlv
github.com/derekparker/cmd (download)
cd .; git clone https://github.com/derekparker/cmd C:\GoWorks\src\github.com\derekparker\cmd
Cloning into 'C:\GoWorks\src\github.com\derekparker\cmd'...
remote: Repository not found.
fatal: repository 'https://github.com/derekparker/cmd/' not found
package github.com/derekparker/cmd/dlv: exit status 128
```

**Comment by aarzilli** [comment]
it's `go get -v github.com/derekparker/delve/cmd/dlv`

**Comment by summitxf** [comment]
sorry, I copied error path
actually, I followed this [Installation on Windows](https://github.com/derekparker/delve/blob/master/Documentation/installation/windows/install.md) but still failed, then I git clone the whole project and go install locally.

and this path is also not found
> https://github.com/derekparker/delve/cmd/dlv

anyway, currently it work well now. thanks. :)
