### ISSUE TITLE
Doesn't work at all in Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by tmikov** [derekparker/delve#67]
I downloaded Go 1.4.1 and built my test app - it worked. Then I did 
go get github.com/derekparker/delve/cmd/dlv
dlv path/to/my/app
continue

It prints "new thread spawned 11399" and hangs. ^C doesn't work. The app isn't running.

I tried setting breakpoints, etc, but it always hangs after the first "continue".

**Comment by derekparker** [comment]
Hmmm... What kind of app is it? What happens when you run it by itself,
does it panic?

You say the process isn't running, what does `ps` have to say about your
process while Delve is running?

I'm wondering if your program is crashing and a signal is occurring that
delve is ignoring, causing your app to die and delve to block in a `wait`
call while waiting for a breakpoint trap.

If it's not too much trouble could you try `strace`ing delve and see if
it's hanging out at a `wait` call? Or if your code is open source maybe I
can try delve against it and see what's going on.

**Comment by derekparker** [comment]
@tmikov any update on this?

**Comment by tmikov** [comment]
Yes, sorry. The app is "hello world", but it hardly matters because it never even reaches "main". It locks up as soon as I do "continue" in the very beginning then and I need to kill "dlv" from a different terminal. I will run "strace" and post as soon as I have something.

**Comment by tmikov** [comment]
Some more information after testing. The main() routine contains just "fmt.Printf(hello world)" and it never executes. However there is some static variable initialization of logging, etc, If I compile a truly trivial app printing "Hello world", "dlv" does work. So, I suspect that the logging is causing the problem here. I am using "https://github.com/op/go-logging" . 

I should note that the app itself does work and I can debug it with "gdb".

Unfortunately it is not open source, but I might be able to narrow it down to an example illustrating the problem. 

I ran an "strace" and it is inclear. There are 5 threads. One is blocked in "select(0, NULL, NULL, NULL, {0, 10000}", three are blocked in "futex(0x8b8380, FUTEX_WAIT, 0, NULL)"

**Comment by derekparker** [comment]
@tmikov thanks for looking into it more. If you could post a gist of a small program that reproduces the failure I'll look into this issue further - could be related to #41. I was just able to reproduce a bug that's causing Delve to hang.

**Comment by derekparker** [comment]
Alright, I know where we're hanging just not sure why. I'll start looking into a fix for this.

**Comment by derekparker** [comment]
@tmikov figured out what's wrong - now to fix it. Thank you very much for your help and for reporting this.

**Comment by derekparker** [comment]
Closing in favor of #70.

**Comment by tmikov** [comment]
This doesn't seem like an easy fix :-(
Do you still need me to prepare a sample reproducing the problem?

**Comment by derekparker** [comment]
Yeah it's tough, I have some ideas for how to get around this for the time being though.

No need for a small sample, thank you though.
