### ISSUE TITLE
how to install delve offline

### ISSUE THREAD

**Issue by archdevil0** [derekparker/delve#674]
My computer have no network, but I can copy files to it. So how to install delve?

**Comment by aarzilli** [comment]
Download https://api.github.com/repos/derekparker/delve/tarball/master copy it to your computer rename it into delve.tar.gz unpack it into $GOPATH/github.com/derekparker rename the directory that is created (something like `derekparker-delve-6bff4d1`) to just `delve`, then follow the install instructions from there.

**Comment by archdevil0** [comment]
@aarzilli  Thank you
but directory is : $GOPATH/src/github.com/derekparker

**Comment by aarzilli** [comment]
You are right.
