### ISSUE TITLE
Unable to install devle using brew on OSX

### ISSUE THREAD

**Issue by reasonerjt** [derekparker/delve#677]
I tried to use brew to install delve following the instructions, but see "not found" error:

```
~$ brew install -v go-delve/delve/delve
Updating Homebrew...
Error: No available formula with the name "go-delve/delve/delve"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```
Is it still eligible to install delve using brew now?

**Comment by Greyeye** [comment]
dont use brew, production branch version isnt compatible with the OSX sierra (aka macOS) 
you will have to follow instruction on this issue ticket to get it working.
https://github.com/derekparker/delve/issues/645

**Comment by freezlite** [comment]
So why you cant modify your documentation for this? I spend about 2 days because documentantion.

**Comment by gobijan** [comment]
@freezlite: the better question would be: what is missing to get it into the production branch and how can I help you doing this?
Also you could contribute to the docs if you are not satisfied with them.

**Comment by derekparker** [comment]
Should be resolved: https://github.com/derekparker/delve/issues/702.
