### ISSUE TITLE
dlv - Killed 9?

### ISSUE THREAD

**Issue by Greymarch** [derekparker/delve#680]
OSX 10.12.1
go version go1.7.4 darwin/amd64

First installed delve using homebrew instructions on this site.  Receiving a "Killed 9" error when I run dlv from the terminal.

Then installed delve using the manual method.  Still receiving a "Killed 9" error when I run dlv from the terminal.

Have force-quit the taskgated process several times before running dlv, doesnt fix the problem.

I press start debugging in VSC, and the VSC debugger (not VSC itself) simply hangs.  No output in the debug console, and the stop debugger button does nothing when pressed.

I installed a dlv-cert certificate and key.  I set the dlv-cert to allow all to trust, and set the key to allow all applications to control.

What am I missing?  Really need to be able to debug my Go apps from inside VSC.  How do I fix this?

**Comment by caledhwa** [comment]
I am also experiencing this exact same problem.

**Comment by woeitje** [comment]
Same issue as @Greymarch installed certificate, did always allow and set all applications to have control. Process directly gets killed. Simple http Handle func in main.go, runs perfectly without dlv.
OSX: 10.12.3
go version go1.7.1 darwin/amd64

`dlv debug main.go 
Killed: 9
`

**Comment by derekparker** [comment]
@jtorvald @Greymarch still having this issue? The last time we actually ran into this was because of problems with Go binaries being codesigned.

**Comment by jtorvald** [comment]
@derekparker I haven't tried anymore. I'm using Gogland and that works with debugging. Thanks for your reply :)

**Comment by aarzilli** [comment]
@jtorvald Gogland uses delve so case closed.
