### ISSUE TITLE
dlv still does not work on mac os x 10.12.1 after build from the latest commit - proc: support for ver. 10.12.1 the OS formerly known as Mac OS X

### ISSUE THREAD

**Issue by john-deng** [derekparker/delve#686]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
   Delve Debugger
   Version: 0.11.0-alpha
   Build: 63b8fa82698bc9bcf8380c0304fe290047d68240

   Here is the git log,
    commit 63b8fa82698bc9bcf8380c0304fe290047d68240
    Author: aarzilli <alessandro.arzilli@gmail.com>
    Date:   Thu Nov 10 11:20:08 2016 +0100

    proc: support for ver. 10.12.1 the OS formerly known as Mac OS X

    Fixes #645

2. What version of Go are you using? (`go version`)?                                                                                                                                       
    go version go1.7.3 darwin/amd64

3. What operating system and processor architecture are you using?
   Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64

4. What did you do?
    1). go debug main.go
    2). CERT=dlv-cert make test

5. What did you expect to see?

    1) debug main.go properly
    2) all test should be passed ?

6. What did you see instead?

# dlv debug main.go                                                                                                                               21:17:26  2016-12-17
could not launch process: could not fork/exec

# CERT=dlv-cert make test                                                                                                                                 21:17:09  2016-12-17
go test -exec=/Users/johnd/workspace/go/src/github.com/derekparker/delve/scripts/testsign -ldflags="-s -X main.Build=63b8fa82698bc9bcf8380c0304fe290047d68240" github.com/derekparker/delve/cmd/dlv github.com/derekparker/delve/cmd/dlv/cmds github.com/derekparker/delve/config github.com/derekparker/delve/dwarf/frame github.com/derekparker/delve/dwarf/line github.com/derekparker/delve/dwarf/op github.com/derekparker/delve/dwarf/reader github.com/derekparker/delve/dwarf/util github.com/derekparker/delve/proc github.com/derekparker/delve/proc/test github.com/derekparker/delve/service github.com/derekparker/delve/service/api github.com/derekparker/delve/service/debugger github.com/derekparker/delve/service/rpc1 github.com/derekparker/delve/service/rpc2 github.com/derekparker/delve/service/rpccommon github.com/derekparker/delve/service/test github.com/derekparker/delve/service/test/cmd github.com/derekparker/delve/terminal github.com/derekparker/delve/version
2016/12/17 21:18:44 dialing:dial tcp [::1]:40573: getsockopt: connection refused
FAIL	github.com/derekparker/delve/cmd/dlv	4.030s
ok  	github.com/derekparker/delve/cmd/dlv/cmds	0.917s
?   	github.com/derekparker/delve/config	[no test files]
ok  	github.com/derekparker/delve/dwarf/frame	1.207s
ok  	github.com/derekparker/delve/dwarf/line	1.327s
ok  	github.com/derekparker/delve/dwarf/op	1.276s
?   	github.com/derekparker/delve/dwarf/reader	[no test files]
ok  	github.com/derekparker/delve/dwarf/util	1.257s
--- FAIL: TestExit (0.23s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestExitAfterContinue (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestHalt (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStep (0.22s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestBreakpoint (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestBreakpointInSeperateGoRoutine (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestBreakpointWithNonExistantFunction (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestClearBreakpointBreakpoint (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextGeneral (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextConcurrent (0.20s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextConcurrentVariant2 (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextFunctionReturn (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextFunctionReturnDefer (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextNetHTTP (0.48s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestRuntimeBreakpoint (0.20s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestFindReturnAddress (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestFindReturnAddressTopOfStackFn (0.15s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestSwitchThread (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestCGONext (0.78s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStacktrace (0.14s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStacktrace2 (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStacktraceGoroutine (0.15s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestKill (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestGetG (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestContinueMulti (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestBreakpointOnFunctionEntry (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestProcessReceivesSIGCHLD (0.24s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue239 (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestVariableEvaluation (0.23s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestFrameEvaluation (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestPointerSetting (0.27s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestVariableFunctionScoping (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestRecursiveStructure (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue316 (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue325 (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestBreakpointCounts (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue262 (0.20s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue305 (0.14s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue341 (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestCondBreakpoint (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestCondBreakpointError (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue356 (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepIntoFunction (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue384 (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue332_Part1 (0.20s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue332_Part2 (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue396 (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue414 (0.15s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestPackageVariables (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue149 (0.14s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestPanicBreakpoint (0.14s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestCmdLineArgs (0.21s)
	proc_test.go:53: Launch(): could not fork/exec
--- FAIL: TestIssue462 (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextParked (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepParked (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue573 (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestTestvariables2Prologue (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextDeferReturnAndDirectCall (0.14s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestNextPanicAndDirectCall (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepCall (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepCallPtr (0.15s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepReturnAndPanic (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepDeferReturn (0.01s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepIgnorePrivateRuntime (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue561 (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepOut (0.01s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepConcurrentDirect (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepConcurrentPtr (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepOutDefer (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepOutDeferReturnAndDirectCall (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepOnCallPtrInstr (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue594 (0.22s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestStepOutPanicAndDirectCall (0.01s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestWorkDir (0.21s)
	proc_test.go:53: Launch(): could not fork/exec
--- FAIL: TestNegativeIntEvaluation (0.00s)
	proc_test.go:38: Launch(): could not fork/exec
--- FAIL: TestIssue419 (0.21s)
	proc_test.go:38: Launch(): could not fork/exec
FAIL
FAIL	github.com/derekparker/delve/proc	85.351s
?   	github.com/derekparker/delve/proc/test	[no test files]
?   	github.com/derekparker/delve/service	[no test files]
?   	github.com/derekparker/delve/service/api	[no test files]
ok  	github.com/derekparker/delve/service/debugger	0.876s
?   	github.com/derekparker/delve/service/rpc1	[no test files]
?   	github.com/derekparker/delve/service/rpc2	[no test files]
?   	github.com/derekparker/delve/service/rpccommon	[no test files]
--- FAIL: Test1Restart_afterExit (0.24s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1Restart_breakpointPreservation (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1Restart_duringStop (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_exit (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_step (0.24s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1NextGeneral (0.25s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1NextFunctionReturn (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_breakpointInMainThread (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_breakpointInSeparateGoroutine (0.21s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_breakAtNonexistentPoint (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_clearBreakpoint (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_switchThread (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_infoLocals (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_infoArgs (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_traceContinue (0.21s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_traceContinue2 (0.00s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_FindLocations (0.23s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_FindLocationsAddr (0.22s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_EvalVariable (0.24s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_SetVariable (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_FullStacktrace (0.16s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1Issue355 (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1Disasm (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1NegativeStackDepthBug (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1ClientServer_CondBreakpoint (0.23s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1SkipPrologue (0.01s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1SkipPrologue2 (0.22s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1Issue419 (0.22s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1TypesCommand (0.28s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: Test1Issue406 (0.27s)
	integration1_test.go:34: could not launch process: could not fork/exec
--- FAIL: TestRestart_afterExit (0.00s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestRestart_breakpointPreservation (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestRestart_duringStop (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_exit (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_step (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_stepout (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestNextGeneral (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestNextFunctionReturn (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_breakpointInMainThread (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_breakpointInSeparateGoroutine (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_breakAtNonexistentPoint (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_clearBreakpoint (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_switchThread (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_infoLocals (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_infoArgs (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_traceContinue (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_traceContinue2 (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_FindLocations (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_FindLocationsAddr (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_FindLocationsExactMatch (0.22s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_EvalVariable (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_SetVariable (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_FullStacktrace (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestIssue355 (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestDisasm (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestNegativeStackDepthBug (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_CondBreakpoint (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestSkipPrologue (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestSkipPrologue2 (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestIssue419 (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestTypesCommand (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestIssue406 (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestEvalExprName (0.01s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestClientServer_Issue528 (0.23s)
	integration2_test.go:41: could not launch process: could not fork/exec
--- FAIL: TestVariableEvaluation (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestVariableEvaluationShort (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestMultilineVariableEvaluation (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestLocalVariables (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestEmbeddedStruct (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestComplexSetting (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestEvalExpression (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestEvalAddrAndCast (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestMapEvaluation (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestUnsafePointer (0.01s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestIssue426 (0.00s)
	variables_test.go:84: Launch(): could not fork/exec
--- FAIL: TestPackageRenames (0.53s)
	variables_test.go:84: Launch(): could not fork/exec
FAIL
FAIL	github.com/derekparker/delve/service/test	81.403s
?   	github.com/derekparker/delve/service/test/cmd	[no test files]
0  0x0000000000000000 in (nil)
   at irrelevant.go:10
--- FAIL: TestIssue411 (0.18s)
	command_test.go:86: could not launch process: could not fork/exec
--- FAIL: TestScopePrefix (0.18s)
	command_test.go:86: could not launch process: could not fork/exec
--- FAIL: TestOnPrefix (0.01s)
	command_test.go:86: could not launch process: could not fork/exec
--- FAIL: TestNoVars (0.24s)
	command_test.go:86: could not launch process: could not fork/exec
--- FAIL: TestOnPrefixLocals (0.02s)
	command_test.go:86: could not launch process: could not fork/exec
--- FAIL: TestIssue387 (0.25s)
	command_test.go:86: could not launch process: could not fork/exec
FAIL
FAIL	github.com/derekparker/delve/terminal	7.573s
?   	github.com/derekparker/delve/version	[no test files]
make: *** [test] Error 1

**Comment by AlexejK** [comment]
Interesting, it does work for me though when i am running it with latest macOS release.

**Comment by aarzilli** [comment]
The "could not fork/exec" sounds more like a certificate problem.

**Comment by john-deng** [comment]
@aarzilli Thanks you, you are right, it is certificate problem, after recreate the dlv-cert, it works now.

I found a useful tutorial for creating the certificate, I'd like to post it here in case someone might need this. https://www.youtube.com/watch?v=4K2bDLzYiAQ
