### ISSUE TITLE
Command failed: could not find FDE for PC 0x7f1b5a43a430

### ISSUE THREAD

**Issue by newthinker** [derekparker/delve#692]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 0.11.0-alpha
Build: f4aaffbbf34ce4c2ca8b55e65b569407064c4787
```

2. What version of Go are you using? (`go version`)?
```
go version go1.7.4 linux/amd64
```

3. What operating system and processor architecture are you using?
```
CentOS Linux release 7.2.1511 (Core)
```

4. What did you do?
debug a very simple code, like helloworld.

5. What did you expect to see?
can step/list and so on

6. What did you see instead?
next: Command failed: could not find FDE for PC 0x7f1b5a43a430
list: Stopped at: 0x7f1b5a43a430

**Comment by aarzilli** [comment]
Before you can use `next` you need to start the program. Set a breakpoint and use `continue`.
