### ISSUE TITLE
dlv version hasnt been updated in a while

### ISSUE THREAD

**Issue by ramya-rao-a** [derekparker/delve#696]
The Go extension for VS Code implements debugging by using dlv.
We want to implement the "Step Out" feature which was added to dlv last October.
For our users on the older `dlv`, we want to show a message to upgrade to the newer `dlv`.
But currently there is no way for us to know whether the `dlv` on the user's machine supports `Step Out` or not

`dlv` does not return any error if a command that has not been implemented is used. So we cannot depend on any error message from dlv

The `dlv version` returns `0.11.0-alpha` from last 11 months. https://github.com/derekparker/delve/blob/master/version/version.go

If this version can be updated, then we can use the version to decide whether the user has  the `dlv` on the user's machine supports `Step Out` or not

**Comment by derekparker** [comment]
Thanks for opening this issue, we are absolutely in need of a new release. There has been a lot of work and new features, fixes, etc.. since the last release.

We will coordinate a new release this week.

**Comment by Aleishus** [comment]
waiting for it....

**Comment by derekparker** [comment]
https://github.com/derekparker/delve/pull/699

**Comment by aaronhackney** [comment]
You are awesome, thanks. This may not be the place to report, but I tried the alpha that was just pushed, delve-0.11.0-alpha.zip,  and I still have the "could not launch process: could not get thread count" issue on OSX 10.12.2. Thanks again!

**Comment by derekparker** [comment]
@aaronhackney the current version as of patch #699 will be `0.12.0`, so try from the branch (which is currently basically master as far as code / features / fixes are concerned). Once that PR merges the official latest version will be `0.12.0`.

**Comment by aaronhackney** [comment]
Thanks for the response Derek! I tried the 0.12.0 and the master branch and I still get thread issues. Let me know if I can help in any way. Thanks again for this awesome tool.
$ dlv debug
could not launch process: error waiting for thread stop -268435459
$ dlv debug hello.go
could not launch process: could not get thread count

**Comment by derekparker** [comment]
Latest version is now [v0.12.1](https://github.com/derekparker/delve/blob/master/CHANGELOG.md#0121-2017-01-11). The changelog shows the major changes in `v.0.12.0`.

We will be implementing regular releases in the near future with pre-built assets.

@aaronhackney if you're still having issues on OSX definitely file an issue or jump on an existing issue that describes your problem. Thanks!

**Comment by ramya-rao-a** [comment]
Thanks @derekparker !
