### ISSUE TITLE
how to stop at main entry = main() function without explicitly setting breakpoint 

### ISSUE THREAD

**Issue by muravjov** [derekparker/delve#700]
1. What version of Delve are you using (`dlv version`)?

Version: 0.11.0-alpha

2. What version of Go are you using? (`go version`)?

go version go1.7.4 linux/amd64

3. What operating system and processor architecture are you using?

$ uname -a
Linux ilya-vaio 3.19.0-18-generic #18~14.04.1-Ubuntu SMP Wed May 20 09:38:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

4. What did you do?

$ dlv exec go_binary
dlv) bt
0  0x00000000004523e0 in _rt0_amd64_linux
   at ./programming/golang/git/src/runtime/rt0_linux_amd64.s:8
(dlv) continue
Hello, world!
Process 4471 has exited with status 0
(dlv)

5. What did you expect to see?

I would like to stop at main() function automatically, not at runtime/rt0_linux_amd64.s:8

6. What did you see instead?

See above, continue runs through main(), didn't stop and program is finished.

**Comment by derekparker** [comment]
Currently there is no way to do this, you must set a breakpoint when you start debugging the process.
