### ISSUE TITLE
[feature request] allow to print more elements than 64

### ISSUE THREAD

**Issue by iamzhout** [derekparker/delve#701]
1. What version of Delve are you using (`dlv version`)?
0.11.0-alpha

2. What version of Go are you using? (`go version`)?
go version devel +ffedff7 Sun Jan 8 00:01:30 2017 +0000 linux/amd64

3. What operating system and processor architecture are you using?
Ubuntu14.04 - amd64

4. What did you do?
do dlv debugging, and try to use `print` to get array variable value

Currently delve `print` command has [64 elements limit](https://github.com/derekparker/delve/blob/master/Documentation/cli/expr.md#elements-limit), suggest to add an option to change this limitation on the fly, as it will be much more convenient if developer wants to get more data from array, slice, map, etc.

**Comment by ahakanbaba** [comment]
+1

**Comment by StephenWeatherford** [comment]
Yes, the limit of 64 is very low, especially for strings

**Comment by aarzilli** [comment]
The `config` added in 48288edd187f094959c12776689471162ec41438 can do this.
