### ISSUE TITLE
go get doesnt work 

### ISSUE THREAD

**Issue by NikosEfthias** [derekparker/delve#704]
1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
1.7.4
3. What operating system and processor architecture are you using?
linux/amd64 
4. What did you do?
go get github.com/derekparker/delve
5. What did you expect to see?
successfully to be able to build
6. What did you see instead?
![delve](https://cloud.githubusercontent.com/assets/9097437/21957063/24db648a-daa8-11e6-8fb7-088be2bd23f5.png)

**Comment by aarzilli** [comment]
See https://github.com/derekparker/delve/blob/master/Documentation/installation/linux/install.md

**Comment by NikosEfthias** [comment]
thank you @aarzilli
