### ISSUE TITLE
remote debug server has to be killed with ^C after debugee ends

### ISSUE THREAD

**Issue by f0zi** [derekparker/delve#707]
I'm doing some remote debugging where the debugee is running in a docker container. Instead of simply running the tool I run `dlv debug --listen=:2345 --headless`. When the tool finishes I would like the process (and the container) to exit, but this does not happen with dlv. I either have to kill it or attach to it and type ^C.

I would say as delve at that point is not accepting any incoming connections any more it should exit when the client closes the connection.

1. What version of Delve are you using (`dlv version`)?
Version: 0.11.0-alpha
2. What version of Go are you using? (`go version`)?
go version go1.7.4 linux/amd64
3. What operating system and processor architecture are you using?
Ubuntu 16.4; Windows 10
4. What did you do?
    - `dlv debug --listen=:2345 --headless`
    - Connect with `dlv connect`
    - let the debugee run to completion
5. What did you expect to see?
debug server should either exit when the client exits or support remote restarting / exiting
6. What did you see instead?
debug server was
    - not accepting any more connections
    - not accepting any input (except ^C)
    - idling

**Comment by f0zi** [comment]
@aarzilli This has nothing to do with os/windows, the debug server is running on Ubuntu or in a docker container.

**Comment by aarzilli** [comment]
This doesn't happen anymore.
