### ISSUE TITLE
Screen colors

### ISSUE THREAD

**Issue by carlca** [derekparker/delve#708]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
version 0.12.1
2. What version of Go are you using? (`go version`)?
version go1.7.4
3. What operating system and processor architecture are you using?
Windows 10 Pro 64 bit Insider Preview build 15007
4. What did you do?
ls command to show source followed by c to continue.
5. What did you expect to see?
Would like to be able to change the dark blue color of the current line indicator to a brighter color. I know it's not the most crucial issue ever but my eyesight isn't getting any better!
6. What did you see instead?
Not a lot because of the low contrast effect of dark blue on black.

**Comment by alexbrainman** [comment]
@carlca you can switch colours off, with
```
set TERM=dumb
```
or you can change colour here https://github.com/derekparker/delve/blob/master/terminal/terminal.go#L21

Alex

**Comment by aarzilli** [comment]
The terminal emulator you are using should give you the option to adjust the colors, we don't control the exact rgb value we are just asking for 'blue'.

**Comment by carlca** [comment]
Understood. Thanks Guys.
