### ISSUE TITLE
go get github.com/derekparker/delve/cmd/dlv fails with an error

### ISSUE THREAD

**Issue by dhanunjay** [derekparker/delve#71]
When i do 'go get github.com/derekparker/delve/cmd/dlv' it fails with the following error
# github.com/derekparker/delve/proctl
../../derekparker/delve/proctl/proctl.go:31: undefined: BreakPoint
../../derekparker/delve/proctl/proctl.go:32: undefined: BreakPoint

**Comment by derekparker** [comment]
What OS are you using?

**Comment by derekparker** [comment]
More specifically, are you using OS X? Delve currently does not support OS X, however I've been working a lot on OS X support and it should be landing soon.

**Comment by dhanunjay** [comment]
I am on XUBUNTU with GO 1.4. I have also installed libreadline-dev.

**Comment by derekparker** [comment]
Hmmm.. is this the first time you've tried pulling down & installing Delve?

**Comment by dhanunjay** [comment]
Yes first time. I will try again and update the thread. I am very excited to try delve. 

thanks for looking into the issue.

**Comment by dhanunjay** [comment]
Derek,

I was able to repro the issue on 32 bit XUBUNTU. However i have tried on a clean 64bit XUBUNTU everything worked as expected. Not sure if the architecture is an issue.

**Comment by derekparker** [comment]
Ah, yeah I should of asked that as well. Currently only 64 bit systems are supported, it won't take much to support 32 bit systems, however I've just been focusing on OS X support as of late. I'll be working on 32 bit support after OS X support.
