### ISSUE TITLE
[feature request] Break without any parameters sets the breakpoint at the selected frame next instruction

### ISSUE THREAD

**Issue by ahakanbaba** [derekparker/delve#718]
1. What version of Delve are you using (`dlv version`)?

```
[vagrant@k8s-env ~]$ dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:
```
2. What version of Go are you using? (`go version`)?
```
[vagrant@k8s-env ~]$ go version
go version go1.7.4 linux/amd64
```
3. What operating system and processor architecture are you using?
```
[vagrant@k8s-env ~]$ uname -a
Linux k8s-env 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
4. What did you do?
Typed only `break`
5. What did you expect to see?
A breakpoint placed at the selected frame next instruction 
6. What did you see instead?
An error message like 
```
(dlv) break
Command failed: Malformed breakpoint location "" at 0: empty string
```

I am suggesting a feature like gdb. 
http://www.delorie.com/gnu/docs/gdb/gdb_29.html

```
break
When called without any arguments, break sets a breakpoint at the next instruction to be executed in the selected stack frame ....
```

Something like this looks very cool 
```
// breakpoint to the next instruction in frame 0
(dlv) break 

// breakpoint to the next instruction in frame 4
(dlv) frame 4 break 
```

I need to point out that not all debuggers behave like in this feature request. 
PDB has different semantics for the `break` without any arguments. 
https://docs.python.org/2/library/pdb.html
```
Without argument, list all breaks,
```

I am not sure whether the implementation in dlv is reasonable given this comment 
https://github.com/derekparker/delve/issues/441#issuecomment-191391694

```
IIRC GDB may try and "figure it out" by setting a break point on the next line, but that information is not actually encoded into the debug info line table.
```

**Comment by aarzilli** [comment]
`break +1` does this, I don't see why this is so useful that it should be the default behavior of `break`.

**Comment by ahakanbaba** [comment]
Silly me. 
I have not read the linespec [documentation](https://github.com/derekparker/delve/blob/master/Documentation/cli/locspec.md) carefully .

`break +1` does everything I need. Closing the issue
