### ISSUE TITLE
Support gdb remote serial protocol

### ISSUE THREAD

**Issue by aarzilli** [derekparker/delve#727]
Optionally support a backend that connects to something speaking the [gdb remote serial protocol](https://sourceware.org/gdb/onlinedocs/gdb/Remote-Protocol.html).

This will allow delve to use gdb-server, lldb-server and, more interestingly, mozilla rr as backends, giving delve timetravelling debugging essentially for free on linux.

Blockers: needs refactoring of proc to make stacktraces, variable evaluation and BinaryInfo features independent from proc.Process.

**Comment by derekparker** [comment]
This is done.
