### ISSUE TITLE
terminal status is not restored when dlv "die"

### ISSUE THREAD

**Issue by raff** [derekparker/delve#73]
With the new "liner" package it is necessary to call liner.Close() to restore the terminal (enable echo, etc.)

While the code does call "defer line.Close()", the line.Close() is not executed when the application terminates because of an error (all the calls to "die() terminate with os.Exit() that doesn't execute any deferred code)

I suggest to either add some "context" do the "die" method (pass the liner or pass some context object if there are other components that need to be released) or use some package that implements "atexit" functionalities.

If you have a preferred method I can work on a pull request.

**Comment by derekparker** [comment]
Yeah I'm fine with passing along `line` to `die`, I think it makes sense to put the responsibility in that function to restore terminal state, since it's the one calling `os.Exit`.

**Comment by raff** [comment]
ok, I'll prepare a pull request and submit it (actually I already did this
some time ago... and then managed to delete all my changes ):

**Comment by pnasrat** [comment]
Thanks I noticed this in my testing also.

**Comment by derekparker** [comment]
This is fixed.
