### ISSUE TITLE
Delve doesnt work with go 1.8 on win 10 amd_64

### ISSUE THREAD

**Issue by jcbritobr** [derekparker/delve#742]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
**Version: 0.11.0-alpha**

2. What version of Go are you using? (`go version`)? **1.8**
3. What operating system and processor architecture are you using? **win 10 amd_64**
4. What did you do?
**try to debug a simple example**
5. What did you expect to see?
**delve moving between breakpoints and show program data**
6. What did you see instead?
**delve crash when i do next command**

here is the program:

package main

```
import (
	"log"
)

func init() {
	log.SetPrefix("TRACE: ")
	log.SetFlags(log.Ldate | log.Lmicroseconds | log.Llongfile)
}

func main() {

	log.Println("message")
	log.Fatalln("fatal message")

}
```

here is the output:

2017/02/17 20:20:49 server.go:71: Using API v1
2017/02/17 20:20:49 debugger.go:61: launching process with args: [./debug]
API server listening at: 127.0.0.1:2345
2017/02/17 20:20:49 debugger.go:238: created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x493496, File:"C:/Goworkspace/src/logging/main.go", Line:14, FunctionName:"main.main", Cond:"", Tracepoint:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(nil), LoadLocals:(*api.LoadConfig)(nil), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2017/02/17 20:20:49 debugger.go:393: continuing
2017/02/17 20:20:55 debugger.go:413: nexting
2017/02/17 20:20:57 debugger.go:413: nexting
Failed to next.

**Comment by derekparker** [comment]
Can you try switching to the latest tagged release `v0.12.1`, and if that still does not work try building from source and see if the issue is resolved. If so, we will be tagging a new release soon anyways, but the latest tagged release is `v0.12.1` and you are running `v0.11.0-alpha`.

**Comment by jcbritobr** [comment]
@derekparker, go get github.com/derekparker/delve/cmd/dlv only gets **v0.11.0-alpha**. I will try build from sources.

**Comment by jcbritobr** [comment]
hi @derekparker, version 0.12.1 works perfectly. Thank you. I will close this thread
