### ISSUE TITLE
How to debug a program which has some paramters with delve?

### ISSUE THREAD

**Issue by jiebanghan** [derekparker/delve#744]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 0.12.1
2. What version of Go are you using? (`go version`)?
go version go1.6.2 linux/amd64
3. What operating system and processor architecture are you using?
Ubuntu 16.04.1 LTS \n \l
4. What did you do?
I just want to debug a program which has some parameters with delve. The command is like that 
./foo --bzzaccount $BZZKEY --datadir $DATADIR --bzznetworkid 322
I debug it like dlv exec ./foo--build-flags="--bzzaccount $BZZKEY --datadir $DATADIR --bzznetworkid 322"
but it does not work. So would you please tell me what shouid I do? thank you.
5. What did you expect to see?
6. What did you see instead?

**Comment by aarzilli** [comment]
`dlv exec ./foo -- --bzzaccount $BZZKEY --datadir $DATADIR --bzznetworkid 322`
