### ISSUE TITLE
How can you debug a binary like terraform 

### ISSUE THREAD

**Issue by huydinhle** [derekparker/delve#746]
Hi, I  love using delve to debug my go program. I am currently working on terraform project. I wonder if anyone here has been able to use Delve to debug terraform binary https://github.com/hashicorp/terraform

Thank you very much for your help.

**Comment by derekparker** [comment]
Hey, sorry for the delay in responding. You should be able to debug just like any other Go program using Delve. If you build the binary yourself, ensure you compile for optimal debugging (`-gcflags=-N -l`) and then you can use `dlv exec ./binanry`.

**Comment by huydinhle** [comment]
Thank you for the help @derekparker
