### ISSUE TITLE
Variable returned from function is not visiable to debuger

### ISSUE THREAD

**Issue by kirk-patton** [derekparker/delve#748]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 0.12.1
Build: d89d115ef9efb3acdb3a1052ac058b79f36a4940

2. What version of Go are you using? (`go version`)?
go version go1.7.3 darwin/amd64

3. What operating system and processor architecture are you using?
Darwin C02PWBQBG8WP-lm 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

4. What did you do?
main.go
package main

import (
	"fmt"
)

func main() {
	x := foo()
	fmt.Printf("foo() returns: %s\n", x)
}

func foo() (value string) {
	return "some value"
}

========================================
Debug session
https://git.corp.yahoo.com/gist/kpatton/705c7872ca9b4540259b528b130e6248

5. What did you expect to see?
Expected "some value"

6. What did you see instead?
Command failed: could not find symbol value for x
(no locals)

**Comment by aarzilli** [comment]
The link doesn't load, can you host it somewhere else? Can you reproduce this with 1.8?

**Comment by kirk-patton** [comment]
https://gist.github.com/kirk-patton/0c2bc0d902f3083c397601d98a3da6c6

I will try 1.8 and see if I run into the same issue

**Comment by kirk-patton** [comment]
Just tried go1.8 on linux amd64. Same issue

(dlv) p v
Command failed: could not find symbol value for v

**Comment by aarzilli** [comment]
did you disable compiler optimizations when you compiled foo?

**Comment by kirk-patton** [comment]
Just now tried with '-gcflags "-N -l"'.  Now it works as expected. :-D

Thanks!
Kirk
