### ISSUE TITLE
Use subcommands rather than flags

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#75]
Instead of `dlv -run` you could simply type `dlv run`, etc... Thoughts?

**Comment by pnasrat** [comment]
It depends on who your audience is - my experience with docker is some users have a dislike of go style flags as non-getopty/traditional. 

The command based approach would be more similar to the go tool itself, and  subcommands could have flags. I think I've definitely feel -run being a boolean doesn't make much sense.

```
dlv --run=false --pid 10027
dlv --run=true --pid 10027
```


dlv attach -p <pid>

Note then attach could also work for a host:port
 
Personally whatever works for invocation - but I think I'd tend to lean towards subcommands and short flags or args. The use case I can think of are:

* Load a program (with args) without executing - enter delve interface, run delve commands (set breakpoints, etc then execute within delve (either single step or just run/cont)
* Load a program (with args) without executing and a core file for postmortem debugging
* Attach to a running program (local)
* Attach to a running program (remote)
* Run with a program/attached to a program with scripted input (batch mode)
* Build and load
