### ISSUE TITLE
go debug error

### ISSUE THREAD

**Issue by zuojinmin** [derekparker/delve#750]
First, open a port Request used to listening to the network, and then to debug the program, can't open, shows that the port has occupied then that I want to close off this service all not a line, the kill pid have failed

ZuojinmindeMacBook - Pro: zuo0118 zuojinmin $lsof - I: 8080COMMAND PID USER FD TYPE DEVICE SIZE/OFF the NODE NAMEThe debug 1467 zuojinmin 3 u x2802924a2f2f6d2d IPv6 0 0 t0 TCP * : HTTP - Alt (LISTEN)ZuojinmindeMacBook - Pro: zuo0118 zuojinmin $kill 9 1467ZuojinmindeMacBook - Pro: zuo0118 zuojinmin $lsof - I: 8080COMMAND PID USER FD TYPE DEVICE SIZE/OFF the NODE NAMEThe debug 1467 zuojinmin 3 u x2802924a2f2f6d2d IPv6 0 0 t0 TCP * : HTTP - Alt (LISTEN)

**Comment by derekparker** [comment]
Can you format your command line session better so I can read through it and understand what you're doing and what the output is I'm seeing.

Also, I'm not sure what the issue is, are you unable to run your program under Delve?

**Comment by zuojinmin** [comment]
I can use the DLV debugging, but the closing time have been shut out

2017/03/02 10:54:19 server.go:71: Using API v1
2017/03/02 10:54:19 debugger.go:65: launching process with args: [/Users/zuojinmin/Documents/zuogo/src/zuo0118/debug]
API server listening at: 127.0.0.1:2345
2017/03/02 10:54:19 debugger.go:397: continuing
2017/03/02 10:54:19 [1;34m[I] [asm_amd64.s:2086] http server Running on http://:8083
2017/03/02 10:54:19 [1;35m[C] [asm_amd64.s:2086] ListenAndServe:  listen tcp :8083: bind: address already in use

Display port has been occupied, not close out of port services, the background check DLV process did not shut down,Ide is vscode, debug is useful for the first time, but can't shut down, need to background tasks manually close the DLV process

**Comment by aarzilli** [comment]
This looks like a bug in vscode plugin which is developed here: https://github.com/Microsoft/vscode-go
