### ISSUE TITLE
opps! I got this.

### ISSUE THREAD

**Issue by horatii** [derekparker/delve#751]
C:\WINDOWS\system32>go get -v -u github.com/peterh/liner github.com/derekparker/delve/cmd/dlv
github.com/peterh/liner (download)
github.com/derekparker/delve (download)
github.com/derekparker/delve/pkg/proc
# github.com/derekparker/delve/pkg/proc
C:\GOPATH\src\github.com\derekparker\delve\pkg\proc\disasm.go:9: undefined: ArchInst

e-mail:lijinggang@021.com

**Comment by aarzilli** [comment]
32bit windows isn't supported.
