### ISSUE TITLE
Installation with brew ignores my existing go installation

### ISSUE THREAD

**Issue by seguri** [derekparker/delve#753]
I followed the suggested instructions for installation (`brew install go-delve/delve/delve`) and later discovered go 1.8 was also installed. Why is my existing go 1.7.4 installation ignored?

I'm new to go but, as a general rule, I don't expect  my language version to be updated without my consent. `brew info` did not show any install option to keep existing go installation.

3. What operating system and processor architecture are you using? osx 10.11.6, x86_64

**Comment by aarzilli** [comment]
AFAIK our brew formula does not mandate any particular version of go, I think you should bring up this problem with homebrew.

**Comment by seguri** [comment]
So @aarzilli, how do you exactly call this line in delve's formula?

    depends_on "go" => :build

**Comment by aarzilli** [comment]
I would call it "not a particular version of go"

**Comment by seguri** [comment]
Exactly. And that's the problem. It requires a go version I don't want to install.

Can you tell me how to fix this?

```
% go version
go version go1.7.4 darwin/amd64
% brew install --ignore-dependencies go-delve/delve/delve
==> Installing delve from go-delve/delve
==> Downloading https://github.com/derekparker/delve/archive/v0.12.1.tar.gz
Already downloaded: /Users/mark/Library/Caches/Homebrew/delve-0.12.1.tar.gz
==> dlv-cert is already installed, no need to create it
==> make build BUILD_SHA=v0.12.1
Last 15 lines from /Users/mark/Library/Logs/Homebrew/delve/01.make:
2017-03-03 12:03:31 +0100

make
build
BUILD_SHA=v0.12.1

go build -ldflags="-s -X main.Build=v0.12.1" github.com/derekparker/delve/cmd/dlv
/bin/sh: go: command not found
make: *** [build] Error 127

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/go-delve/homebrew-delve/issues
```

**Comment by seguri** [comment]
Hi @aarzilli, do you know how to solve this?

**Comment by aarzilli** [comment]
Either install go with brew or install delve without brew, look at the contents of the brew script and execute the steps manually.

**Comment by seguri** [comment]
Can you leave the issue open to see if anyone else knows how to fix this?

**Comment by aarzilli** [comment]
@seguri #758

**Comment by justinclift** [comment]
@seguri It's probably better to ask the Homebrew team for advice on this, as they've had similar things come up with other languages before (eg Python).

One ***possible*** approach would be to create a new option for the formula, eg `--use-existing-go`, which makes it skip over the `depends_on "go" => :build` line when set.

**Comment by seguri** [comment]
@justinclift as you can see above, I already tried to ignore go dependency without success. I agree with you that in the future, with more dependencies, it would become a `--without-go` option.

**Comment by justinclift** [comment]
Understood.  What did the Homebrew team say?
