### ISSUE TITLE
Using Delve to drive tests?

### ISSUE THREAD

**Issue by wrouesnel** [derekparker/delve#756]
This is nebulously a feature request:

A common problem I have with testing things I write in Go is that I have a function which does something like:
```go
if err := initializeSomeBlackboxCBinding(); err != nil {
  // It didn't work so the clean up is obvious here.
}
// Other code
if err := callSomeBlackboxCBinding() ; err != nil {
  // But here I may have done other setup on the assumption the binding is still working correctly, 
  // which it may not be if it's a system service. Rather then failing out.
}
```

The problem is that figuring out all the possible return cases of that blackbox binding is usually nigh impossible, and depends on some system service. A practical example is dealing with `udev` bindings. For my purposes I don't want to trace every code path - I just want to know how my code behaves if that service goes down at that point (i.e. for whatever reason I `kill -9` it, say the OOM killer fires.)

This is almost impossible to test while keeping the code readable I find. To make it testable I have to embed hooks deep within parts of the code which have no purpose other then to let me predictably kill the service at that point.

What I'd *like* to be able to do is define a test case which gives a reference to the block of code I want, breakpoint and trigger a script right before it's executed - giving me a chance to "break" system services in the ways I'm worried about deterministically. Then spit out the results as a coverage report for testing to boot.

Has anyone used Delve to do this, is there a clever alternate I'm not seeing, could this be considered as a use case?

**Comment by aarzilli** [comment]
Doing this interactively seems trivial so I imagine you want to do this programmatically, right? You can use our [debugger package](https://godoc.org/github.com/derekparker/delve/service/debugger) if you want. The code will have to run in a different process, we don't do self-debugging.

**Comment by derekparker** [comment]
@wrouesnel I'm a little unclear on what you're after here, possibly my own misunderstanding. Are you trying to run your tests interactively with Delve or as @aarzilli are you trying to do something more programmatic? E.g. you mention executing a script _before_ the breakpoint is triggered, is I understand you correctly?

If you want to simply run your tests interactively you can use `dlv test`.

**Comment by wrouesnel** [comment]
What I want to do is semihost my program, programmatically, so I can run my tests.

i.e. when you reach line, break point, run script, then resume.

The idea being to let me run integration tests where I can break system services and thus cross-check what happens at every possible point of failure (i.e. all the `if err != nil` error handlers) without having to split obvious functions into a lot of different components.

It sounds like the debugger package would let me do that, but I'll need to develop my own test runner to support enough syntax / source annotation to make it possible.

**Comment by aarzilli** [comment]
It's an interesting idea, if you end up doing it I would like hearing how it goes.
