### ISSUE TITLE
Allow non-members to view delve-dev's mailing list

### ISSUE THREAD

**Issue by justinclift** [derekparker/delve#757]
Would it be feasible to relax the view permission on the delve-dev mailing list, so people aren't required to have a Google account just to view it?

eg this is what I get when trying to access the page:

![delve mailing list unviewable](https://cloud.githubusercontent.com/assets/406299/23578085/58c11daa-00c6-11e7-9c16-ad37d77645a5.png)

**Comment by aarzilli** [comment]
I'm in favor.

**Comment by derekparker** [comment]
Done, settings on mailing list have been updated.

**Comment by justinclift** [comment]
Awesome, thanks @derekparker.  Now I can follow along with how things are going. :smile:
