### ISSUE TITLE
Makefile errors out when GOPATH has multiple dirs

### ISSUE THREAD

**Issue by justinclift** [derekparker/delve#759]
### What version of Delve are you using (`dlv version`)?

Latest git (as of 7th March 2017)

### What version of Go are you using? (`go version`)?

go version go1.8 darwin/amd64

### What operating system and processor architecture are you using?

OSX 10.11.6, 64 bit Intel

### What did you do?

Ran "make install" from a clone of the git repo

### What did you expect to see?

Successful run of make install

### What did you see instead?

Make errors out due to incorrect assumption that GOPATH will only contain one path:

```
$ make install
go install -ldflags="-s -X main.Build=bb07fc36b9df2b9baec074ee8a48b1941f049f55" github.com/derekparker/delve/cmd/dlv
codesign -s "dlv-cert"  /Users/jc/go:/Users/jc/git_repos/bin/dlv
/Users/jc/go:/Users/jc/git_repos/bin/dlv: No such file or directory
make: *** [install] Error 1
```

It's not hard to work around by setting GOBIN first, but it should probably be fixed at some point. :wink:

**Comment by justinclift** [comment]
As a thought towards fixing this, it might be useful to figure out the installed path to delve by using something like this:

```
OLDPATH=$PATH
PATH=$GOPATH
hash -r
DELVEBIN=`which dlv`
if [ "$DELVEBIN" != "" ]; then
  # Delve was found, so sign it
  PATH=$OLDPATH
  hash -r
  codesign -s "$(CERT)" $DELVEBIN
fi
```

That's untried, concept only code, but it seems like a reasonable approach.

**Comment by Mirodil** [comment]
I have similar error
```
scripts/gencert.sh || (echo "An error occurred when generating and installing a new certicate"; exit 1)
go install -ldflags="-s -X main.Build=2c0e31160de8cba2a4351dcf39486d05313b4da1" github.com/derekparker/delve/cmd/dlv
codesign -s "dlv-cert"  /bin/dlv
/bin/dlv: No such file or directory
make: *** [install] Error 1

```
