### ISSUE TITLE
Drop info from certian commands

### ISSUE THREAD

**Issue by derekparker** [derekparker/delve#76]
Instead of `info sources`, just type `sources`. None of those commands of info conflict so it shouldn't be an issue, and would be less typing. Thoughts, concerns?

**Comment by pnasrat** [comment]
What is the goal. If you're trying to emulate gdb command line then obviously this breaks that - but I think we can do better user experience than GDB. 

I'd love for an actual debugging API to be better defined so eg the websocket API ine #57 could be more restful and we could eg implement a grpc API ontop also. Something a little higher level to consume than proctl

This is more comparable to eg JDWP http://docs.oracle.com/javase/8/docs/technotes/guides/jpda/jdwp-spec.html than to a CLI focussed debugger but I think might lead to a richer tool ecosystem - for IDE integration/web frontends/etc.

**Comment by derekparker** [comment]
I have absolutely no problem breaking away from gdb style commands. Right now `info` is the one that most closely mimics gdb. The goal is to have the best user experience we can.

I'm certainly up for outline a higher level api - I've tossed around the idea of going more traditional client/server route with Delve. All clients (cli, web, ide) would speak with a debug "server" which would speak a well defined protocol, trivializing the addition of new clients.

If you'd like to open a discussion about it I'm up for fleshing the idea out more, and in the meantime I might spike on this idea, and see what it looks like. Initially there was no need for this type of design, however I think now it may be beneficial.

**Comment by pnasrat** [comment]
Happy to flesh out more. What's the best forum for discussion?

Just as another approach:

https://developer.chrome.com/devtools/docs/protocol/1.1/index
https://developer.chrome.com/devtools/docs/protocol/1.1/console

That being said that doesn't block iterating on the CLI right now.

**Comment by derekparker** [comment]
@pnasrat I can create an issue today to begin discussion and track changes.
