### ISSUE TITLE
Use dlv attach PID and it tells error

### ISSUE THREAD

**Issue by yingqin678** [derekparker/delve#766]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
$ dlv version
Delve Debugger
Version: 0.12.1
Build:
2. What version of Go are you using? (`go version`)?
go version go1.7 windows/amd64
3. What operating system and processor architecture are you using?
windows 7 amd64
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\isource\go-workspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
4. What did you do?
package main

import (
"fmt"
"sync"
"time"
)

func dostuff(wg *sync.WaitGroup, i int) {
fmt.Printf("goroutine id %d\n", i)
time.Sleep(300 * time.Second)
fmt.Printf("goroutine id %d\n", i)
wg.Done()
}

func main() {
var wg sync.WaitGroup
workers := 10

wg.Add(workers)
for i := 0; i < workers; i++ {
	go dostuff(&wg, i)
}
wg.Wait()
}
5. What did you expect to see?
I use 'go build' or '$ go build -ldflags="-linkmode=internal"' to generate the binary file
run the binary file
$ ./go.exe
goroutine id 1
goroutine id 0
goroutine id 3
goroutine id 2
goroutine id 6
goroutine id 7
goroutine id 8
goroutine id 5
goroutine id 9
goroutine id 4
goroutine id 1
goroutine id 0
goroutine id 3
goroutine id 2
goroutine id 9
goroutine id 5
goroutine id 8
goroutine id 7
goroutine id 6
goroutine id 4

another console :
$ ps
PID PPID PGID WINPID TTY UID STIME COMMAND
12984 12408 12984 12920 pty1 4344533 19:48:22 /d/isource/go-workspace/src/go_test/src/mian/go/go
11736 1844 11736 9112 pty0 4344533 19:48:27 /usr/bin/ps
12408 12068 12408 7920 pty1 4344533 17:29:46 /usr/bin/bash
1844 10948 1844 11424 pty0 4344533 17:19:16 /usr/bin/bash
12068 1 12068 12068 ? 4344533 17:29:46 /usr/bin/mintty
10948 1 10948 10948 ? 4344533 17:19:16 /usr/bin/mintty
$ dlv attach 12984
could not attach to pid 12984: decoding dwarf section info at offset 0x0: too short
6. What did you see instead?
i wish to succeed to attach to the program

**Comment by alexbrainman** [comment]
I cannot reproduce this with Delve 0.12.1 and go1.7.

@yingqin678 I suspect you are trying to attach to the wrong process. I modified your example to print PID. Perhaps you should do that and try again.

```
c:\Users\Alex\dev\src\a>type main.go
package main

import (
        "fmt"
        "os"
        "time"
)

func main() {
        fmt.Printf("my pid is %v\n", os.Getpid())
        time.Sleep(time.Minute)
}

c:\Users\Alex\dev\src\a>go build -o a.exe && start a.exe

c:\Users\Alex\dev\src\a>dlv attach 2728
Type 'help' for list of commands.
(dlv) goroutines
[5 goroutines]
  Goroutine 1 - User: c:/users/alex/dev/go/src/runtime/time.go:59 time.Sleep (0x4401c3)
  Goroutine 2 - User: c:/users/alex/dev/go/src/runtime/proc.go:260 runtime.gopark (0x429fbf)
  Goroutine 3 - User: c:/users/alex/dev/go/src/runtime/proc.go:260 runtime.gopark (0x429fbf)
  Goroutine 17 - User: c:/users/alex/dev/go/src/runtime/proc.go:260 runtime.gopark (0x429fbf)
  Goroutine 18 - User: c:/users/alex/dev/go/src/runtime/asm_amd64.s:576 runtime.asmcgocall (0x451807)
(dlv) goroutine 1
Switched from 0 to 1 (thread 3224)
(dlv) bt
0  0x0000000000429fbf in runtime.gopark
   at c:/users/alex/dev/go/src/runtime/proc.go:260
1  0x000000000042a074 in runtime.goparkunlock
   at c:/users/alex/dev/go/src/runtime/proc.go:265
2  0x00000000004401c3 in time.Sleep
   at c:/users/alex/dev/go/src/runtime/time.go:59
3  0x00000000004010f4 in main.main
   at c:/users/alex/dev/src/a/main.go:11
4  0x0000000000429b8b in runtime.main
   at c:/users/alex/dev/go/src/runtime/proc.go:183
5  0x00000000004525a0 in runtime.goexit
   at c:/users/alex/dev/go/src/runtime/asm_amd64.s:2086
(dlv) q
Would you like to kill the process? [Y/n] n

c:\Users\Alex\dev\src\a>
```

**Comment by yingqin678** [comment]
i had got  wrong pid.it's the WINPID in windows to attach
