### ISSUE TITLE
feature query. Web gui like this one ?

### ISSUE THREAD

**Issue by joeblew99** [derekparker/delve#768]
wondring is anyone knows of a web based IDE for DLV ?

https://github.com/cs01/gdbgui

**Comment by lloiser** [comment]
There are already several editor integrations: https://github.com/derekparker/delve/blob/master/Documentation/EditorIntegration.md

If you really need a web gui for this it's probably the best idea to start with one of the javascript implementations of these integrations and port it to the browser (or better in an electron window).

**Comment by derekparker** [comment]
Going to close this issue as we (the core project) will likely never take this on. We have a lot of editor integrations, and it's not something we work on, yet the community is absolutely free to build any frontend they would like on top of Delve.
