### ISSUE TITLE
Command failed: could not find symbol value for xxx

### ISSUE THREAD

**Issue by chenziliang** [derekparker/delve#769]
Hi 

I can't print local variable below is the information you will need.

code snippet

```
   114: func (out *Smartouter) doWriteEvents(events []*base.Event) error {
   115:         var allEvents []*base.Event
=> 116:         for _, event := range events {
   117:                 processedEvents, eventsSummary, err := out.preprocessors.Preprocess(event)
   118:                 if err == nil {
   119:                         allEvents = append(allEvents, processedEvents...)
   120:                 }
   121:                 _ = eventsSummary
(dlv) print len(allEvents)
Command failed: could not find symbol value for allEvents
```

1.
$dlv version
Delve Debugger
Version: 0.12.1
Build:

2.
$go version
go version go1.8 linux/amd64

3. ubuntu linux/amd64

**Comment by aarzilli** [comment]
Did you compile the program yourself or use `dlv debug`? Is this code in main or in a package other than main? If it is in another package it could be golang/go#19340.

**Comment by chenziliang** [comment]
@aarzilli I didn't compile the program by using `dlv debug` instead by using `go build`. It is my `main`

**Comment by aarzilli** [comment]
Then you need to pass `-gcflags='-N -l'` to `go build`.

**Comment by chenziliang** [comment]
Thanks !

**Comment by x-yuri** [comment]
@aarzilli I tried to follow your `-gcflags` advice, but it doesn't seem to work:

`a.sh`:

```sh
set -eu
docker run --rm -itv "$PWD:/app" -w /app alpine:3.19 sh -euc '
    apk add go delve
    go build -gcflags="-N -l"
    dlv exec ./a
'
```

`go.mod`:

```go.mod
module example.com/a

go 1.21.5
```

`a.go`:

```go
package main

import "fmt"

const c = "world"

func main() {
    fmt.Println(fmt.Sprintf("hello %v", c))
}
```

```
$ sh a.sh
...
> main.main() ./a.go:8 (PC: 0x47c7da)
     3: import "fmt"
     4:
     5: const c = "world"
     6:
     7: func main() {
=>   8:     fmt.Println(fmt.Sprintf("hello %v", c))
     9: }
(dlv) p c
Command failed: could not find symbol value for c
```

Has something changed?

**Comment by aarzilli** [comment]
> Has something changed?

No, non-integer constants are not exported to debug_info. But you know that since you have read on commented on https://github.com/golang/go/issues/35527
