### ISSUE TITLE
debugged process is left suspended after exiting delve

### ISSUE THREAD

**Issue by alexbrainman** [derekparker/delve#772]
1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 0.12.1
Build:

2. What version of Go are you using? (`go version`)?

go version go1.7 windows/amd64

3. What operating system and processor architecture are you using?

windows/amd64

4. What did you do?

```
c:\Users\Alex\dev\src\a>type main.go
package main

import (
        "fmt"
        "os"
        "time"
)

func main() {
        fmt.Printf("my pid is %v\n", os.Getpid())
        time.Sleep(time.Minute)
}

c:\Users\Alex\dev\src\a>go build -o a.exe main.go && start a.exe

c:\Users\Alex\dev\src\a>dlv attach 3784
Type 'help' for list of commands.
(dlv) q
Would you like to kill the process? [Y/n] n

c:\Users\Alex\dev\src\a>
```

5. What did you expect to see?

I expect a.exe to continue running after I exit from dlv.

6. What did you see instead?

a.exe process is suspended after I exit from dlv.

Alex

**Comment by derekparker** [comment]
@aarzilli I believe this has been fixed, let me know if I'm wrong about that.
