### ISSUE TITLE
Issue using next command on Mac

### ISSUE THREAD

**Issue by tylerlrhodes** [derekparker/delve#776]
1. What version of Delve are you using (`dlv version`)?

bash-3.2$ dlv version
Delve Debugger
Version: 0.12.1
Build: v0.12.1

2. What version of Go are you using? (`go version`)?

go version go1.8 darwin/amd64

3. What operating system and processor architecture are you using?

MacOS Sierra x64

4. What did you do?

https://gist.github.com/tylerlrhodes/b106963eeac76cf145d9405976a5e4d9

Basically just trying to step through some code, I've tried this using the command line and also from VS Code.  While breakpoints in VS Code seem to work, stepping over a line seems to generate a panic of some kind.

5. What did you expect to see?

The ability to step over a line / user the next keyword

6. What did you see instead?

(dlv) next
Command failed: Invalid address 0x0

**Comment by aarzilli** [comment]
There is a problem with 0.12.1 and go 1.8, upgrade to master.

**Comment by tylerlrhodes** [comment]
I'm just starting out with Go and Delve, what's the easiest way to do that?

Is there another go get command to use besides the one in the install docs?

It does seem to work okay on windows with both of these versions

**Comment by aarzilli** [comment]
Try this:

```
cd $GOPATH/src/github.com/derekparker/delve
git checkout master
git pull
CERT=dlv-cert make install
```

**Comment by tylerlrhodes** [comment]
I was able to build it with the latest from master, however the next command just hangs

bash-3.2$ CERT=dlv-cert make install
go install -ldflags="-s -X main.Build=28a0e5bd63d22340ecfaa2177a29e1c1f1b5d41c" github.com/derekparker/delve/cmd/dlv
codesign -s "dlv-cert"  /Users/tylerrhodes/go/bin/dlv
bash-3.2$

<autogenerated>
(dlv) break main.main
Breakpoint 1 set at 0x1088efb for main.main() ./bitvector.go:38
(dlv) continue
> main.main() ./bitvector.go:38 (hits goroutine(1):1 total:1) (PC: 0x1088efb)
    33: func (bv *BitVector) IsBitSet(x int) bool {
    34:         word, bit := x/64, uint(x%64)
    35:         return word < len(bv.bytes) && bv.bytes[word]&(1<<bit) != 0
    36: }
    37:
=>  38: func main() {
    39:         var bitvec BitVector
    40:         bitvec.SetBit(0)
    41:         if bitvec.IsBitSet(0) {
    42:                 fmt.Printf("\nBit 0 is set!")
    43:         }
(dlv) next

**Comment by aarzilli** [comment]
Can you post the program you are trying to debug?

**Comment by tylerlrhodes** [comment]
I put it in a gist for you:

https://gist.github.com/tylerlrhodes/359faba1f5817f5c54cc09fad5ca1d8d

**Comment by GlenDC** [comment]
I have the same issue, while debugging an application. I use however "OS X El Capitan x64" rather than "MacOS Sierra x64". All other info is similar for me. So I am going to try to help debug this issue, although I can't promise I will get anywhere with this, as I've never seen this codebase or contributed to it before.

**Comment by tylerlrhodes** [comment]
Great, I would love to have this work on the Mac.

It does seem to work just fine on Windows using the same versions of delve
and go.  I'd be willing to help test it if needed.

**Comment by GlenDC** [comment]
I do have to say @tylerlrhodes that I can debug your gist fine, while I can't debug http://github.com/rivine/rivine/rivined without hanging when I use the `next` command in a `dlv debug` process.

So for me your gist works fine when I do the following:

1. start the process in the same dir as the gist is placed using `dlv debug`
2. add breakpoint to the main file: `(dlv) b main.main`
3. continue: `(dlv) continue`
4. next: `(dlv) next`

And for me that does just go next, and I can use whatever commands are available to me.

**Comment by GlenDC** [comment]
Hmmm... Weirdly enough the `next` command now also doesn't hang any longer when debugging my application mentioned earlier. So I'm not sure what's going on. For now I can use the `dlv` command fine... How curious.

**Comment by tylerlrhodes** [comment]
That's strange.  I just did a pull from master and tried it again, but no luck here....

**Comment by xissy** [comment]
I had the same issue and solved it with `brew install go-delve/delve/delve --HEAD`.

**Comment by tylerlrhodes** [comment]
Hadn't looked at it for a while.

I can confirm that this works on my end too on the MacOS
