### ISSUE TITLE
"locals" printing out var with extra characters in its name: '·2'

### ISSUE THREAD

**Issue by b0o** [derekparker/delve#779]
1. What version of Delve are you using (`dlv version`)? `0.12.1`
2. What version of Go are you using? (`go version`)? `go1.8 darwin/amd64`
3. What operating system and processor architecture are you using? `Darwin 16.4.0 Darwin Kernel Version 16.4.0`

I'm wondering why one of my variables is being printed oddly. Here's a sample debug session:

```
$ dlv test ./sqlx/ --init="./breakpoints.dlv"
Type 'help' for list of commands.
Breakpoint 1 set at 0x1298478 for ****/sqlx.(*Row).scanAny() /****/gocode/src/****/sqlx/sqlx.go:733
(dlv) c
> ****/sqlx.(*Row).scanAny() /****/gocode/src/****/sqlx/sqlx.go:733 (hits goroutine(6):1 total:1) (PC: 0x1298478)
   728:                 r.err = sql.ErrNoRows
   729:                 return r.err
   730:         }
   731:         defer r.rows.Close()
   732:
   733:         v := reflect.ValueOf(dest)
=> 734:         if v.Kind() != reflect.Ptr {
   735:                 return errors.New("must pass a pointer, not a value, to StructScan destination")
   736:         }
   737:         if v.IsNil() {
   738:                 return errors.New("nil pointer passed to StructScan destination")
(dlv) locals
scannable = false
v·2.flag = 22
values.len = 24175792
values.cap = 0
fields.len = 23092064
fields.cap = 842350964104
columns.len = 21244809
columns.cap = 4
v·2.typ = (*reflect.rtype)(0x13a0280)
v·2.ptr = unsafe.Pointer(0xc420077950)
values.ptr = (*interface {})(0x1)
m = (*github.com/jmoiron/sqlx/reflectx.Mapper)(0xc4201c6240)
fields.ptr = (*[]int)(0xc42004f158)
columns.ptr = (*string)(0x12957c1)
base.itab = (*uint8)(0x140b580)
base.data = (*uint8)(0xc4201c6240)
```

I'm wondering why `v·2` is showing up in the output of `locals` when I'd expect it to just be `v`. Also, since the name is using a weird unicode character, I'm unable to `print` the var:

```
(dlv) p v·2
Command failed: 1:2: illegal character U+00B7 '·'
```

Attempting to `print` the variable `v` gives the following error:

```
(dlv) p v
Command failed: could not find symbol value for v
```

My best guess is that this has something to do with the use of reflection?

**Comment by aarzilli** [comment]
Either you did not pass -gcflags='-N -l' while compiling or it's because of this bug: https://github.com/golang/go/issues/19340

**Comment by aarzilli** [comment]
Closing for lack of feedback. Either user error or duplicate of #738
