### ISSUE TITLE
Problems with Go 1.8?

### ISSUE THREAD

**Issue by carlca** [derekparker/delve#781]
Delve 0.12.1
Go 1.8
Win 10 Pro 64 bit Insider Edition

What I did:
dlv debug nodes.go - ok
b main.main - ok
c - ok
s - failed

What I expected to see:
Redisplay of source with execution point at next line

What I actually saw:
Large number of assembler lines followed by Process 17240 has exited with status 2

Thanks in advance.

**Comment by carlca** [comment]
The reason my title is "Problems with Go 1.8?" is that I previously run Delve with Golang 1.7 and it worked perfectly and as expected then. The only thing that has changed on my system is the upgrade to Go 1.8.

**Comment by aarzilli** [comment]
Update your delve to master.

**Comment by carlca** [comment]
Forgive me newbieness, but how do I do that in Git?

**Comment by carlca** [comment]
Forgive my

**Comment by aarzilli** [comment]
```
cd $GOPATH/src/github.com/derekparker/delve/
git checkout master
git pull
go install (or whatever you need to do to compile and copy dlv to PATH)
```

**Comment by carlca** [comment]
That worked perfectly. Thanks!

**Comment by aarzilli** [comment]
You're welcome.
