### ISSUE TITLE
dlv could not start debug on OS X

### ISSUE THREAD

**Issue by jferrer21** [derekparker/delve#789]
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
0.12.2

2. What version of Go are you using? (`go version`)?
1.8.1 darwin/amd64

3. What operating system and processor architecture are you using?
OSX Sierra 10.12.4 

4. What did you do?
Run the program

5. What did you expect to see?
debug info

6. What did you see instead?

2017/04/14 17:18:35 server.go:73: Using API v1
2017/04/14 17:18:35 debugger.go:68: launching process with args: [/Users/jf/Documents/GO/debug]
could not launch process: could not fork/exec
Process exiting with code: 1

**Comment by aarzilli** [comment]
Did you sign the executable?

**Comment by jferrer21** [comment]
Yes.

**Comment by aarzilli** [comment]
Are you sure? Because that error only happens if you are trying to debug something that isn't an executable or if you didn't sign delve correctly.

**Comment by jferrer21** [comment]
I re-install everything, and now it is working.  Thank you.

**Comment by aarzilli** [comment]
You're welcome.
