### ISSUE TITLE
Unable to update "dlv" package in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by blackhatCoder** [derekparker/delve#799]
I am using Ubuntu 16.04 LTS and I have Go-1.6 installed. Whenever I open Atom code editor, `go-debug` package suggests me to update `dlv` package. So I run 
`go get -u github.com/derekparker/delve/cmd/dlv` in terminal to update it. 

But it gives the following error : 

`# github.com/derekparker/delve/pkg/proc/core
Desktop/goWorkspace/src/github.com/derekparker/delve/pkg/proc/core/linux_amd64_core.go:440: undefined: io.SeekCurrent
Desktop/goWorkspace/src/github.com/derekparker/delve/pkg/proc/core/linux_amd64_core.go:447: undefined: io.SeekCurrent
`

How do I resolve this issue ?

**Comment by aarzilli** [comment]
(Here's the fix)[https://github.com/derekparker/delve/pull/800], it's trivial you can even apply it manually.
