### ISSUE TITLE
when installing with homebrew, it was not automatically linked

### ISSUE THREAD

**Issue by deltaskelta** [derekparker/delve#806]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 0.12.2
Build: v0.12.2

2. What version of Go are you using? (`go version`)?

go version go1.8.1 darwin/amd64

3. What operating system and processor architecture are you using?

OSSierra

4. What did you do?

copied and pasted brew install command from readme

5. What did you expect to see?

It installed and I would expect the binary to be automatically linked into my path.

6. What did you see instead?

I had to hunt down the path to the binary in the cellar and then add it to my bash_profile in order to achieve the desired effect. While this is not a "huge" issue for most people, it could make the difference for someone who is not thoroughly familiar with paths and environments (like the $GOPATH issues)

**Comment by JulianZhao** [comment]
I did the same thing with different result: the binary didn't generated, nothing was produced..........

**Comment by deltaskelta** [comment]
I recently installed it again and it was linked this time so I am closing this issue since it must have been fixed somewhere along the way...
