### ISSUE TITLE
Ubuntu Bash Windows 10 dlv debug session hanging

### ISSUE THREAD

**Issue by bamsy** [derekparker/delve#810]
I am currently setting up my go enviroment on Ubuntu bash on Windows 10. And when I run dlv debug the session hangs and I never see the (dlv) prompt.

1. What version of Delve are you using (`dlv version`)?
`Version: 0.12.2`

2. What version of Go are you using? (`go version`)?
`go version go1.8.1 linux/amd64`

3. What operating system and processor architecture are you using?
I am using Ubuntu Bash on Windows 10.
Ubuntu Version:
`Ubuntu 16.04.2 LTS`

4. What did you do?
I ran the following:
`dlv debug log=true`

And I get the following output
`2017/04/29 09:04:17 server.go:73: Using API v1`
`2017/04/29 09:04:17 debugger.go:90: launching process with args: [/home/bamsy/dev/go/src/github.com/bamsy/hello/debug]`

5. What did you expect to see?
I expected to see the (dlv) prompt

6. What did you see instead?

After the above lines were printed  the terminal just appears to be hung and I need to CTRL-C to get out of it.

I did a little debugging and found that the program never exits a for loop in the following function

func (dbp *Process) wait(pid, options int) (int, *sys.WaitStatus, error) 

which is in the following file:
https://github.com/derekparker/delve/blob/master/pkg/proc/native/proc_linux.go

It seems the wpid is always returning 0 with no error and the process is never in a zombie state so the for loop goes forever.

**Comment by aarzilli** [comment]
Delve is supported on linux and windows not on the linux-windows chimera. I'm not even sure ptrace works in that environment. AFAIK even go isn't officially supported there yet (or possibly ever): https://github.com/golang/go/issues/16628, https://github.com/golang/go/issues/17365

**Comment by derekparker** [comment]
Closed due to lack of support for Go with this setup, and the fact that (as mentioned in those threads) it's up to Microsoft to make Linux things work properly using their setup.
