### ISSUE TITLE
Command failed: could not find FDE for PC 0x7fff63374000

### ISSUE THREAD

**Issue by aidylewis** [derekparker/delve#814]
> What version of Delve are you using (`dlv version`)?
```
$ dlv version
Delve Debugger
Version: 0.12.2
Build: v0.12.2
```

> What version of Go are you using? (`go version`)?
```
$ go version
go version go1.8.1 darwin/amd64
```
> What operating system and processor architecture are you using?
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42
```
> What did you do?
```
# $GOPATH/bin
$ dlv exec ./k6 run ~/projects/k6-load-tests/js/gtm.js
Type 'help' for list of commands.
(dlv) n
Command failed: could not find FDE for PC 0x7fff63374000
```
Application
https://github.com/loadimpact/k6

> What did you expect to see?

k6 source file 

>  What did you see instead?
```
Command failed: could not find FDE for PC 0x7fff63374000
```

Many Thanks
@aidylewis

**Comment by derekparker** [comment]
Try setting a breakpoint at main and stepping from there, e.g.:

```
break main.main
continue
```

**Comment by derekparker** [comment]
Related to: https://github.com/derekparker/delve/issues/374

Going to close this as the above steps should fix, please reopen if that isn't the case.

**Comment by aidylewis** [comment]
Good man. Thanks
