### ISSUE TITLE
print panics with runtime error: index out of range

### ISSUE THREAD

**Issue by zhouhuangjing** [derekparker/delve#815]
Delve Debugger: Version: 0.12.2
go version: go1.7.3 linux/amd64
Ubuntu 16.04.1 LTS
Docker: Version 17.03.1-ce-mac5 (16048)
Mac: 10.12.4

I run delve with headless mode in  docker container and then attached it. When I tried to print some complicated object (simple one is fine), delve panics.

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc420228b40, 0x47a5e00, 0xc420064850, 0x4010100, 0xc420019294, 0x2)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:90 +0x93d
github.com/derekparker/delve/service/api.(*Variable).writeStructTo(0xc420228900, 0x47a5e00, 0xc420064850, 0x1, 0x4566e96, 0x1)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:160 +0x26b
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc420228900, 0x47a5e00, 0xc420064850, 0x100, 0x4566e96, 0x1)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:75 +0xf9f
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc4202286c0, 0x47a5e00, 0xc420064850, 0x100, 0x4566e96, 0x1)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:58 +0xc4b
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc420228480, 0x47a5e00, 0xc420064850, 0x4010100, 0x4566e96, 0x1)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:95 +0x8d9
github.com/derekparker/delve/service/api.(*Variable).writeStructTo(0xc420228240, 0x47a5e00, 0xc420064850, 0x1, 0x0, 0x0)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:160 +0x26b
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc420228240, 0x47a5e00, 0xc420064850, 0x100, 0x0, 0x0)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:75 +0xf9f
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc420228000, 0x47a5e00, 0xc420064850, 0x100, 0x0, 0x0)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:58 +0xc4b
github.com/derekparker/delve/service/api.(*Variable).writeTo(0xc4201c2090, 0x47a5e00, 0xc420064850, 0x10101, 0x0, 0x0)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:95 +0x8d9
github.com/derekparker/delve/service/api.(*Variable).MultilineString(0xc4201c2090, 0x0, 0x0, 0xc420019012, 0xa)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/service/api/prettyprint.go:27 +0x7a
github.com/derekparker/delve/terminal.printVar(0xc420066ba0, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0xc420019012, 0xa, 0xc420019012, 0xa)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/terminal/command.go:855 +0x232
github.com/derekparker/delve/terminal.(*Commands).CallWithContext(0xc420132a50, 0xc420019010, 0x1, 0xc420019012, 0xa, 0xc420066ba0, 0x0, 0xffffffffffffffff, 0x0, 0x0, ...)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/terminal/command.go:264 +0xae
github.com/derekparker/delve/terminal.(*Commands).Call(0xc420132a50, 0xc420019010, 0x1, 0xc420019012, 0xa, 0xc420066ba0, 0x1, 0x37)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/terminal/command.go:269 +0x91
github.com/derekparker/delve/terminal.(*Term).Run(0xc420066ba0, 0x0, 0x0, 0x0)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/terminal/terminal.go:132 +0x3bb
github.com/derekparker/delve/cmd/dlv/cmds.connect(0x7fff5fbff73c, 0xf, 0xc4200ef0c0, 0x4567f20)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:367 +0x6b
github.com/derekparker/delve/cmd/dlv/cmds.connectCmd(0xc4200aca00, 0xc420069ac0, 0x1, 0x1)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:352 +0x67
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200aca00, 0xc420069a80, 0x1, 0x1, 0xc4200aca00, 0xc420069a80)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:569 +0x203
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200ac600, 0xc4200ace00, 0xc4200acc00, 0xc4200aca00)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:656 +0x339
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200ac600, 0xc4200001a0, 0xc4200001a0)
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:615 +0x2b
main.main()
	/private/tmp/delve-20170412-11765-1isbpji/delve-0.12.1/src/github.com/derekparker/delve/cmd/dlv/main.go:13 +0x55

**Comment by aarzilli** [comment]
what does the object look like?

**Comment by aarzilli** [comment]
There is no array access at service/api/prettyprint.go:90 in its current version (which is the same as the one in release 0.12.2), I remember there being a bug on that line that could cause this error but it was fixed before 0.12.2 (it's the last commit touching that file).

I'm inclined to believe that this bug has been already fixed in 0.12.2 and you say you are using 0.12.2 but the stack trace clearly says 0.12.1. 

You should update or provide a way to reproduce this.

**Comment by derekparker** [comment]
Please update to `v0.12.2` and reopen if you still experience this issue.
