### ISSUE TITLE
--backend option not available when installing via brew

### ISSUE THREAD

**Issue by ramya-rao-a** [derekparker/delve#816]
1. What version of Delve are you using (`dlv version`)? 0.12.2
2. What version of Go are you using? (`go version`)? 1.8
3. What operating system and processor architecture are you using? Mac OS X El Capitan (10.11.6)
4. What did you do? Run `dlv -h`
5. What did you expect to see? Usage for the `--backend` option
6. What did you see instead? No usage for the `--backend` option

I Installed the latest delve in Windows using `go get`. I can see the `--backend` option there
But not in my Mac when installed via brew

**Comment by derekparker** [comment]
The new backend feature has not made it into an actual release yet, thus homebrew won't have it. We will be cutting a release this week that will include it.

You can try using homebrew to install master of Delve instead of v0.12.2, which will have the feature.

**Comment by ramya-rao-a** [comment]
Thanks!
