### ISSUE TITLE
Cannot debug non-main pkg error when using --backend=lldb option in Windows

### ISSUE THREAD

**Issue by ramya-rao-a** [derekparker/delve#817]
1. What version of Delve are you using (`dlv version`)? 0.12.2
2. What version of Go are you using? (`go version`)? 1.7
3. What operating system and processor architecture are you using? Windows 10 64 bit
4. What did you do? Run `dlv debug hello.go --backend=lldb`
5. What did you expect to see? Delve to start without error
6. What did you see instead? The error `Can not debug non-main package`

The same using `--backend=native` works as expected.

**Comment by derekparker** [comment]
Can you post steps of how using the native backend works? If you're debugging a non-main package, you'd have to debug it via `dlv test`, because `dlv debug` calls `go build` under the hood, which builds main packages.

**Comment by ramya-rao-a** [comment]
It is a main package. Just trying to debug the hello package here: https://github.com/golang/example/blob/master/hello/hello.go

A simple `dlv debug hello.go --backend=native` works fine

**Comment by aarzilli** [comment]
The debug command doesn't take a path to a file but a path to a package. I don't see how `dlv debug hello.go --backend=native` can possibly work.

**Comment by ramya-rao-a** [comment]
`dlv debug . --backend=lldb` and `dlv debug --backend=lldb` also gives the same "Can not debug non-main package" error
`dlv debug . --backend=native` and `dlv debug --backend=native` work fine

**Comment by aarzilli** [comment]
Weird. Can you do `go build -gcflags='-N -l' hello.go` then `dlv --backend=lldb exec ./main`?

**Comment by ramya-rao-a** [comment]
@aarzilli 

`dlv exec ./hello.exe --backend=lldb` gives `./hello.exe is not executable`
`dlv exec ./hello.exe --backend=native` works fine

`stat ./hello.exe` gives the below

![image](https://cloud.githubusercontent.com/assets/16890566/25675082/0c31b53e-2ff2-11e7-844c-2c97d7995835.png)

**Comment by aarzilli** [comment]
Oh, I see. The lldb backend isn't supported on windows. You said you were using windows but apparently I didn't read it. 

The error message is weird however, not sure why that's happening.

**Comment by ramya-rao-a** [comment]
Then all we need is a better error message :)

**Comment by aarzilli** [comment]
Is there a particular reason why you want to use the lldb on windows? I gave it a very very low priority because we are under the impression that the native backend works well on windows.

**Comment by ramya-rao-a** [comment]
Oh, I personally had no intention of using lldb on windows.

Got sucked into the whole `--backend` option due to #818 
From there I was experimenting around the 2 options in different platform and found this.

Also, to fix #818 from VS Code side, I added an option where user can specify the backend option from configuration.

Now for any which reason some one sets it to `lldb` in Windows, they will face this issue.
Therefore thought it would be right to log this

**Comment by aarzilli** [comment]
I see, thanks.
