### ISSUE TITLE
OSX homebrew install failing to populate build version

### ISSUE THREAD

**Issue by SteelPhase** [derekparker/delve#823]
Attempted to update delve using brew `brew reinstall --HEAD go-delve/delve/delve`
It appears as though this [commit](https://github.com/derekparker/delve/commit/24b20099aa3c464cc1f3cb245e82bd836a69c877) may have caused the issue. brew is still attempting to pass in BUILD_SHA

Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
==> Summary
🍺  /usr/local/Cellar/delve/HEAD-f29b9ed: 6 files, 10.2MB, built in 12 seconds
user@host:~$dlv version
Delve Debugger
Version: 0.12.2
Build: 
```
2. What version of Go are you using? (`go version`)?
```
go version go1.8.1 darwin/amd64
```
3. What operating system and processor architecture are you using?
`osx 10.12.4`
4. What did you do?
`dlv version`
5. What did you expect to see?
```
user@host:~$dlv version
Delve Debugger
Version: 0.12.2
Build: f29b9edad20b105f0bede65a6da15cbdd744ff77
```
6. What did you see instead?
```
user@host:~$dlv version
Delve Debugger
Version: 0.12.2
Build: 
```

**Comment by renannprado** [comment]
I've just compiled today (without homebrew) and I also don't have the Build number.

**Comment by SteelPhase** [comment]
This looks to be resolved thanks to the above referenced PR
