### ISSUE TITLE
Dlv cannot attached to a simple GoRoutine

### ISSUE THREAD

**Issue by kktam** [derekparker/delve#853]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?   Version: 1.0.0-rc.1
2. What version of Go are you using? (`go version`)? go version go1.7.3 darwin/amd64
3. What operating system and processor architecture are you using? OSX Sierra, debugging using Visual Studio Code with Go extension and Delve.
4. What did you do? run a simple program from an code example (see code below).
5. What did you expect to see? debugger stops at a debug breakpoint in goroutine GenerateMarkdown()
6. What did you see instead? Debugger stop at main thread, but not inside any breakpoint in GenerateMarkdown().

main.go
```
package main

import (
	"net/http"
	"os"

	"github.com/russross/blackfriday"
)

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	http.HandleFunc("/markdown", GenerateMarkdown)
	http.Handle("/", http.FileServer(http.Dir("public")))
	http.ListenAndServe(":"+port, nil)
}

func GenerateMarkdown(rw http.ResponseWriter, r *http.Request) {
	markdown := blackfriday.MarkdownCommon([]byte(r.FormValue("body")))
	rw.Write(markdown)
}

```

index.html
```
<html>
  <head>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="page-title">
        <h1>Markdown Generator</h1>
        <p class="lead">Generate your markdown with Go</p>
        <hr />
      </div>

      <form action="/markdown" method="POST">
        <div class="form-group">
          <textarea class="form-control" name="body" cols="30" rows="10"></textarea>
        </div>

        <div class="form-group">
          <input type="submit" class="btn btn-primary pull-right" />
        </div>
      </form>
    </div>
    <script src="/js/bootstrap.min.js"></script>
  </body>
</html>


```

**Comment by aarzilli** [comment]
We have a test case (TestNextNetHTTP) that covers exactly this setup, I'm skeptical that this is a problem with delve. Can you reproduce this using the command line interface?

**Comment by kktam** [comment]
@aarzilli can you provide some steps in how to use the cli to perform debugging, and attach go routine to a debugger. Is there any sample code and online documentation?

**Comment by aarzilli** [comment]
`dlv attach <pid> <path to executable>`

**Comment by derekparker** [comment]
Please reopen if still an issue.
