### ISSUE TITLE
Any chance you can get Delve work in Eclipse Che(the docker web IDE)

### ISSUE THREAD

**Issue by JCzz** [derekparker/delve#857]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

**Comment by aarzilli** [comment]
[Several IDE plugins already exist](https://github.com/derekparker/delve/blob/master/Documentation/EditorIntegration.md), I don't think there's anything that would prevent the same being done for Eclipse. But doing the work to develop IDE specific plugins is beyond the scope of this project, if you want to try your hand at it, here's [delve's API documentation](https://github.com/derekparker/delve/blob/master/Documentation/EditorIntegration.md).

**Comment by JCzz** [comment]
Thanks

**Comment by aarzilli** [comment]
Let us know if you need help.

**Comment by JCzz** [comment]
Just lastly; if you can help regarding this Stackoverflow:

https://stackoverflow.com/questions/43987476/unable-to-run-delve-in-eclipse-che-could-not-launch-process-operation-not-per

Any direction is appreciated - thanks

2017-05-31 12:06 GMT+02:00 Alessandro Arzilli <notifications@github.com>:

**Comment by JCzz** [comment]
Cool, thanks for the direction.



2017-05-31 16:17 GMT+02:00 Alessandro Arzilli <notifications@github.com>:
