### ISSUE TITLE
Could not find __debug_frame section in binary

### ISSUE THREAD

**Issue by saleemjaffer** [derekparker/delve#860]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
`Version: 0.12.2`

2. What version of Go are you using? (`go version`)?
`devel +0716fef`

3. What operating system and processor architecture are you using?
`OSX El Captain, darwin/amd64`

4. What did you do?
 `dlv exec \path\to\main\package`

5. What did you expect to see?
Expected the debugger to start

6. What did you see instead?
Got this msg: `could not find __debug_frame section in binary`

I built the binaries using `go install -gcflags '-N -l'`

**Comment by aarzilli** [comment]
This is probably an issue with the linker, what packages are you importing in your binary? Specifically I'm looking for anything that would use cgo.

**Comment by aarzilli** [comment]
Just to clarify. This `\path\to\main\package` is the path to an executable file, right?

**Comment by saleemjaffer** [comment]
Yes the `path\to\main\package` is the path to an executable. 

My main package imports other packages too. So I have mentioned all the packages imported by the non main packages too.

"context"
"math/rand"
"time"
"sync"
"database/sql"
"net/url"
"github.com/lib/pq/hstore"
"io"
"mime/multipart"
"os"
"path/filepath"
"strconv"
"strings"
"plugin"
"encoding/json"

**Comment by aarzilli** [comment]
I see now that `0716fef` is a 1.8 pre-release. I imagine you are using it because plugin support was removed during the 1.8 beta. We don't support unreleased versions of go, especially since the most likely cause of this bug is the plugin package, which is known to be broken on macOS.

**Comment by saleemjaffer** [comment]
:( So the bottomline is if I am using Go plugins on a Mac I cannot use Delve?

**Comment by aarzilli** [comment]
Correct.
