### ISSUE TITLE
Can't run a go program unless it's the only main program in the current directory (i.e. it can be compiled with "go build")

### ISSUE THREAD

**Issue by raff** [derekparker/delve#87]
"dlv run" should work like "go run" and allow passing a go source file to compile and run. Right now it executes "go build" with no source files, that doesn't work if the current directory contains multiple files implementing "main".

Suggestion: if the first parameter after "dlv run" is "name.go", assume it's the program to run and call "go build" appropriately.

**Comment by sharpner** [comment]
It would be awesome if this behaviour could be documented...
took me a while to figure out that dlv run does work differently from go run =)

**Comment by derekparker** [comment]
Closing due to moving discussion to: https://groups.google.com/forum/#!topic/delve-dev/xjf3jyGfA_w
