### ISSUE TITLE
Can't reach a breakpoint, stuck in another function

### ISSUE THREAD

**Issue by krasi-georgiev** [derekparker/delve#872]
https://gist.github.com/krasi-georgiev/516155ca4808606e77037149f9995869

`dlv debug`
`b main.go:24`
`c` 

it never reaches a breakpoint at `fmt.Println(bufStream)`

`c` cicles back to `return newError(C.Pa_StartStream(s.paStream))`
in portaudio.go 

Delve Version: 1.0.0-rc.1
go1.8 darwin/amd64
go-debug 1.4.3

Here is a short video
https://screencast.com/t/gzxr1utP2b0t

I posted this in the Atom github but it is delve related as I can reproduce in the terminal as well

https://github.com/lloiser/go-debug/issues/102

**Comment by jcbritobr** [comment]
this happens on windows 10 home edition.

dlv version: 1.0.0-rc.1
go1.8 win/amd64

it continues wthout hit a breakpoint.

here is the trace:

2017/06/14 09:44:48 server.go:73: Using API v1
2017/06/14 09:44:48 debugger.go:97: launching process with args: [C:\goworkspace\src\filetraining\debug]
API server listening at: 127.0.0.1:2345
2017/06/14 09:44:49 debugger.go:504: continuing

**Comment by aarzilli** [comment]
@jcbritobr your problem seems different, there is no `created breakpoint` message in the log, why should it stop at a breakpoint?

**Comment by friends110110** [comment]
https://github.com/derekparker/delve/issues/961
mac also can not reach the breakpoint
