### ISSUE TITLE
DYLD_ / LD_ environment variables will not be forwarded correctly on OS X

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#877]
Hi,

Here's an interesting issue: https://youtrack.jetbrains.com/issue/GO-4001#comment=27-2237730

According to the information available here: https://stackoverflow.com/a/33589760/951414 it seems that OS X doesn't like forwarding any of the DYLD_ or LD_ to the applications anymore, for "security" reasons.

As such, when using the lldb backend on OS X, some applications will fail to launch. The IDE will forward the said environment variable when configured manually but I'm not sure if Delve itself needs to then do anything special to pick it up and then forward it itself to the lldb backend.

I'll try and work on a patch for this soon, but given my 0 experience with this stuff, any pointers / solutions would be welcomed.

(and yes, I know that the users can disable the "security" feature but I'm not sure what effects that will have)

**Comment by aarzilli** [comment]
I guess in gdbserver.go we should scan our environment and pass anything starting with LD_ and DYLD_ using the `-e NAME=VALUE` option of debugserver... that should work.

**Comment by dlsniper** [comment]
I'll have a patch in the next couple of days.

**Comment by aarzilli** [comment]
Have fun!
