### ISSUE TITLE
fail to pass flags to the program in macos

### ISSUE THREAD

**Issue by buf1024** [derekparker/delve#878]
according to the guide, it seems fail to pass arguments to to the program.

the test program code:
```go
package main

import "flag"
import "fmt"

func main() {
	file := flag.String("c", "", "configuration file")
	flag.Parse()
	fmt.Printf("file=%s\n", *file)
}
```

the relate program info:
```
luoguochundeMacBook-Pro:bin luoguochun$ dlv version
Delve Debugger
Version: 1.0.0-rc.1
Build:
luoguochundeMacBook-Pro:bin luoguochun$ go version
go version go1.8.3 darwin/amd64
```
the os is macos 10.12.5.

and I use the following command to debug the test program:
```
luoguochundeMacBook-Pro:bin luoguochun$ dlv exec main -- -c abc.conf
Type 'help' for list of commands.
(dlv) r
Process restarted with PID 14692
(dlv) c
file=
Process 14692 has exited with status 0
(dlv) 
```
it is expected to print the args "-c abc.conf", but actually, prints empty string.

is this the wrong way the pass args the the debug program? 
thanks a lot!

**Comment by aarzilli** [comment]
Update to master and see if it still happens, it should be fixed.

**Comment by buf1024** [comment]
@aarzilli thank you, the master branch indeed fixed the bug!
