### ISSUE TITLE
Can't put breakpoint 

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#879]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
The latest delve from the master.
2. What version of Go are you using? (`go version`)?
1.8
3. What operating system and processor architecture are you using?
mac os x
4. What did you do?
I've started one dlv in headless mode 
`dlv debug --headless --listen=:2345 --log --api-version=2`
inside the webinar directory from https://github.com/dlsniper/webinar/blob/master/webinar.go
And another one 
`dlv connect :2345`
and hit `continue`
5. What did you expect to see?
I'd like to put a breakpoint on line 30, inside the handler.
6. What did you see instead?
Just a hanging terminal :–)

**Comment by aarzilli** [comment]
What's the output on the terminal that you are running the headless server on? Are you getting debugserver's authorization prompt? This works for me...

**Comment by ignatov** [comment]
```
webinar > dlv debug --headless --listen=:2345 --log --api-version=2
2017/06/15 16:55:41 debugger.go:97: launching process with args: [/Users/ignatov/src/gocode/src/github.com/dlsniper/webinar/debug]
API server listening at: [::]:2345
2017/06/15 16:55:47 debugger.go:504: continuing
2017/06/15 16:55:47 starting server...
```

and 
```
~ > dlv connect :2345
Type 'help' for list of commands.
(dlv) c

```
and I can't type inside the second terminal.
If I press Ctrl+C I'll get
```
received SIGINT, stopping process (will not forward signal)> runtime.mach_semaphore_wait() /usr/local/Cellar/go/1.7.1/libexec/src/runtime/sys_darwin_amd64.s:418 (PC: 0x59beb)
   413:	// func mach_semaphore_wait(sema uint32) int32
   414:	TEXT runtime·mach_semaphore_wait(SB),NOSPLIT,$0
   415:		MOVL	sema+0(FP), DI
   416:		MOVL	$(0x1000000+36), AX	// semaphore_wait_trap
   417:		SYSCALL
=> 418:		MOVL	AX, ret+8(FP)
   419:		RET
   420:
   421:	// func mach_semaphore_timedwait(sema, sec, nsec uint32) int32
   422:	TEXT runtime·mach_semaphore_timedwait(SB),NOSPLIT,$0
   423:		MOVL	sema+0(FP), DI
(dlv)
```

**Comment by aarzilli** [comment]
What if you type `b webinar.go:30` in the second terminal? After pressing Ctrl-C

**Comment by ignatov** [comment]
I can put a breakpoint after Ctrl+C.
But initially I was trying to do the same from the IntelliJ plugin and failed, looks like delve is hanging until Ctrl+C. And it's impossible to install breakpoint over JSON-RPC.

**Comment by aarzilli** [comment]
It's hanging until Ctrl+C because you gave the `c` command, if you don't give it, it should accept the breakpoint immediately. Same thing with the API, if you get the breakpoint in before the continue it should take it. Also Ctrl+C isn't special, it just sends a request for RPCServer.Command with parameter "halt".

**Comment by ignatov** [comment]
We usually send 'continue' command to the debugger after connection, why do I need to send 'halt'. Could you explain that please?

**Comment by aarzilli** [comment]
Continue will resume the target process, while the target process is running breakpoints can't be added or removed. If you need to set a breakpoint you should do it before starting the target. Even if we did let clients set breakpoints on a running process (which is impossible) your client would have a race condition with the target process (breakpoint only gets hit if you manage to set it before the target goes over that instruction).

**Comment by ignatov** [comment]
That sounds strange. You said that I couldn't change breakpoints on a running process, but every graphical debugger I've ever seen has such ability.
That means that we need stop the target process, install breakpoints and resume it again, right?

**Comment by aarzilli** [comment]
> That means that we need stop the target process, install breakpoints and resume it again, right?

Yes.

**Comment by ignatov** [comment]
Do I need to call `halt` command for that?

**Comment by aarzilli** [comment]
Yes.

**Comment by ignatov** [comment]
Will be cool to have such breaks for putting breakpoints inside the debugger virtual machine, not on the client side. Also, inside the debugger VM we could do these operations synchronously.

We've already had several debugger clients for JS backends in browsers, and only in Firefox, you need to stop the whole world for this operation. It's quite inconvenient and requered a lot of work from the client.
@derekparker what do you think?

**Comment by aarzilli** [comment]
> Will be cool to have such breaks for putting breakpoints inside the debugger virtual machine

I should point out that there is no virtual machine.

**Comment by ignatov** [comment]
OK, the remote process.

**Comment by aarzilli** [comment]
We could do the halt/set breakpoint/restart in our `service/debugger` package, probably.

**Comment by aarzilli** [comment]
No, not in `service/debugger` it would have to be in the rpc server. But it would mess badly with how we do the locking.

**Comment by derekparker** [comment]
Hmm... if we can find a good, reasonable way to accomplish this I'm all for adding this functionality to the Delve API.

**Comment by ignatov** [comment]
I've already emulated this behaviour on my side, but it's a bit complicated, thread state boolean flags and so on.
So, there's no rush at the moment.

**Comment by derekparker** [comment]
Going to close this for now, but I'm still open to adding a new method to our API to hide some of the details, if it makes sense.
