### ISSUE TITLE
build tags are not documented or maybe are not supported

### ISSUE THREAD

**Issue by karlmutch** [derekparker/delve#881]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.0.0-rc1

2. What version of Go are you using? (`go version`)?
1.8.3

3. What operating system and processor architecture are you using?
Ubuntu 14.04

4. What did you do?
used the -tags option for conditional compilation both before and after the -- inside dlv test, dlv debug

Examples I tried included

 9992  dlv test -test.v -tags "NO_CUDA" -loglevel=debug
 9993  dlv test -test.v --build-flags "-tags NO_CUDA" -loglevel=debug
 9994  dlv debug -test.v --build-flags "-tags NO_CUDA" -loglevel=debug
 9995  dlv debug -test.v -tags "NO_CUDA" -loglevel=debug
 9996  dlv debug -test.v --build-flags "NO_CUDA" -loglevel=debug

However the NO_CUDA never seemed to take effect at the build step

5. What did you expect to see?
The code conditionally compiled to include code or exclude code specified by the go build -tag option

6. What did you see instead?
tag is being ignored

**Comment by karlmutch** [comment]
Answer 👍 

dlv test  --build-flags "-tags "NO_CUDA""

**Comment by jpap** [comment]
Multiple tags didn't work for me using @karlmutch's approach.  What worked for me was to mix single and double quotes as follows:
```
dlv test --build-flags="-tags 'TAG1 TAG2 TAG3'"
```
