### ISSUE TITLE
did not debug go use dlv

### ISSUE THREAD

**Issue by kingangelAOA** [derekparker/delve#897]
use atom go-debug

go version: 1.8.3
system: mac
when i debug go
Starting delve with config "Debug"
Delve output: could not launch process: dial tcp :60451: getsockopt: connection refused
delve closed with code 1

**Comment by aarzilli** [comment]
```
stat /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver
```

If you don't have it install XCode's command line tools.

**Comment by derekparker** [comment]
Please reopen with more information if this problem persists.
