### ISSUE TITLE
Compile Fail via LiteIDE， Please help me what‘s problem has been happened..!!

### ISSUE THREAD

**Issue by shiminyang** [derekparker/delve#899]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
**A:   I downloaded the source code from Github  and link is  - github.com/derekparker/delve**
2. What version of Go are you using? (`go version`)?
**A:  go version go1.8 windows/amd64**
3. What operating system and processor architecture are you using?
**A: OS  -  windows 10 / Intel(R) Core(TM) i5 CPU @3.20Ghz 3.19Ghz**
4. What did you do?
**A:  I want compile the delve via source code I downloaded by using LiteIDE**
5. What did you expect to see?
**A:  I  expect delve compile is OK.!!**
6. What did you see instead?
**A:  Some exceptions are as follow:
**# _/F_/go_registry/delve_for_go_debugging/delve-master/cmd/dlv
.\main.go:13: too many arguments in call to cmds.New
	have (bool)
	want ()****

**Comment by aarzilli** [comment]
You didn't install delve correctly, delete `F:\go_registry\delve_for_go_debugging\` and [follow the instructions](https://github.com/derekparker/delve/blob/master/Documentation/installation/windows/install.md)
