### ISSUE TITLE
Cannot debug golang using intellij idea 2017

### ISSUE THREAD

**Issue by ignatov** [derekparker/delve#900]
We have an issue in our issue tracker:
https://youtrack.jetbrains.com/issue/GO-4060

> I tried to debug a simple hello world application on windows and get the following error:
could not get Go symbols runtime.pclntab and runtime.epclntab symbols must be in the same section

> IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by aarzilli** [comment]
Which version of go, and what does the source code to this simple hello world program looks like. The binary output of `go build -gcflags '-N -l'` could also be helpful.

**Comment by alexbrainman** [comment]
Dup of golang/go#14710 ?

Alex

**Comment by aarzilli** [comment]
No feedback
