### ISSUE TITLE
why could not show some variable when debuging the go program?

### ISSUE THREAD

**Issue by jiebanghan** [derekparker/delve#906]
The result is  below:

> github.com/ethereum/go-ethereum/internal/ethapi.(*PublicDebugAPI).PrintBlock() ./mychain/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:1392 (PC: 0xafc5e1)
  1387:         return fmt.Sprintf("%x", encoded), nil
  1388: }
  1389:
  1390: // PrintBlock retrieves a block and returns its pretty printed form.
  1391: func (api *PublicDebugAPI) PrintBlock(ctx context.Context, number uint64) (string, error) {
=>1392:         block, _ := api.b.BlockByNumber(ctx, rpc.BlockNumber(number))
  1393:         if block == nil {
  1394:                 return "", fmt.Errorf("block #%d not found", number)
  1395:         }
  1396:         return fmt.Sprintf("%s", block), nil
  1397: }
(dlv) p block
Command failed: could not find symbol value for block
(dlv)

So please tell me how to show block? is there some setting in Makefile in order to debug it?

**Comment by aarzilli** [comment]
The reason is almost certainly that the compiler optimized away or registerized the block variable. You will have to compile with optimizations disabled (`go build -gcflags '-N -l'`), see also https://github.com/golang/go/issues/19340

**Comment by jiebanghan** [comment]
thank you very much

**Comment by jiebanghan** [comment]
GOBIN = build/bin
GO ?= latest

geth:
        build/env.sh go run -gcflags='-N -l'  build/ci.go  install ./cmd/geth
        @echo "Done building."
        @echo "Run \"$(GOBIN)/geth\" to launch geth."

i modified it above, but the error is the same. could not see the variable

**Comment by aarzilli** [comment]
You should ask the ethereum project, I don't know.

**Comment by jiebanghan** [comment]
Ok, thank you very much

**Comment by derekparker** [comment]
@jiebanghan it looks like from your example you're adding the compiler flags to the `go run` step instead of the `go install` step, maybe try that instead and see if it works.
