### ISSUE TITLE
Debugging hangs when polling for Amazon SWF activities

### ISSUE THREAD

**Issue by shaunenslin** [derekparker/delve#907]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?   Version: 1.0.0-rc.1
2. What version of Go are you using? (`go version`)?  go version go1.8 darwin/amd64
3. What operating system and processor architecture are you using?  OSX Sierra

4. What did you do? 
I used to use godebug, but moving to delve, but having an issue working with Amazon's simple workflow engine.
I have a go program which poles for an Amazon SWF workflow activity. See below on line 94.
The polling works by either waiting for a minute, or when an activity is received, we should move onto line 95.
![screen shot 2017-06-30 at 9 59 47 am](https://user-images.githubusercontent.com/15326780/27726972-e27f5f26-5d7c-11e7-977a-455f09bcbc79.png)

5. What did you expect to see?
In GODEBUG, it will wait on line 94 until an SWF activity is started and then continue debugging on line 95.
ps. Just for info the code does work and if I run without delve, then the GO code does work as expected.

6. What did you see instead?
As below, debugging seems to hang and even after starting the workflow, dlv doesnt seem to pick it up and continue onto line 95. However, you will see at the bottom we just seem to sit in a waiting s
![screen shot 2017-06-30 at 10 08 30 am](https://user-images.githubusercontent.com/15326780/27726854-54fc2544-5d7c-11e7-8a0c-eca5c46fc27b.png)

Is this an issue

**Comment by aarzilli** [comment]
`kill -QUIT <pid of dlv process>` when it gets stuck

**Comment by shaunenslin** [comment]
Could do, but the problem here is that it always gets stuck on any sort of poling of amazon swf activities.

https://docs.aws.amazon.com/sdk-for-go/api/service/swf/#SWF.PollForDecisionTask

Any idea why it would always get stuck at that point?
Is there anything I can run to outside of the debug environment to see why it may be stuck?

**Comment by aarzilli** [comment]
There is a known cause for delve getting stuck on macOS: https://github.com/derekparker/delve/issues/902. However this looks too deterministic to be that, is it possible that by using the debugger you slowed down your process too much, and amazon just decided to hang up on you?

**Comment by shaunenslin** [comment]
ok, could be a mac issue as it is working ubuntu with go 1.6
I will try the aarzilli:manualstopcond branch on my mac and let you know.

thanks a mill for all your efforts.

**Comment by derekparker** [comment]
Please reopen if still an issue.
