### ISSUE TITLE
Compilation error: reference to undefined identifier 'syscall.PTRACE_PEEKUSR` (Archlinux)

### ISSUE THREAD

**Issue by crinkelite** [derekparker/delve#908]
1. What version of Delve are you using (`dlv version`)?
commit dbc1ce1e5bee25ba16ac27a7945fe0e970aa7ed6 (HEAD -> master, origin/master, origin/HEAD)
Author: custa <custa@users.noreply.github.com>
Date:   Tue Jun 6 05:20:10 2017 +0800

2. What version of Go are you using? (`go version`)?
go version go1.8.1 gccgo (GCC) 7.1.1 20170528 linux/amd64

3. What operating system and processor architecture are you using?
Linux bigarch 4.11.7-1-ARCH #1 SMP PREEMPT Sat Jun 24 09:07:09 CEST 2017 x86_64 GNU/Linux

4. What did you do?
`go get github.com/derekparker/delve/cmd/dlv`
I've also tried
`make install` on the latest github commit.

5. What did you expect to see?

6. What did you see instead?
\# github.com/derekparker/delve/pkg/proc/native
go/src/github.com/derekparker/delve/pkg/proc/native/ptrace_linux.go:47:60: error: reference to undefined identifier ‘syscall.PTRACE_PEEKUSR’
  _, _, err := syscall.Syscall6(syscall.SYS_PTRACE, syscall.PTRACE_PEEKUSR, uintptr(tid), uintptr(off), uintptr(unsafe.Pointer(&val)), 0, 0)

**Comment by aarzilli** [comment]
Looks like a problem with either gccgo or the arch build of gccgo. Did you build it yourself or did you get it from the arch repository?

**Comment by crinkelite** [comment]
I got gccgo from the from the arch repositories. 
I suppose I'll try to compile my own to see if that helps.

**Comment by derekparker** [comment]
Please reopen if the issue persists past the above resolution steps.
