### ISSUE TITLE
Can you support go 1.4 >?  It seems to not work with go 1.4 on Mac OSX.

### ISSUE THREAD

**Issue by hasjoel** [derekparker/delve#91]
When attempting to run with go1.4.2 ( I know docs say you need go 1.4):
make install

I get this error.

import <home>/go/pkg/darwin_amd64/github.com/derekparker/delve/dwarf/util.a: object is [darwin amd64 go1.4.2 X:precisestack] expected [darwin amd64 go1.4 X:precisestack]

Can go1.4.2 be supported, too?

**Comment by derekparker** [comment]
I'm running go 1.4.2 on OS X with no problems. Have you built previously with an older version of Go? Trying clearing out anything Delve related in pkg and try again.

**Comment by hasjoel** [comment]
That was it.  Must have compiled under 1.4 at one point then upgraded to 1.4.2.  Removing everything under pkg worked fine for me.
