### ISSUE TITLE
Goglang IDE and delve debugger

### ISSUE THREAD

**Issue by abzfarah** [derekparker/delve#918]
Not sure if this is related to the delve debugger, but when I try to run the debugger via Gogland (newest version) I get the error.

`Error running Build mattermost.go and run: Cannot run program "/Volumes/Gogland 1.0 EAP/Gogland 1.0 EAP.app/Contents/plugins/intellij-go-plugin/lib/dlv/mac/dlv" (in directory "/Users/***/go/src/github.com/mattermost/platform"): error=13, Permission denied`

Any ideas how I can resolve this, or is this Gogland issue?

thanks in advance

**Comment by hemant24** [comment]
Hi abzfarah,

I am also facing same issue. How did you able to resolve it ?

Thanks in advance

**Comment by abzfarah** [comment]
@hemant24 Hey make sure the IDE is MOUNTED on the drive. Open it from the applications folder.
