### ISSUE TITLE
Setting a breakpoint on main.init doesn't properly show the code location/listability

### ISSUE THREAD

**Issue by jgeiger** [derekparker/delve#922]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
https://github.com/derekparker/delve/commit/07e53f7cbb0b5329f698d61ea309eb997c14e4b9
```
➜  /tmp dlv version
Delve Debugger
Version: 1.0.0-rc.1
Build: 
```
2. What version of Go are you using? (`go version`)?
```go version go1.8.3 linux/amd64```
3. What operating system and processor architecture are you using?
Mint + upgrades
```
➜  uname -a
Linux host-linux 4.10.17-041017-generic #201705201051 SMP Sat May 20 14:53:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

4. What did you do?
Source:
```
package main

import "fmt"

func init() {
	fmt.Println("I am in init")
}

func main() {
	fmt.Println("I am in main")
}
```
Commands:
```
dlv debug
b main.init
b main.main
c
ls
```

5. What did you expect to see?
Something similar to: (the first line may not be correct, it was just copied and edited from the "what I did see"
```
> main.main() ./example.go:5 (hits goroutine(1):1 total:1) (PC: 0x47b8a8)
     4:	
=> 5:	func init() {
     6:		fmt.Println("I am in init")
     7:	}
     8:	
     9:	func main() {
    10:		fmt.Println("I am in main")
    11:	}
```

6. What did you see instead?
```
> main.init() ./example.go:12 (hits goroutine(1):1 total:1) (PC: 0x47b99f)
     7:	}
     8:	
     9:	func main() {
    10:		fmt.Println("I am in main")
    11:	}
```

**Comment by aarzilli** [comment]
`main.init` (and any init function in general) is a compiler generated function, the reason is that it can be defined multiple time and that it needs to call the init of imported packages, see this example: https://play.golang.org/p/RzZh4JhnSv

If you do `disass -l main.init` you can see what the autogenerated init does. If you want to set a breakpoint in one specific init function `b file:line` is the easiest way.

**Comment by jgeiger** [comment]
I've added #928 to update the docs to reflect this suggestion.
