### ISSUE TITLE
Feature request: display full strings

### ISSUE THREAD

**Issue by DexterHaslem** [derekparker/delve#927]
When displaying long strings in the debugger, it will say "...+<num chars remaining> more",
eg "some really long string that is probably a url...+123 more". This makes it impossible to get the actual value out of the debugger because watches, debug console and trying to copy value all return this ellipsis version of the string.

I assume there was some reason for not displaying full strings which could understandably get big, but adding an option or way to enable verbatim strings would be nice.

**Comment by aarzilli** [comment]
@derekparker this feature request has come up multiple times, should we add a `configure` command to the command line to change this kinds of parameters?

**Comment by derekparker** [comment]
@aarzilli yeah, that seems fine, also an entry in the config file as well. Could be a flag on `print` also.

**Comment by zhouhaibing089** [comment]
another thing is: could we also add an option to display `[]byte` as string?
