### ISSUE TITLE
Delve crashes when single stepping through optimization disable program

### ISSUE THREAD

**Issue by dhanunjay** [derekparker/delve#93]
package main

import ( 
"fmt"
"github.com/bsphere/le_go"

 )
 
 
func main() {
 le, err := le_go.Connect("########-####-####-####-##########") // replace #s with token

 if err != nil {
 panic(err)
 }
 c:= make(chan int, 1)
 go tst("go routine", c)

 defer le.Close()

 le.Println("Logentries test log message")
 v:= <-c
 fmt.Println(v)
}

func tst(name string, c chan<- int) {
	fmt.Println(name)
	c <- 1
}

Repro Steps:
1. Compile the above program with: go build -gcflags -N
2. set a break point at statement 'c:= make(chan int, 1)'
3. set a break point at statement 'func tst(name string, c chan<- int) {'
4. continue and then keep single step (N command)

Expected: no crash
Actual: crashes with error: panic: Could not read byte

**Comment by derekparker** [comment]
Thought I had labelled this before, but thanks for opening this.

**Comment by derekparker** [comment]
Should be fixed now, if this is still an issue feel free to reopen.
