### ISSUE TITLE
After upgrade to dlv can no longer do dlv attach

### ISSUE THREAD

**Issue by rlk833** [derekparker/delve#930]
I used homebrew to upgrade delve to 1.0.0-rc.1 on a Mac OS 10.11.6 (15G1510). Since then I can no longer do dlv attach pid. dlv debug still works.

When I do dlv attach _pid_  I get
`could not attach to pid 18272: must specify executable path on macOS`

I don't know where to go from here. What executable path? dlv started fine, the process is running fine. My current directory is the source directory in go of my main.go, just like always.

1. Delve 1.0.0-rc.1
2. Go go1.8.3 darwin/amd64
3. Mac OS 10.11.6

Thanks.

PS: I tried sudo dlv attach, same error.

**Comment by aarzilli** [comment]
> What executable path?

the one that's running on the process you are attaching to.

**Comment by rlk833** [comment]
I'm sorry, I don't understand what that means. The process is already executing. So it must have an executable path.  How could it be running without a path?

Nothing has changed on how I start the process since before upgrading to the latest delve. Something related to the upgrade, or the the homebrew upgrade procedure, is causing the problem.

**Comment by aarzilli** [comment]
> I'm sorry, I don't understand what that means. The process is already executing. So it must have an executable path. How could it be running without a path?

Yes, that's right. You have to pass that path to delve so it can load debug symbols from it.

In principle we could get it from the process id but we need to be a signed executable to do that and we're trying to avoid that.

**Comment by derekparker** [comment]
@rlk833 if you run `dlv help attach` the output will show you the full syntax for running that command.

**Comment by rlk833** [comment]
@derekparker Thanks, I see that now, though without the above explanation here I wouldn't of understood what that meant. 

I was previously running a pre-1.0.0 version and it didn't require this. It may of been it was signed, not sure.

**Comment by tommitytom** [comment]
I'm having the exact same issue with this.  The documentation doesn't seem very clear.  Is it the `--wd` flag I need to be setting here?  I have tried to the following to no avail:

`dlv attach 26577 --wd "."`
`dlv attach 26577 --wd="."`
`dlv attach 26577 --wd=.`
`dlv attach 26577 --wd ${GOPATH}/bin`
`dlv attach 26577 --wd "${GOPATH}/bin"`

Plus loads of other variations how I expect flags may be passed, and many variations on the path that I'm running my application from.  Maybe you could give an example?

**Comment by aarzilli** [comment]
No you need to pass the path of the executable you are attaching to.

**Comment by shabbyrobe** [comment]
I had the exact same problem too. Passing the exact path of the executable in all of the variations listed above doesn't resolve the issue. No amount of Ring TFM seems to have helped.
