### ISSUE TITLE
Need help configuring launch.json to debug a docker container from Visual Studio Code

### ISSUE THREAD

**Issue by rpfister51** [derekparker/delve#942]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

> dlv version
Delve Debugger
Version: 1.0.0-rc.1
Build:

2. What version of Go are you using? (`go version`)?

> go version
go version go1.8.3 windows/amd64

3. What operating system and processor architecture are you using?

Client:
Windows 10 Enterprise, version 1607
Intel 64-bit operating system, x64-based processor

Container:
Debian GNU/Linux 8

4. What did you do?

I started a container process with:
dlv exec ./collector -l 0.0.0.0:2320 --headless=true --log=true -- --config=/go/src/perfhub-worker/configs/collector-config.json --workerid="4"

I set a breakpoint in Visual Studio Code and started a debug session, with the "Attach to perfhub collector" configuration from the following launch.json file.

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to perfhub collector",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "remotePath": "/go/src/perfhub-collector/collector",
            "port": 2320,
            "host": "localhost",
            "program": "${workspaceRoot}",
            "env": {"GOPATH": "C:/Users/rpfister/go",
                    "GOROOT": "C:/Go"},
            "args": [],
            "showLog": true
        }
    ]
}

I was then able to step through code.  But, at a certain point, the container exited, but VS Code continued to step through code as if nothing had happened.

5. What did you expect to see?

I expected the VS Code debug session to somehow notice that there was no response to "next".  A message such as "Connection lost, unable to step over " (or continue, or step into...) would be appropriate,   The it should stop debugging.

6. What did you see instead?

VS Code debug continued to behave as if it were continuing to control execution in the docker container.

**Comment by rpfister51** [comment]
I've studied this and see that I should have "mode": "remote" (not "debug") to connect to the headless dlv server I started in a docker container.  I think I was actually debugging a process started locally by VS Code.  I'm still frustrated; I've spent a lot of time trying to figure the right way to connect to a docker container.  Any help would be appreciated.

**Comment by aarzilli** [comment]
You should map the port 2320 to a host port (assuming you aren't already doing that) then connect to it with whatever configuration vscode takes to connect to a remote instance of delve.

**Comment by rpfister51** [comment]
Thanks @aarzilli for your response.  I have mapped port 2320 to host port 2320, so that's not the problem.  The "configuration vscode takes" is the problem.  The Visual Studio Code documents essentially say to use the configuration attributes expected by your debugger (https://code.visualstudio.com/docs/editor/debugging), with some generic discussion of attributes that are commonly used.  There is also some hover help, which I have found so far to be misleading.

Visual Studio Code pushes the problem to debugger; Delve doesn't really document - at least as far as I can see - how to use VS Code with Delve.  I'm left in the middle.

Any suggestions from users who successfully debug docker containers from Visual Studio Code would be appreciated.

**Comment by aarzilli** [comment]
This is something that's handled by the VSCode plugin, if it's not documented anywhere you'd have to read the source code of that or ask for help [here](https://github.com/Microsoft/vscode-go). I can't help you because I don't use VSCode.

**Comment by rpfister51** [comment]
Here's what I've figured out about launch.json (the configuration file for the debugger within Visual Studio Code) so far; I'd appreciate any corrections.

“name”: This is a string, user defined, that identifies this particular launch configuration.  It will display in the debug viewlet, but has no other purpose.

“type”: “go” is the only value that works for debugging a go program.

“request”: “launch” is the only value that works for debugging a go program.  Hovering over this value can be misleading because it suggests that the value can be either “launch” or “attach”. It looks like, for Delve, the go debugger, the only acceptable value is “launch”.

“mode”:  The hover help says "One of 'debug', 'remote', 'test', 'exec'." It looks like debug, test, and exec are for testing are for debugging locally.  It seems like remote is the only logical choice, but hasn't worked yet.

“remotePath”: The hover help is "If remote debugging, the path to the source code on the remote machine, if different from the local machine." Seems straightforward.

“port”: The hover help is "The port that the delve debugger will be listening on." Again, seems straightforward, I've set this to the port configured on the remote machine by the dlv exec command.

“host”: The hover help is "The host name of the machine the delve debugger will be listening on." Here I'm a little less sure what to do. In my case both the docker container and VS 
Code are on the same machine - my development machine.  In the delve command within the docker container I set it to listen on 127.0.0.1, so I set this configuration attribute to the same value.

“program”:  The hover help is "Path to the program folder (or any file within that folder) when in 'debug' or 'test' mode, and to the pre-built binary file to debug when in 'exec' mode."  Since I'm in remote mode, maybe I should not have this set.

"env": The hover help is "Environment variables passed to the program."  Does this have any applicability when in remote mode?

**Comment by rpfister51** [comment]
The current status is that I seem to be able to connect to the remote server, but I'm not able to step through code.  The debugger seems to freeze, as shown in the attached file.

Verbose logs as written to Debug Console:
`C:\Users\rpfister\AppData\Local\Temp\vscode-go-debug.txt
11:38:18 AM, 8/9/2017
InitializeRequest
InitializeResponse
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: C:\Users\rpfister\go\src\perfhub-collector\perfhub-collector.go (C:/Users/rpfister/go/src/perfhub-collector/perfhub-collector.go) :100
Creating on: C:\Users\rpfister\go\src\perfhub-collector\perfhub-collector.go (C:/Users/rpfister/go/src/perfhub-collector/perfhub-collector.go) :101
`
![frozen](https://user-images.githubusercontent.com/12035948/29130488-fb5058b2-7cf7-11e7-9e78-0c639cb3eabd.png)

**Comment by rpfister51** [comment]
The latest is that I can connect to the headless server (the one inside the docker container) easily enough from the command line.  I can set breakpoints, list them, and step through the code.  I just can't do it from Visual Studio Code.

**Comment by rpfister51** [comment]
I now see this as a VS Code bug; not a delve problem.

**Comment by JCzz** [comment]
Did you ever succeed in remote debug with VS code? If so I would very much like the step. Thanks in advance. I can tell you that I have also looked at eclipse che as a potential ide. I guess we a all looking for at good ide that supports delve - or some documentations on making it work :-)

Just a note to derekparker: Thanks for the good work on Delve

**Comment by rpfister51** [comment]
Yes, it does now work.  This is not a delve problem, but a bug in the go plugin for Visual Studio Code (vscode-go) that was causing problems.  That was corrected and put into an August; so if you have the a version of the plugin no older than that you should be fine.

Have you tried the sample project at https://github.com/lukehoban/webapp-go/tree/debugging ?

Be sure you're on the debugging branch and look for the launch.json file in the .vscode directory.  Be sure to read the comments that explain how to use it.  If you still have questions you can send me an email at my github user name at yahoo dot com.

**Comment by JCzz** [comment]
Yes, fantastic it actually works in the latest - thanks Robert!
