### ISSUE TITLE
How to debug a go program that has SID permissions and is owned by root:wheel

### ISSUE THREAD

**Issue by rogerbrandtdev** [derekparker/delve#943]
I need to debug a program that will run with elevated privileges.  It needs to create aliases on the local loopback interface.  I have tried debugging within the Gogland-EAP IDE for GO developers and remote debugging within that IDE as well.

At the command line, my GO settings are
GOBIN=/Users/rbrandt/GoglandProjects/em-amp-aws_metadata_service/bin/
GOROOT=/usr/local/Cellar/go/1.8.3/libexec
GOPATH=/Users/rbrandt/go:/Users/rbrandt/GoglandProjects/em-amp-aws_metadata_service

My program has a main module and three other modules, server, form, and query.

I have created subdirectories bin, src, and pkg.

I have built the program with this command
go install -gcflags=-N -l form main query server
sudo chown root:wheel bin/main
Password:
sudo chmod ug+s bin/main

This results in the binary in the bin directory being privileged
-rwxr-xr-x  1 rbrandt  EM\Domain Users  8934692 Aug  8 13:26 bin/main

1. What version of Delve are you using (`dlv version`)?  
Version: 1.0.0-rc.1

2. What version of Go are you using? (`go version`)? 
go1.8.3 darwin/amd64

3. What operating system and processor architecture are you using? from uname -a -- 
      Darwin osxrbranmbp15.corp.elmae 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53: PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

4. What did you do?
CASE A:
time dlv --backend=native --log --listen=:2345 --headless=true --api-version=2 exec $PWD/bin/main

CASE B:
and also
sudo time dlv --backend=native --log --listen=:2345 --headless=true --api-version=2 exec $PWD/bin/main

5. What did you expect to see?
process starting and available to debug

6. What did you see instead?
CASE A:
process terminated before Gogland-EAP IDE could connect via remote debugging, since the process was not run with sufficient privileges.

2017/08/08 13:02:31 debugger.go:97: launching process with args: [bin/main]
API server listening at: [::]:2345
2017/08/08 13:03:34 debugger.go:496: halting
2017/08/08 13:03:34 debugger.go:350: created breakpoint: ...
2017/08/08 13:03:34 debugger.go:505: continuing
2017/08/08 13:03:42 debugger.go:551: nexting...
2017/08/08 13:03:44 debugger.go:551: nexting
2017/08/08 13:03:44 Failed to execute ifconfig with args [lo0 alias 169.254.169.254]
2017/08/08 13:03:44 exit status 1

CASE B:
process could not be launched

2017/08/08 12:56:44 debugger.go:97: launching process with args: [/Users/rbrandt/GoglandProjects/em-amp-aws_metadata_service/bin/main]
could not launch process: error waiting for thread stop -268435459

**Comment by aarzilli** [comment]
Does solution b works if you don't use the native backend?

**Comment by aarzilli** [comment]
No user feedback.
