### ISSUE TITLE
VariableShadowed flag not applied to func arguments

### ISSUE THREAD

**Issue by lloiser** [derekparker/delve#951]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
> dlv version
Delve Debugger
Version: 1.0.0-rc.1
Build: $Id: b6077a6a35c48a31716aad2ad3fdf77bbdf70abd $
```

2. What version of Go are you using? (`go version`)?

```
> go1.9rc2 version
go version go1.9rc2 windows/amd64
```
go1.9rc2 has been built as described in here https://golang.org/dl/#go1.9rc2
(= `go get golang.org/x/build/version/go1.9rc2`)

3. What operating system and processor architecture are you using?

Windows 10 Pro (10.0.15063 Build 15063)
x64 based architecture

4. What did you do?

Given the following code:
```go
package main

import "fmt"

func main() {
	shadow(42)
}

func shadow(i int) {
	fmt.Println("arg", i)
	for i := 0; i < 5; i++ {
		fmt.Println("shadow", i)
		for i := 20; i < 25; i++ {
			fmt.Println("another shadow", i)
		}
	}
}
```

Now run `dlv debug`
Add breakpoint at the inner most `fmt.Println` (line 14) and continue
```
(dlv) list
> main.shadow() [redacted]/main.go:14 (PC: 0x49660a)
     9: func shadow(i int) {
    10:         fmt.Println("arg", i)
    11:         for i := 0; i < 5; i++ {
    12:                 fmt.Println("shadow", i)
    13:                 for i := 20; i < 25; i++ {
=>  14:                         fmt.Println("another shadow", i)
    15:                 }
    16:         }
    17: }
(dlv) locals
(i) = 0
i = 20
(dlv) args
i = 42
```

5. What did you expect to see?

Both the `i` argument (from `args`) and the `i` with value `0` are marked as shadowed (surrounded by brackets)

6. What did you see instead?

The `i` from `args` is missing the brackets

Is this a bug or has the user of these APIs to figure it out themselves? Like if a variable with the same name occurs in `locals` and `args` then skip the on from `args`?

-----

If it helps here is the JSON representation of the combined calls to `ListLocalVars` and `ListFunctionArgs`:
```js
[
  // locals:
  {
    "name": "i",
    "addr": 825741434416,
    "onlyAddr": false,
    "type": "int",
    "realType": "int",
    "flags": 2, // <-- as you can see the outer "i" has the flag
    "kind": 2,
    "value": "0",
    "len": 0,
    "cap": 0,
    "children": [],
    "unreadable": ""
  },
  {
    "name": "i",
    "addr": 825741434424,
    "onlyAddr": false,
    "type": "int",
    "realType": "int",
    "flags": 0, // <-- inner "i" variable, no flag ✓
    "kind": 2,
    "value": "20",
    "len": 0,
    "cap": 0,
    "children": [],
    "unreadable": ""
  },
  // args:
  {
    "name": "i",
    "addr": 825741434728,
    "onlyAddr": false,
    "type": "int",
    "realType": "int",
    "flags": 0, // <-- the argument "i" has no flag
    "kind": 2,
    "value": "42",
    "len": 0,
    "cap": 0,
    "children": [],
    "unreadable": ""
  }
]
```

**Comment by aarzilli** [comment]
> Is this a bug or has the user of these APIs to figure it out themselves?

I think it should be a bug. However when we process the ListFunctionArgs call we don't load local variables at all so this may take a while to fix.
