### ISSUE TITLE
could not launch process: stub exited while attempting to connect: signal: abort trap

### ISSUE THREAD

**Issue by msgtonaveen** [derekparker/delve#955]
1. What version of Delve are you using (`dlv version`)?
Version: 1.0.0-rc.1
Build: f553c95eeb29be1694c12eb8769c3531bb628f5d
2. What version of Go are you using? (`go version`)?
go version go1.9 darwin/amd64
3. What operating system and processor architecture are you using?
macOS Sierra Version 10.12, 1.6 GHz Intel Core i5
4. What did you do?
dlv exec file
5. What did you expect to see?
The debug session should begin
6. What did you see instead?
could not launch process: stub exited while attempting to connect: signal: abort trap

**Comment by aarzilli** [comment]
> dlv exec file

what's file what happens if you do `lldb-server gdbserver :8181 -- file`?

**Comment by msgtonaveen** [comment]
file is the go generated binary.

**Comment by msgtonaveen** [comment]
If I rutn lldb-server gdbserver :8181 -- generatedbinaryname, I get

```
using the default platform: host
Platform has no NativeProcessProtocol support
UNREACHABLE executed at /Library/Caches/com.apple.xbs/Sources/lldb/lldb-360.1.70/source/Host/common/NativeProcessProtocol.cpp:449!
Abort trap: 6
```

**Comment by aarzilli** [comment]
Looks like your lldb doesn't work.

**Comment by Mirodil** [comment]
@aarzilli what is the way to resolve it?

**Comment by aarzilli** [comment]
Not a bug (problem with user setup)
