### ISSUE TITLE
Feature Request: Step over should not include deferred functions

### ISSUE THREAD

**Issue by dlsniper** [derekparker/delve#956]
Hi,

Here's a feature request that came up on Gogland's tracker:

```
What happens:
The "Step over" function "steps into" defer functions
E.g. Stepping through the Copy function below "Step over" steps twice into Close function.

What I would prefer:
"Step over" should not include deferred functions. (Only "Step Into" should include deferred functions)
```

The code example:

```go
package main

import (
	"fmt"
	"io"
	"os"
)

func Copy(dst, src string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	cerr := out.Close()
	if err != nil {
		return err
	}
	return cerr // step over - defer
}

func main() {
	fmt.Println(Copy("demo", "demo"))
}
```

I'm happy to discuss this further as needed.
Thank you.

**Comment by aarzilli** [comment]
I think I agree. The only question I have is whether this new behavior should replace the old one or be selected by a flag in the DebuggerCommand packet.

I think the change is simple, it should suffice to change this lines in pkg/proc/threads.go:

```
			if bp != nil {
				bp.DeferReturns = deferreturns
			}
```

into this:

```
			if bp != nil && stepInto {
				bp.DeferReturns = deferreturns
			}
```

**Comment by ThomasKrenn** [comment]
From a IDE users perspective I think there is no need for a flag. The user can use step-into or set a break point in the deferred function. (Without this change the user has no choice - defered  function are always included)

**Comment by dlsniper** [comment]
I also think this shouldn't be yet one more flag but rather just the default behavior. Too many flags would make delve lose it's easy to use feeling it has now imho. I'm happy to send the PR if you think that's a good solution.

**Comment by derekparker** [comment]
Fixed via https://github.com/derekparker/delve/commit/5c9b2009cab214c1f912a2d8c6c89eec9f3ada2b.
