### ISSUE TITLE
Get commit hash from binary

### ISSUE THREAD

**Issue by Juan-AdYouLike** [derekparker/delve#968]
Hello, how i can extract the commit hash from the binary dlv. I know what the binary is compiled with the flags go install -ldflags="-X main.Build=2c0e31160de8cba2a4351dcf39486d05313b4da1" github.com/derekparker/delve/cmd/dlv. So i suppose using nm/objdump/readelf it could be possible but i'm unable to find it.

**Comment by aarzilli** [comment]
`dlv version`. The variable is `github.com/derekparker/delve/pkg/version.DelveVersion` there's probably some way to extract it with objdump but I don't know it.

**Comment by Juan-AdYouLike** [comment]
@aarzilli Thanks for your answer, but i really looking for a way to extract the information with objdump/nm for academic proposes :-)
