### ISSUE TITLE
dlv debugging of go apps using AudioToolbox breaks after upgrading to latest Command Line Tools (Xcode 9 for OS 10.12)

### ISSUE THREAD

**Issue by alanpeevers** [derekparker/delve#969]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 1.0.0-rc.1
2. What version of Go are you using? (`go version`)? 1.9
3. What operating system and processor architecture are you using? Darwin Kernel Version 16.7.0 x86_64
4. What did you do? Just opened a go script with TestFoo() test func in it
5. What did you expect to see? The "run test | debug test" annotation links above TestFoo() should both work.
6. What did you see instead? Only "run test" worked. The debug session just stopped (never hit breakpoint set on first line of TestFoo()). If I stop debugging, debugger prints a useless error. There was a warning from debugger (actually, from ld, IIRC) after it initializes about AudioToolbox.tld and AudioToolbox.dylib being out of sync, and something about "resorting to library version". Sorry I do not have the exact text of the warning.

**Comment by alanpeevers** [comment]
Sorry, it's AudioToolbox.tbd (text-based stub library), not .tld

**Comment by alanpeevers** [comment]
Something in the CLT upgrade left a (minor?) inconsistency between the tbd and the dylib...

**Comment by aarzilli** [comment]
Needs more context.

**Comment by ohc192** [comment]
Here is the exact same error you are describing.

$ go build noise.go 
# github.com/gordonklaus/portaudio


ld: warning: text-based stub file /System/Library/Frameworks//AudioToolbox.framework/AudioToolbox.tbd and library file /System/Library/Frameworks//AudioToolbox.framework/AudioToolbox are out of sync. Falling back to library file for linking.
./# command-line-arguments
ld: warning: text-based stub file /System/Library/Frameworks//AudioToolbox.framework/AudioToolbox.tbd and library file /System/Library/Frameworks//AudioToolbox.framework/AudioToolbox are out of sync. Falling back to library file for linking.

**Comment by aarzilli** [comment]
Closing, no feedback.
