### ISSUE TITLE
Delve cannot debug go-qml example projects

### ISSUE THREAD

**Issue by dominicwilliams** [derekparker/delve#97]
Delve cannot debug go projects based upon go-qml. This can be tested using the examples that come with the go-qml package.

For example, upon running `dlv run basiclayouts.go` delve successfully compiles the debug binary but then fails to run it and outputs error message:

`[Could not launch program: decoding dwarf section info at offset 0x0: too short]`

**Comment by derekparker** [comment]
Sorry for the late response, but this is likely due to cgo. Thanks for the report! I have plans to significantly improve cgo support very soon.

**Comment by derekparker** [comment]
Closing as duplicate of #79.
