### ISSUE TITLE
Extremely slow startup of debug for specific project

### ISSUE THREAD

**Issue by delaneyj** [derekparker/delve#970]
1. What version of Delve are you using (`dlv version`)?
Version 1.0.0-rc1
Build: b6077a6

2. What version of Go are you using? (`go version`)?
1.9 windows/amd64

3. What operating system and processor architecture are you using?
Windows10 Pro 64bit 

4. What did you do?
```
go get -u github.com/goxjs/example/tree/master/triangle
cd $GOPATH/github.com/goxjs/example/tree/master/triangle
go run main.go #Less than 2 seconds 
dlv debug main.go #Between 60-90s
```

5. What did you expect to see?
Generally similar startup times, or some details of what could be causing the slow down.

6. What did you see instead?
30-40x slow down in startup.

**Comment by aarzilli** [comment]
It's recompiling all dependencies with optimizations disabled which unfortunately can not be cached: https://github.com/golang/go/issues/19340

**Comment by ITSecMedia** [comment]
This issue is currently an extreme pain.

**Comment by Kliton** [comment]
Any update?

**Comment by jkryanchou** [comment]
I would try gdb to replace delve by using `go install -v <package>` to compile with cached.
