### ISSUE TITLE
Can not set breakpoint

### ISSUE THREAD

**Issue by newpot** [derekparker/delve#976]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.1
Build: $Id: b6077a6a35c48a31716aad2ad3fdf77bbdf70abd

2. What version of Go are you using? (`go version`)?
go version go1.7.4 linux/amd64

3. What operating system and processor architecture are you using?
Ubuntu 17.04

4. What did you do?
Tried to set breakpoint

5. What did you expect to see?

6. What did you see instead?
periutil$ dlv debug periutil.go
Type 'help' for list of commands.
(dlv) b periutil.go:42
Command failed: input/output error

**Comment by aarzilli** [comment]
Can you post the output of `cat /proc/sys/kernel/yama/ptrace_scope`

**Comment by newpot** [comment]
periutil$ cat /proc/sys/kernel/yama/ptrace_scope
1

**Comment by aarzilli** [comment]
Can you think of anything else you may have installed that would prevent ptrace from working? What about seccomp? Is this running in a container? Is the problem only with line 42 of periutil.go or everywhere? What's at that line? If you run a "make test" for delve do all the tests fail? Can you figure out the memory address of periutil.go:42 using `go tool objdump` and set the breakpoint like this: `b *0x401000` (with whatever the memory address of line 42 is instead of 0x401000?)

**Comment by newpot** [comment]
Thanks for replying.

There is no seccomp running, neither it is on a container. There is nothing special of line 42 which is just a random line number. Same thing happens if I use another line.

(dlv) b periutil.go:49
Command failed: input/output error

**Comment by newpot** [comment]
Issue happened on a real server with Ubuntu 17.04. Just tried on VM with Ubuntu 17.04. Same thing.

**Comment by newpot** [comment]
make test looks ok except for "no test files".

xguo2@hw-srv1:~/workspace/psdiag/diag/app/src/github.com/derekparker/delve$ make test
go test -p 1  -ldflags="-X main.Build=5c9b2009cab214c1f912a2d8c6c89eec9f3ada2b" github.com/derekparker/delve/cmd/dlv github.com/derekparker/delve/cmd/dlv/cmds github.com/derekparker/delve/pkg/config github.com/derekparker/delve/pkg/dwarf/frame github.com/derekparker/delve/pkg/dwarf/godwarf github.com/derekparker/delve/pkg/dwarf/line github.com/derekparker/delve/pkg/dwarf/op github.com/derekparker/delve/pkg/dwarf/reader github.com/derekparker/delve/pkg/dwarf/util github.com/derekparker/delve/pkg/goversion github.com/derekparker/delve/pkg/proc github.com/derekparker/delve/pkg/proc/core github.com/derekparker/delve/pkg/proc/gdbserial github.com/derekparker/delve/pkg/proc/native github.com/derekparker/delve/pkg/proc/test github.com/derekparker/delve/pkg/terminal github.com/derekparker/delve/pkg/versiongithub.com/derekparker/delve/service github.com/derekparker/delve/service/api github.com/derekparker/delve/service/debugger github.com/derekparker/delve/service/rpc1 github.com/derekparker/delve/service/rpc2 github.com/derekparker/delve/service/rpccommon github.com/derekparker/delve/service/test github.com/derekparker/delve/service/test/cmd
ok      github.com/derekparker/delve/cmd/dlv    6.025s
?       github.com/derekparker/delve/cmd/dlv/cmds       [no test files]
ok      github.com/derekparker/delve/pkg/config 0.005s
ok      github.com/derekparker/delve/pkg/dwarf/frame    0.004s
?       github.com/derekparker/delve/pkg/dwarf/godwarf  [no test files]
ok      github.com/derekparker/delve/pkg/dwarf/line     0.301s
ok      github.com/derekparker/delve/pkg/dwarf/op       0.004s
?       github.com/derekparker/delve/pkg/dwarf/reader   [no test files]
ok      github.com/derekparker/delve/pkg/dwarf/util     0.004s
ok      github.com/derekparker/delve/pkg/goversion      0.063s
ok      github.com/derekparker/delve/pkg/proc   42.813s
ok      github.com/derekparker/delve/pkg/proc/core      0.812s
ok      github.com/derekparker/delve/pkg/proc/gdbserial 0.930s
?       github.com/derekparker/delve/pkg/proc/native    [no test files]
?       github.com/derekparker/delve/pkg/proc/test      [no test files]
ok      github.com/derekparker/delve/pkg/terminal       5.644s
?       github.com/derekparker/delve/pkg/version        [no test files]
?       github.com/derekparker/delve/service    [no test files]
?       github.com/derekparker/delve/service/api        [no test files]
ok      github.com/derekparker/delve/service/debugger   0.006s
?       github.com/derekparker/delve/service/rpc1       [no test files]
?       github.com/derekparker/delve/service/rpc2       [no test files]
?       github.com/derekparker/delve/service/rpccommon  [no test files]
ok      github.com/derekparker/delve/service/test       48.089s
?       github.com/derekparker/delve/service/test/cmd   [no test files]

**Comment by newpot** [comment]
After "r" command, "c" will execute the program. "n" and "ls" will fail. Looks like source file or symbol is not loaded.

(dlv) ls
Stopped at: 0x7f3d88af4c20
=>no source available
Command failed: open : no such file or directory

(dlv) n
Command failed: could not find FDE for PC 0x7f3d88af4c20

"make build" devle and copied binary to periutil folder. After "./dlv debug" starts, debug file was generated.

xguo2@hw-srv1:~/workspace/psdiag/diag/app/src/util/periutil$ ls -l
total 24484
-rwxrwxr-x 1 xguo2 xguo2  2883432 Oct  2 10:29 debug
-rwxrwxr-x 1 xguo2 xguo2 14024458 Oct  2 10:19 dlv
-rw-rw-r-- 1 xguo2 xguo2     1999 Sep 28 13:42 periutil.go
-rw-rw-r-- 1 xguo2 xguo2      189 Sep 28 13:26 periutil_test.go

**Comment by newpot** [comment]
"sources" command did give list of all source files.
(dlv) sources
/home/xguo2/workspace/psdiag/diag/app/src/common/cli/cli.go
/home/xguo2/workspace/psdiag/diag/app/src/common/i2c/i2c.go
/home/xguo2/workspace/psdiag/diag/app/src/common/misc/misc.go
/home/xguo2/workspace/psdiag/diag/app/src/config/config.go
/home/xguo2/workspace/psdiag/diag/app/src/hardware/hwdev/hwdev.go
/home/xguo2/workspace/psdiag/diag/app/src/util/periutil/periutil.go
/usr/lib/go-1.7/src/bytes/buffer.go
...

**Comment by aarzilli** [comment]
Can you set a breakpoint on a function `break main.main`? I may need to see the binary to figure out what's happening.

**Comment by newpot** [comment]
I think something wrong during loading.

(dlv) break main.main
Command failed: input/output error

**Comment by newpot** [comment]
Found issue.
In my project, I changed go/ folder to app/. GOPATH has the correct setting. I think somewhere in delve package, "go/" is used instead of value from $GOPATH.

I have a old go workplace. Pointed $GOPATH to that one and dlv is working.

**Comment by newpot** [comment]
I was wrong... Not due to folder name.
Copied some hello code to app/ folder and it is working.

**Comment by newpot** [comment]
Finally located issue.
it is due to one of go package is linked to a C binary with CGO.
Found some discussion about this topic. Have not get it work yet.

Tried and same error.
go build -gcflags="-N -l" -o debug
dlv exec ./debug

**Comment by dklann** [comment]
I am having a similar issue as shown in this thread. GOPATH is set to ~/src/go and all other "subsystems" (`go get`, `go install`, etc.) seem to work fine. I came across Delve via MS VS Code. Running on Arch Linux with kernel 4.14.15-1-ARCH, go version 1.9.3, delve version 1.0.0-rc2 (Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c $), installed with `go get -u github.com/derekparker/delve/cmd/dlv`. It's a simple app so far: just main.go in `${GOPATH}/github.com/dklann/rd-dropbox` (it's public on github.com).

**Comment by aarzilli** [comment]
Works for me:

```
$ dlv debug github.com/dklann/rd-dropbox/cmd/rd-dropbox
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x76959b for main.main() ./cmd/rd-dropbox/main.go:61
(dlv) c
> main.main() ./cmd/rd-dropbox/main.go:61 (hits goroutine(1):1 total:1) (PC: 0x76959b)
    56:	
    57:	var (
    58:		verbose = kingpin.Flag("verbose", "Be chatty when running").Short('v').Bool()
    59:	)
    60:	
=>  61:	func main() {
    62:		kingpin.CommandLine.HelpFlag.Short('h')
    63:		kingpin.Version("0.0.1")
    64:		kingpin.Parse()
    65:	
    66:		db, err := sql.Open("mysql", "rduser:8-XNmVk1WYHYgXEE@tcp(service)/Rivendell")
(dlv) n
> main.main() ./cmd/rd-dropbox/main.go:62 (PC: 0x7695b2)
    57:	var (
    58:		verbose = kingpin.Flag("verbose", "Be chatty when running").Short('v').Bool()
    59:	)
    60:	
    61:	func main() {
=>  62:		kingpin.CommandLine.HelpFlag.Short('h')
    63:		kingpin.Version("0.0.1")
    64:		kingpin.Parse()
    65:	
    66:		db, err := sql.Open("mysql", "rduser:8-XNmVk1WYHYgXEE@tcp(service)/Rivendell")
    67:		if err != nil {
(dlv) 
> main.main() ./cmd/rd-dropbox/main.go:63 (PC: 0x7695d3)
    58:		verbose = kingpin.Flag("verbose", "Be chatty when running").Short('v').Bool()
    59:	)
    60:	
    61:	func main() {
    62:		kingpin.CommandLine.HelpFlag.Short('h')
=>  63:		kingpin.Version("0.0.1")
    64:		kingpin.Parse()
    65:	
    66:		db, err := sql.Open("mysql", "rduser:8-XNmVk1WYHYgXEE@tcp(service)/Rivendell")
    67:		if err != nil {
    68:			log.Fatal(err)
(dlv) 
> main.main() ./cmd/rd-dropbox/main.go:64 (PC: 0x7695ec)
    59:	)
    60:	
    61:	func main() {
    62:		kingpin.CommandLine.HelpFlag.Short('h')
    63:		kingpin.Version("0.0.1")
=>  64:		kingpin.Parse()
    65:	
    66:		db, err := sql.Open("mysql", "rduser:8-XNmVk1WYHYgXEE@tcp(service)/Rivendell")
    67:		if err != nil {
    68:			log.Fatal(err)
    69:		}
(dlv) 
> main.main() ./cmd/rd-dropbox/main.go:66 (PC: 0x7695f1)
    61:	func main() {
    62:		kingpin.CommandLine.HelpFlag.Short('h')
    63:		kingpin.Version("0.0.1")
    64:		kingpin.Parse()
    65:	
=>  66:		db, err := sql.Open("mysql", "rduser:8-XNmVk1WYHYgXEE@tcp(service)/Rivendell")
    67:		if err != nil {
    68:			log.Fatal(err)
    69:		}
    70:		defer db.Close()
    71:	
(dlv) 
```

kernel: `4.4.0-109-generic #132-Ubuntu` tried both 1.9.2 and a recent-ish devel build.

**Comment by dklann** [comment]
So, clearly something is amiss in my setup or configuration. Any suggestions on where to start looking? Thanks for your help!

**Comment by aarzilli** [comment]
Does delve work with a pure go program? If it does it could be something different with the linker/compiler, looking at which options are passed to them using objdump could be helpful.

**Comment by aarzilli** [comment]
Closing, no feedback.

**Comment by aaron-sysdig** [comment]
this issue occurred for me on M1 mac because the GOARCH flag was set to amd64, changing it to arm64 fixed the issue
