### ISSUE TITLE
custom GOPATH?

### ISSUE THREAD

**Issue by cg31** [derekparker/delve#981]
It seems delve only uses GOPTAH from environment.

Could is possible to add a new flag to specify a custom GOPTAH?

it will be used like: 
dlv --gopath=/path/to/my/project debug

**Comment by aarzilli** [comment]
This option doesn't exist for `go` itself I don't see why it should exist for delve. If you are using a unix shell `GOPATH=/path/to/my/project dlv debug` does this exact thing.

**Comment by cg31** [comment]
If I use delve in command line, I do use shell like that.

But the dilemma is when I use Visual Studio Code, it is inconvenient to use shell command like that, unless I re-start vscode.

**Comment by aarzilli** [comment]
You should ask VSCode.

**Comment by cg31** [comment]
vscode, or the go extension toolchain, already support custom GOPATH, now it is only delve doesn't support in the toolchain.

**Comment by dlsniper** [comment]
GoLand supports this. VS Code should support this on their side.

**Comment by derekparker** [comment]
@dlsniper thoughts on this feature from an IDE perspective?

**Comment by dlsniper** [comment]
I'm not familiar with the implementation details of VS Code but I don't see why this is a delve issue. 

> But the dilemma is when I use Visual Studio Code, it is inconvenient to use shell command like that, unless I re-start vscode.

I don't understand why it would be easier to type ` dlv --gopath=/some/path ` vs ` GOPATH=/some/path dlv ` in the console of the editor.

**Comment by derekparker** [comment]
@dlsniper thanks, agreed.
