### ISSUE TITLE
can't compile on linux/amd64

### ISSUE THREAD

**Issue by muellert** [derekparker/delve#983]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

None. Trying to compile 5c9b2009cab214c1f912a2d8c6c89eec9f3ada2b

2. What version of Go are you using? (`go version`)?

go version go1.7.4 linux/amd64

3. What operating system and processor architecture are you using?

Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
(IOW, a current Stretch)

4. What did you do?

* clone this repo, then
* $ export GOPATH=`/bin/pwd`
* $ make install

5. What did you expect to see?

I expected to see a 'bin' subdirectory with the delve binary in it.

6. What did you see instead?

go install -ldflags="-X main.Build=5c9b2009cab214c1f912a2d8c6c89eec9f3ada2b" github.com/derekparker/delve/cmd/dlv
can't load package: package github.com/derekparker/delve/cmd/dlv: cannot find package "github.com/derekparker/delve/cmd/dlv" in any of:
	/usr/lib/go-1.7/src/github.com/derekparker/delve/cmd/dlv (from $GOROOT)
	/srv/myhome/mnt/sw-dev/golang/delve/delve/src/github.com/derekparker/delve/cmd/dlv (from $GOPATH)
Makefile:49: recipe for target 'install' failed
make: *** [install] Error 1

There's no 'src' subdirectory in the repo, but adjusting the PREFIX variable in the Makefile did not help, either.

**Comment by aarzilli** [comment]
Your go is not set up correctly, see: https://golang.org/doc/install

**Comment by muellert** [comment]
I installed go from the OS packages - nothing special here. That _should_ work, and I can eg. compile restic.
