### ISSUE TITLE
dlv doesn't accept multiple packages on the commandline

### ISSUE THREAD

**Issue by nuliknol** [derekparker/delve#984]
1. What version of Delve are you using (`dlv version`)?
Version: 1.0.0-rc.1

2. What version of Go are you using? (`go version`)?
go version go1.8.3 linux/amd64

3. What operating system and processor architecture are you using?
Fedora 26, linux 64 bits (AMD 64)

4. What did you do?
executed this  on the command line:
[niko@localhost src]$ dlv debug github.com/ethereum/go-ethereum/cmd/geth/main.go github.com/ethereum/go-ethereum/cmd/geth/config.go  github.com/ethereum/go-ethereum/cmd/geth/chaincmd.go github.com/ethereum/go-ethereum/cmd/geth/monitorcmd.go github.com/ethereum/go-ethereum/cmd/geth/accountcmd.go github.com/ethereum/go-ethereum/cmd/geth/consolecmd.go github.com/ethereum/go-ethereum/cmd/geth/misccmd.go github.com/ethereum/go-ethereum/cmd/geth/bugcmd.go gopkg.in/urfave/cli.v1 --  --verbosity 5 --ipcdisable --port 40401 --rpc --rpcport 9101 --pprof --datadir=/home/niko/saved-niko-home/myeth/ --networkid=15 console 

5. What did you expect to see?
Expected to see this:
[niko@localhost src]$ go run github.com/ethereum/go-ethereum/cmd/geth/main.go github.com/ethereum/go-ethereum/cmd/geth/config.go  github.com/ethereum/go-ethereum/cmd/geth/chaincmd.go github.com/ethereum/go-ethereum/cmd/geth/monitorcmd.go github.com/ethereum/go-ethereum/cmd/geth/accountcmd.go github.com/ethereum/go-ethereum/cmd/geth/consolecmd.go github.com/ethereum/go-ethereum/cmd/geth/misccmd.go github.com/ethereum/go-ethereum/cmd/geth/bugcmd.go gopkg.in/urfave/cli.v1  --verbosity 5 --ipcdisable --port 40401 --rpc --rpcport 9101 --pprof --datadir=/home/niko/saved-niko-home/myeth/ --networkid=15 console 
INFO [10-08|08:06:52] Starting peer-to-peer node               instance=Geth/v1.7.0-unstable/linux-amd64/go1.8.3
INFO [10-08|08:06:52] Allocated cache and file handles         database=/home/niko/.ethereum/geth/chaindata cache=128 handles=1024
INFO [10-08|08:06:52] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [10-08|08:06:52] Disk storage enabled for ethash caches   dir=/home/niko/.ethereum/geth/ethash count=3
INFO [10-08|08:06:52] Disk storage enabled for ethash DAGs     dir=/home/niko/.ethash               count=2
INFO [10-08|08:06:52] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [10-08|08:06:52] Loaded most recent local header          number=4296248 hash=df3add…e46390 td=984074232195640169337
INFO [10-08|08:06:52] Loaded most recent local full block      number=4293719 hash=7f9298…6591ea td=978058709511454175803
INFO [10-08|08:06:52] Loaded most recent local fast block      number=4295996 hash=a33a95…afe986 td=983483567909307236910
INFO [10-08|08:06:52] Loaded local transaction journal         transactions=0 dropped=0
INFO [10-08|08:06:52] Regenerated local transaction journal    transactions=0 accounts=0
WARN [10-08|08:06:52] Blockchain not empty, fast sync disabled 
INFO [10-08|08:06:52] Starting P2P networking 
....
[aborted with Ctrl-C]

6. What did you see instead?
A saw this:
[niko@localhost src]$ dlv debug github.com/ethereum/go-ethereum/cmd/geth/main.go github.com/ethereum/go-ethereum/cmd/geth/config.go  github.com/ethereum/go-ethereum/cmd/geth/chaincmd.go github.com/ethereum/go-ethereum/cmd/geth/monitorcmd.go github.com/ethereum/go-ethereum/cmd/geth/accountcmd.go github.com/ethereum/go-ethereum/cmd/geth/consolecmd.go github.com/ethereum/go-ethereum/cmd/geth/misccmd.go github.com/ethereum/go-ethereum/cmd/geth/bugcmd.go gopkg.in/urfave/cli.v1 --  --verbosity 5 --ipcdisable --port 40401 --rpc --rpcport 9101 --pprof --datadir=/home/niko/saved-niko-home/myeth/ --networkid=15 console 
//# command-line-arguments
github.com/ethereum/go-ethereum/cmd/geth/main.go:115: undefined: configFileFlag
github.com/ethereum/go-ethereum/cmd/geth/main.go:146: undefined: initCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:147: undefined: importCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:148: undefined: exportCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:149: undefined: removedbCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:150: undefined: dumpCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:152: undefined: monitorCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:154: undefined: accountCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:155: undefined: walletCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:157: undefined: consoleCommand
github.com/ethereum/go-ethereum/cmd/geth/main.go:157: too many errors
exit status 2
[niko@localhost src]$ 

How can I fix it?

**Comment by aarzilli** [comment]
`dlv debug github.com/ethereum/go-ethereum/cmd/geth/`

**Comment by nuliknol** [comment]
why doesn't it work with only the main.go file ? The Go language works.

**Comment by derekparker** [comment]
@nuliknol under the hood it is using `go build` not `go run`. Additionally in your example I suspect you only need to pass in the first file (for the `go run` example).
