### ISSUE TITLE
'could not find symbol value' in for loop

### ISSUE THREAD

**Issue by dvic** [derekparker/delve#987]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.1
Build:

2. What version of Go are you using? (`go version`)?
go version go1.9.1 darwin/amd64

3. What operating system and processor architecture are you using?
macOS Sierra 10.12.6 Macbook Pro 15" 2017

4. What did you do?
Using https://gist.github.com/dvic/633738f5dcad90cd3be30455cff38c47, I did:
- `dlv debug .`
- `break main.go:33`
- `continue`
- app stops at line 33
- `print i`

5. What did you expect to see?
the value of `i` (0)

6. What did you see instead?
`Command failed: could not find symbol value for i`

When I step into the function `runPerson` on line 37, then I can print the arguments (`i` and `p`)

**Comment by dvic** [comment]
I can also confirm that it is working when installing with `go get -u github.com/derekparker/delve/cmd/dlv`. It also outputs the same version as Intellij IDEA. It seems an issue with the brew installed version?

**Comment by aarzilli** [comment]
Brew installs the last release which doesn't support go 1.9, IDEA has a build from master.

**Comment by dvic** [comment]
Ah, I see, thanks, I've created https://github.com/derekparker/delve/pull/988 in case this should be mentioned in the docs.

**Comment by aarzilli** [comment]
Fixed by release of 1.0.0-rc.2
