### ISSUE TITLE
Function is not calling.

### ISSUE THREAD

**Issue by Ankur008** [derekparker/delve#990]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)-
Delve Debugger
Version: 1.0.0-rc.1
Build: 5c9b2009cab214c1f912a2d8c6c89eec9f3ada2b
2. What version of Go are you using? (`go version`)?- go version go1.8.3 linux/amd64
3. What operating system and processor architecture are you using?- ubuntu16.04.3 LTS
4. What did you do? 
5. What did you expect to see?
6. What did you see instead?

I am trying to print local variables and its values till the breakpoint. For this, I am trying to change the code and create a cmd "verbose"

/pkg/terminal/command.go
`val, err := t.client.GetVariable(ctx.Scope,t.loadConfig())
`
/service/client.go
//get all variable
```
`	func (c *RPCClient) GetVariable(scope api.EvalScope, cfg api.LoadConfig) (*api.Variable, error) {
	var out EvalOut
	//err := c.call("Eval", EvalIn{scope, expr, &cfg}, &out)
	return out.Variable, nil
}

```
/pkg/proc/variables.go

```
func (scope *EvalScope) GetVariable(cfg LoadConfig) (*Variable, error) {
 fmt.Println("GetVariable")

 var  i *Variable
 /*vars, err := scope.variablesByTag(dwarf.TagVariable, nil)

 if err != nil {
 fmt.Println("Error while fetching the variable  ",err)
 }
 
 for i := range vars {
 fmt.Println("variabkes ",vars[i].Name)
 }*/
 return i, nil
}

```

But GetVariable() is not calling i.e. GetVariable is not printed. 

Is there anywhere I need to define function? 
P.S.- This is not a bug. I am not able to find the solution elsewhere that's why putting it here.

**Comment by aarzilli** [comment]
You need to plumb any new api call through all the service layer (`service/rpc2/server.go` and `service/debugger/debugger.go`). What's the point of this new function? Eval already exists.

**Comment by Ankur008** [comment]
I am trying to print all the local variable with its value. How we plumb new api ? How we write the function @aarzilli

**Comment by aarzilli** [comment]
> I am trying to print all the local variable with its value.

This also exists, it's called ListLocalVariables.

**Comment by Ankur008** [comment]
so basically ListLocalVariables list all the local variables in one go. What I want is print the local variable as the program executed. 

Let's suppose there is 10 line of the program, then it should print the status of the local variable for each line.

**Comment by Ankur008** [comment]
Thanks for ListLocalVariables

@aarzilli  Check out my gist https://gist.github.com/Ankur008/e5a740ac33948744877b1b6594714670

I am calling the locals at line no 52,

But I am getting the fixed output i.e. variable value is not changing throughout the program. Can you check why this is happening?
