### ISSUE TITLE
Problems with WATCH in VSCode + Delve 

### ISSUE THREAD

**Issue by carlca** [derekparker/delve#991]
1. What version of Delve are you using (`dlv version`)?
`Delve Debugger
Version: 1.0.0-rc.1`
2. What version of Go are you using? (`go version`)?
`go version go1.9.1 darwin/amd64`
3. What operating system and processor architecture are you using?
`macOS 10.13.0 High Sierra'
4. What did you do?
Error in WATCH display of variable: key
5. What did you expect to see?
Contents of variable: key
6. What did you see instead?
`Unable to eval expression: "could not find symbol value for key"`

![screen shot 2017-10-13 at 15 00 37](https://user-images.githubusercontent.com/260612/31549920-89a84284-b027-11e7-8a9d-4be0327dba2e.png)

**Comment by aarzilli** [comment]
Update to the latest version of delve compiled from master.

**Comment by carlca** [comment]
Thanks! Will do.

**Comment by carlca** [comment]
Perfect! Everything looks fine now. Thanks very much.
