### ISSUE TITLE
Can not debug non-main package

### ISSUE THREAD

**Issue by patientplatypus** [derekparker/delve#994]
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.1
2. What version of Go are you using? (`go version`)?
go version go1.9.1 darwin/amd64
3. What operating system and processor architecture are you using?
MacOsx Sierra 64

patientplatypus:~/Documents/golang/src/github.com/patientplatypus/gorest/config:22:52:49$dlv debug sessions.go

Can not debug non-main package

That's...not helpful.

**Comment by aarzilli** [comment]
If it has tests you can use `dlv test`.

**Comment by derekparker** [comment]
@patientplatypus the source code you are debugging must be able to produce an actual binary in order for Delve to have something to run and debug. As mentioned, if that package has tests you can debug the code using `dlv test`, which will build a test binary to run and debug.

**Comment by waylandc** [comment]
Simplified directory structure as per Go recommendations...


```code
.
├── Makefile
├── broker.go
├── cmd
   ├── server
   │   └── server.go
   └── sseclient
       └── sseclient.go

```

This project has 2 build targets to build a sseclient.exe and server.exe (each belong to main package).

To start dlv, I do this
```shell
dlv cmd/sseclient/sseclient.go
```

How do I set a breakpoint in the broker.go file?

```shell
45 Type help followed by a command for full documentation.
 46 (dlv) b broker.go:99
 47 Command failed: Location "broker.go:99" not found
 48 (dlv) b ../../broker.go:99
 49 Command failed: Location "../../broker.go:99" not found
 50 (dlv)
```
