### ISSUE TITLE
When I run delve as root, none of my vendor packages are being found

### ISSUE THREAD

**Issue by evanluc** [derekparker/delve#995]
1. What version of Delve are you using (`dlv version`)?

1.0.0-rc.1

2. What version of Go are you using? (`go version`)?

go version go1.8.3 darwin/amd64

3. What operating system and processor architecture are you using?

Mac OSX El Capitan - x86 

4. What did you do?

I ran delve as sudo from my project's directory (`$GOPATH/src/project/`) because I need to listen on ports 80/443.

5. What did you expect to see?

I expected to see all my packages being found and my program being compiled as usual.

6. What did you see instead?

I saw a number of path errors such as:
`cannot find package "golang.org/x/net/context" in any of:
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/Users/ev/go/src/golang.org/x/net/context (from $GOPATH)
`
These are all files that are in my Glide` /vendor` at the root of the project.
This does not happen when I run delve as my default user.

**Comment by aarzilli** [comment]
Delve just calls `go` to build. I just tried and I get the same thing when doing `sudo go build` on one of my project. I don't know if it's indetended behavior but it's what `go` does.

**Comment by aarzilli** [comment]
Alright, the reason is that your $GOPATH is something other than $HOME/go and sudo won't forward it to delve. You would have to do `sudo -E dlv...`
