### ISSUE TITLE
Add a command to set the current frame

### ISSUE THREAD

**Issue by yasushi-saito** [derekparker/delve#997]
gdb has the "frame" command that sets the default frame for subsequent commands like "print" or "list". I don't see an equivalent in dlv. I see that "frame 3 print xxx" does the same thing in dlv, but it's cumbersome to type the frame number every time, especially from the commandline.

**Comment by whit537** [comment]
Pdb additionally [has](https://docs.python.org/3/library/pdb.html#debugger-commands) (u)p and (d)own commands for navigating the stack.

**Comment by aarzilli** [comment]
Implemented by 82aff3f18ad19c8ba190abd45a8689609dcffb50
